### ISSUE TITLE
How to return the abs dir of `vapoursynth/plugins/` or current loaded plugin ?

### ISSUE THREAD

**Issue by hooke007** [vapoursynth/vapoursynth#1015]

**Comment by theChaosCoder** [comment]
One way could be:

```
import vapoursynth as vs
print (vs.sys.path)
```

**Comment by hooke007** [comment]
It's python's PATH not vsplugins'

**Comment by theChaosCoder** [comment]
Oh sorry, you're correct.

**Comment by DJATOM** [comment]
I think it's not possible with current python API, but you can make a plugin that finds a folder where it was loaded (C API has desired method) and then call that plugin under python to get plugin path. For example, look at https://github.com/AmusementClub/vs-mlrt/blob/master/scripts/vsmlrt.py#L32 and https://github.com/AmusementClub/vs-mlrt/blob/master/vstrt/vs_tensorrt.cpp#L544

**Comment by hooke007** [comment]
Yeah, I noticed it and that's why i am curious that is there any undocumented api.

**Comment by couleurm** [comment]
i swear i saw a python script which for looped through all loaded vs plugins and their available functions, that can probably be repurposed for your usecase

**Comment by hooke007** [comment]
That issue is posted by me too. I have checked and it does no help for my usecase.

**Comment by myrsloik** [comment]
If you have a good reason why it'd be useful I could easily expose getPluginPath from the API in python.

**Comment by theChaosCoder** [comment]
For example when you ship your own script + plugins. In case of a namespace conflict, you could inform the user about it, incl. the path of the dll.

btw is it possible to unload a plugin?

**Comment by hooke007** [comment]
I am trying to do sth similar to https://github.com/vapoursynth/vapoursynth/issues/1015#issuecomment-1871429641

Check and Load the folder in this path.

**Comment by myrsloik** [comment]
plugin_path property added in R66
