### ISSUE TITLE
Flatpack or Snap for linux?

### ISSUE THREAD

**Issue by jlw4049** [vapoursynth/vapoursynth#1017]
Curious if the VapourSynth team would be interested in creating a flatpack or snap package to be used easily in a cross distro compatible manor. 

Right now installing VapourSynth is not easy for the typical user.

**Comment by myrsloik** [comment]
I don't have the time to create it. If you make it and keep it updated I'll happily link it and promote it.

**Comment by jlw4049** [comment]
Let me think about it for a few days before I decide if I can spare the time

**Comment by jlw4049** [comment]
For now i'll close this until I can get back to it
