### ISSUE TITLE
VapourSynth Editor not recognizing LSMASH

### ISSUE THREAD

**Issue by ghostyolk** [vapoursynth/vapoursynth#1020]
I'm not well versed in code and by some miracle was able to download a fully-functioning VapourSynth on my own Mac, however I am unable to do the same on my girlfriend's Mac.

I got as far as getting everything downloaded as it should be, however I'm coming upon an error that I can't figure out how to fix.

As soon as I pull up the VapourSynth Editor and pull up the script.vpy file in it, I hit Check Script to see if everything is working correctly. I get this error: 

"Failed to evaluate the script:
Python exception: No attribute with the name lsmas exists. Did you mistype a plugin namespace?

Traceback (most recent call last):
File "src/cython/vapoursynth.pyx", line 2244, in vapoursynth.vpy_evaluateScript
File "src/cython/vapoursynth.pyx", line 2245, in vapoursynth.vpy_evaluateScript
File "/Library/Frameworks/VapourSynth.framework/video_edit/script.vpy", line 17, in 
video = core.lsmas.LWLibavSource(source=abs_file_path)
File "src/cython/vapoursynth.pyx", line 1756, in vapoursynth.Core.__getattr__
AttributeError: No attribute with the name lsmas exists. Did you mistype a plugin namespace?"

Can someone help me fix this issue? I'm not sure where to even start. I compared my own VapourSynth Editor to hers, and noticed that the "core.lsmas.LWLibavSource" is completely blue on my own, however only the "core" part of that is blue on hers. How do I make her computer recognize the LSMASH plugin? 

Let me know if I should upload any screenshots to make this easier. Thank you!

**Comment by srappan** [comment]
- your missing the lsmash plugin in the expected location, that's what the error means
- stop using vapoursynth editor, use [vs-preview](https://github.com/Jaded-Encoding-Thaumaturgy/vs-preview) and an actual ide
- this isn't a vapoursynth issue

**Comment by ghostyolk** [comment]
thank you! sorry for posting in the wrong forum but i appreciate the help :) 

> * your missing the lsmash plugin in the expected location, that's what the error means
> * stop using vapoursynth editor, use [vs-preview](https://github.com/Jaded-Encoding-Thaumaturgy/vs-preview) and an actual ide
> * this isn't a vapoursynth issue
