### ISSUE TITLE
Cython syntax error when building on Linux

### ISSUE THREAD

**Issue by topranks** [vapoursynth/vapoursynth#1025]
Unsure if anyone may have pointers for me here.  I'm trying to compile on Ubuntu 22.04, and when running make I get the following error:
```
Error compiling Cython file:
------------------------------------------------------------
...

    env.core.funcs.removeLogHandler(env.log, env.core.core)
    env.log = NULL


cdef void __stdcall _logCb(int msgType, const char *msg, void *userData) noexcept nogil:
                                                                        ^
------------------------------------------------------------

src/cython/vapoursynth.pyx:218:73: Syntax error in C variable declaration
make: *** [Makefile:2079: src/cython/vapoursynth.c] Error 1
```

I'm not very familiar with cython, unsure if there is some change that has made it think [this syntax ](https://github.com/vapoursynth/vapoursynth/blob/a9896f9cba980a164587669f6cabe84d42223db1/src/cython/vapoursynth.pyx#L218)is invalid?  My Cython was installed from Ubuntu packages:
```
me@officepc:~/vapoursynth$ dpkg -l  | grep cython 
ii  cython3                                    0.29.28-1ubuntu3                            amd64        C-Extensions for Python 3
```
```
me@officepc:~/vapoursynth$ cython3 --version
Cython version 0.29.28
```

If anyone has any suggestions they would be most appreciated.

**Comment by HolyWu** [comment]
Cython 3.x is required since R64. You need to install the latest Cython via `pip`.

**Comment by topranks** [comment]
> Cython 3.x is required since R64. You need to install the latest Cython via `pip`.

Ah ok.  That was mentioned but I thought the requirement was satisfied as the "cython3" package was there.

Removed that and installed via pip, so now have:
```
me@officepc:~# cython --version 
Cython version 3.0.8
```

And it compiled just fine.  Thanks for the help!!

**Comment by myrsloik** [comment]
I've updated the documentation to reflect this now
