### ISSUE TITLE
vspipe sometimes only use one thread

### ISSUE THREAD

**Issue by efschu** [vapoursynth/vapoursynth#1030]
I realy dunno why this is happening.

I have this script:

```python
from vsrife import RIFE
from pathlib import Path
import vapoursynth as vs
import sys
import os

core = vs.core
core.num_threads = 14

core.std.LoadPlugin(path='/usr/lib/x86_64-linux-gnu/libffms2.so')
core.std.LoadPlugin(path="/mnt/hts/libs/libvstrt.so")

sys.path.append("/home/efeu/Downloads/VSGAN-tensorrt-docker/")
from src.rife_trt import rife_trt

clip = core.ffms2.Source(source='/tmp/tmpvideo', cache=False)

clip = core.resize.Bicubic(clip, width=640, height=480, format=vs.RGBS, matrix_in_s='709') # RGBS means fp32, RGBH means fp16

clip = core.trt.Model(clip, engine_path="/workspace/realesr-general-wdn-x4v3_opset16_640_480.engine", num_streams=4, device_id=0)

clip = core.resize.Bicubic(clip, width=1280, height=960, format=vs.RGBS, matrix_in_s='709') # RGBS means fp32, RGBH means fp16

clip = rife_trt(clip, multi = 2, scale = 1.0, device_id = 1, num_streams=4, engine_path="rife46_ensembleFalse_op18_clamp_1280x960_P40.engine")

clip = core.resize.Bicubic(clip, format=vs.YUV420P8, matrix_s='709')
clip.set_output()
``` 

when i start to test this with
`vspipe -c y4m  /workspace/test2.vpy -p .`

I mostly get this result:
![Bildschirmfoto vom 2024-03-07 11-47-07](https://github.com/vapoursynth/vapoursynth/assets/51944948/b796b5ee-121e-4809-a092-489a1d4bad0c)

as you see, vspipe only runs on one core.

But sometimes it runs as it should (I changed absolutly nothing, just rerun this multiple times):
![Bildschirmfoto vom 2024-03-07 11-46-02](https://github.com/vapoursynth/vapoursynth/assets/51944948/d90cbb46-3354-4ea5-90ba-9d5718607694)

What's the reason that vspipe ignores `core.num_threads` sometimes and sometimes not?

VSPipe R62
running on docker container:
nvcr.io/nvidia/tensorrt:24.01-py3

**Comment by myrsloik** [comment]
Try printing core.num_threads after setting it to see if it actually registers properly.

**Comment by efschu** [comment]
It tells 14, but then again runs on once core
```
14
vstrt: TensorRT version mismatch, built with 2454 but loaded with 2199; continue but fingers crossed...
Script evaluation done in 2.38 seconds
Terminated/66550 (33.64 fps)
```

**Comment by myrsloik** [comment]
I guess this is where you'd sprinkle debug printfs in the thread pool and see why things don't work out the way they should.

**Comment by efschu** [comment]
For testing I took another docker container (styler00dollar/vsgan_tensorrt) and cannot reproduce this behaviour.

So I will not debug this.
