### ISSUE TITLE
zimg-related errors on (Linux) build

### ISSUE THREAD

**Issue by 64kramsystem** [vapoursynth/vapoursynth#1031]
Hello,

I'm trying to build thr project on an Ubuntu 22.04 machine, but when invoking `make install`, I get error related to zimg.

I'm trying to build the current master version (past tag `R66-RC1`). The libzimg-dev version installed on my system is 3.0.3.

The errors log (extract) is at the bottom. If the [corresponding line](https://github.com/vapoursynth/vapoursynth/blob/master/src/core/vsresize.cpp#L112) is removed, the build follows (although it then raises an unrelated error).

I had a look at the [zimg repository](https://github.com/sekrit-twc/zimg), and it seems that `ZIMG_TRANSFER_ST428` has been added to 3.0.5, so the problem should be that VS, as of now, requires either an unstable Ubuntu version (mantic) or a yet-to-be-released LTS (noble).

Not sure if anything can be done in the project, but I'm reporting this for reference in case other people encounter the error.
It's still possible to download and install the Ubuntu 22.04 packages `libzimg-dev libzimg2` from [here](https://packages.ubuntu.com/noble/libzimg-dev), although this carries the risk of system breakage.

```
  CXX      src/core/libvapoursynth_la-vsresize.lo
src/core/vsresize.cpp:112:18: error: ‘ZIMG_TRANSFER_ST428’ was not declared in this scope; did you mean ‘ZIMG_TRANSFER_ST2084’?
  112 |     { "st428",   ZIMG_TRANSFER_ST428 },
      |                  ^~~~~~~~~~~~~~~~~~~
      |                  ZIMG_TRANSFER_ST2084
src/core/vsresize.cpp:115:1: error: no matching function for call to ‘std::unordered_map<std::__cxx11::basic_string<char>, zimg_transfer_characteristics_e>::unordered_map(<brace-enclosed initializer list>)’
  115 | };
      | ^
In file included from /usr/include/c++/11/unordered_map:47,
                 from /usr/include/c++/11/functional:61,
                 from /usr/include/c++/11/pstl/glue_algorithm_defs.h:13,
                 from /usr/include/c++/11/algorithm:74,
                 from src/core/vsresize.cpp:23:
```

**Comment by myrsloik** [comment]
Now requires zimg 3.0.5 to avoid cryptic compilation errors
