### ISSUE TITLE
(Linux) build looks for `cython3` executable, while Python package installs `cython`

### ISSUE THREAD

**Issue by 64kramsystem** [vapoursynth/vapoursynth#1032]
In order to build the project on Linux, one needs to install the latest Cython version, via Python package (`pip3 install cython`).

During the build process, the `cython3` executable is used, however, the Cython package actually installs a `cython` executable, causing the build to fail.

This problem can be fixed by creating a symlink, however, I think that the build script should handle this.

For reference my system is an Ubuntu 22.04.

**Comment by HolyWu** [comment]
The configure does check for BOTH `cython3` and `cython`.

https://github.com/vapoursynth/vapoursynth/blob/e301b104f42e149179ded0112c14b29d5c0d8c71/configure.ac#L296

https://github.com/vapoursynth/vapoursynth/actions/runs/8077434642/job/22067708480#step:7:163

**Comment by 64kramsystem** [comment]
> The configure does check for BOTH `cython3` and `cython`.
> 
> https://github.com/vapoursynth/vapoursynth/blob/e301b104f42e149179ded0112c14b29d5c0d8c71/configure.ac#L296
> 
> https://github.com/vapoursynth/vapoursynth/actions/runs/8077434642/job/22067708480#step:7:163

:thinking: Thanks for checking. I'll double check - I suspect it had to do with the system-wide vs. local installation.
