### ISSUE TITLE
documentation and location of portable vapoursynth install

### ISSUE THREAD

**Issue by hydra3333** [vapoursynth/vapoursynth#1037]
Hello.

The installation documentations says:
```
By far the easiest way is to download and run the automatic script called Install-Portable-VapourSynth-RXX.ps1. 
It will then automatically download and set up embedded Python, pip and VapourSynth in the directory it was run from.
```

So I did that and it instead created a subfolder called `vapoursynth-portable` and installed it into that ...
Is that by design ? I guess it seems so by the looks of the .ps1.  
Could I just move the files/folders up 1 level into the folder I wanted ?  
(I have loads of scripts already referencing a specific folder location where it expects to find portable vapoursynth)

Note to self: editing the .ps1 file to this seems to work:
```
    #[string]$TargetFolder = ".\vapoursynth-portable",
    [string]$TargetFolder = ".\",
```

_edit: being a dummy, I don't how to use parameters ..._
```
param(
    [int]$VSVersion = 66,
    #[string]$TargetFolder = ".\vapoursynth-portable",
    [string]$TargetFolder = ".\",
    [string]$DownloadFolder = ".\Downloads",
    [switch]$Python38,
    [switch]$Unattended
)
```

Thanks for the new release !

PS:
I wonder if the documentation could mention how to run the .ps1 file ?
Some systems including mine won't run the .ps1 by double-clicking on it, and a commandline must be used with this is added for it to work even then: `-executionpolicy bypass`
Perhaps a bit like the below:

Start a CMD box and use powershell to execute the .ps1 file, eg
```
powershell -executionpolicy bypass -File .\Install-Portable-VapourSynth-RXX.ps1
```

**Comment by theChaosCoder** [comment]
> in the directory it was run from.

It was changed in the recent commit

**Comment by myrsloik** [comment]
Hint:
`powershell -executionpolicy bypass -File .\Install-Portable-VapourSynth-RXX.ps1 -TargetFolder <wherever you want> -Unattended`

In my very default win10 install I can right click and run the script just fine but just like you I need to set the execution policy when running from the commandline. I have no idea why things are this way by default.

The MPV installer script gets around it by having a bat file that forwards everything to the powershell script and adds the execution policy argument.

**Comment by hydra3333** [comment]
> It was changed in a recent commit to creating a vapoursynth-portable subfolder. Imagine downloading it and "installing" it in your downloads folder.

Yep, I pop the .ps1 into the folder where I have other things like ffmpeg and dgtools and where a load of scripts expect to find vapoursynth and hope it installs there. 
Now with myrsloik's hint I can use the installer properly now albeit via a .bat which is fine by me.

**Comment by hydra3333** [comment]
Any hints as to what I am doing wrong ?

Hi, a couple of things.

If the TargetFolder already exists and we have cd'd into it and TargetFolder has no trailing backslash, we see this:
```
G:\TEST\Vapoursynth-x64>powershell -executionpolicy bypass -File "G:\TEST\Vapoursynth-x64\Install-Portable-VapourSynth-R66.ps1" -TargetFolder "G:\TEST\Vapoursynth-x64" -Unattended
Fetching latest version information...
Installing...
New-Item : The given path's format is not supported.
At G:\TEST\Vapoursynth-x64\Install-Portable-VapourSynth-R66.ps1:64 char:1
+ New-Item -Path ".\" -Name "$TargetFolder" -ItemType Directory -Force  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-Item], NotSupportedException
    + FullyQualifiedErrorId : System.NotSupportedException,Microsoft.PowerShell.Commands.NewItemCommand

Determining latest Python 3.12.x version...
Python version 3.12.2 will be used for installation
Downloading Python...
Downloading VapourSynth...
Downloading Pip...
Extracting Python...
Installing Pip...
Collecting pip
  Using cached pip-24.0-py3-none-any.whl.metadata (3.6 kB)
Collecting setuptools
  Using cached setuptools-69.2.0-py3-none-any.whl.metadata (6.3 kB)
Collecting wheel
  Using cached wheel-0.43.0-py3-none-any.whl.metadata (2.2 kB)
Using cached pip-24.0-py3-none-any.whl (2.1 MB)
Using cached setuptools-69.2.0-py3-none-any.whl (821 kB)
Using cached wheel-0.43.0-py3-none-any.whl (65 kB)
Installing collected packages: wheel, setuptools, pip
Successfully installed pip-24.0 setuptools-69.2.0 wheel-0.43.0
Extracting VapourSynth...
Installing VapourSynth...
Processing g:\test\vapoursynth-x64\wheel\vapoursynth-66-cp312-cp312-win_amd64.whl
Installing collected packages: VapourSynth
Successfully installed VapourSynth-66
Deleting downloaded files...
Installation complete
Press Enter to continue...:
```

If the TargetFolder already exists and we have cd'd into it and TargetFolder has trailing backslash, we see this:
```
G:\TEST\Vapoursynth-x64>powershell -executionpolicy bypass -File "G:\TEST\Vapoursynth-x64\Install-Portable-VapourSynth-R66.ps1" -TargetFolder "G:\TEST\Vapoursynth-x64\" -Unattended
Test-Path : Illegal characters in path.
At G:\TEST\Vapoursynth-x64\Install-Portable-VapourSynth-R66.ps1:23 char:24
+ ... ended -and (Test-Path -Path @("$TargetFolder\portable.vs") -PathType  ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (G:\TEST\Vapours...ded\portable.vs:String) [Test-Path], ArgumentException
    + FullyQualifiedErrorId : ItemExistsArgumentError,Microsoft.PowerShell.Commands.TestPathCommand

Fetching latest version information...
Script will install the latest VapourSynth version.
Proceed with install of R66? (y/n):
```

Trying withthout the folder pre-existing:
```
G:\TEST>dir
 Volume in drive G is G-DRIVE
 Volume Serial Number is D47D-C313

 Directory of G:\TEST

16/03/2024  05:46 PM    <DIR>          .
13/03/2024  09:55 PM             5,316 Install-Portable-VapourSynth-R66.ps1
               1 File(s)          5,316 bytes
               1 Dir(s)  3,406,232,584,192 bytes free

G:\TEST>powershell -executionpolicy bypass -File ".\Install-Portable-VapourSynth-R66.ps1" -TargetFolder G:\TEST\Vapoursynth-x64 -Unattended
Fetching latest version information...
Installing...
New-Item : The given path's format is not supported.
At G:\TEST\Install-Portable-VapourSynth-R66.ps1:64 char:1
+ New-Item -Path ".\" -Name "$TargetFolder" -ItemType Directory -Force  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-Item], NotSupportedException
    + FullyQualifiedErrorId : System.NotSupportedException,Microsoft.PowerShell.Commands.NewItemCommand

Could not create 'G:\TEST\Vapoursynth-x64' folder, aboring
```

**Comment by myrsloik** [comment]
Didn't escape backslashes. Last case is definitely complaining because you have a tab (\t) in your line

**Comment by hydra3333** [comment]
Cool.  Thanks and bye.

**Comment by L4cache** [comment]
> Didn't escape backslashes. Last case is definitely complaining because you have a tab (\t) in your line

No, the problem is you use this `New-Item -Path ".\" -Name xxx` thing in the script so it will only work for relative path!

**Comment by myrsloik** [comment]
Now that issue is fixed. I'll update the release and docs in a day or two.
