### ISSUE TITLE
Linux build fails to compile VSCore::isPortableInit in vscore.cpp

### ISSUE THREAD

**Issue by sceedy** [vapoursynth/vapoursynth#1038]
The latest git update I did failed to build on linux targets, with multiple errors in function VSCore::isPortableInit in source file vscore.cpp. The function apears to only contain win32 function calls. Surounding the function with
#ifdef VS_TARGET_OS_WINDOWS
...
#endif
allows to build to complete without any apparent degridation to the funtionality I use.

**Comment by myrsloik** [comment]
Probably fixed now
