### ISSUE TITLE
Install script's default download location and processing to it afterwards is a disaster

### ISSUE THREAD

**Issue by Mr-Z-2697** [vapoursynth/vapoursynth#1039]
The install script downloads files into Downloads folder relative to the working directory by default, not script location, not target folder, after installation it deletes the downloaded files and the Downloads folder.
If the working directory is user's home directory which is the default when you open a cmd or powershell, the name matches the system default Downloads folder, and... the install script will **DELETE ANYTHING INSIDE IT**.

I stay calm because I tried this in a VM, but this can be disastrous for other ones.
Please download to target folder, use more unique folder name, check if the folder is used by others, or at least, don't just delete everything.

**Comment by Mr-Z-2697** [comment]
I see there's a parameter

**Comment by theChaosCoder** [comment]
I think renaming it to something like Downloads-VS or VS-Downloads would reduce the risk.

**Comment by L4cache** [comment]
The risk should be eliminated not just reduced and it's simple: don't execute the f-word `rm -rf` equivalent in random place!

**Comment by myrsloik** [comment]
Fixed

**Comment by L4cache** [comment]
`rm -rf` equivalent is still there, ableit not executed in such random place... I'd suggest you make the script only specificly delete the file it just downloaded.
