### ISSUE TITLE
R66 portable missing VapourSynth.dll

### ISSUE THREAD

**Issue by zhongfly** [vapoursynth/vapoursynth#1040]
In https://github.com/vapoursynth/vapoursynth/commit/50b1328fa66de0e275d4b3aa4af738b1f8b45f3a#diff-245fa285b4f915286e4fa4a5412a236ca39d6640311c4ce6a10a7176c89d4398L25 ,you delete the line copying `VapourSynth.dll`.
But `setup.py` still need this file.
https://github.com/vapoursynth/vapoursynth/blob/5e2c5fba263b7cb00895b446bd490e4d0505d682/installer/setup.py#L35-L43
https://github.com/vapoursynth/vapoursynth/blob/5e2c5fba263b7cb00895b446bd490e4d0505d682/setup.py#L54-L65
Looks like deleting that line was a mistake

**Comment by myrsloik** [comment]
Exactly when do you need setup.py? Isn't the wheel enough for all use cases?

**Comment by zhongfly** [comment]
> Exactly when do you need setup.py? Isn't the wheel enough for all use cases?

At least the Windows CI for this project still uses it and fails because it can't find the dll file.
https://github.com/vapoursynth/vapoursynth/actions/runs/8217043936/job/22472288007#step:12:796

**Comment by L4cache** [comment]
About your PR:
VapourSynth.dll in portable "root"... and wheel files...
There's already 2 identical VapourSynth.dll in 2 wheel files, now it counts 3. This is not how we should do it.
duplicated dll in wheels are kinda inevitable though.

**Comment by hooke007** [comment]
Is there any reason to make current portable version so 'trouble'?
Now I have to firstly install pip and then install the wheel to make it ready to work.

**Comment by myrsloik** [comment]
> Is there any reason to make current portable version so 'trouble'? Now I have to firstly install pip and then install the wheel to make it ready to work.

There's an install script. If you think it's "trouble" to handle python packages the way python packages are generally handled I suggest you switch to another scripting language.

**Comment by theChaosCoder** [comment]
I think you could also simply unzip the wheel file. It contains, more or less, only the vapoursynth.dll

**Comment by L4cache** [comment]
> > Is there any reason to make current portable version so 'trouble'? Now I have to firstly install pip and then install the wheel to make it ready to work.
> 
> There's an install script. If you think it's "trouble" to handle python packages the way python packages are generally handled I suggest you switch to another scripting language.

`pip install vapoursynth` when
(I know there's a package can be installed that way, but I mean full featured installation)

**Comment by myrsloik** [comment]
https://pypi.org/project/VapourSynth-portable/

**Comment by L4cache** [comment]
> https://pypi.org/project/VapourSynth-portable/

Sorry I didn't know that, but when I try it it tells me "Failed to initialize VSScript"

**Comment by hooke007** [comment]
> I think you could also simply unzip the wheel file. It contains, more or less, only the vapoursynth.dll

But you do not have to unzip anything else in R65.

**Comment by hooke007** [comment]
> I think you could also simply unzip the wheel file. It contains, more or less, only the vapoursynth.dll

Which is actually what we did in mpv's build toolchain https://github.com/shinchiro/mpv-winbuild-cmake/pull/637/files
It's ugly.

**Comment by hooke007** [comment]
Isn't we are talking about "VapourSynth.dll" ?

**Comment by L4cache** [comment]
> Isn't we are talking about "VapourSynth.dll" ?

I see, the SDK files are incompatible with the workflow and dll is needed to generate new ones.

**Comment by myrsloik** [comment]
> VapourSynth.dll is indeed very convenient for builders, but not necessary. With lld, we can just linking to MSVC style import library and delayload, but bfd doesn't support this. I plan to use lld instead of bfd for the GCC toolchain in the future to completely eliminate the current ugly hacking.

I could put a bonus copy of vapoursynth.dll in a subdirectory that's never used if it really matters. One of the main reasons to remove vapoursynth.dll is that it would otherwise be used instead of the copy installed by pip. You're the first one to say a proper reason to keep it around.
