### ISSUE TITLE
API3 propGetData fails

### ISSUE THREAD

**Issue by videoh** [vapoursynth/vapoursynth#1045]
I have a string indexing_path I would like to pass in as a parameter. It is declared as indexing_path:data:opt; so it should be optional. However, if I omit the parameter then in the create function this call triggers a fatal exception in VirtualDub when I open the script.

const char *indexing_path = vsapi->propGetData(in, "indexing_path", 0, nullptr);

Howver, if I include the parameter everything is fine. Your assistance in resolving this would be greatly appreciated. Thank you.

**Comment by myrsloik** [comment]
If it's optional you still need to provide a dummy error reporting variable. Like this:
```
int err;
vsapi->propGetData(in, "indexing_path", 0, &err);
```

**Comment by videoh** [comment]
Oh, thank you, thank you, thank you! And thank you for the fast reply. This is for DGMPGDec so now I can make the new release.
