### ISSUE TITLE
As of cython 3.x, frame prop enums are IntFlag

### ISSUE THREAD

**Issue by JustinTArthur** [vapoursynth/vapoursynth#1046]
This wouldn't normally be too weird, except you might expect to be able to do this:
```python
clip.std.SetFrameProps(_Matrix=MatrixCoefficients.MATRIX_ST170_M)
```
Because cython opted for `IntFlag` instead of `IntEnum` for `cpdef` and because we try sequence coercion first, the property will now be set to `[2, 4]` instead of `6`.

**Comment by myrsloik** [comment]
I'm too bad at python to understand this. Why does a single value turn into a sequence at all? And can I check for the IntFlag type to get around it?

**Comment by myrsloik** [comment]
The offending change in cython:
https://github.com/cython/cython/pull/4877/commits/b1bd202bcdb0c31e9ce8ad1e8c80a44b15bf3ae5

**Comment by myrsloik** [comment]
"Fixed"
I suppose the true fix would be to make them IntEnum type but that will probably require a complete rework of how things are done.
