### ISSUE TITLE
I don't know the license of our repo

### ISSUE THREAD

**Issue by sdy623** [vapoursynth/vapoursynth#1048]
Could anyone tell me about the license of the repo. It is GPL or Apache or MIT or some other specital licenses.

**Comment by Setsugennoao** [comment]
https://github.com/vapoursynth/vapoursynth/blob/master/COPYING.LESSER

**Comment by sdy623** [comment]
Thank u very much. I’m making a conga package build recipe, the meta.yaml requires this
