### ISSUE TITLE
Cannot import module in python script because of the dash in "vs-scripts"

### ISSUE THREAD

**Issue by d3xMachina** [vapoursynth/vapoursynth#1070]
I have a script in the vs-scripts folder. Because of the dash that wasn't present in the earlier versions of Vapoursynth I cannot use the "from" directive like so : 
`from vs-scripts.CropResize import CropResize`
A dash is not permitted here in Python.

Suggestion : Rename vs-script to vs_scripts. (and vs-plugins to vs_plugins, vs-coreplugins to vs_coreplugins for consistency)

**Comment by Setsugennoao** [comment]
What...

**Comment by d3xMachina** [comment]
Vapoursynth R65 (portable installation) : 
![image](https://github.com/vapoursynth/vapoursynth/assets/16732772/25308d31-461d-4650-9dc6-907bb82235d3)
I created the scripts folder here but coreplugins and plugins were already there.

Here is the install folder of Vapoursynth R68 from a portable installation with the powershell script provided in "Release" : 
![image](https://github.com/vapoursynth/vapoursynth/assets/16732772/725e2058-c909-40c4-ad8e-e71915112c51)
vs-scripts was already created. It's where you're supposed to put your vapoursynth scripts right ?

My script is called "frameinterpolation.vpy" and I try to import "CropResize.py". Both are in the vs-scripts folder. 
frameinterpolation.vpy : 
![image](https://github.com/vapoursynth/vapoursynth/assets/16732772/398a4883-9f60-4fea-aadd-c07b1fc9e1ee)

Result :
![image](https://github.com/vapoursynth/vapoursynth/assets/16732772/3bd471b7-4a4a-4354-9abb-38a13e4310d6)

The error happens because a "-" is not valid in a module name in Python.

**Comment by theChaosCoder** [comment]
vs-scripts is in python path (see python312._pth), you should be able to simply call `from CropResize import CropResize`

**Comment by d3xMachina** [comment]
> vs-scripts is in python path (see python312._pth), you should be able to simply use `from CropResize import CropResize`

You're right, that works. Thanks.
