### ISSUE TITLE
Update doc to explain how the `getFrame*()`, filter modes and thread pool work

### ISSUE THREAD

**Issue by CrendKing** [vapoursynth/vapoursynth#1071]
### Story

Recently I was working on a new VS filter. It tries to "filter" certain frames from source clip, based on the frame data. To do so, I use a custom thread to go through frames one by one in sequential order and store the "good" frames in a cache. When the filter's `GetFrame` callback gets called, it returns the stored frames. Seems a simple task.

When the filter is in `fmFrameState` or `fmUnordered` mode, everything works as expected. When I flip to one of the `fmParallel*` modes, it immediately dead locks. I spend a long time to debug and read VapourSynth source to understand what's going on.

It turns out that (correct me if wrong), VapourSynth internally uses a thread pool to run tasks. Every "get frame" call, regardless where it originates from, is actually a task that pushed to the task queue, waiting for one of the threads in the pool to pick up.

In `fmFrameState` / `fmUnordered` mode, there is only one thread from downstream calling my filter's `GetFrame` callback, and there are 16 threads, that leaves 15 threads available for my custom thread to call `getFrame()` on my upstream.

In `fmParallel*` modes, VapourSynth spawns as many threads as possible to swarm the filter's `GetFrame` callback. Since the filter can't just return `nullptr` from the callback, I put condition variable there to wait for the custom thread to analyze frames. That blocks all the threads in the thread pool. Now the custom thread can no longer call `getFrame()` / `getFrameAsync()`, and can no longer unblock all the callback threads. It is effectively dead lock.

### Takeaway

Now I understand why, I don't blame VapourSynth for designing like this. It is simple and elegant: All `GetFrame` are equal. However, I do blame VapourSynth's documentation for not explaining the whole thing clearly. And it is not some trivial obscure details. It literally determine how a filter can be written. For example, for my filter, it just has to stay as `fmUnordered`.

1. At the bottom of [`getFrame`](http://www.vapoursynth.com/doc/api/vapoursynth4.h.html#getframe), there is a warning "Never use inside a filter’s “getframe” function." It is inaccurate information. What's actually correct is that, `getFrame` can't be used ANYWHERE in a `fmParallel*` filter, and `getFrame` can be used ANYWHERE in a non-`fmParallel*` filter, as long as there are more than 1 thread in the thread pool, which is usually the case for modern CPUs, unless user intentionally [changes](http://www.vapoursynth.com/doc/api/vapoursynth4.h.html#setthreadcount) it.
2. [`getFrameAsync`](http://www.vapoursynth.com/doc/api/vapoursynth4.h.html#getframeasync) is vulnerable to the thread pool issue the same way `getFrame` is. In fact, `getFrame` is just a thin wrapper adding the standard conditional-variable-wait logic on top of `getFrameAsync`.
3. The doc for the two functions assumes only external/library callers use them. And the doc for `VSFilterMode` doesn't fully explain the implication of each choice. I hope VapourSynth team can improve these 3 docs, which could be extremely valuable for others. Could be a bit too long to put in the page, and I don't see a Wiki section in this repo though.

**Comment by myrsloik** [comment]
I'm curious exactly how the black box you tried to wrap works.

1&2: getFrame isn't officially supported in those places, I simply fixed it well enough to be able to use as a fallback for avisynth compatiblity.

Can you make a small sample demonstrating the deadlock with getframe? That could actually be a bug.

**Comment by CrendKing** [comment]
Here's a rough demo of what I was talking about.

<details>
<summary>Filter code</summary>

```cpp
struct Context {
    const VSAPI *vsapi;

    VSNode *clip;

    std::map<int, const VSFrame *> frames;
    int maxGetFrameNo;
    int processedFrameNo;

    std::mutex mutex;
    std::condition_variable producerCv;
    std::condition_variable consumerCv;
};

auto VS_CC filterGetFrame(int n, int activationReason, void *instanceData, void **frameData, VSFrameContext *frameCtx, VSCore *core, const VSAPI *vsapi) -> const VSFrame * {
    auto *ctx = static_cast<Context *>(instanceData);

    {
        const std::unique_lock<std::mutex> lock(ctx->mutex);
        ctx->maxGetFrameNo = std::max(ctx->maxGetFrameNo, n);
    }
    ctx->producerCv.notify_one();

    std::unique_lock<std::mutex> lock(ctx->mutex);

    while (!ctx->frames.contains(n)) {
        ctx->consumerCv.wait(lock);
    }

    const VSFrame *frame = ctx->frames[n];
    ctx->vsapi->addFrameRef(frame);
    return frame;
}

auto VS_CC filterFree(void *instanceData, VSCore *core, const VSAPI *vsapi) -> void {
    auto *ctx = static_cast<Context *>(instanceData);

    for (auto &p : ctx->frames) {
        ctx->vsapi->freeFrame(p.second);
    }

    delete ctx;
}

auto VS_CC frameDone(void *instanceData, const VSFrame *frame, int n, VSNode *node, const char *errorMsg) -> void {
    if (errorMsg != nullptr) {
        return;
    }

    auto *ctx = static_cast<Context *>(instanceData);

    static const int SELECT_EVERY = 2;

    if (n % SELECT_EVERY == 0) {
        {
            const std::unique_lock<std::mutex> lock(ctx->mutex);
            ctx->frames.emplace(n / SELECT_EVERY, frame);
        }
        ctx->consumerCv.notify_all();
    }

    {
        const std::unique_lock<std::mutex> lock(ctx->mutex);
        ctx->processedFrameNo = n;
    }
    ctx->producerCv.notify_one();
}

auto requestFrames(Context *ctx) -> void {
    int requestFrameNo = 0;

    while (true) {
        {
            std::unique_lock<std::mutex> lock(ctx->mutex);

            while ((!ctx->frames.empty() && ctx->maxGetFrameNo < ctx->frames.rbegin()->first) || ctx->processedFrameNo < requestFrameNo - 1) {
                ctx->producerCv.wait(lock);
            }
        }

        ctx->vsapi->getFrameAsync(requestFrameNo, ctx->clip, frameDone, ctx);
        requestFrameNo += 1;
    }
}

auto VS_CC filterCreate(const VSMap *in, VSMap *out, void *userData, VSCore *core, const VSAPI *vsapi) -> void {
    auto *ctx = new Context;
    ctx->vsapi = vsapi;

    int propGetError = peSuccess;
    ctx->clip = vsapi->mapGetNode(in, "clip", 0, &propGetError);
    ctx->maxGetFrameNo = -1;
    ctx->processedFrameNo = -1;

    const std::array deps = {
        VSFilterDependency { ctx->clip, rpNoFrameReuse }
    };
    vsapi->createVideoFilter(out, "Demo", vsapi->getVideoInfo(ctx->clip), filterGetFrame, filterFree, fmParallel, deps.data(), 1, ctx, core);

    std::thread(requestFrames, ctx).detach();
}

VS_EXTERNAL_API(auto) VapourSynthPluginInit2(VSPlugin *plugin, const VSPLUGINAPI *vspapi) -> void {
    vspapi->configPlugin("com.crendking.vs_filters", "demo", "Demo", VS_MAKE_VERSION(1, 0), VAPOURSYNTH_API_VERSION, 0, plugin);
    vspapi->registerFunction("Demo", "clip:vnode", "clip:vnode;", filterCreate, nullptr, plugin);
}
```
</details>

Pair with this script:
```
import vapoursynth
vapoursynth.core.std.LoadPlugin(r'demo.dll')
input_clip.text.FrameProps().demo.Demo().set_output()
```

You will notice that `frameDone()` may get called once, then further `getFrameAsync()` from the `requestFrames` thread will not trigger the callback.

This works because of 2 factors:

1. A `fmParallel` upstream. All `text` filters [are `fmParallel`](https://github.com/vapoursynth/vapoursynth/blob/2804ed7a4926863f4a12e879d95155c4b05ecdf3/src/core/textfilter.cpp#L724), which triggers the "swarming" effect I was talking about. If you swap the order of the text and demo, it no longer blocks.
2. Not every `frameDone()` unblocks a `GetFrame` callback. If that `SELECT_EVERY` is 1, everything works. If it is above 1, suddenly dead block. This is because if `SELECT_EVERY == 1`, every `frameDone` unblocks one callback, `getFrameAsync` calls, that task gets pushed into the task queue earlier than the next `GetFrame` callback, then `frameDone` gets called, cycle repeats. If `SELECT_EVERY > 1`, once it returns, one `GetFrame` callback takes its place in the thread pool, and dead lock.

**Comment by myrsloik** [comment]
That's api misuse. You're not allowed to block infinitely in filtergetframe. All the threads get wedged in a wait inside your demo filter and then there are simply no threads left to process the rest.
You're fighting against the threading model. Either you do filter threading or you do library user threading.

**Comment by CrendKing** [comment]
@myrsloik Thanks for the the information. I get I'm not using the API you authors intend to, and it is completely OK however you guys design the API model of VS. But my original point was that there is no way I could know the info you gave here until I read all the source code of VS: There is no mentioning of `VSFilterGetFrame()` must not block indefinitely. There is no text about how a filter should implement it or how to use `getFrame()` with different filter modes. And there is not even a single word about thread pool or VS' threading model. The documentation is lacking critical information for us to write plugin properly.

All I'm asking is to update the doc to include how VS utilizes a thread pool to schedule tasks about frame handling. That both `VSFilterGetFrame()` and `getFrame()` share the thread pool. And `fmParallel*` immediately saturate the thread pool while the other two don't. With these information, competent developers will be able to figure out the rest, just from the doc.
