### ISSUE TITLE
FrameProp String Question

### ISSUE THREAD

**Issue by CineManiac93** [vapoursynth/vapoursynth#1085]
Is there a way to put out a frame prop as a string such as, 'core.text.Text(clip, str( clip.Matrix ) )' where it would extract the frameprop and convert it to a string?

**Comment by dnjulek** [comment]
What do you want to do with this string? Print it to frame? You need to explain the end goal.

**Comment by CineManiac93** [comment]
Apologies, yes I'd like to print it to the frame, but I don't want to use the font of `text.FrameProps`.

**Comment by CineManiac93** [comment]
```
uhdcsp_prps = add_hdr_measurement_props(uhdcsp, maxrgb=False, percentile=100, downscale=False, max_luminance=True, no_planestats=False, linearized= True)

uhdmap = core.std.CopyFrameProps(uhdmap, uhdcsp_prps, props=['HDRMax', 'HDRAvg'])

uhdmap = core.text.FrameProps(uhdmap, props=['HDRMax', 'HDRAvg'], alignment=9)
```

I'm using awsmfunc's `add_hdr_measurement_props`

I'd like to do something like 


`clip1 = core.assrender.Subtitle(clip1, text=str(clip2.HDR Max), alignment=9)`

**Comment by dnjulek** [comment]
you need to learn how strings work in python, use this as a reference and search on google
https://github.com/OpusGang/awsmfunc/blob/5c6d78dfc8e060007591516cefba0965b2713795/src/awsmfunc/base.py#L1238-L1279

**Comment by L4cache** [comment]
Frame Props is most likely to be changed every frame, and your intended technique of subtitling it won't support that I'm afraid.

**Comment by CineManiac93** [comment]
Okay, that's unfortunate, thank you, though.

**Comment by WolframRhodium** [comment]
```python3
clip1 = core.akarin.Text([clip1, clip2], format="{y.HDRMax}", alignment=9)
```
[ref](https://github.com/AkarinVS/vapoursynth-plugin?tab=readme-ov-file#text)
