### ISSUE TITLE
Query

### ISSUE THREAD

**Issue by rajib86sm87** [vapoursynth/vapoursynth#1086]
Hi,
I have VapourSynth R69 64 bit, python 3.12.5 64 bit, Git 2.46.0 64 bit, VSCode 1.92.2 64 bit. And vspreview 0.3.9. I ran a simple script - script.vpy.

`import vapoursynth as vs

core = vs.core

blank_clip = core.std.BlankClip(width=1920, height=1080, color=[0,255,0])

blank_clip.set_output()`

AFAIU this shows a green screen when run.

Runs fine with 0.3.9. But when I use the latest 0.9.0 I get an error.

![Output](https://github.com/user-attachments/assets/815d2cfa-85c8-4e70-9954-b5a630618e41)

What is wrong here? What am I doing wrong? What to do to fix this?

**Comment by Vodes** [comment]
I'm not sure why people keep thinking otherwise but vspreview and other packages from the relevant org aren't affiliated with vapoursynth.

In any case you just have to update stgpytools. Or rather update vsjet because that includes the former as a proper dependency now.

**Comment by amayra** [comment]
more like what are doing 

or what are you trying to do

**Comment by LightArrowsEXE** [comment]
> more like what are doing
> 
> or what are you trying to do

more like "what are you even trying to say, @amayra?"
