### ISSUE TITLE
Vapoursynth-Portable not updated on PyPi

### ISSUE THREAD

**Issue by Ichunjo** [vapoursynth/vapoursynth#1087]
Vapoursynth portable is still stuck on R66 on PyPi. 
I believe this commit removed the auto upload https://github.com/vapoursynth/vapoursynth/commit/4e45c5b21006ddf4864ae63c2cedc7366def3408#diff-5ce5c9ff86f58b1f87b35b5227b2e84cb69f022d6741e1854f3e1e181091773cL186-L192

**Comment by myrsloik** [comment]
Duplicate
