### ISSUE TITLE
R70 not working after install

### ISSUE THREAD

**Issue by tuanden0** [vapoursynth/vapoursynth#1090]
OS: Windows 11
Python: 3.8.10

After install Vapoursynth R70, run command `vspipe --help` and nothing happended, nothing printed on stdout.

Tried encode video with command `"vspipe" -c y4m "test.vpy" - | "x265" --y4m --preset veryslow --crf 18 -o "test.hevc" -` and it returned `x265 [error]: unable to open input file <->`

Rollback to R69, everything is OK.

**Comment by myrsloik** [comment]
Works here
Does vspipe --version work?

**Comment by tuanden0** [comment]
@myrsloik 
no, it printed nothing

**Comment by myrsloik** [comment]
Make sure the visual studio runtime is the latest version. If possible run it under a debugger to see where it crashes.

**Comment by tuanden0** [comment]
@myrsloik @doomtop 

I can confirm that after install latest `vc_runtime 14.36` version R70 works.
