### ISSUE TITLE
Output RGB24 rawdata does not work

### ISSUE THREAD

**Issue by JepEtau** [vapoursynth/vapoursynth#1092]
I try to output frames as rawdata in rgb24
see attached picture

![{26818E18-57C3-47DF-A32E-4558E9BA17D3}](https://github.com/user-attachments/assets/b4d25817-41d2-48b3-ab2b-8aa3852bfdf9)

but it works with yuv420p8
![{EFFDFD0E-9DF6-40D2-B13A-6128ABCAA50A}](https://github.com/user-attachments/assets/6ae6accc-6b0c-43a8-8dc3-658836433b07)

**Comment by RivenSkaye** [comment]
This looks like an issue with whatever you're using to preview the image, and the assumptions it makes about the frame data layout. Ffmpeg will sometimes do this as well, and specifying the planar order as BGR will often fix the rendering. With your current setup, try `clip.std.ShufflePlanes([2,1,0], colorfamily=vs.RGB24).set_output()`

**Comment by dnjulek** [comment]
are you displaying planar RGB without converting to packed?

**Comment by JepEtau** [comment]
> This looks like an issue with whatever you're using to preview the image, and the assumptions it makes about the frame data layout. Ffmpeg will sometimes do this as well, and specifying the planar order as BGR will often fix the rendering. With your current setup, try `clip.std.ShufflePlanes([2,1,0], colorfamily=vs.RGB24).set_output()`

it has nothing to do with planes.
whatever I use to preview the image: mpv, ffmpeg, or as subprocess of a python script to display with matplotlib, write to image, send to a ffmpeg subprocess, -> same problem.
If i replace vspipe by whatever else (Avisynth, FFMpeg, numpy array, ...) as the input of the tool to preview a video, it works perfectly.

there is a bug in vapoursynth or the doc is erroneous, or vapoursynth doesn't support to output rawdata,

**Comment by JepEtau** [comment]
> are you displaying planar RGB without converting to packed?

There is no conversion.
It's not written in vapoursynth's doc whether the RGB output is packed or planar.
