### ISSUE TITLE
Is there a python-free version?

### ISSUE THREAD

**Issue by Sazu-bit** [vapoursynth/vapoursynth#1098]
I'd like to ask if there's a python free release. Much of the programming seems to be based on C++. Python is currently getting in my way, so I am attempting to purge it. Unfortunately I rely on FFMPEG which depends on vapoursynth and in turn vapoursynth depends on python.

**Comment by myrsloik** [comment]
You can use the C API in vapoursynth4.h but then obviously you miss out on things being user friendly.

**Comment by DJATOM** [comment]
If you don't need vapoursynth support in ffmpeg, just compile it on your own without vapoursynth support. That should be much easier to do than stripping down python stuff from vapoursynth.

**Comment by Sazu-bit** [comment]
That sounds like more of a plan, off to the ffmpeg team
