### ISSUE TITLE
The array returned by get_read_array() in python shouldn't be writable

### ISSUE THREAD

**Issue by myrsloik** [vapoursynth/vapoursynth#128]
No idea how to fix it

**Comment by myrsloik** [comment]
Proper support isn't implemented for read only array thingies in cython yet. But maybe one day it will be...

**Comment by splinter98** [comment]
That's only half true. Cython's memoryview doesn't support read only. However cython does expose the functions to enable a class to have the same functionality, which read only is supported.

**Comment by myrsloik** [comment]
Poke. I know this is a small thing but has there been any progress?

**Comment by splinter98** [comment]
Some, I'm about three quarters my way through implementing this need to get slicing frame slicing working properly (as in being able to select a smaller region of the frame), and then I should be good to submit a pull request.

**Comment by myrsloik** [comment]
Yearly poke

**Comment by myrsloik** [comment]
Probably fixed
