### ISSUE TITLE
Python Crashes with EXC_BAD_ACCESS, KERN_INVALID_ADDRESS

### ISSUE THREAD

**Issue by ChrisK2** [vapoursynth/vapoursynth#135]
```
Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000

Thread 2 Crashed:
0   libsystem_platform.dylib      	0x00007fff8e4383ca _platform_memmove$VARIANT$Nehalem + 138
1   org.python.python             	0x00000001005057fd bufferedwriter_write + 498
2   vapoursynth.so                	0x000000010092bc99 __Pyx_PyObject_CallOneArg + 329
3   vapoursynth.so                	0x000000010096e8fa __pyx_f_11vapoursynth_frameDoneCallback + 2586
4   libvapoursynth.dylib          	0x00000001009ce678 VSThreadPool::returnFrame(std::__1::shared_ptr<FrameContext> const&, std::__1::shared_ptr<VSFrame> const&) + 120
5   libvapoursynth.dylib          	0x00000001009ce1dd VSThreadPool::runTasks(VSThreadPool*, std::__1::atomic<bool>&) + 3565
6   libvapoursynth.dylib          	0x00000001009cf745 void* std::__1::__thread_proxy<std::__1::tuple<void (*)(VSThreadPool*, std::__1::atomic<bool>&), VSThreadPool*, std::__1::reference_wrapper<std::__1::atomic<bool> > > >(void*) + 101
7   libsystem_pthread.dylib       	0x00007fff870782fc _pthread_body + 131
8   libsystem_pthread.dylib       	0x00007fff87078279 _pthread_start + 176
9   libsystem_pthread.dylib       	0x00007fff870764b1 thread_start + 13
```
Python 3.4.2 on OS X 10.10.1, VapourSynth master @ a1775cdc73fab
Full Crash Report: http://privatepaste.com/7dea23449f
Script Excerpt: http://privatepaste.com/c70cf1b761 (Example, won't work like that)
vsenc: http://privatepaste.com/ce3f2c134f

The loop processes fine various times, the crash happens  directly after x264 in ``encoder.x264enc()`` finishes. The prints for "Loading new sourcefile" or "Trim:" did not happen.

**Edit:** on further inspection, it seems like the crash happens while trying to access the last frame of the clip: http://privatepaste.com/8dbc9a29c1 . Note how x264 is asked to encode 528 frames (``--frames 528`` comes from the clip duration), but only actually manages to encode 527.

I also had this once happen on a different (Ubuntu) machine.

Edit 2: When restarting the script to encode the exact same segment again, encoding proceeds without error and the script continues to run. So this seems to be no user-input error.

**Comment by myrsloik** [comment]
No enough information to reproduce
