### ISSUE TITLE
Missing overloads from std.AssumeFPS

### ISSUE THREAD

**Issue by haasn** [vapoursynth/vapoursynth#146]
The original avisynth function includes some overloads for AssumeFPS, the most important of which is the ability to pass in a float instead of a ratio.

It would be cool if at least this overload could be implemented, since it makes interfacing with eg. mpv a bit easier.

**Comment by myrsloik** [comment]
The problem is that a raw float rarely is what the user actually wants. The user wants a float appropriately rounded to a rational number a bit away from it like 24000/1001 for 23.976. Except when adjusting video duration to match audio. Then they don't.

What's wrong with using the Fraction class in python?

**Comment by haasn** [comment]
I don't know much python, so I can't comment on Fraction in particular. What I do know is that eg. mpv provides me only with a reported container fps as a float, so I need to get from 23.976024627685547 or whatever it reports me to a ratio. Right now I'm using fpsnum = int(fps * 1e6), fpsden = 1e6 but for the sake of convenience a float interface that does something similar might as well be provided.

**Comment by splinter98** [comment]
With regards to the Fraction class try the following:

````python
from fractions import Fraction
#Import vapoursynth & get core

fps = Fraction(23.976024627685547)

output = core.std.AssumeFPS(clip, fpsnum=fps.numerator, fpsden=fps.denominator)
````

However most float based framerates are either 23.676....., 29.970.... or 59.940.... which have a denominator of 1001, and the

**Comment by myrsloik** [comment]
I'll add a function that "cleverly" converts a float to a rational framerate then. And if no common integer or 1001 denominator fps is close enough it does fpsnum = int(fps * 1e6), fpsden = 1e6.

Or something like that.

**Comment by myrsloik** [comment]
Rejected. There's no reason to have an "almost assume this fps" function in the core. I'll help you with a python function if you can't figure out how to write one yourself.
