### ISSUE TITLE
Timecode output from vspipe

### ISSUE THREAD

**Issue by myrsloik** [vapoursynth/vapoursynth#147]
VSPipe should be able to also output a timecode v2 file for use during mkv muxing to make vfr handling easier.

**Comment by dubhater** [comment]
I guess it's done.

**Comment by myrsloik** [comment]
Looks done to me, unless it turns out that the accumulated error becomes too big for long clips.

**Comment by dubhater** [comment]
Depends how long is a long clip. At the end of a clip with 3\*60\*60\*60000/1001 frames, the timecodes are off by less than 1 microsecond. But even that can be avoided.
