### ISSUE TITLE
Clang build an unusable VS on ARM

### ISSUE THREAD

**Issue by YamashitaRen** [vapoursynth/vapoursynth#150]
Vapoursynth (latest git) works fine if I build it with gcc but it throws me errors if I try to run it after building it with clang 3.5 (on ARM) : https://gist.github.com/YamashitaRen/e8c004f6d5fc2018f509

**Comment by myrsloik** [comment]
That's simply the generic message for when the python module can't load the main library. Is the library really in the right place?

**Comment by YamashitaRen** [comment]
Why wouldn't it be ?
I'm only using clang insteaf of gcc...
https://gist.githubusercontent.com/YamashitaRen/524dad48b91733ee1cbc/raw/449f999fa300b9dd32fe004e0842a4ea0f39224c/Make%20&&%20make%20install
Really, putting aside the use of clang, I have done nothing fancy.

**Comment by dubhater** [comment]
getCPUFeatures() doesn't set can_run_vs when the target isn't x86. https://github.com/vapoursynth/vapoursynth/blob/master/src/core/cpufeatures.c#L55 Gcc works only by accident.

**Comment by YamashitaRen** [comment]
I confirm the fix to be working :)
