### ISSUE TITLE
resize filter didn't do any colorspace conversions between BT601 and BT709

### ISSUE THREAD

**Issue by pingplug** [vapoursynth/vapoursynth#151]
I resize a video clip from 1440x1080(YUV420P8) to 848x480(YUV420P8), but I found the colorspace is still BT709
I tried a wrong table and inv_table in sws_setColorspaceDetails(), but the result is the same
It seemd that sws_setColorspaceDetails() ignored inv_table and table

**Comment by myrsloik** [comment]
It sure is ignoring everything and it hates your way of life!

SWScale is a steaming pile of shit. The plan is to simply map all internal resize calls to https://github.com/sekrit-twc/zimg in the next release if I have the time time write some wrapper code.

Use fmtconv or zimg for proper handling.
