### ISSUE TITLE
SelectEvery doesn't like cycle=1

### ISSUE THREAD

**Issue by mgroshans** [vapoursynth/vapoursynth#152]
In avisynth to duplicate every frame I would simply `clp.selectevery(1, 0, 0)` so in vapoursynth I attempted `clp.std.SelectEvery(cycle=1, offsets=[0, 0]` but that gives me an error, `SelectEvery: invalid cycle size`.

I worked around it by using `clp.std.SelectEvery(cycle=2, offsets=[0, 0, 1, 1])` but it feels a little more verbose than necessary.

**Comment by myrsloik** [comment]
Not being identical to avisynth isn't necessarily a bug. SelectEvery has a lot more restrictions to prevent the weirdest abuses that should be done with other functions to be more clear.

Use Interleave([clip, clip]) for duplication.
