### ISSUE TITLE
SelectEvery does not adjust play time

### ISSUE THREAD

**Issue by fr3aker** [vapoursynth/vapoursynth#155]
When using SelectEvery the output clip will have the exact same play time as the input clip (with less fps). This sounds counter-intuitive and should probably be changed.

**Comment by myrsloik** [comment]
I don't understand your point.

**Comment by fr3aker** [comment]
One would expect the ouput clip to still have the same frame rate as the input clip and a shorter play time. Currently you have the same play time for the truncated clip with a changed frame rate.

**Comment by myrsloik** [comment]
Sometimes you want one thing, sometimes another. Maybe I should make time adjustments optional in the filters where both can make sense.

**Comment by fr3aker** [comment]
It should be fine if the documentation at least says what the user can expect to happen. I agree that fixing the fps with assumefps is trivial, but for me this behaviour was very unexpected.

**Comment by myrsloik** [comment]
Fixed in R27
