### ISSUE TITLE
Add support to save VS scripts (.py) outside of python site-packages

### ISSUE THREAD

**Issue by sl1pkn07** [vapoursynth/vapoursynth#156]
Hi

is possible add support in the build system, a save a VS python scripts outside of system python site-packages?

the method is (thanks @4re for the suggestion) save a file called, for example, 'vapoursynth.pth' containing a path of the VS python modules, for example the plugin dir 'foo/lib/vapoursynth' (or the path set by --libdir option) in the python site-package (as vapoursynth.so)

is for centralize all VS plugins/scripts in a same place

greetings

**Comment by myrsloik** [comment]
Sounds reasonable I guess. I'll think about it.

**Comment by dubhater** [comment]
It should be doable.

**Comment by myrsloik** [comment]
On windows I guess it's doable for a single global folder at least. I wonder if I can make it search per user directories too.

**Comment by splinter98** [comment]
Another option is to use [venv](https://docs.python.org/3/library/venv.html).

On Windows:
```Batch
> py -3 -m venv --system-site-packages vspython
> copy "C:\Program Files (x86)\VapourSynth\core64\vspipe.exe" vspython\Scripts\
```

On Linux:
```Bash
$ python3 -m venv --system-site-packages vspython
$ cp /usr/local/bin/vspipe vspython/bin
```

Now running vspipe from that location will use all plugins located in it's local site-packages directory and keeping them separate from the main python installation.

If you want to put this vspipe back on the path then run the following:

Windows:
```batch
> vpython\Scripts\activate
```

Linux:
```Bash
$ source vpython/bin/activate
```

If any vapoursynth plugin is in pypi or has a distutils running `pip install` or `python setup.py install` will install into this virtual environment.

run `deactivate` when finished

**Comment by Paviluf** [comment]
I agree it will be cleaner that way.

**Comment by myrsloik** [comment]
Python already has one gazillion ways of doing this.

**Comment by Paviluf** [comment]
Can you show us a simple way of doing this please ?

**Comment by 4re** [comment]
What's described in first post is not simple enough? I don't understand the need for anything else.

**Comment by splinter98** [comment]
Really the python scripts need to make their way into pypi so you can pip install them. May as well use the existing package managing system for python for python scripts.

If the issue is a permissions issues (because user doesn't have write access to) then use --user or --home flags as documented in the python documentation: https://docs.python.org/3/install/index.html#alternate-installation-the-user-scheme

Now I can see an argument for doing something similar to the way flask web framework wraps ups it's plugins but that's a slightly different topic. (i.e. being able to do from vs.plugins.some_script import some_function).

**Comment by rectalogic** [comment]
Instead of copying `vspipe` into the `venv/bin`, you can just set `PYTHONEXECUTABLE` to `venv/bin/python` e.g. `PYTHONEXECUTABLE=.../venv/bin/python vspipe -c y4m something.py - | ...`

**Comment by Setsugennoao** [comment]
This is more than necroposting, you've basically exhumed the body and beat it up.
