### ISSUE TITLE
Memory leak in assvapour destructor

### ISSUE THREAD

**Issue by sekrit-twc** [vapoursynth/vapoursynth#158]
Script: http://pastebin.com/TQs4sv9G

The cached frame objects AssData::lastframe and AssData::lastalpha are not freed in assFree, resulting in a leak of two frame buffers per assvapour instance.

Fix:

diff --git a/vapoursynth-R26/src/filters/assvapour/assvapour.c b/vapoursynth-R26/src/filters/assvapour/assvapour
index fcda1c4..8885dd7 100644
--- a/vapoursynth-R26/src/filters/assvapour/assvapour.c
+++ b/vapoursynth-R26/src/filters/assvapour/assvapour.c
@@ -286,6 +286,8 @@ static void VS_CC assFree(void *instanceData, VSCore *core, const VSAPI *vsapi)
 {
     AssData *d = (AssData *)instanceData;
     vsapi->freeNode(d->node);
+    vsapi->freeFrame(d->lastframe);
+    vsapi->freeFrame(d->lastalpha);
     ass_renderer_done(d->ass_renderer);
     ass_library_done(d->ass_library);
     ass_free_track(d->ass);

**Comment by dubhater** [comment]
Looks reasonable.
