### ISSUE TITLE
Feature: Port -1 and -2 field orders to EEDI3, nnedi3, etc.

### ISSUE THREAD

**Issue by sekrit-twc** [vapoursynth/vapoursynth#159]
Please add support for using the new semantics of _FieldBased to automatically select field order. This is required to make full rate (1 frame per field) deinterlacing work in the presence of field dominance inversions. In EEDI3 and nnedi3 for AviSynth, these were field order modes "-1" and "-2".

**Comment by myrsloik** [comment]
Done in this project, I guess

**Comment by HolyWu** [comment]
Should VIVTC be updated to support this feature as well?

**Comment by myrsloik** [comment]
The answer is maybe some day. It's on my list. There's also the issue of VDecimate not having memory efficient caching...
