### ISSUE TITLE
AddBorders missing check for values < 0

### ISSUE THREAD

**Issue by splinter98** [vapoursynth/vapoursynth#161]
If you set any of the side parameters for AddBorders to a value less than 0 Vapoursynth crashes with an error about being unable to free invalid memory pointers.

We should check for this and raise a more useful error to the user.

Sample script to reproduce error:
```python
import vapoursynth as vs

core = vs.get_core()

clip = core.std.BlankClip(format=vs.YUV420P8)

clip.std.AddBorders(top=-2).set_output()
```

**Comment by myrsloik** [comment]
Fixed, obviously the weird error is because of the memory corruption.
