### ISSUE TITLE
R27 windows installation missing plugins?

### ISSUE THREAD

**Issue by brachna** [vapoursynth/vapoursynth#165]
Is R27 installer for Windows missing core plugins?

core.list_functions() doesn't list imwri and avs namespaces.
core64/plugins folder doesn't have them as well.

VapourSynth x64 on Windows 8.1.

**Comment by myrsloik** [comment]
1. There is no avisynth support for x64.
2. http://forum.doom9.org/showthread.php?t=170981 not included since it's huge and messy right now
