### ISSUE TITLE
Configure Failed on Mac OS X 

### ISSUE THREAD

**Issue by vongola12324** [vapoursynth/vapoursynth#166]
There's an error when I run ./configure.

System: Mac OS X Yosemite
Compile: clang-602.0.53  
Log:
checking dynamic linker characteristics... darwin14.3.0 dyld
checking how to hardcode library paths into programs... immediate 
./configure: line 17002: syntax error near unexpected token 'AVCODEC,'
./configure: line 17002: '       PKG_CHECK_MODULES(AVCODEC, libavcodec >= 54.34.1)'

How to fix it? :cry:

**Comment by captainadamo** [comment]
You don't have libavcodec installed.

**Comment by dubhater** [comment]
This looks like exactly your problem: http://myitcorner.com/blog/?p=207

**Comment by robertmk** [comment]
I have the exact same problem but in my case I installed pkg-config from source and not using darwin ports or homebrew and I get the same error. I have installed libavcodec from recent source.

**Comment by robertmk** [comment]
Never mind. I did not rerun autogen after installing pkg-config. Now the error is gone.
