### ISSUE TITLE
glitch - R27 w/FFMS2 2.21 duplicates first second of video

### ISSUE THREAD

**Issue by dvdan23** [vapoursynth/vapoursynth#167]
vapoursynth R27 seems to have introduced a funky behavior the first second or so of of a video gets duplicated causing a glitch. happens with no filters, just open a video with ffms2-2.21 using vspipe to ffmpeg. 

reverting back to R26 and ffms2-2.20 and the glitch goes away.

**Comment by dubhater** [comment]
Does it happen if you make vspipe output to a file (raw yuv with y4m headers)? Can you produce one such file with r27, and one with r26?

**Comment by dvdan23** [comment]
I'll try to get this done this evening.

**Comment by dvdan23** [comment]
Here you go. First second of video is duplicated (glitch) in the R27 versions. No change with file vs pipe output.

Vapoursynth R26 / FFMS2.20
http://publish.dvlabs.com/dvlabs/vapoursynth/tears-R26-FFMS220.mp4

Vapoursynth R27 / FFMS2.21
http://publish.dvlabs.com/dvlabs/vapoursynth/tears-R27-FFMS221.mp4
http://publish.dvlabs.com/dvlabs/vapoursynth/tears-R27-FFMS221-y4m.mp4

Same script on each;
#!/usr/bin/env python3
import vapoursynth as vs
core = vs.get_core()
core.std.LoadPlugin(path=r'/usr/local/lib/libffms2.so')
src = core.ffms2.Source(source=r'$1')
src.set_output()

**Comment by dubhater** [comment]
Is it better with the current ffms2 from git?

**Comment by dvdan23** [comment]
Yep!
