### ISSUE TITLE
imwri: YUV dump

### ISSUE THREAD

**Issue by maxlovic** [vapoursynth/vapoursynth#168]
Hi!
Had a look at VapourSynth to automate AviSynth tasks with Python. What I need to do is to convert BMP images to YUV raw files.
I wrote the following script:
```
import vapoursynth as vs
core = vs.get_core()
print(core.version())
image = core.imwri.Read('input.bmp', alpha=False)
image = core.std.CropAbs(image, 4224, 2176, 26, 7)
image = core.resize.Bicubic(image, format=vs.YUV420P8)
core.imwri.Write(image, 'YCbCr', 'output.yuv')
```

Well, that is not implemented in imwri plugin. Is there a way to gain access to the image buffer within a Python script to dump the file myself?

**Comment by splinter98** [comment]
Several ways:

The default way is through vspipe using ```image.set_output()``` and ```vspipe script.vpy output.yuv```

But a pure python way:

```python
with open("output.yuv", "wb") as f:
    image.output(f)
````

**Comment by maxlovic** [comment]
Thanks a lot!
