### ISSUE TITLE
Add float support to more functions and optimize them

### ISSUE THREAD

**Issue by myrsloik** [vapoursynth/vapoursynth#169]
All functions should have float support (if it makes sense at all).
Especially the ones from genericfilters is missing this.

**Comment by IFeelBloated** [comment]
been thinking about it but got this feeling that genericfilters.cpp needs rewriting rather than modifying to support float, even the GenericParams struct needs drastic modifications as some parameters will go float...

**Comment by myrsloik** [comment]
Yes, parts of it will probably need to be redone at least. YAY! But that isn't the real reason I've turned my procrastination all the way up to 11.

For example Convolution would now need to take either a float or integer array as input. Or something. I haven't decided how to make that stuff make sense. Even thought about add an argument type that's float or integer but that's probably a horrible idea too. Think of an elegant solution to that and this will get somewhere. It's one of the few things that really should be done in the core that isn't a major new feature (audio, plugin management, api revision and so on)

**Comment by myrsloik** [comment]
The code itself is also very simple so rewriting it isn't really an issue.

**Comment by IFeelBloated** [comment]
I'll just make matrix[] in convolution float, internal calculation will always be double for any pixel type, and cast to the target format when the calc is done..

**Comment by IFeelBloated** [comment]
Got an idea here, so matrix[] goes float (value ranges from 0.0-1.0) as the parameter BUT, scale the values within to 0-1024 internally for integer formats so no performance loss to integer stuff and values stay double for float stuff, no scaling

**Comment by myrsloik** [comment]
Done

**Comment by WolframRhodium** [comment]
Will BoxBlur have floating point support?
[Guided Filter](http://kaiminghe.com/eccv10/index.html) requires it.

**Comment by myrsloik** [comment]
I guess it could be added easily. Rounding errors won't be a problem?

**Comment by WolframRhodium** [comment]
No, I think.

**Comment by myrsloik** [comment]
Float support added (but not tested yet)

**Comment by WolframRhodium** [comment]
Thanks. It‘s nearly identical to Convolution (except at the border, which doesn't matter).
