### ISSUE TITLE
Splice cause access violation when clip format mismatch

### ISSUE THREAD

**Issue by MonoS** [vapoursynth/vapoursynth#174]
As the title, vapoursynth raise a 0xC0000005 error (AFAIK access violation) when splicing two clip with different format
	
	import vapoursynth as vs
	
	core = vs.get_core()
	
	YUV = core.std.BlankClip(width=10, height=10, format=vs.YUV420P8, length=1)
	RGB = core.std.BlankClip(width=10, height=10, format=vs.RGB24, length=1)
	
	test = core.std.Splice([YUV, RGB], mismatch=True)
	
	test.set_output()

**Comment by dubhater** [comment]
What application did you use to run this script?

**Comment by MonoS** [comment]
After further inspection, the problem resides into the preview of vsedit, getting only the information about the clip or trying to open it with vspipe [causing "can't output clip with varying dimension"] don't cause the crash.

My apologies
