### ISSUE TITLE
vspipe console output 

### ISSUE THREAD

**Issue by brothermechanic** [vapoursynth/vapoursynth#176]
Hello
Thank you for this great software!
I have a issue
i run vspipe
vspipe camera1.vpy -
http://wstaw.org/m/2015/09/09/plasma-desktopJv4437.png
Is this output normal? how to hide it?

**Comment by myrsloik** [comment]
Of course it's normal. The - means output to stdout. Use /dev/null instead.

**Comment by brothermechanic** [comment]
Oh, sorry!
Thank you!
