### ISSUE TITLE
How to build on Raspberry Pi?

### ISSUE THREAD

**Issue by bluepuma77** [vapoursynth/vapoursynth#177]
I tried to build vapoursynth on a Raspberry Pi 2 `Linux pi 3.18.0-trunk-rpi2 #1 SMP PREEMPT Debian 3.18.5-1~exp1+rpi19 (2015-08-08) armv7l GNU/Linux` based on latest [Debian](https://github.com/debian-pi/raspbian-ua-netinst), but didn't succeed. In addition to the `INSTALL` file requirements I had to install `apt-get install cython autoconf libtool `.

Then I failed with the tesseract libraries, even though I installed pretty much everything apt-get provided, finally found the disable switch `./configure --disable-ocr`, I think this bit should be added to the the [`INSTALL` file](https://github.com/vapoursynth/vapoursynth/blob/master/INSTALL).

Then I received an `configure: error: C++ compiler does not understand std::mutex (a C++11 feature).` error and I tried to use newer g++ and gcc compilers via 
```
apt-get install gcc-4.8
apt-get install g++-4.8
update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50
update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50
```
but finally failed with missing libraries
```
root@pi:~/vapoursynth# make
  CXX    src/core/libvapoursynth_la-cachefilter.lo
src/core/cachefilter.cpp: In member function 'void VSCache::adjustSize(bool)':
src/core/cachefilter.cpp:128:20: warning: enumeration value 'caNoChange' not handled in switch [-Wswitch]
             switch (recommendSize()) {
                    ^
src/core/cachefilter.cpp:140:20: warning: enumeration value 'caGrow' not handled in switch [-Wswitch]
             switch (recommendSize()) {
                    ^
  CC     src/core/libvapoursynth_la-cpufeatures.lo
src/core/cpufeatures.c:60:22: fatal error: sys/auxv.h: No such file or directory
 #include <sys/auxv.h>
                      ^
compilation terminated.
Makefile:1199: recipe for target 'src/core/libvapoursynth_la-cpufeatures.lo' failed
make: *** [src/core/libvapoursynth_la-cpufeatures.lo] Error 1
```

Is ist possible to build vapoursynth on an Raspberry Pi?

**Comment by dubhater** [comment]
``auxv.h`` is not really required. If you can't find it anywhere in ``/usr/include`` (``find /usr/include -name auxv.h``), just apply this patch:
```diff
diff --git a/src/core/cpufeatures.c b/src/core/cpufeatures.c
index 97f173d..6a3bb2b 100644
--- a/src/core/cpufeatures.c
+++ b/src/core/cpufeatures.c
@@ -57,12 +57,12 @@ void getCPUFeatures(CPUFeatures *cpuFeatures) {
     }
 }
 #elif defined(VS_TARGET_OS_LINUX)
-#include <sys/auxv.h>
+//#include <sys/auxv.h>
 
 void getCPUFeatures(CPUFeatures *cpuFeatures) {
     memset(cpuFeatures, 0, sizeof(CPUFeatures));
 
-    unsigned long long hwcap = getauxval(AT_HWCAP);
+    unsigned long long hwcap = 0; //getauxval(AT_HWCAP);
 
     cpuFeatures->can_run_vs = 1;
 
```

**Comment by wm4** [comment]
(Why would you want to run VS on RPI...??)

**Comment by myrsloik** [comment]
Some things we'll never know...
