### ISSUE TITLE
Add quantum-depth=32 support to imwri

### ISSUE THREAD

**Issue by Kagami** [vapoursynth/vapoursynth#181]
It would be nice to have support for 32bit quantum depth in imwri plugin since some image format (e.g. EXR) allow it.

**Comment by myrsloik** [comment]
Why aren't you using float (hdri) for 32bits? That's probably the more sane thing to do...

**Comment by Kagami** [comment]
I'm using HDRI, but I want 32bit float images. Here is my test script:

```python
import vapoursynth as vs
core = vs.get_core()
c = core.ffms2.Source("in.mkv")[0]
c = core.fmtc.resample(c, css="444")
c = core.fmtc.bitdepth(c, bits=32)
c = core.fmtc.matrix(c, mat="709", col_fam=vs.RGB)
c = core.imwri.Write(c, "EXR", "out%06d.exr")
c.set_output()
```

`identify` reports that output EXRs have only 16bit per component.

**Comment by myrsloik** [comment]
I'll have to test it then and see what it does. Could be some kind of bug.

**Comment by myrsloik** [comment]
Q32 support added (not really tested yet but will be soon)

**Comment by Kagami** [comment]
Thanks for the fix. It turned out IM [doesn't support 32bit EXRs](http://git.imagemagick.org/repos/ImageMagick/blob/a788814dc4711bb631b1aeb0eb97b8ebf7b3d38d/coders/exr.c#L541) though, only half-float. So the only format that can benefit from this change (for writing) is probably 32bpc TIFF.
Btw, [OpenImageIO library](https://github.com/OpenImageIO/oiio) looks like a good alternative for that kind of things.

**Comment by myrsloik** [comment]
Too bad all general libraries are shit. I'd rather find a library that only does a few of the high bitdepth formats well.
