### ISSUE TITLE
EEDI3 returns a tearing image when "dh=True"

### ISSUE THREAD

**Issue by Evalyn-155** [vapoursynth/vapoursynth#182]
It looks like screen tearing.

![eedi3](https://cloud.githubusercontent.com/assets/11040951/10282835/725b4e96-6baf-11e5-84ac-343f8b3a432a.jpg)

When "dh=Ture", It generally produce a significent horizonal tearing area.

Nobody has used eedi3 before casue it's so so so slow?

**Comment by dubhater** [comment]
Is it always at the same height?

**Comment by dubhater** [comment]
Never mind, found it.
