### ISSUE TITLE
<vapoursynth/VapourSynth.h> or <VapourSynth.h>?

### ISSUE THREAD

**Issue by invisiblearts** [vapoursynth/vapoursynth#184]
.pc files gives `/path/to/include/vapoursynth` so it should be `<VapourSynth.h>`
However under usual circumstances it should be /path/to/include, otherwise most plugins(including `<vapoursynth/VapourSynth.h>`) won't build if vapoursynth is installed in a non-standard directory and pkg-config is used for cflags.

**Comment by dubhater** [comment]
Then the plugins that use ``#include <vapoursynth/VapourSynth.h>`` should be updated.

**Comment by invisiblearts** [comment]
But on UNIX-like systems these plugins build w/o questions because by default paths like `/usr/local/include` are searched, and the use of `#include <VapourSynth.h>` will break that..

**Comment by dubhater** [comment]
pkg-config gives you the correct path to VapourSynth.h. How is anything going to break?

**Comment by invisiblearts** [comment]
Well, just some configure scripts need to add the pkg-config part even when vapoursynth is installed in a standard prefix.

**Comment by dubhater** [comment]
That makes no sense. The point of a configure script is to adapt the Makefile to the user's system. It cannot assume anything about VapourSynth's location.

**Comment by invisiblearts** [comment]
Got it.
