### ISSUE TITLE
hdri in imagemagick has to be enabled for vapoursynth to be able to build against it, bug or feature?

### ISSUE THREAD

**Issue by 4re** [vapoursynth/vapoursynth#185]
As the title says, I didn't notice because I had it set enabled since it was allowed, but https://github.com/4re/vapoursynth-portage/issues/19 can't build because of that (neither me).
From the change-log I had the impression it was optional.

**Comment by myrsloik** [comment]
It should be optional, I'll take a look at it

**Comment by 4re** [comment]
I assume it's fixed now, thx.
