### ISSUE TITLE
VapourSynth header is c++11?

### ISSUE THREAD

**Issue by 4re** [vapoursynth/vapoursynth#186]
Basically, when trying to compile packages who use C++98, like d2vsource, the compiler starts to scream like crazy stuff like:
```
/usr/include/vapoursynth/VSHelper.h:52:65: error: default template arguments may not be used in function templates without -std=c++11 or -std=gnu++11
 static inline T* vs_aligned_malloc(size_t size, size_t alignment) {
```
https://github.com/4re/vapoursynth-portage/issues/21

r27 was ok about this, r28 is not.

**Comment by myrsloik** [comment]
Right, I forgot that you're not allowed to do that before C++11. Should be fixed now.

**Comment by 4re** [comment]
I can't reopen this, but nothing changed (or almost nothing).
https://bpaste.net/show/2812c48a2041

**Comment by myrsloik** [comment]
Try again now

**Comment by 4re** [comment]
Now the world is bright and wonderful again, thx.
