### ISSUE TITLE
vspipe version check

### ISSUE THREAD

**Issue by kice** [vapoursynth/vapoursynth#197]
vspipe check the local vapoursynth version if is match the vspipe version before run.

**Comment by myrsloik** [comment]
Why? Vspipe only uses the api and because of that it'll work with ancient main library versions too

**Comment by kice** [comment]
I share the vpy with my friends, but some of them did not add vspipe to the path. So I always share the vpy with vspipe. One told me that R27 vspipe cannot run with R28 VS and it took me a long time to solve the problem.

**Comment by myrsloik** [comment]
Don't do half assed distributions.
