### ISSUE TITLE
cannot compile

### ISSUE THREAD

**Issue by emi1e** [vapoursynth/vapoursynth#198]
Hi,
I have been trying to compile Vapoursynth today, I am stuck with this issue :

[...]
  YASM     src/core/asm/x86/merge.lo
  YASM     src/core/asm/x86/transpose.lo
  CXXLD    libvapoursynth.la
src/core/.libs/libvapoursynth_la-exprfilter.o: In function `jitasm::Frontend::ResolveJump()':
exprfilter.cpp:(.text._ZN6jitasm8Frontend11ResolveJumpEv[_ZN6jitasm8Frontend11ResolveJumpEv]+0x26a): warning: memset used with constant zero length parameter; this could be due to transposed parameters
  CXX      src/vsscript/libvapoursynth_script_la-vsscript.lo
  CXXLD    libvapoursynth-script.la
/usr/bin/ld: /usr/local/lib/libpython3.5m.a(dictobject.o): relocation R_X86_64_32S against `.text' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libpython3.5m.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
make: *** [libvapoursynth-script.la] Error 1

I am on Linux Mint 17.2. 
Can you help me please :) ? Thank you.

**Comment by 4re** [comment]
You are not explaining step by step how you got there. For my system `-fPIC` is just added fine at the configure stage.

**Comment by dubhater** [comment]
It seems you have a static Python you compiled yourself. Any reason you're not using the official package? VapourSynth only requires Python version 3.5 in Windows, for binary compatibility reasons. Earlier versions will work in Linux.

Anyway, if you must use a static Python you compiled yourself, you need to compile it with ``-fPIC``. Its configure script will probably accept ``--with-pic``.
