### ISSUE TITLE
Cannot execute vspipe

### ISSUE THREAD

**Issue by cobrafast** [vapoursynth/vapoursynth#200]
`vspipe` always fails with

    Failed to initialize VapourSynth environment

even when the `PYTHONPATH` environment variable is passed directly to it.

No errors were reported during make or make install.

On a sidenote, make install fails with any prefix other than `/usr/local` with

    libtool: install: error: cannot install `vapoursynth.la' to a directory not ending in /usr/local/lib/python3.4/site-packages

so I cannot try any other ways of installing.

I'm on Debian Wheezy.

**Comment by cobrafast** [comment]
Works with the `R29` tag code, but not with `master`.

**Comment by dubhater** [comment]
If you run ``PYTHONPATH=/usr/local/lib/python3.4/site-packages python3``, what happens when you type ``import vapoursynth``?

Also, is libtool refusing to install vapoursynth.la elsewhere because you compiled Python 3.4 yourself with the prefix /usr/local?

**Comment by dubhater** [comment]
Looking at https://packages.debian.org/wheezy/python/python3, it seems you did compile 3.4 yourself. Is 3.2 too old for VapourSynth?

**Comment by cobrafast** [comment]
No, I did not compile Python myself, I installed the more recent Jessie package (https://packages.debian.org/jessie/python/python3) and it's installed straight in /usr, not /usr/local.

**Comment by dubhater** [comment]
Okay then. What about my other question? And post all the commands you ran to acquire and install VapourSynth, along with their full output.

**Comment by invisiblearts** [comment]
Similar problem on Ubuntu 15.04. R28 worked fine but R29 does not.
