### ISSUE TITLE
Why -no-undefined for the Cython module?

### ISSUE THREAD

**Issue by pigoz** [vapoursynth/vapoursynth#201]
Homebrew suggests to build Python extensions with `-undefined dynamic_lookup` so that python symbols are picked up at runtime (I think they suggest this so that build products are redistributable). Is there any reason not to do this for Vapoursynth?

I am currently using the following diff for https://github.com/mpv-player/homebrew-mpv and it seems to work correctly.

```diff
diff --git a/Makefile.am b/Makefile.am
index 88287a0..dfcaace 100644
--- a/Makefile.am
+++ b/Makefile.am
@@ -98,8 +98,8 @@ pyexec_LTLIBRARIES = vapoursynth.la

 vapoursynth_la_SOURCES = src/cython/vapoursynth.pyx
 vapoursynth_la_CPPFLAGS = $(PYTHON3_CFLAGS)
-vapoursynth_la_LIBADD = $(PYTHON3_LIBS) libvapoursynth.la
-vapoursynth_la_LDFLAGS = -no-undefined -avoid-version -module
+vapoursynth_la_LIBADD = libvapoursynth.la
+vapoursynth_la_LDFLAGS = -undefined dynamic_lookup -avoid-version -module
 vapoursynth_la_LIBTOOLFLAGS = $(commonlibtoolflags)

 MOSTLYCLEANFILES = src/cython/vapoursynth.c \
```

**Comment by dubhater** [comment]
"so that build products are redistributable"

Does that mean it's about licenses? How does this affect Linux? What about cross-compiling for Windows?

**Comment by dubhater** [comment]
Oh, the question. ``-no-undefined`` is there because I add it everywhere. If I remember correctly, it's required when compiling a Windows DLL, and it doesn't cause problems for other platforms (so far).

**Comment by pigoz** [comment]
By redistributable I mean that if you compile a Python extension against some python interpreter, and load it in another one it will cause it can lead to a segfault (because they might not be ABI compatible).

OTOH when using `-undefined dynamic_lookup` the Python symbols can be loaded from the host interpreter, so in theory there are no ABI concerns. At least this looks like it's the case on OS X: not sure on Windows+Linux, that's why I started this thread.

**Comment by myrsloik** [comment]
When would this actually happen? Doesn't Python already guarantee ABI compatibility?

**Comment by pigoz** [comment]
@myrsloik @dubhater this is why the Homebrew team enforces `--undefined dynamic_lookup` http://blog.tim-smith.us/2015/09/python-extension-modules-os-x/

**Comment by myrsloik** [comment]
I guess we should change it then

**Comment by dubhater** [comment]
Can't you just keep patching it for your special situation?

**Comment by dubhater** [comment]
I mean, it doesn't **need** to be done the way you say, you just prefer it.

**Comment by pigoz** [comment]
I don't prefer it. It just prevents crashes when redistributing the python module. But sure, I guess it can be patched downstream.

**Comment by pigoz** [comment]
Btw, is a patch welcome?
