### ISSUE TITLE
Documentation issues

### ISSUE THREAD

**Issue by myrsloik** [vapoursynth/vapoursynth#206]
There should be nicer link to the website in the docs, for example in the right hand navigation bar

**Comment by magicgoose** [comment]
[Getting started](http://www.vapoursynth.com/doc/gettingstarted.html) has one issue, it shows how to load plugin (FFMS2) — by accessing file through absolute path to the binary, which is also clearly Windows-only (because it's `.dll`).

I don't know yet if this is the only way to load plugins (or there are some abstractions), but it should be at least commented how to do this on platforms other than windows. (BTW, I did install ffms2 via Homebrew, can it be used in VS then?)
(And of course, ideally, plugins should be imported by name, in a cross-platform way.)

**Comment by dubhater** [comment]
LoadPlugin works the same way everywhere. Obviously in OS X you will load ffms2.dylib (or libffms2.dylib?), not ffms2.dll, and absolute paths won't start with a drive letter.

Paths relative to the script will also work, in vspipe and probably vsedit. (It depends on the application.)

Plugins placed in certain folders will be loaded automatically. See [Plugin Autoloading](http://www.vapoursynth.com/doc/autoloading.html).

ffms2 from Homebrew should work, though Homebrew may not install it in the autoload folder.

**Comment by myrsloik** [comment]
I've now removed the explicit plugin loading in the example script and instead make a clear reference to auto-loading with a link. I think that should make it more obvious how things are supposed to be used. I only explicitly load plugins when developing them.

**Comment by dubhater** [comment]
Isn't Avisynth's blur() a Gaussian thing? Judging by generic.GBlur(), that's not simply a 3x3 convolution.

**Comment by myrsloik** [comment]
It's a separable 3x3 convolution. After looking at the code I think all it does is split it into two passes because of that. Nothing exciting to see there. Maybe it's marginally faster since there are fewer loads?

**Comment by Endilll** [comment]
http://www.vapoursynth.com/doc/pythonreference.html#Function lists `plugin` attribute twice.

**Comment by Endilll** [comment]
Maybe http://www.vapoursynth.com/doc/apireference.html colorspace props should reference ITU-T H.265, as Resize docs, because it defines more values for respective props comparing to AVC standard.

**Comment by Endilll** [comment]
[Docs for plugin init](http://www.vapoursynth.com/doc/api/vapoursynth.h.html#vsinitplugin) should clearly state that optional arguments can't precede mandatory ones in string containing filter’s list of arguments. Almost all plugins I saw have been following this rule already, but I remember spotting one in the wild that breaks it.

**Comment by myrsloik** [comment]
Right, I should definitely document it and add a check as well.

**Comment by Kamekameha** [comment]
Why can't they?  Parameters are always named because of the nature of passing values through a map, so order shouldn't really be an issue.

**Comment by myrsloik** [comment]
You'd more or less require explicitly named arguments if you don't put optional arguments last.

**Comment by Kamekameha** [comment]
In Python?  Well, yeah, but that's a limitation on the Python syntax specific to positional arguments, not Vapoursynth's.  That is, if we limit ourselves to keyword arguments then, as previously said, the order wouldn't matter, whether it's Python or Vapoursynth.

Couple that with Python's 'required keyword' arguments and what you just described would be essentially the same "feature".

**Comment by Endilll** [comment]
Maybe it's just me, but _clamping_ in [Expr](http://www.vapoursynth.com/doc/functions/expr.html) docs doesn't clarify in which manner it's done (wrapping or saturating).

**Comment by myrsloik** [comment]
It's just you.

**Comment by kgrabs** [comment]
I have a suggestion for the eedi3 documentation of the "sclip" parameter, based on some testing with abs diff clips (for the gamma part) and scratching my head at the reliability checker explanation.

      sclip
         An external clip, usually a bobbed clip using a resizer or another deinterlacer. It is used via the gamma parameter for penalizing changes in interpolation direction and also by the reliability checker for pixelwise weighted merging with the output. With extremely high gamma values, eedi3's output becomes almost identical to the sclip. Using a stronger reliability check with lower threshold values has a similar effect; merging more of the sclip into the output. By default Catmull-Rom interpolation is used.
