### ISSUE TITLE
Support for python filters

### ISSUE THREAD

**Issue by invisiblearts** [vapoursynth/vapoursynth#207]
It seems that python filters beyond simply wrapping C/C++ (native code) plugins are still not feasible.(Correct me if I'm wrong) Even core.std.BlankClip returns a read-only clip. Python filters are not necessarily slow since sometimes what we need is only using other libraries which may have a python interface, and python does far better in doing mainly logical stuff.
Also, this requires a frame request procedure just as it is in C plugins so that we don't need to process every frame to get a certain frame.

**Comment by 4re** [comment]
http://forum.doom9.org/showthread.php?t=172206 ?

**Comment by dubhater** [comment]
C is the one true language!!!

Also any filter you write in Python will run in one thread only.

**Comment by myrsloik** [comment]
Use cython to write a "normal" plugin? All you have to do is grab src/cython/vapoursynth.pxd and off you go. You can export the normal entry points and all.

Cython may even be able to produce code that's only horribly slow if you stay away from some python-isms.

**Comment by splinter98** [comment]
if you you code it up well in cython (and use things like cdef and nogil exclusively) you MAY be able to produce something that compiles entirely to C with some form of reasonable performance.

Python is inherently single threaded in that only one thread can run at a single time (thanks to the GIL) but cython can bypass that as it compiles python to C before going to a .pyd (which is essentially a dll/so renamed)

Whilst I'm no Cython expert, I recommend trying it out and seeing if it's possible or not.

**Comment by invisiblearts** [comment]
http://forum.doom9.org/showthread.php?t=172206 is mostly what I'm seeking for... Maybe documentation can be more specific about std.ModifyFrame and all these?
Anyway it seems that due to the intrinsic limitations of python, only by using cython can we utilize multi-threading... Thanks anyway.

**Comment by myrsloik** [comment]
You may be able to use stuff like cffi too for some magic. Just another insane idea.
