### ISSUE TITLE
vapoursynth.Error: LoadLibraryEx failed with code 87: update windows and try again

### ISSUE THREAD

**Issue by Usernamezhx** [vapoursynth/vapoursynth#210]
"Don’t be this guinea pig. Use windows update. Install KB2533623 and don’t be afraid of new things" but it doesnt work . I have be here for a few days. It makes me crazy......... thank you!

**Comment by Usernamezhx** [comment]
My win7 has all ready to install the KB2533623 。please help me thanks very much.

**Comment by myrsloik** [comment]
Apparently the MSDN article is lists the wrong update. Or not all of them. Installing IE11 will pull int he necessary updates at least. I can't be bothered to narrow it down more than that.
