### ISSUE TITLE
No rule to make target `src/core/vsresize.c'

### ISSUE THREAD

**Issue by nilsboy** [vapoursynth/vapoursynth#211]
I get this error for release R29 and R30 - R28 works. I'm on Ubuntu 14.04.

    make: *** No rule to make target `src/core/vsresize.c', needed by `src/core/libvapoursynth_la-vsresize.lo'.  Stop.

Any ideas?
Thank you.

**Comment by dubhater** [comment]
``make distclean`` and try again.

**Comment by nilsboy** [comment]
Wow - thanx for the fast response :) - that worked!
