### ISSUE TITLE
Will vapoursynth support AviSynth 2.5 x64 API in the futrue?

### ISSUE THREAD

**Issue by fuchanghao** [vapoursynth/vapoursynth#212]
DGDecNV 2051

import vapoursynth as vs
core = vs.get_core()
core.avs.LoadPlugin(r'C:\Program Files (x86)\AviSynth+\plugins64+\DGDecodeNV.dll')

Failed to evaluate the script:
Python exception: Avisynth Loader: 2.5 plugins can't be loaded on x64
Traceback (most recent call last):
  File "src\cython\vapoursynth.pyx", line 1489, in vapoursynth.vpy_evaluateScript (src\cython\vapoursynth.c:26885)
  File "E:/[philosophy-raws][Vocaloid]/Live&Making.vpy", line 11, in <module>
    core.avs.LoadPlugin(r'C:\Program Files (x86)\AviSynth+\plugins64+\DGDecodeNV.dll')
  File "src\cython\vapoursynth.pyx", line 1381, in vapoursynth.Function.__call__ (src\cython\vapoursynth.c:25200)
vapoursynth.Error: Avisynth Loader: 2.5 plugins can't be loaded on x64

But this not worked.
And sometime I have to use the DGDecodeNV as the source filter during decomb some 30i video.
Both ffms2 and l-smash have seek problem.

**Comment by dubhater** [comment]
Probably not. With what container/codec do you have the seek problems?

**Comment by fuchanghao** [comment]
VS Code:
a = r"H:\Ghost in the Shell STAND ALONE COMPLEX\STAND_ALONE_COMPLEX_2ND_GIG_01\BDMV\STREAM\00000.m2ts"
src8 = core.lsmas.LWLibavSource(a,threads=1)
src8 = core.std.Trim(src8, 45748, 89807)
src8 = core.std.AssumeFPS(src8,fpsnum=30000,fpsden=1001)
src8 = core.std.SetFrameProp(src8, prop="_FieldBased", intval=2)
src8 = core.vivtc.VFM(src8,order=1,mi=32,cthresh=6)

deint = core.nnedi3.nnedi3(src8,field=1)
decomb = haf.daa(src8)
def FilterCombedFrame(n,f):
    if f.props._Combed:
        return deint
    else:
        return decomb
src8 = core.std.ShufflePlanes([src8,deint,decomb], [0,1,2], vs.YUV)
src8 = core.std.FrameEval(src8, FilterCombedFrame, src8)
src8 = core.vivtc.VDecimate(src8)

**Comment by myrsloik** [comment]
No, 2.5 API can never be supported effectively because of internal differences in VapourSynth. Simply get people to update their plugins. It's not like Avisynth 2.5 was ever usable on x64 anyway.
