### ISSUE TITLE
Official binary packages for popular Linux distributions

### ISSUE THREAD

**Issue by myrsloik** [vapoursynth/vapoursynth#214]
It'd be nice if there were official and up to date packages for more distros. Like all those pesky debian ones that move their shit around.

I think arch linux is the only one where someone maintains packages.

**Comment by invisiblearts** [comment]
I'm trying to package zimg and VapourSynth on RPM-based distributions such as OpenSUSE (The distribution I'm using) and Fedora.
And therefore I see that there are a few problems for packaging.
First, how should zimg be packaged? Mainstream distributions already have a package called zimg and that has nothing to do with ours.
Second, imagemagick is always shit - its API changes frequently and VS now uses the newest one. (at least on OpenSUSE, which I could test locally) Therefore it is difficult to add imwri plugin to the main repository for slow-moving distributions.

**Comment by dubhater** [comment]
What about a tarball that works on most distros ~3 years old or newer, including the current Debian stable (jessie)?
```
vapoursynth.tar:
lib/libgcc_s.so
lib/libstdc++.so.6
lib/libvapoursynth.so
lib/libvapoursynth-script.so.0
lib/libzimg.so.2
lib/vapoursynth.so
lib/vspipe
plugins/libeedi3.so
plugins/libmorpho.so
plugins/libremovegrain.so
plugins/libvinverse.so
plugins/libvivtc.so
python3.sh
vspipe.sh
```
You may notice that the plugins with dependencies, such as imwri, are not present. These are left as an exercise to the user.

**Comment by myrsloik** [comment]
I applaud your observation that imagemagick is eternal shit. Actually I'd like to replace imagemagick with something markedly less shitty but haven't located anything yet. Apart from trying to use as many individual image format libraries as possible (an abandoned plugin that does that exists and could be revived). Stupid thing even miscompiles constantly on windows nowadays and they removed all older copies of the source. I hate them.

Since 'z' is under tha wtfpl I'd simply suggest renaming it to something like (lib)zresize. Nobody has to find out...

I'm not so sure about the tarball idea. I mean in practice there are only like 2.5 relevant packaging systems for linux. I think it should be doable in an elegant way.

**Comment by invisiblearts** [comment]
I already packaged VapourSynth and zimg (z.lib in my case but maybe libzresize is a better idea) for OpenSUSE and Fedora. Though not tested, they seems to work.
[Project Site](https://build.opensuse.org/project/show/home:invisiblearts) Because they're the first two packages I've ever packed they may contain tons of problems...

**Comment by myrsloik** [comment]
The proper number to use is 3

**Comment by invisiblearts** [comment]
Better fix it in Makefile - it's not very easy to make relative soft links while packaging and it is also some kind of common rule.

**Comment by myrsloik** [comment]
Ok

**Comment by dubhater** [comment]
@invisiblearts: The library versions have been discussed in #89.

**Comment by invisiblearts** [comment]
@dubhater Looks reasonable.

**Comment by sl1pkn07** [comment]
gentoo also have a package maintaner

https://github.com/4re/vapoursynth-portage

**Comment by myrsloik** [comment]
I've added arch linux and gentoo to the list. And the brew packages on osx that are now apparently mainstream too. I think those are all the packages that exist.

Apart from https://launchpad.net/~djcj/+archive/ubuntu/vapoursynth
But I'm a bit suspicious about those since they were compiled with insane settings for distribution before (AVX2 for general consumption binaries)

**Comment by dubhater** [comment]
@darealshinji What CFLAGS/CXXFLAGS do you use these days for the packages in your PPA?

**Comment by darealshinji** [comment]
@dubhater For Vapoursynth (which includes its own copy of ImageMagick) its:
``` make
PYTHON3_CFLAGS=-I/usr/include/python3.4m
PYTHON3_LIBS=-lpython3.4m
TESSERACT_CFLAGS=-I/usr/include
TESSERACT_LIBS=-ltesseract -lm
CXXFLAGS += -Wno-missing-field-initializers -fno-strict-aliasing
PKG_CONFIG_PATH=$(magick_dir)/libs/lib/pkgconfig
IMAGEMAGICK_LIBS="`pkg-config --static --libs Magick++` -lpthread"
```
Aside of that it's using the default build flags on Ubuntu which are:
``` make
CFLAGS=-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security
CPPFLAGS=-D_FORTIFY_SOURCE=2
CXXFLAGS=-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security
LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro
```
On Ubuntu version greater than 14.04 it's `-fstack-protector-strong` instead of `-fstack-protector --param=ssp-buffer-size=4`. Though on Ubuntu and Debian GCC is patched to always use these flags when using `-O2` or higher (exceptions are `-g` and `-Wl,-Bsymbolic-functions`).
There's also a patch that removes the `-O3` from Makefile.am.

**Comment by dubhater** [comment]
Sounds good.

(Patching Makefile.am should not be necessary because CXXFLAGS are inserted after AM_CXXFLAGS on the command line, so -O2 will override -O3.)
