### ISSUE TITLE
Resizers don't like interlaced video

### ISSUE THREAD

**Issue by dubhater** [vapoursynth/vapoursynth#216]
Even operations like bit depth conversion fail with an error if the input has the _FieldBased property and it's not 0.

**Comment by dubhater** [comment]
Related: the resizer doesn't identify itself in the error message.

**Comment by myrsloik** [comment]
Fixed the error message part

**Comment by myrsloik** [comment]
Interlaced resizing is iffy though. What do you suggest? Automatically invoke bob, resize, and then put the fields back together?

**Comment by dubhater** [comment]
Whatever it takes to make it work?

**Comment by myrsloik** [comment]
But that's also a matter of taste. I kinda prefer to make it explicit.

**Comment by dubhater** [comment]
"interlaced" parameter?

**Comment by myrsloik** [comment]
Deinterlace before resizing?

Of course you can't do that in woobly but everyone else can...

**Comment by dubhater** [comment]
There are also those who need the output to be interlaced. Deinterlacing it before and interlacing it after is a lot of unnecessary processing in that case.

**Comment by junh1024** [comment]
Some valid case:

Say you have 1920x1080i, you want to resize to 1280x1080i before you pass it to a deinterlacer to speed up deinterlacing.

**Comment by myrsloik** [comment]
Add the code from interlace_example.cpp then, I won't stop you. But remember that interlacing is evil.

**Comment by dubhater** [comment]
According to @sekrit-twc this valid case doesn't require special handling, because there is no vertical resizing happening.

**Comment by myrsloik** [comment]
Now I get it. So you basically want it to work with horizontal resizing and depth conversion? Just make a more detailed check for when to reject input.

But won't dithering in depth conversion leak between fields? maybe that's so little it doesn't matter anyway.
