### ISSUE TITLE
Request for avs_compat: mvtools2 x64 fix

### ISSUE THREAD

**Issue by pinterf** [vapoursynth/vapoursynth#217]
x64 version of avisynth mvtools2 (2.6.0.5) uses both nchannels and sample_type for storing MVAnalysisData pointers. A hack with magicalNChannelsForMVTools already exists, for 32 bit it is enough.
But 64 bit pointers occupy nchannels and sample_type. Could you please implement this new hack (let's say magicalSampleTypeForMVTools) in avs_compat?

**Comment by myrsloik** [comment]
There's a perfectly good native version. Use it.

**Comment by pinterf** [comment]
Yes, I know, but I need specifically MDepan which is not ported yet. (experimenting with DepanStabilize which needs output of MDepan)

**Comment by myrsloik** [comment]
I guess I'll add that. But consider encouraging jackoneill to porting the remaining useful parts.

**Comment by pinterf** [comment]
Thank you, working fine, now I can see the full 64 bit pointer! Then I tried to build my own build of avscompat and succeeded. (I'd like to make my avs DePanStabilize mod work, avs 2.6 interface, x64, YUV444 + stacked 16 bit support)
