### ISSUE TITLE
Feature request, support for LAV Filters as source filter.

### ISSUE THREAD

**Issue by J1Man** [vapoursynth/vapoursynth#221]
I would like to request a feature.  **Can you add support for open-source "Lav Filters" (https://github.com/Nevcairiel/LAVFilters) as a source filter**?

Lav Filters support hardware decoding on many different systems (Nvidia Cuvid, Intel QuickSync, Intel MVC 3D, DXVA2) for almost all video types (HEVC, H264, VP9, MPEG-4, Mpeg-2, dvd, etc.) with all resolutions (SD, HD, 4K UHD). Software decoding is also available.  Hardware decoding for source video provides significant speed up when re-encoding video.  It gets updated regularly (usually daily through nightly builds) with new features. 

Lav filters can output the hardware (or software) decoded video in almost all YUV (4:2:0,4:2:2,4:4:4) and RGB (RGB24, RGB32, RGB48) formats in 8bit, 10bit or 16bit.  YUV or RGB Output of Lav filters can be directly processed by Vapoursynth internal functions or 3rd party Vapoursynth plugins. 

Currently one of the few advantages that Avisynth has over Vapoursynth is the ability to support hardware decoding through Lav Filters.

Please let me know what you think.

Best Regards

**Comment by invisiblearts** [comment]
It won't be at a high priority, based on my blind guess, as LAVFilter is Windows-only, while VapourSynth put more effort on cross-platform stuff.
At least you can use the AVS plugin on Windows..

**Comment by myrsloik** [comment]
Uh? What you really want is a directshow source filter?

**Comment by J1Man** [comment]
Yes, Lav Filters is a directshow source filter.

**Comment by fuchanghao** [comment]
But can vapoursynth support MVC 3D reading with intel media sdk?

**Comment by J1Man** [comment]
Yes, it would be possible to read MVC 3D videos via Lav Filters, if Vapoursynth had Lav Filters support.  Lav Filters use Intel Media SDK to decode MVC 3D videos.

**Comment by myrsloik** [comment]
Ask the avisynth filter authors first. I don't mind helping to add support for VS to existing filters which will be much faster. You can also try your luck with directshowsource from the latest test builds of avs+ which will now work in R33.
