### ISSUE TITLE
unable to read the image by anisynth+'s imagesource.

### ISSUE THREAD

**Issue by fuchanghao** [vapoursynth/vapoursynth#222]
import vapoursynth as vs
import sys
import functools

core = vs.get_core(accept_lowercase=True,threads=1)

core.max_cache_size = 1024

core.avs.LoadPlugin(path=r"C:\Program Files (x86)\AviSynth+\plugins64+\ImageSeq.dll")
core.avs.LoadPlugin(path=r"C:\Windows\System32\DevIL.dll")

src = core.avs.ImageSource("F:\BBB-1080-png\big_buck_bunny_%05d.png", 00001, 14315, 24)

src.set_output()

error message:

Failed to evaluate the script:
Python exception: invalid token (, line 11)
Traceback (most recent call last):
  File "src\cython\vapoursynth.pyx", line 1488, in vapoursynth.vpy_evaluateScript (src\cython\vapoursynth.c:26938)
  File "<string>", line 11
    src = core.avs.ImageSource("F:\BBB-1080-png\big_buck_bunny_%05d.png", 00001, 14315, 24)
                                                                              ^
SyntaxError: invalid token

**Comment by myrsloik** [comment]
https://github.com/vapoursynth/vapoursynth/blob/d9dfd8b237d10d8c5eeecb9785106551060ad898/doc/pythonreference.rst#windows-file-paths-strings-with-backslashes

**Comment by fuchanghao** [comment]
adding r or not didn't change the error.

like

>
import vapoursynth as vs
import sys
import functools

core = vs.get_core(accept_lowercase=True,threads=1)

core.max_cache_size = 1024

core.avs.LoadPlugin(r"C:\Program Files (x86)\AviSynth+\plugins64+\ImageSeq.dll")
core.avs.LoadPlugin(r"C:\Windows\System32\DevIL.dll")

src = core.avs.ImageSource(r"F:\sintel_trailer-1080-png\big_buck_bunny_%05d.png", 0001, 1253, 24)

src.set_output()

>

**Comment by myrsloik** [comment]
Numbers may not start with 0. Change 00001 to 1.
