### ISSUE TITLE
AVIsource would trun 180 when adding RGB24 source.

### ISSUE THREAD

**Issue by fuchanghao** [vapoursynth/vapoursynth#223]
Tested in VS R32 test2.

When AVI was played in MPC-BE it worked fine:

http://www.imagebam.com/image/1a486b475858788

But while use the following VS codec, It turned 180 And I don't know what's wrong.

http://www.imagebam.com/image/495cd7475858777

> import vapoursynth as vs
import sys
core = vs.get_core(accept_lowercase=True,threads=1)
core.max_cache_size = 8192
src = core.avisource.AVISource(r"C:\Volumes\bbb.avs\bbb.avi")
src.set_output()

AVI mediainfo:

> General
Complete name                            : C:\Volumes\bbb.avs\bbb.avi
Format                                   : AVI
Format/Info                              : Audio Video Interleave
Format profile                           : OpenDML
File size                                : 82.9 GiB
Duration                                 : 9mn 56s
Overall bit rate                         : 1 194 Mbps

> Video
ID                                       : 0
Format                                   : RGB
Codec ID                                 : 0x00000000
Codec ID/Info                            : Basic Windows bitmap format. 1, 4 and 8 bpp versions are palettised. 16, 24 and 32bpp contain raw RGB samples
Duration                                 : 9mn 56s
Bit rate                                 : 1 194 Mbps
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate                               : 24.000 fps
Bit depth                                : 8 bits
Bits/(Pixel*Frame)                       : 24.000
Stream size                              : 82.9 GiB (100%)

**Comment by myrsloik** [comment]
Use FlipVertical to work around it for now. I'll fix it in R32, apparently I misplaced an if statement and nobody notied until now.

**Comment by myrsloik** [comment]
`https://dl.dropboxusercontent.com/u/73468194/VapourSynth-R32-RC3.exe`
Try this build and see if it works

**Comment by fuchanghao** [comment]
Now it worked fine.

Thanks you.
