### ISSUE TITLE
CPU load fluctuations

### ISSUE THREAD

**Issue by Efenstor** [vapoursynth/vapoursynth#224]
I see strange fluctuations in CPU load which are visible when doing heavy-load processing. Simple processing has the same fluctuations too but as the progress goes very fast they are much harder to discern. At first I blamed ffmpeg or plugins for this but then ruled it out, as simple input-output script, as well as writing into /dev/null produces identical peaks and dips, which become longer and longer with time.

vspipe to ffmpeg (note encoding framerates steadily decreasing):
![screenshot](https://cloud.githubusercontent.com/assets/11175574/14295222/59210a3c-fba7-11e5-8c29-4090126f0da3.jpg)
![screenshot-1](https://cloud.githubusercontent.com/assets/11175574/14295224/5923d898-fba7-11e5-808b-43ecdc7aad94.jpg)

vspipe to /dev/null:
![screenshot-2](https://cloud.githubusercontent.com/assets/11175574/14295225/5929d734-fba7-11e5-84a6-9bcb14125884.jpg)
![screenshot-3](https://cloud.githubusercontent.com/assets/11175574/14295223/59227354-fba7-11e5-8c4b-c76ba30cc2a0.jpg)

I suspect it has something to do with caching. Running vspipe with -r 6 or more makes the graph a bit smoother and the framerates are dropping slower but still dropping.

And here is my "complex" script, if you need it:

```
import vapoursynth as vs
core = vs.get_core()

clip = core.lsmas.LWLibavSource(filename, fpsnum=30000, fpsden=1001)

# IVTC
clip = core.vivtc.VFM(clip, 1, mode=0, micmatch=0)
clip = core.vivtc.VDecimate(clip)

# Convert to RGB24
clip = core.resize.Bilinear(clip=clip, format=vs.RGB24, matrix_in_s="709")

# Debarrel Canon HF100 with Raynox x0.3 on with the 37mm-37mm ring
clip = core.vcmove.DeBarrel(clip=clip, a=0.005, b=0.009, c=0.085, test=0)

# Crop debarrel border leftovers
new_height = 1073	# just as much as needed
old_width = clip.width
old_height = clip.height
aspect = old_width/old_height
new_width = int(new_height*aspect+.5)
new_left = int((old_width-new_width)/2+.5)
new_top = int((old_height-new_height)/2+.5)
clip = core.std.CropAbs(clip, new_width, new_height, new_left, new_top)
clip = core.resize.Bicubic(clip, old_width, old_height)

# Output as YUV420
clip = core.resize.Bilinear(clip=clip, format=vs.YUV420P8, matrix_s="709")
clip.set_output()
```

**Comment by dubhater** [comment]
Does it help to make the cache larger? The default limit is 1 GiB.
```python
core = vs.get_core()
core.max_cache_size = 4000
```

**Comment by Efenstor** [comment]
Erm, not really. :) "core.max_cache_size = X" doesn't help at all, whatever size I specify. But wonderfully the never-use-it-with-Python function "std.Cache" remedies the problem. Options do not seem to matter, or at least matter much.

**Comment by dubhater** [comment]
How? Where in the chain did you put it?

**Comment by Efenstor** [comment]
Right after the source:
```
clip = core.lsmas.LWLibavSource(filename, fpsnum=30000, fpsden=1001)
clip = core.std.Cache(clip=clip)
```

**Comment by dubhater** [comment]
Suspicious. What happens if you make that
```python
clip = core.lsmas.LWLibavSource(...)
print(clip)
```
?
What does it print?

**Comment by Efenstor** [comment]
Nothing tremendous, I suppose:
```
VideoNode
	Format: YUV420P8
	Width: 1920
	Height: 1080
	Num Frames: 990
	FPS Num: 30000
	FPS Den: 1001
	Flags: MakeLinear
```

**Comment by Efenstor** [comment]
Interestingly enough, although std.Cache relieves the peaks and dips in the CPU load, the processing frame rates still have a tendency to decline logarithmically until stabilize on some level.

**Comment by dubhater** [comment]
std.Cache should be added automatically now.
