### ISSUE TITLE
Please allow installation to conda python

### ISSUE THREAD

**Issue by eugenesvk** [vapoursynth/vapoursynth#225]
I wanted to use Vapoursynth with StaxRip, but VS wouldn't install unless I had the default python installation (the installer would just complain there is no python even though there actually is a miniconda python).
I can't use VS portable because StaxRip can't deal with it and is unlikely to support a portable version in the future https://github.com/stax76/staxrip/issues/48#issuecomment-207188983.
Would you please allow to choose a custom python location to install VS to? Or even better make it a pip package :)

**Comment by myrsloik** [comment]
Exactly what does conda change in a python install? I could improve the detection in the installer

**Comment by eugenesvk** [comment]
Sorry, I don't know the exact changes. There doesn't seem to be much except for a bunch of extra conda-specific dlls, otherwise the standard python folders seem to be in place. When I just moved VS folder + vapoursynth.pth from site-packages to the conda's python site-packages I could load the module, but when I tried a test `vspipe.exe` through an error (maybe it had old system python path hard-coded somwhere).
If install could just allow selection of python.exe folder and assume that as a path instead of looking itself, I could install and see if it breaks anything

**Comment by eugenesvk** [comment]
Config files are here, though I've only changed menus, otherwise all other settings are  not changed https://github.com/eugenesvk/temp

**Comment by myrsloik** [comment]
If you've gotten that far your real problem is that staxrip can't be pointed at a user selected VS install. You can get around it by creating the VS registry keys too I guess. If you like doing things the hard way...

**Comment by eugenesvk** [comment]
> staxrip can't be pointed at a user selected VS install

I agree, but unfortunately the dev of StaxRip doesn't want to fix that issue :(

> by creating the VS registry keys too

How? When I moved VS python files to my conda install the registry keys 
`HKEY_LOCAL_MACHINE\SOFTWARE\VapourSynth` and 
`HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\VapourSynth`
were still pointing to VS dlls in their original installation folder and yet it didn't work for some reason (I uninstalled system python, pointed StaxRip in settings to my conda python.exe, and conda python by itself was able to import VS module).

Is there something else that somehow ties the VS install to the system python location?

**Comment by J1Man** [comment]
It would be great if you added support for the detection of Anaconda and Miniconda python distributions to the Vapoursynth installer.  They are both created by the same company and they are very popular.  The only difference between them is that Miniconda is much smaller.   

Miniconda with Python 3.5 is recognized by Vapoursynth installer if it is installed for all users (in admin mode) under "C:\Program Files\Python35".  I also confirmed that Vapoursynth can be used via Staxrip without any problems if Miniconda is installed under "C:\Program Files\Python35".  Problem is that nobody installs Miniconda under that location.  I just did it for testing purposes.  This test proves that Miniconda works with Vapoursynth as long as it is installed under the only location that is supported by Vapoursynth.  Please note that I did not test the operation of the plugins.

Both Anaconda and Miniconda add the location of the "active python environment" to the Windows Path variable.  It would be best if Vapoursynth could just read the PATH variable and get the "active python environment" location from there.  **The catch is that the PATH variable does not specify if Python version is 3.5 or not**.  Vapoursynth installer should run "python --version" command to confirm that Python version is 3.5.   

Please note that both Anaconda and Miniconda support multiple Python versions (2.7, 3.4 and 3.5).  Most people still use Python 2.7 with Anaconda and Miniconda.  **It is very important for Vapoursynth installer to confirm that Python 3.5 is installed in the "active python environment" of Anaconda (or Miniconda)**.  If incorrect python version is installed, Vapoursynth installer should quit (as it does now).

Of course, Vapoursynth installer should still check the directory "C:\Program Files\Python35" and prefer to use that original python distribution if it is installed.

My discussion above focused mainly on Vapoursynth installer's ability to detect Python location and version, but I am wondering if there are any functional issues.  Would Vapoursynth and its plugins operate correctly if Python is installed at a location other than "C:\Program Files\Python35"?

**Comment by eugenesvk** [comment]
@J1Man 
Thanks for a bunch of testing and confirmation that it's a fixed Python35 path that's part of the issue!

Just two minor things:
1) I installed the default Python35 in another folder (outside of "Program Files", though still in "Python35") and VS + StaxRip worked fine in this setup. So it's not just them checking "Program Files\Python35", the system python is special in some other way
That partially answers your 
>Would Vapoursynth and its plugins operate correctly if Python is installed at a location other than "C:\Program Files\Python35"?

Seemed to work for me. Not sure about other plugins since I only tested VS and StaxRip.

2)
> prefer to use that original python distribution if it is installed.

I'd really prefer to have a choice myself rather than making that default location. What if another bugged app forces me to have a system-wide python located there but which I don't ever want to use? Don't want other apps to hook there as well if I can avoid it.

**Comment by myrsloik** [comment]
VS support both global and per user installs of normal python to any location. What it really looks for are the registry entries in hklm/hkcu\software\<Python>.

**Comment by eugenesvk** [comment]
> What it really looks for are the registry entries in hklm/hkcu\software<Python>

Thanks! I've changed these to Conda's paths and finally could get rid of that extra python that was just confusing my system. And StaxRip also works this way if you point it to Conda python and VS install location.
Would you kindly allow to set it manually via a config file? The Conda paths are identical to the default registry ones vis-a-vis `python.exe` so all that is needed during install is ask the user where his prefered `pyton.exe` is located and then use that path to append all others (`Lib` and `DLLs`) in the config file — and then just read these config file values.

**Comment by splinter98** [comment]
I feel that [PEP 514](https://www.python.org/dev/peps/pep-0514/) (currently in draft) is fundamental to solving this issue in the long run. Once implemented by other python venders it should just be a case of searching venders in the registry for an appropriate version of python.

IIRC, Vapoursynth already works with python virtual environments, as long as vspipe (or the program/library calling vsscript) is located inside python virtual environment structure.

**Comment by myrsloik** [comment]
I see that PEP514 actually got accepted. I installed anaconda python and saw that it appears to write things the intended way. So I guess I'll try adding proper support for this in the installer.

The sane way would be to list all suitable python environments found and allow multiple ones to be selected, right?

**Comment by splinter98** [comment]
Yes, if multiple versions of Python are detected then prompt the user to which version(s) to install it to with a shortcut button for select all/none.

if only one version of Python is discovered then use that (but maybe inform the user if it isn't the official distribution).

If vspipe is installed inside the python environment it will be used by that version of python. if it is installed outside from the python environment then it will use the default python environment. (which is the same as how python virtual environments work)

**Comment by myrsloik** [comment]
Actually there is a bit of a problem with allowing all of them. VSScript.dll still only uses one. Should it just pick a random one if multiple python installations are selected?
Things stop making sense when you get to pick more than one python environment. Or there needs to be a second setting to choose the default one that vsscript should use. (too many settings and too complicated IMO)

I'm tempted to only allow a single python installation to be selectable for 32 and 64 bit respectively. Comments?

**Comment by splinter98** [comment]
When the program that loads vsscript is outside of a python directory, I believe it will always try and load the default python installation. So even if you install it to anaconda vspipe (for example) may still try and load the official python (if both are available) unless we explicitly tell it to load another version of python.

I believe you can select which python installation to use when vspipe (for example) is located outside of a python installation by using Py_SetPath().

we could enable vsscript to support setting the path (defaulting to a registry key to the version of python we have set on windows or ignoring if PYTHONPATH/PYTHONHOME are set which I think can be used to override default behaviour).

**Comment by myrsloik** [comment]
I have now come to the conclusion that anaconda doesn't support everything needed in all cases. It doesn't set SysArchitecture which means that there's no safe way to detect if a per user installation written to HKCU is 32 or 64 bit. Go poke them to fix this.

**Comment by myrsloik** [comment]
And using the system python is also kinda a bad solution. What if the user doesn't install VS for the system python?

**Comment by splinter98** [comment]
Arguably we probably should be using our own copy of python rather than the system python (or any other version for that matter) as it would give us more control (and remove the python prerequisite as it is bundled).

Personally I found having the vapoursynth module inside system python a little odd, whilst you can import vapoursynth inside a python script and use the filters to a certain extent vapoursynth doesn't really 'work' unless called from vsscript (I have found it useful for debugging however). Having our own version of Python (at least in windows) would give us more control and also remove the recurring shall we update python again? question as we can update python without the user needing to install the latest version each time.

**Comment by myrsloik** [comment]
This is implemented as sanely as it can be. You can now choose between multiple python installations and select a specific one to use. Any remaining issues are basically that Anaconda is derp. I mean it. It's fucking shit.

1. It doesn't remove its registry keys on uninstall
2. Only works if you choose to set is as system python, with the added effect that you'll appear to have a "normal" python installation as well, why they didn't change the registry path their python reads is a mystery
3. Doesn't write SysArchitecture so installs registered in HKCU can't be used since the bitness is unknown. For HKLM it can be inferred form the location
4. No obvious bug tracker or other place to report this so until you get them to fix 1-3 I'm not going to pursue this further (or find some other distribution that's less shit for me to test with)
