### ISSUE TITLE
unable support non-english path.

### ISSUE THREAD

**Issue by fuchanghao** [vapoursynth/vapoursynth#226]
The vpy file are UTF-8 format.But when the source path are not english path like this.

The vpy file would show error that they can't find the source.

sample code

> import vapoursynth as vs
import sys
core = vs.get_core(accept_lowercase=True,threads=1)
core.max_cache_size = 1024
a=r"G:\ハーモニー\BDROM\BDMV\STREAM\00000.m2ts"
res = core.lsmas.LWLibavSource(a,threads=1)
res.set_output()

error message

> Failed to evaluate the script:
Python exception: 'NoneType' object has no attribute 'set_output'
Traceback (most recent call last):
  File "src\cython\vapoursynth.pyx", line 1491, in vapoursynth.vpy_evaluateScript (src\cython\vapoursynth.c:26897)
  File "F:/test.vpy", line 10, in <module>
    res.set_output()
AttributeError: 'NoneType' object has no attribute 'set_output'

**Comment by myrsloik** [comment]
I thought of a horrible partial workaround. You can use python's string.encode() to get a bytes object containing the string with the local encoding. This will be passed through unmodified by VS. It's of course horrible and evil but will make it possible to open all files representable in the local codepage at least.

**Comment by myrsloik** [comment]
Fixed upstream
