### ISSUE TITLE
Please Update installer to use vs2015u3 runtimes 

### ISSUE THREAD

**Issue by fuchanghao** [vapoursynth/vapoursynth#230]
http://download.microsoft.com/download/1/e/a/1ead6e71-6ecf-40c2-b2c1-8e45c416b302/vc_redist.x86.exe
http://download.microsoft.com/download/e/9/5/e953b5cd-5efd-407a-9ea3-49f48c18cad5/vc_redist.x64.exe

**Comment by myrsloik** [comment]
I'll get on that immediately. Just have to update visual studio first...

**Comment by HolyWu** [comment]
The links he gave were incorrect. They are still 2015 Update 2 (v14.0.23918).

The files for 2015 Update 3 (v14.0.24210) are:
https://download.microsoft.com/download/4/2/F/42FF78CE-8DE0-4C88-AD7A-5F8DFFB49F74/vc_redist.x86.exe
https://download.microsoft.com/download/4/2/F/42FF78CE-8DE0-4C88-AD7A-5F8DFFB49F74/vc_redist.x64.exe

**Comment by myrsloik** [comment]
Done, I guess
