### ISSUE TITLE
upgrade Visual C++ 2015 Redistributable to 14.0.24212

### ISSUE THREAD

**Issue by fuchanghao** [vapoursynth/vapoursynth#232]
When visual studio 2015 update to 14.0.25424.

It also update the Visual C++ 2015 Redistributable to 14.0.24212 with bug fix.

14.0.24212-x86
http://download.microsoft.com/download/9/a/2/9a2a7e36-a8af-46c0-8a78-a5eb111eefe2/vc_redist.x86.exe
14.0.24212-x64
http://download.microsoft.com/download/2/a/2/2a2ef9ab-1b4b-49f0-9131-d33f79544e70/vc_redist.x64.exe

**Comment by myrsloik** [comment]
Will be in the next installer
