### ISSUE TITLE
vapoursynth portable cannot work subfolder...

### ISSUE THREAD

**Issue by kyh96403** [vapoursynth/vapoursynth#236]
I am using vapoursynth filter(VSScript.dll)..
If exe file exist in vapoursynth folder, it is work...
But move vapoursynth folder to sub folder, it is not work...
Please improve it~~
I want to move vapoursynth's file to sub folder~~

**Comment by myrsloik** [comment]
If you're using vsscript.dll directly then simply load it with an altered search path using loadlibraryex and it should find the rest.

**Comment by kyh96403** [comment]
Maybe... you test install version python and vapoursynth...
I want using portable version python and vapoursynth.
Portable version only work same folder exe and vsscript.dll.... ㅜ_ㅜ;;

**Comment by kyh96403** [comment]
Maybe... you test install version python and vapoursynth...
 I want using portable version python and vapoursynth.
 Portable version only work same folder exe and vsscript.dll.... ㅜ_ㅜ;;
Loadlibrary(Ex) is success but, call "vsscript_init" is fail...
So cannot work....

**Comment by myrsloik** [comment]
Not supported. I won't scan the whole harddrive for files.
