### ISSUE TITLE
Which funtion should I use instead of core.generic.Hysteresis?

### ISSUE THREAD

**Issue by fuchanghao** [vapoursynth/vapoursynth#237]
Do TCanny has such type funtion I can use?

**Comment by myrsloik** [comment]
No, but I intend to stuff a few more functions into a separate plugin. See this comment:
[https://github.com/vapoursynth/vapoursynth/pull/235/files/38f0ebf5c7c687a2cb894788c4d2db5c221f8972#diff-5ccf3bf6c430a6fc2b90ebb4a6c558c8R1](url)

**Comment by fuchanghao** [comment]
OK I see.

Thanks for the reply.
