### ISSUE TITLE
Why use clang-cl instead of ICC to improved speed?

### ISSUE THREAD

**Issue by fuchanghao** [vapoursynth/vapoursynth#238]
Visual Studio 2015 update3.
ICC 16 update 3
Clang 3.8.1

I tested expr/lut/convolution/MaskedMerge etc. with threads=1 in my E5 2695 v2 CPU.
ICC 16 it's  5-10% faster than the clang-cl build(both offcial and built by myself).

**Comment by myrsloik** [comment]
Buy me a license and I'll make icc builds too

**Comment by fuchanghao** [comment]
license
https://mega.nz/#!MFxiFRxa!Mxr9WkyzyX-tkDgKvvFGHLXIsCWLphO608zoJJQcnSY

software
http://registrationcenter-download.intel.com/akdlm/irc_nas/9046/parallel_studio_xe_2016_update3_setup.exe

**Comment by msg7086** [comment]
He's saying that you should provide the money for him so that he can own a copy of icc.

**Comment by dubhater** [comment]
clang is cooler.

**Comment by myrsloik** [comment]
I'd rather use gcc for release builds. And icc is a huge bloated pile of crap that likes to add extra dependencies.
