### ISSUE TITLE
vapoursynth portable cannot work subfolder 2...

### ISSUE THREAD

**Issue by kyh96403** [vapoursynth/vapoursynth#240]
A:
My Path/VapourSynth(Python + VapourSynth portable version)
LoadLibrary(My Path/VapourSynth/vsscript.dll) is ok...
But call 'vsscript_init' is fail..

B:
My Program + Python + VapourSynth portable version
LoadLibrary(MyPath/vsscript.dll) is ok...
And call vsscript_init is ok...

Your answer is Not "I won't scan the whole harddrive for files."
What file is needed ??

**Comment by myrsloik** [comment]
It has to do with search paths. You may be able to get around it with loadlibraryex, as I may or may not have mentioned. But you obviously didn't do that. So I'll ask WHY DO YOU THINK SOFTWARE WILL WORK AFTER YOU MOVE FILES AROUND? 

Especially when you don't tell it where they now are? Did you even try to look at which dlls vsscript.dll and vapoursynth.dll has imports from?

**Comment by kyh96403** [comment]
I already test 'LoadLibraryEx' with LOAD_WITH_ALTERED_SEARCH_PATH.
But fail...
In case A and B...
LoadLibrary(Ex)(MyPath/vsscript.dll) is ok...
So that is not LoadLibrary(Ex)'s problem...
I thnik... "vsscript_init" fail is Python's problem...
So I hook GetModuleFileNameW.. and return dll's path...
it is work~~

Thanks~~
