### ISSUE TITLE
Is it compatible with vaapi?

### ISSUE THREAD

**Issue by JulianLai** [vapoursynth/vapoursynth#241]

**Comment by dubhater** [comment]
Absolutely. There is no incompatibility between VapourSynth and vaapi.

**Comment by wm4** [comment]
I think he was asking for vaapi surface input/output support.

**Comment by wm4** [comment]
PS: also he is asking in context with SVP, which means SVP would need to support that.

**Comment by laichiaheng** [comment]
@wm4 The SVP developer says that it's a question to mpv devs.

**Comment by JulianLai** [comment]
@wm4 The SVP developer says that it's a question to mpv devs.

**Comment by wm4** [comment]
>@wm4 The SVP developer says that it's a question to mpv devs.

Yeah, and I'm saying it's a question to them. Obviously mpv can't pass vaapi surfaces through SVP if neither vapoursynth nor SVP support vaapi surfaces.
