### ISSUE TITLE
How to build on mac os x?

### ISSUE THREAD

**Issue by Selur** [vapoursynth/vapoursynth#242]
cloning the git repository and calling './autogen.sh' inside the repository gives me:

>autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force 
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in `.'.
libtoolize: copying file `./ltmain.sh'
libtoolize: Consider adding `AC_CONFIG_MACRO_DIR([m4])' to configure.ac and
libtoolize: rerunning libtoolize, to keep the correct libtool macros in-tree.
libtoolize: Consider adding `-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
autoreconf: running: /usr/local/autoconf-2.69/bin/autoconf --force
configure.ac:16: error: possibly undefined macro: AS_IF
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:19: error: possibly undefined macro: AC_DEFINE
configure.ac:61: error: possibly undefined macro: AS_CASE
configure.ac:99: error: possibly undefined macro: AC_MSG_ERROR
configure.ac:377: error: possibly undefined macro: AC_COMPILE_IFELSE
configure.ac:379: error: possibly undefined macro: AC_LANG_SOURCE
configure.ac:416: error: possibly undefined macro: AC_MSG_CHECKING
configure.ac:435: error: possibly undefined macro: AC_MSG_RESULT
autoreconf: /usr/local/autoconf-2.69/bin/autoconf failed with exit status: 1

**Comment by myrsloik** [comment]
That's odd, all you should need is the stuff xcode installs.

**Comment by dubhater** [comment]
Did you install pkg-config?

**Comment by Selur** [comment]
I got pkgbuild and pkgutil on my system,... (not sure not sure if I ever installed pkg-conf)

**Comment by dubhater** [comment]
I don't know what those two are. You need pkg-config. You can easily check if you have it by trying to run ``pkg-config`` in a shell.

**Comment by Selur** [comment]
pkg-config isn't installed,...
are there any other dependencies one should be  ware of?

**Comment by dubhater** [comment]
Probably only what's documented: http://www.vapoursynth.com/doc/installation.html#linux-and-os-x-compilation-instructions

pkg-config is such a basic thing to have when compiling software that no one thought to list it there.

**Comment by myrsloik** [comment]
I guess I've always missed it too because brew probably grabbed it as a dependency for something else. Btw, why do you want to compile it yourself? The version in brew updated and good

**Comment by Selur** [comment]
Simple: I'm not using brew.
Since:
a. last time I tested it (years ago), it totally screwed my system.
b. it's easier to trace dependencies if you know what is used for compiling
