### ISSUE TITLE
In latest vapoursynth, Crash happened when using the miscfilters.

### ISSUE THREAD

**Issue by fuchanghao** [vapoursynth/vapoursynth#245]
vapoutsynth r1878
miscfilters v2.

When reading sth like this it would crash the whole vapoursyth with no error message.

```
input = a vs.YUV420P8 format video
def scale(val, bits):
    return val * ((1 << bits) - 1) // 255
bits = input.format.bits_per_sample
mthr=60
sobelm = core.std.Sobel(input, min=scale(mthr, bits), planes=[0])
output = core.misc.Hysteresis(core.std.Median(sobelm, planes=[0]), sobelm, planes=[0])
output.set_output()
```

**Comment by myrsloik** [comment]
I can't reproduce it. Seems to work here.

**Comment by fuchanghao** [comment]
OK test passed when building the source by self.

but crash in the official release.

too strange.

**Comment by myrsloik** [comment]
Maybe I didn't recompile it before releasing it or something. Will make another release sow e can find out...

**Comment by myrsloik** [comment]
I think I know why. I compiled my released build with clang. But oddly enough there's no code in there that should cause a crash... I'll try to debug it properly sometime.

**Comment by myrsloik** [comment]
Compiled it with clang and tried an x64 release build of the script you posted. I guess this issue is done. Heisenbug.

**Comment by fuchanghao** [comment]
it woeked fine with 
vapoutsynth r1890
miscfilters v3

thanks for the help.
