### ISSUE TITLE
What plugins should I use now instead of generic.TEdge.

### ISSUE THREAD

**Issue by fuchanghao** [vapoursynth/vapoursynth#247]
I know I can use the Tcanny for canny edge to get the better result.

But when I'm updating the scripts vsTAAmbk to support VS R33.1 or newer.

I need some plugins to support it.

**Comment by myrsloik** [comment]
Use sobel or prewitt? They're also a h/v convolution combined in the same way. You should be able to tweak them into something similar (note that sobel and prewitt were broken in r33 so use r34 rc if you want to try to replace it)
