### ISSUE TITLE
Convolution filter does not output correct results

### ISSUE THREAD

**Issue by 4re** [vapoursynth/vapoursynth#249]
Bug is more apparent in 8bit (vertical stripes and oversaturated image).

An example of this in 8bit:
`core.std.Convolution(res, matrix= [1, 1, 1, 1, 0, 1, 1, 1, 1], planes=0)` x8
[http://imgur.com/a/RB6Gk](http://imgur.com/a/RB6Gk)

**Comment by myrsloik** [comment]
Fixed it now, WHY U ALWAYS DO DIS AFTER A RELEASE? YYYYYY?
