### ISSUE TITLE
[vapoursynth-34]: compilation failure

### ISSUE THREAD

**Issue by tokiclover** [vapoursynth/vapoursynth#251]
Compiling with GCC-4.9.3:
I am getting this:
```
Makefile:1461: recipe for target 'src/core/libvapoursynth_la-vsresize.lo' failed
make: *** [src/core/libvapoursynth_la-vsresize.lo] Error 1
make: *** Waiting for unfinished jobs....
```
because of this:
```
src/core/vsresize.cpp: In constructor ‘{anonymous}::vszimg::vszimg(const VSMap*, void*, VSCore*, const VSAPI*)’:
src/core/vsresize.cpp:740:26: error: ‘struct vszimgxx::zfilter_graph_builder_params’ has no member named ‘allow_approximate_gamm
a’
                 m_params.allow_approximate_gamma = 1;
                          ^
src/core/vsresize.cpp:762:26: error: ‘struct vszimgxx::zfilter_graph_builder_params’ has no member named ‘nominal_peak_luminance
’
                 m_params.nominal_peak_luminance = propGetScalarDef<double>(in, "nominal_luminance", NAN, vsapi);
```

Sorry but I am not into C++ so, I cannot provide any patch to fix this but report the issue at hand.

[vapoursynth-34-build.log.txt](https://github.com/vapoursynth/vapoursynth/files/546267/vapoursynth-34-build.log.txt)

**Comment by 4re** [comment]
Are you linking against zimg 2.3?

**Comment by myrsloik** [comment]
Definitely not using a new enough zimg. The other issue is probably because of that too.

**Comment by tokiclover** [comment]
No, only to zimg-2.2.1? Is this where the zAPI change to 2.2?

**Comment by tokiclover** [comment]
Yes, zimg-2.3 links fine with vs-34; see #250 for comments on this with patch which should be modified to require zimg-2.3 or greater instead of only checking the API version.
