### ISSUE TITLE
Interlaced resizing completely broken

### ISSUE THREAD

**Issue by dubhater** [vapoursynth/vapoursynth#256]
Any frame with _FieldBased 1 or 2 will look like the first image here, or worse:
http://forum.doom9.org/showthread.php?p=1788420#post1788420

This is the bad commit: https://github.com/vapoursynth/vapoursynth/commit/296952bdbe4f805cb840e3bf9df98d4a52915b02

```python
src = core.d2v.Source("top field first.d2v")
src = core.resize.Bicubic(src, format=vs.RGB24, matrix_in_s="470bg")
```

**Comment by myrsloik** [comment]
Is this fixed now?

**Comment by dubhater** [comment]
Yes.
