### ISSUE TITLE
vapoursynth install error

### ISSUE THREAD

**Issue by diootty** [vapoursynth/vapoursynth#258]
I did downlod installer(VapourSynth-R35.exe) and run.

at select components klick next,  appear message.

'At least one version of the core liberary has to be installed.'

why appear this message?

**Comment by sofakng** [comment]
Do you have Python 3.5 or 3.6 installed?  I'm guessing you have 3.6 installed which isn't supported but should be very soon.  (commits were made a few days ago)

**Comment by diootty** [comment]
yes I has installed Python 3.6. vapoursynth is work only Python3.5?

**Comment by sofakng** [comment]
Yes, the current released version only supports Python 3.5, but support for 3.6 should be very soon based on the commits made last week.

**Comment by diootty** [comment]
Thasnk you very much!

**Comment by myrsloik** [comment]
Link to the python 3.6 test build is in the doom9 thread.

**Comment by myrsloik** [comment]
And I improved the error message a bit too
