### ISSUE TITLE
Failed to initialize VapourSynth environment with Python 3.6 on Windows

### ISSUE THREAD

**Issue by Rast1234** [vapoursynth/vapoursynth#260]
Hello. In commits included in the latest (R35) release, i noticed https://github.com/vapoursynth/vapoursynth/commit/cbbcd46ba48f3152940a44cf33f316f931d4bafd which is about Python 3.6 on Windows.

I tried it and always get "Failed to initialize VapourSynth environment" error. Also i can't install Vapoursynth with installer, because it does not let me proceed at the step with checkboxes, with error "At least one version of the core library has to be installed". I have only 3 options, and all selected:

* VapourSynth SDK
* Pismo PFM Runtime (required for AVFS)
* Visual Studio Runtimes (2013 & 2015)

I tried portable Python 3.5 and portable Vapoursynth R35, and it worked. Looks like Python 3.6 is not supported. Maybe you can mention this somewhere to help people not run into this problem?

**Comment by myrsloik** [comment]
The documentation clearly states that only Python 3.5 is supported.
