### ISSUE TITLE
Corruption on Frames without subtitles when using sub.TextFile

### ISSUE THREAD

**Issue by Frechdachs** [vapoursynth/vapoursynth#261]
When using sub.TextFile frames without subtitles get mangled on random requests.

[Example Image](https://abload.de/img/fm06nkkx.png)

Although I think I remember it happening without vsedit, I was only able to reliably reproduce it in vsedit by repeatedly refreshing the preview. So I reported it first there. ([https://bitbucket.org/mystery_keeper/vapoursynth-editor/issues/19/visual-artifacts-when-using-subtextfile](https://bitbucket.org/mystery_keeper/vapoursynth-editor/issues/19/visual-artifacts-when-using-subtextfile))

I currently work around it by trimming the clip with the burnt in subtitles exactly at the first and the last appearing subtitle line, and trim it back in the clip without subtitles. But it's a bit annoying.

**Comment by dubhater** [comment]
Is that VapourSynth r35 or newer?

**Comment by Frechdachs** [comment]
R35. But I remember it happening even before the renaming of assvapour.

**Comment by myrsloik** [comment]
Can anyone reproduce this on windows? I can't. That's an interesting detail

**Comment by HolyWu** [comment]
Yes, I can reproduce. 

vpy
```python
import vapoursynth as vs
core = vs.get_core()

clip = core.std.BlankClip(format=vs.YUV420P8, color=[255, 128, 128])
clip = core.sub.TextFile(clip, 'test.ass')

clip.set_output()
```

ass
```
[Script Info]
; Script generated by Aegisub 3.2.2
; http://www.aegisub.org/
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
PlayResX: 640
PlayResY: 480

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,20,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:01.00,0:00:03.00,Default,,0,0,0,,TEST
```

[Result](http://i.imgur.com/YSSIiZU.png)

**Comment by myrsloik** [comment]
Reproduced by me as well. But on my computer it mostly turns into a birghtening of the image. Odd

**Comment by dubhater** [comment]
Can't reproduce with HolyWu's script, with or without vsedit. Versions:
 - VapourSynth https://github.com/vapoursynth/vapoursynth/commit/4f712bd650d4abbfec15905bb67005e85b30bc88
- zimg 2.4
- libass 0.13.4
- vsedit r15

Please list your versions if you can still reproduce it.

**Comment by dubhater** [comment]
Valgrind found nothing either.

**Comment by myrsloik** [comment]
VapourSynth R36 and the compile of subtext included with it. Try making a new one for windows and I can see if it's fixed?

**Comment by dubhater** [comment]
What about zimg and vsedit versions? New subtext: 
[subtext-r36-win64.7z.zip](https://github.com/vapoursynth/vapoursynth/files/763563/subtext-r36-win64.7z.zip)
(Actual format is 7z.)

**Comment by dubhater** [comment]
> Can't reproduce with HolyWu's script, with or without vsedit. Versions:
Disregard that. I've been pressing F5 in the preview window.
