### ISSUE TITLE
Expose namespace and name of vapoursynth.Function

### ISSUE THREAD

**Issue by stuxcrystal** [vapoursynth/vapoursynth#262]
I propose that the namespace and name should be exposed as read-only properties to allow Python-based introspection on top of it.

**Comment by myrsloik** [comment]
There's a big problem with this. The core can load plugins (and thus add more functions/namespaces) from everywhere. Including secretly through getframe calls in plugins. Good for flexibility, not so good for presenting fixed lists of options on the Python side.

Solve that problem elegantly and it'll happen...

**Comment by stuxcrystal** [comment]
Exposing `name` as well as `signature` vapoursynth.Function would be an easy first step in that direction.
About the namespace/identifier: According to the documentation the namespace as well as the identifier of the plugin must be unique.

**Comment by myrsloik** [comment]
Expose it how? Examples

**Comment by stuxcrystal** [comment]
vapoursynth.pyx#L1304-1308 defines the following internal values.
```cython
cdef class Function(object):
    cdef Plugin plugin
    cdef str name
    cdef str signature
    cdef const VSAPI *funcs
```

Trying to access them using the current version R35 in vanilla Python-code will result in an exception:
```python
>>> import vapoursynth
>>> core = vapoursynth.get_core()
>>> core.std.ShufflePlanes.signature
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'vapoursynth.Function' object has no attribute 'signature'
```

Adding a read-only property for each attribute should be simple.

**Comment by myrsloik** [comment]
Ok, I'll add a name attribute to Plugin objects and name and signature to Function objects. Anything else you need?

**Comment by stuxcrystal** [comment]
Currently not.

**Comment by stuxcrystal** [comment]
Or actually, can you also add an attribute for the plugin-Instance?

**Comment by myrsloik** [comment]
I guess?

**Comment by stuxcrystal** [comment]
Then, well this would solve the problem of introspection entirely.

**Comment by myrsloik** [comment]
I think I'm done now
