### ISSUE TITLE
Debian repository

### ISSUE THREAD

**Issue by raberto-nowhere** [vapoursynth/vapoursynth#268]
Could debian possibly get a repository? Ubuntu has one and it's a pain to hunt down which commits on ffmpeg, ffms2, and zimg work for the current vapoursynth too

**Comment by myrsloik** [comment]
None of the contributors maintain repositories really. Not sure who does the ubuntu one. Finding the right versions isn't hard though.

zimg: the required branch is listed in install/build instructions
ffmpeg: check out master from around when ffms2 was release
ffms2: latest release

**Comment by stuxcrystal** [comment]
Actually, I needed a heavy dose of googling before finding the right repositories.
You should add a link to the github-repos you actually used to the build-instructions document.

**Comment by myrsloik** [comment]
http://www.vapoursynth.com/doc/installation.html#linux-and-os-x-compilation-instructions <- exactly what's missing from there? I link to zimg

**Comment by stuxcrystal** [comment]
Oh. I didn't think of reading the documentation. *derp*

In my defense: I was on windows. There was no documentation of compiling it there. Only the build-instructions. I honestly didn't think on checking the build instructions for the other OSes.
