### ISSUE TITLE
Unable to make on Fedora 25

### ISSUE THREAD

**Issue by RJXIII** [vapoursynth/vapoursynth#269]
After installing all dependencies, mandatory and optional, I'm facing the following error when I run make:

`src/core/vslog.h:27:73: error: use of deleted function ‘std::atomic<int>::atomic(const std::atomic<int>&)’
 #define vsWarning(...)  vsLog(__FILE__, __LINE__, mtWarning, __VA_ARGS__)
Makefile:1479: recipe for target 'src/core/libvapoursynth_la-vscore.lo' failed
make: *** [src/core/libvapoursynth_la-vscore.lo] Error 1`

**Comment by myrsloik** [comment]
Fixed now

**Comment by RJXIII** [comment]
Thanks, latest pull fixed it. 
I have another issue on running make:
`libtool: warning: '/usr/lib/gcc/x86_64-redhat-linux/6.3.1/../../../../lib64/libzimg.la' seems to be moved
/usr/bin/sed: can't read Setup/SVP/vapoursynth/libvapoursynth.la: No such file or directory
libtool:   error: 'Setup/SVP/vapoursynth/libvapoursynth.la' is not a valid libtool archive
Makefile:1088: recipe for target 'vapoursynth.la' failed
make: *** [vapoursynth.la] Error 1`

**Comment by myrsloik** [comment]
SVP? Is this really a normal install?

**Comment by RJXIII** [comment]
Ah sorry, I just noticed that SVP. Cloned into home directory and retried it, it works fine now.
The SVP part of my path seems to have been picked up from the folder in the other hard disk I was installing it from, as one of the SVP dependencies.
Thanks.
