### ISSUE TITLE
Incorrect values for Average and Max when using std.PlaneStats

### ISSUE THREAD

**Issue by Frechdachs** [vapoursynth/vapoursynth#270]
The `Average` and `Max` values are sometimes wrong when using `std.PlanStats` on clips of various uncommon resolutions.
```python
import vapoursynth as vs

def print_stats(clip):
    for i in range(len(clip)):
        props = clip.get_frame(i).props
        print("Frame: {}, Average: {}, Max: {}".format(i, props.PlaneStatsAverage, props.PlaneStatsMax))

core = vs.get_core()
clip = core.ffms2.Source("1080p.mkv")
clip = core.std.Expr([clip,clip], "x y -")  # Every pixel value should be 0 now
clip = core.std.CropRel(clip, 6, 6, 6, 6)  # Resolution is now 1908x1068
clip = core.std.PlaneStats(clip)
print_stats(clip)
```
With this script I get the following output:
![Image](https://0x0.st/f7e.png)
`Average` and `Max` should be `0` for every frame.

I don't think `std.CropRel` is the culprit because the problem persists if I switch `std.CropRel` with `resize.Bicubic(clip, 1908, 1068)`. However, when using `resize.Bicubic` I can only reproduce this with 8-bit clips, when using `std.CropRel` I can reproduce it with 8-, 10-, and 16-bit clips. Very strange ...

I was able to reproduce it with just `std.BlankClip` and `std.PlaneStats` too, but much less consistently.

Also, I noticed that `Max` is always _at least_ `32768` when `std.PlaneStats` is used on 10- or 16-bit clips.

Edit:
Forgot to metion that I'm currently on https://github.com/vapoursynth/vapoursynth/commit/fe0475945902272ab2594e90d3f1bc9cabced6be.

**Comment by dubhater** [comment]
Do you still get this problem if you pass the clip to PlaneStats twice? It then uses a different code path to calculate PlaneStatsDiff too.
```
clip = core.std.PlaneStats(clip, clip)
```

**Comment by Frechdachs** [comment]
When passing the clip twice, the only problem I can reproduce is this one:

>Also, I noticed that `Max` is always at least `32768` when `std.PlaneStats` is used on 10- or 16-bit clips.

**Comment by myrsloik** [comment]
There's definitely an asm bug for non-mod 8 widths

**Comment by myrsloik** [comment]
Try the latest commit

**Comment by Frechdachs** [comment]
Works now, thank you.
