### ISSUE TITLE
Add "bind" methods

### ISSUE THREAD

**Issue by cleansheets** [vapoursynth/vapoursynth#272]
Add VapourObject and make all user interfacing objects inherit it:
http://pastebin.com/c8qbLYLL
This allows to add methods and attributes as well as allow for seamless wrapping of functions
Plugin, Function, VideoNode, VideoFrame, VideoProps etc

**Comment by stuxcrystal** [comment]
To be honest, I don't really understand why most of your reasons are not already implementable with standard library tools like functools.partial[1]. Additionally you can try the library [forbiddenfruit][2] if you really want to monkey-patch the vapoursynth classes.

In the end, I don't think that being able to monkey-patch classes is a good idea.

[1]: https://docs.python.org/3/library/functools.html#functools.partial
[2]: https://pypi.python.org/pypi/forbiddenfruit/0.1.0

**Comment by myrsloik** [comment]
I believe cdef classes in cython won't work with this anyway since they don't have a __dict__ by default. Also I have no idea what this would accomplish...

**Comment by cleansheets** [comment]
Right, even the forbiddenfruit module says:
 AttributeError: There is no function named __dict__
The goal of implementing such method is to allow wrapping vs functions with added functionality seamlessly. For example, bind c.std.Splice to c.std.original_Splice and bind my new splice function to c.std.Splice with its added new functionality to achieve seamless usage experience and allow for nice propagation with splice operator and all scripts and modules that use c.std.Splice. That is just one example.

**Comment by stuxcrystal** [comment]
Why do want this anyway? All this would accomplish is opening VapourSynth to mokey-patching.

Relying your code on monkey-patches is almost always bad practice. I don't think VapourSynth should support badly written code.
