### ISSUE TITLE
Build problem fatal error: cannot specify -o with -c, -S or -E with multiple files

### ISSUE THREAD

**Issue by kidburglar** [vapoursynth/vapoursynth#278]
Hello everyone,
I'm sure the error come because I set the libs in some tricky directories but I'm curious why I have this error.

My OS is Debian Jessie.

I export env variables for ZIMG first.
`export ZIMG_CFLAGS="$HOME/.local/include/zimg.h"`
`export ZIMG_LIBS="$HOME/.local/lib/libzimg.so"`

I do the classical ./configure
`./configure --prefix=$HOME/.local`

The error show when I launch the make command
`make`

>   CXX      src/core/libvapoursynth_la-cachefilter.lo
g++: fatal error: cannot specify -o with -c, -S or -E with multiple files
compilation terminated.
Makefile:1420: recipe for target 'src/core/libvapoursynth_la-cachefilter.lo' failed
make: *** [src/core/libvapoursynth_la-cachefilter.lo] Error 1

Thanks for your help, cheers.

Edit:
I confirmed that it work if I build zimg with a normal prefix (/usr/local)

**Comment by dubhater** [comment]
```
export ZIMG_CFLAGS="-I$HOME/.local/include"
export ZIMG_LIBS="-L$HOME/.local/lib -lzimg"
```
Or you can just set PKG_CONFIG_PATH:
```
PKG_CONFIG_PATH="$HOME/.local/lib/pkgconfig" ./configure --prefix=$HOME/.local
```

**Comment by kidburglar** [comment]
Perfect, I did the command with PKG_CONFIG_PATH and it's ok now.
Thanks ^^
