### ISSUE TITLE
Unable to compile on stock Ubuntu 16.04 64-bit (fully updated)

### ISSUE THREAD

**Issue by Silvertower** [vapoursynth/vapoursynth#280]
```
  CYTHON   src/cython/vapoursynth.c

Error compiling Cython file:
------------------------------------------------------------
...
    def __init__(self):
        raise Error('Class cannot be instantiated directly')

    def __str__(self):
        return ('Format Descriptor\n'
               f'\tId: {self.id:d}\n'
              ^
------------------------------------------------------------

src/cython/vapoursynth.pyx:597:15: Expected ')', found 'f'
Makefile:1971: recipe for target 'src/cython/vapoursynth.c' failed
make: *** [src/cython/vapoursynth.c] Error 1
```

This might be due to 55cfa608528f170d6a9db7eb11b341450c44d8a9.

**Comment by Silvertower** [comment]
To be more specific: Compiling R35 works fine, but R36 (and master from git) fail. This looks like a change that may require Python 3.6 (just based on git comments; I have not tested with Python 3.6).

**Comment by stuxcrystal** [comment]
The change was introduced by #273. It uses Python 3.6 f-strings to format it's __str__ fuction.

**Comment by myrsloik** [comment]
Did you try to update cython to the latest version?

**Comment by myrsloik** [comment]
Btw, it works in Python 3.5 at least.

**Comment by 4re** [comment]
This incompatibility with <=python3.4 will be kept? I ask because I maintain gentoo's vapoursynth overlay and I don't want to start editing ebuilds only to revert back everything next day.

**Comment by myrsloik** [comment]
What isn't compatible at the moment?

**Comment by 4re** [comment]
Mmh... I don't' know because I can't test python3.4, but I understood from https://github.com/vapoursynth/vapoursynth/issues/280#issuecomment-274725918 that f-strings formatting in PR https://github.com/vapoursynth/vapoursynth/pull/273 was introduced in python at 3.5 release.

**Comment by Kamekameha** [comment]
Yes, but Cython supports f-strings internally regardless of Python version, since 0.24 that is.

**Comment by myrsloik** [comment]
I tested and Python 3.3 is the lowest supported version. 3.2 fails on importing collections.abc (I guess it's easily fixable IF someone cares about python 3.2, I don't)

**Comment by xekon** [comment]
yes updating pip and cython do the trick, im on kubuntu and did the following:
sudo -H pip3 install --upgrade pip
sudo -H pip3 install --upgrade cython
