### ISSUE TITLE
Sobel and Prewitt are slow since R34

### ISSUE THREAD

**Issue by HolyWu** [vapoursynth/vapoursynth#291]
I downloaded portable versions of R33.1 to R35 and tested a bit. I got 40 fps on a 1920x1080 YUV420P8 clip in R33.1. The speed droped to 11~12 fps in R34 to R36.

**Comment by myrsloik** [comment]
I'll use clang for the next release build then. Should improve things again...

**Comment by HolyWu** [comment]
Um...I happen to find out that Sobel and Prewitt didn't have intrinsics. I originally thought they got SIMD optimized in R33 and something messed up in R34.

**Comment by myrsloik** [comment]
I can optimize them if you need it. It isn't much work...

**Comment by HolyWu** [comment]
It's better to have than not. It benefits all users after all.
