### ISSUE TITLE
Any guide to build it via visual studio 2017?

### ISSUE THREAD

**Issue by fuchanghao** [vapoursynth/vapoursynth#294]
I don't know how to change the vcxproj files to support visual studio 2017 (R37-RC1).

**Comment by myrsloik** [comment]
It's already supported. Install the other requirements and it'll work

**Comment by fuchanghao** [comment]
The clang will set the path to C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140 not C:\Program Files (x86)\Microsoft Visual Studio\2017\*\Common7\IDE\VC\VCTargets

* means Community/Professtional/Enterprise

**Comment by myrsloik** [comment]
In that case it's not a supported build configuration (yet)
R38 will probably move to VS2017+clang for releases
If you don't like clang just set the platform toolset to the standard visual studio one

**Comment by myrsloik** [comment]
I've started converting things and at the moment the last major problem is that Python's setuptools hasn't merged VS2017 support yet. But at least there is a pull request for it so I guess it won't take too long.

**Comment by fuchanghao** [comment]
I could only use VC140+clang 4.0.0 but not work with VC141+Clang 4.0.0.
So I still use VC141 instead of Clang to build it.

I don't know if that would cause bugs or not.

**Comment by caoli5288** [comment]
Build by `mingw-w64` toolchain is much more gracefully.

**Comment by myrsloik** [comment]
I've stopped using clang for now. Seems like it still has a few issues with vapoursynth.dll
