### ISSUE TITLE
Crashes of vspipe that happens in vapoursynth R37-RC1

### ISSUE THREAD

**Issue by fuchanghao** [vapoursynth/vapoursynth#295]
fmtconv r20
vapoursynth R37-RC1
zimg 2.4/2.5

When encoding it with vspipe one by one(or use vsedit to preview it again immediately after close it) .

Test result are:
When set the threads=12 to 1 it works but I can't encode the video in single thread.
When using the core.resize it works fine.
It only happened when using the fmtconv.

sample code

```
import vapoursynth as vs
import sys

core = vs.get_core(accept_lowercase=True,threads=12)

a = r'H:\Strike Witches The Movie\StrikeWitches_Movie\BDMV\STREAM\00033.m2ts'
src8 = core.lsmas.LWLibavSource(a,threads = 1)
src16 = core.resize.Spline36(src8, width=1920, height=1080, format=vs.RGB48, matrix_in_s="709")

R = core.std.ShufflePlanes(src16, 0, colorfamily=vs.GRAY)

G = core.std.ShufflePlanes(src16, 1, colorfamily=vs.GRAY)
#G = core.resize.Spline36(G, 1920, 1080, src_left = 1.0, src_top = 0.5, src_width = 1919, src_height = 1079.5)
G = core.fmtc.resample(G, 1920, 1080, sx = 1.0, sy = 0.5,sw = -1.0, sh = -0.5)

B = core.std.ShufflePlanes(src16, 2, colorfamily=vs.GRAY)
#B = core.resize.Spline36(B, 1920, 1080, src_left = 2.0, src_top = 1.0,src_width = 1918, src_height = 1079)
B = core.fmtc.resample(B, 1920, 1080, sx = 2.0, sy = 1.0,sw = -2.0, sh = -1.0)

res = core.std.ShufflePlanes([R ,G ,B], [0,0,0], vs.RGB)
res.set_output()
```

**Comment by dubhater** [comment]
Why use fmtconv at all?

**Comment by fuchanghao** [comment]
yes x64 windows.

**Comment by myrsloik** [comment]
I'll try to reproduce it but this kinda sounds like a fmtconv bug... Does it break with a simple blankclip too?

Negative width/height? you mean flipping in one operation?

**Comment by fuchanghao** [comment]
@myrsloik
-1.0 means src_width = width - 1.0.

test when sending a core.std.BlankClip(width=1920, height=1080, format=vs.YUV420P8, length=24000) as a clip doing the same and piping to x265 for encoding , it will crash in the second encoding time.
But the core.resize works fine.

**Comment by myrsloik** [comment]
Can't reproduce. Since you obviously compile it all yourself you should use the debugger...

**Comment by fuchanghao** [comment]
OK I understand.

**Comment by myrsloik** [comment]
Works in my compiles now. You've probably miscompiled it somehow.

**Comment by fuchanghao** [comment]
tested with R37 official relase.
Happened the same.

**Comment by myrsloik** [comment]
Tested it again and it totally works for me here. Win 10 x64 all updates. 5820k CPU.

**Comment by dubhater** [comment]
> it happened in vscore.cpp
> ```
> PVideoFrame VSNode::getFrameInternal(int n, int activationReason, VSFrameContext &frameCtx) {
>    const VSFrameRef *r = filterGetFrame(n, activationReason, &instanceData, &frameCtx.ctx->frameContext, &frameCtx, core, &vs_internal_vsapi);
> ```

Isn't it pointing to that line because it crashed inside fmtconv's getframe function and you didn't supply a debug build of fmtconv?

**Comment by fuchanghao** [comment]
it seems that the VC141 build of Vapoursynth and fmtconv works fine.
but official fmtconv&Vapoursynth would cause crash,

Too strange.my system is windows server 2016 ,Is that the problem?

**Comment by myrsloik** [comment]
https://dl.dropboxusercontent.com/u/73468194/VapourSynth-R38-test2.exe <- I switched back to vs2017, check to see if this one works properly

**Comment by fuchanghao** [comment]
It works fine now.
