### ISSUE TITLE
16bit RGB frameserving missing hi-byte

### ISSUE THREAD

**Issue by madshi** [vapoursynth/vapoursynth#296]
Let me start by saying that I'm not 100% sure it's a bug in VapourSynth, but I think it's worth investigating.

```
import vapoursynth as vs
core = vs.get_core()
video = core.ffms2.Source(source='bunny_RGB.mkv')
video = core.fmtc.bitdepth(video, bits=16)
video.set_output()

```
The script above should produce 16bit RGB frameserving. When trying to "play" such a script with madVR, I only seem to get a black screen. I've debugged the issue and on a quick check it seems that the high byte of each RGB word is empty, while the low byte looks like it is probably ok.

Of course it could be a bug in madVR, too, sadly no other renderer accepts 16bit RGB, so I can't easily check that. It could also be a bug in the filter which reads/splits the frameserved AVI. Or it could be a bug in the VapourSynth frameserving code. The latter two options are the most likely.

FWIW, upscaling to 16bit in the middle of a script and then downconverting it to 8bit later on works fine. So the issue is not with 16bit transport inside of VapourSynth, or 16bit output of a VapourSynth plugin. The issue is somewhere in the frameserving, or in the AVI splitting, or in the renderer. I don't think it's in the renderer, based on a quick debug.

**Comment by myrsloik** [comment]
Which fourcc is the output with this problem? b64a?

**Comment by sekrit-twc** [comment]
Could it be that the "empty" high byte is actually the LSB (which is zero, because of 8->16 extension) and the "low byte" is the MSB?

**Comment by madshi** [comment]
Yes, it's b64a.

I've tried to swap low and high bytes, but that didn't help. The image isn't black then, anymore, but wildly corrupted. Which makes sense, and which is the reason why I suggested that the low-byte is probably correctly filled.

**Comment by sekrit-twc** [comment]
I tried this in VDubFilterMod and it produces the expected output.

    c = core.std.BlankClip(format=vs.RGB48, color=[64000, 0, 0])
    c.set_output()

Are you reading from the VFW interface?

**Comment by madshi** [comment]
I've simply dragged the vpy script to MPC-HC for playback. Looking at the graph, the DirectShow filter "AVI/WAV file source" is used. GUID is {D3588AB0-0781-11CE-B03A-0020AF0BA770}.

**Comment by myrsloik** [comment]
I can confirm it certainly doesn't work but why it doesn't work is a more difficult question... I'll try to find some more software that supports b64a input to test it further.

**Comment by myrsloik** [comment]
I verified that all the bits are copied out. in a debugger. Not sure how to proceed since I try to avoid directshow as much as possible.

**Comment by madshi** [comment]
In that case I would say there's a 95% chance that the bug is in the DirectShow AVI splitter. Probably not much we can do about that.

**Comment by myrsloik** [comment]
Oddly enough y416 goes through proper

**Comment by myrsloik** [comment]
Stupid phone. Maybe I fill out some header field wrong.

**Comment by madshi** [comment]
I'll double check with AviSynth+ when I find some time. Not sure if it can output b64a, though.

**Comment by madshi** [comment]
Just tried the following script with AviSynth+:

```clip = ImageSource("castle.bmp")
return clip.ConvertBits(16)```

This displays fine in madVR, but it's not using b64a, but instead "RGB48LE".

`DEFINE_GUID(MEDIASUBTYPE_RGB48LE,  '0BGR', 0x0000, 0x0010, 0x80, 0x00, 0x00, 0xaa, 0x00, 0x38, 0x9b, 0x71);`

**Comment by madshi** [comment]
JFYI, done some more tests:

AviSynth+ succeeds sending out any RGB and YUV pixel format between 8 and 16bit to AVI. VapourSynth almost manages to do the same (after your recent 4:2:2 10bit feature addition). However, AviSynth+ has one extra trick up its sleeve:

When a bitdepth is not natively supported for AVI output, AviSynth+ automatically upconverts to 16bit. So e.g. 12bit and 14bit formats are automatically output as 16bit by AviSynth+. While not overly important, this is a nice extra trick.

On the other hand, I think AviSynth+ only supports a specific number of bitdepths, while VapourSynth can do any bitdepth, e.g. 13bit. So that's something VapourSynth does better.

Also, I tried making AviSynth+ output b64a or RGB64LE, but couldn't manage to. Even when forcing an alpha channel on output, it still always sends RGB48LE to AVI output.

**Comment by myrsloik** [comment]
I'll try to think of some more meaningful tests. I don't autoconvert simply because I hate automatic conversions.

**Comment by myrsloik** [comment]
Definitely a madvr bug. You can prove the directshow avi/wav source is innocent by dumping its raw output. Bug appears with no other filters in between.
