### ISSUE TITLE
Pixel shift when using vertical convolution

### ISSUE THREAD

**Issue by WolframRhodium** [vapoursynth/vapoursynth#297]
Example:
```
clip = core.std.Convolution(clip, matrix=[0, 1, 0], mode='v')
```

Theoretically, there should be no difference between before and after this filtering, but that is obviously not in the current version. The problem arises in all formats.

I guess the reason for this problem is the incorrect matrix initialization at [generatefilters.cpp](https://github.com/vapoursynth/vapoursynth/blob/master/src/core/genericfilters.cpp#L2269) and the following line 2278.

They should be
```
d->matrix[4] = d->matrix[1];

d->matrixf[4] = d->matrixf[1];
```

**Comment by dubhater** [comment]
That mistake aside, I wonder if the 1x3 vertical convolution is translated correctly into 3x3. One would expect to start at the top, right?
```C++
d->matrix[7] = d->matrix[0];
d->matrix[4] = d->matrix[1];
d->matrix[1] = d->matrix[2];
d->matrix[0] = 0;
d->matrix[2] = 0;
d->matrix[3] = 0;
d->matrix[5] = 0;
d->matrix[6] = 0;
d->matrix[8] = 0;
```

**Comment by dubhater** [comment]
Or, oh, it's not like a numpad... Nevermind.

**Comment by WolframRhodium** [comment]
In my opinion, the convolution filter in VapourSynth is a "correlation filter", but this does not matter. Most people use a symmetry matrix, and in this case, covolution filter is the same as correlation filter.

**Comment by myrsloik** [comment]
Well spotted, it's fixed now
