### ISSUE TITLE
Do constant folding in Expr

### ISSUE THREAD

**Issue by alexrp** [vapoursynth/vapoursynth#3]
When both of an operator's operands are (recursively) constants, we should compute the result value ahead of time.

**Comment by dubhater** [comment]
There is the obvious case of ``10 5 +``. But what about ``10 x + 5 +``? Should that be handled too?

**Comment by myrsloik** [comment]
Preferably both should be simplified I think. But already the simple case should reduce the needed number of per pixel operations by half in many expressions.

**Comment by myrsloik** [comment]
Done by debhater
