### ISSUE TITLE
build error in win32 build with VC141 toolchain(r2073)

### ISSUE THREAD

**Issue by fuchanghao** [vapoursynth/vapoursynth#302]
I tried fix visual studio and it showed the same error.x64 build works fine.

error log

> 1>  正在创建库 D:\Source code\vapoursynth\msvc_project\Release\VapourSynth.lib 和对象 D:\Source code\vapoursynth\msvc_project\Release\VapourSynth.exp
> 1>正在生成代码
> 1>d:\source code\vapoursynth\zimg\src\zimg\colorspace\operation_impl_sse.cpp : fatal error C1001: 编译器中发生内部错误。
> 1>(编译器文件“f:\dd\vctools\compiler\utc\src\p2\main.c”，第 255 行)
> 1> 要解决此问题，请尝试简化或更改上面所列位置附近的程序。
> 1>请选择 Visual C++
> 1>“帮助”菜单上的“技术支持”命令，或打开技术支持帮助文件来获得详细信息。
> 1>
> 1>d:\source code\vapoursynth\zimg\src\zimg\colorspace\operation_impl_sse.cpp : fatal error C1001: 编译器中发生内部错误。
> 1>(编译器文件“f:\dd\vctools\compiler\utc\src\p2\main.c”，第 255 行)
> 1> 要解决此问题，请尝试简化或更改上面所列位置附近的程序。
> 1>请选择 Visual C++
> 1>“帮助”菜单上的“技术支持”命令，或打开技术支持帮助文件来获得详细信息。
> 1>
> 1>
> 1>LINK : fatal error LNK1000: Internal error during IMAGE::BuildImage
> 1>
> 1>  Version 14.10.25017.0
> 1>
> 1>  ExceptionCode            = C0000005
> 1>  ExceptionFlags           = 00000000
> 1>  ExceptionAddress         = 4FFB294C (4FF40000) "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.10.25017\bin\HostX86\x86\c2.dll"
> 1>  NumberParameters         = 00000002
> 1>  ExceptionInformation[ 0] = 00000000
> 1>  ExceptionInformation[ 1] = 00000004
> 1>
> 1>CONTEXT:
> 1>  Eax    = 00000000  Esp    = 012FED00
> 1>  Ebx    = 00000000  Ebp    = 012FED18
> 1>  Ecx    = 00000000  Esi    = 00000000
> 1>  Edx    = 00001020  Edi    = 01B84A4C
> 1>  Eip    = 4FFB294C  EFlags = 00010246
> 1>  SegCs  = 00000023  SegDs  = 0000002B
> 1>  SegSs  = 0000002B  SegEs  = 0000002B
> 1>  SegFs  = 00000053  SegGs  = 0000002B
> 1>  Dr0    = 00000000  Dr3    = 00000000
> 1>  Dr1    = 00000000  Dr6    = 00000000
> 1>  Dr2    = 00000000  Dr7    = 00000000
> 1>已完成生成项目“Core.vcxproj”的操作 - 失败。

**Comment by myrsloik** [comment]
Looks like you picked the clang/c2 toolchain. That dies all the time. Go check your settings
