### ISSUE TITLE
missing output support for 4:4:4 10bit (Y410)

### ISSUE THREAD

**Issue by madshi** [vapoursynth/vapoursynth#305]
This is a very minor thing. When trying to play vpy scripts with various different output formats with MPC-HC/madVR, here's what I'm getting:

4:2:0 8bit -> works perfectly
4:2:0 10bit -> works perfectly
4:2:0 16bit -> works perfectly
4:2:2 8bit -> works perfectly
4:2:2 10bit -> works perfectly
4:2:2 16bit -> works perfectly
4:4:4 8bit -> works perfectly
4:4:4 10bit -> "VFW module doesn't support YUV444P10 output"
4:4:4 16bit -> works perfectly (after having fixed madVR's Y416 handling)

It's probably not important. But it would be "nice to have" support for all formats. The only one not working is 4:4:4 10bit. FWIW, a suitable FOURCC for that would be Y410.

If you don't consider this worth implementing, I'm fine with closing this issue.

**Comment by myrsloik** [comment]
Should be implemented now but remember to test it so I got it right.

**Comment by madshi** [comment]
Great - thank you!  :)

**Comment by myrsloik** [comment]
https://dl.dropboxusercontent.com/u/73468194/VapourSynth-R38-test2.exe <- Can you verify that this build works?

**Comment by madshi** [comment]
Works! Thank you...  :)
