### ISSUE TITLE
vspipe slower than vsedit ? :)

### ISSUE THREAD

**Issue by alexblhr** [vapoursynth/vapoursynth#306]
Hello
I was doing some tests today and found out that vspipe is slower compared to vsedit pipe with any type of source 
This is my vpy 

```
import vapoursynth as vs
core = vs.get_core();
c = core.ffms2.Source(source='test.mp4',fpsnum=24000,fpsden=1001,cache=True);
c.set_output()
```

`vspipe --y4m test.vpy - | ffmpeg10bit -i pipe: -c:v copy -f NULL -`

8 fps

vsedit with Encode video menu with Y4M header , same executable and `-i pipe: -c:v copy -f NULL -` as arguments

22 fps

for the sake of it i also tested x265 instead of ffmpeg

`vspipe  --y4m test.vpy - | x265 --frames 462 --crf 0 --preset ultrafast --input-csp i420 --input-depth 10 --input-res 3840x2160 --fps 24000/1001 --output test.h265 -`

5.5fps

vsedit with Encode video menu with Y4M header , same executable and `--frames 462 --crf 0 --preset ultrafast --input-csp i420 --input-depth 10 --input-res 3840x2160 --fps 24000/1001 --output test.h265 -` as arguments

10.6fps

Output results in both cases are the same. Mediainfo is the same , so deffinetly its using the same options vspipe vs vsedit. I have no idea why vsedit is faster , but it deffinetly is. Confirmed on multiple machines in case one of them was acting weird. Confirmed with different type of sources.

Ideas ?

**Comment by dubhater** [comment]
That's a rather big difference. Did you look at the clock?

**Comment by alexblhr** [comment]
Clock ? You mean time taken for the encodes to finish ? Yes , vsedit is a lot faster. 2 times faster tbe

**Comment by dubhater** [comment]
And how many minutes did it take to encode one of these samples?

**Comment by alexblhr** [comment]
They are only 462 frames , so its fast. You want exact numbers ?
462/ frames per command :D
Can we get to the point where the assumption of me being an idiot is removed ?

**Comment by HolyWu** [comment]
I can't reproduce your result, and in my test vspipe is faster than vsedit.

vpy
```python
import vapoursynth as vs
core = vs.get_core(threads=0)
clip = core.std.BlankClip(width=1920, height=1080, format=vs.YUV420P8, length=5000, fpsnum=24000, fpsden=1001, color=[128, 128, 128], keep=True)
clip.set_output()
```

`vspipe64 --y4m "test.vpy" - | x264_64 --preset ultrafast --demuxer y4m --sar 1:1 --threads 8 --output NUL -`
encoded 5000 frames, 240.93 fps, 7.07 kb/s, 179.98 KB
x264 [info]: ended at Fri Apr 07 19:52:52 2017
x264 [info]: encoding duration 0:00:21

vsedit's "Encode video" with Y4M header and `--preset ultrafast --demuxer y4m --sar 1:1 --threads 8 --output NUL -` as arguments
encoded 5000 frames, 127.90 fps, 7.07 kb/s, 179.98 KB
x264 [info]: ended at Fri Apr 07 19:54:41 2017
x264 [info]: encoding duration 0:00:40

**Comment by alexblhr** [comment]
@HolyWu 
With your example im getting the same results as you
However , can you try it like that ?

```
import vapoursynth as vs
core = vs.get_core(threads=0)
clip = core.std.BlankClip(width=3840, height=2160, format=vs.YUV422P10, length=5000, fpsnum=24000, fpsden=1001, color=[128, 128, 128], keep=True)
clip.set_output()
```

**Comment by HolyWu** [comment]
YUV420P8
vspipe: 44.39 fps
vsedit: 37.26 fps

YUV422P8
vspipe: 35.99 fps
vsedit: 29.48 fps

YUV420P10
vspipe: 12.17 fps
vsedit: 19.11 fps

YUV422P10
vspipe: 10.33 fps
vsedit: 14.81 fps

Hmm......

**Comment by 4re** [comment]
I did test the last script only with /dev/null output, but for me vspipe is always slower than vsedit, sometimes like really slower.
```
YUV420P8
vsedit 1160
vspipe 936.47

YUV422P10
vsedit 1180
vspipe 395.64

YUV420P16
vsedit 1193
vspipe 574.52
```

**Comment by alexblhr** [comment]
@4re wow thats even worse than here

**Comment by sekrit-twc** [comment]
Can you try my 'pipe_example' application (https://github.com/sekrit-twc/vsxx)? I noticed in some testing that vspipe can be bottlenecked on really fast scripts, because it writes frames from the render threadpool, which blocks the execution.

**Comment by alexblhr** [comment]
@sekrit-twc  vspipe is slower on any type of script no matter if its slow or fast
my scripts run at 10fps , so they are deffinetly slow scripts,  while @4re scripts run at 1000 , deffinetly fast and we both have the same results - vspipe slower than vsedit

i assume even @HolyWu results are wrong for 8bit and vspipe is slower than vsedit even for 8bit because he left full output in vsedit

**Comment by dubhater** [comment]
What is "full output"?

**Comment by alexblhr** [comment]
@dubhater log settings with "common message" enabled

**Comment by myrsloik** [comment]
https://dl.dropboxusercontent.com/u/73468194/VSPipe.exe <- can anyone test with this x64 vspipe and see if it's still slow or at least a little bit better?

**Comment by HolyWu** [comment]
I get an instant crash with the message `getVideoInfo: Out of bounds videoinfo index 0. Valid range: [0,-1]`.

**Comment by myrsloik** [comment]
Doh, that only happened on some files. Download it again and see what happens.

**Comment by HolyWu** [comment]
The difference between the old and new vspipe seems negligible. This time I turned off the progress indicator of x264 and now vsedit is always the fastest.

YUV420P8
vsedit: 35.717
vspipe(old): 32.28
vspipe(new): 32.51

YUV422P8
vsedit: 28.344
vspipe(old): 26.12
vspipe(new): 26.40

YUV420P10
vsedit: 18.615
vspipe(old): 10.74
vspipe(new): 9.92

YUV422P10
vsedit: 14.273
vspipe(old): 8.63
vspipe(new): 8.51

**Comment by myrsloik** [comment]
I can't even reproduce the difference. Can someone with the problem find me on irc so we can go through this in more detail?

**Comment by myrsloik** [comment]
I tried with HolyWu's suggestion and used YUV422P10 instead. Same result. No difference or vspipe is faster.
I also uploaded another vspipe test build (same link as before). If you want to try it. It uses a strategy more similar to vsedit. Maybe you're all just imagining the issue?

**Comment by HolyWu** [comment]
Great. With the new test build vspipe is significantly faster than vsedit.

Test using BlankClip
YUV420P8
vsedit: 37.76
vspipe: 55.34

YUV422P10
vsedit: 15.35
vspipe: 22.26

Test using video files
YUV420P8
vsedit: 24.39
vspipe: 29.63

YUV422P10
vsedit: 9.658
vspipe: 13.15

**Comment by myrsloik** [comment]
This makes no sense at all. I guess many small write calls to a pipe is very bad on some computers somewhere for some reason. Except that it's just fine in other ones.
