### ISSUE TITLE
Is it possible to increase the matrix elements of the convolution filter?

### ISSUE THREAD

**Issue by WolframRhodium** [vapoursynth/vapoursynth#307]
There's a [upper limit](https://github.com/vapoursynth/vapoursynth/blob/7ec40f1e9a4d5ffe72b2e1cdd99bf3a5b8920acb/src/core/genericfilters.cpp#L2206) of numbers in horizontal/vertical convolution filter.
For large radius convolution, current maximum radius (9) is not enough.
Wondering if the maximum numbers of convolution kernel can be increased?

I am looking for a method to use a wide range of BoxFilter.
Because it looks like there's no direct solution, I decide to use vertical and horizontal convolution to implement it.

**Comment by myrsloik** [comment]
I'll increase the max. I've also been thinking about implementing a box blur filter some day since everyone uses insanely big radius stuff, especially in old avisynth scripts. If I write a box filter, what should it be able to apart from the simplest blur?

**Comment by WolframRhodium** [comment]
Can constant coefficient convolution have much better performance than custom convolution?

**Comment by myrsloik** [comment]
Depends on the coefficients. But in general I think only the simplest coefficient cases (like all ones) would be faster. And even then you can quite often reach memory BW limits with several threads.

**Comment by myrsloik** [comment]
I'll increase it to 25 elements (there's actually a reason for this, more could cause overflow issues later if I ever want to optimize it). I've also thought about writing a general FFTW3 based filter but haven't thought about how to structure it. That could also be faster if you want huge convolutions.

**Comment by WolframRhodium** [comment]
Thanks.

**Comment by myrsloik** [comment]
https://dl.dropboxusercontent.com/u/73468194/VapourSynth-R38-test2.exe <- here's a build where it's increased to 25

**Comment by WolframRhodium** [comment]
Good. Thank you.
