### ISSUE TITLE
Create general FFTW3 based convolution filter

### ISSUE THREAD

**Issue by myrsloik** [vapoursynth/vapoursynth#309]

**Comment by HuBandiT** [comment]
Care to outline some requirements? I am currently playing with FFTW3 in VS.

**Comment by myrsloik** [comment]
Requirements is kinda where I got stuck, I just couldn't think of what exactly to do. I think vcmohan did a pile of fftw based filters and while some of them sound a bit interesting they're just too specific for me to bother replicating. Design is hard...

**Comment by HuBandiT** [comment]
Ahh... I know the feeling!

Well, food for thought: provide FFT and IFFT filters for frames, with an integrated parameterizable decomposition into blocks, e.g. decompose this image into 16x16 pixel blocks, with a half-way (8 px) overlap, with specified window, and give me an output image that contains the FFT of each block copied next to each other, that is without overlap (the image gets larger). (Plus inverse of all this.)

Or actually, maybe separate them: 1. parametrizable block-decompose, 2. FFT. (3. IFFT, 4. recompose)

**Comment by myrsloik** [comment]
That could be interesting for prototyping things and it's close to how a couple of other filters work.

**Comment by HuBandiT** [comment]
Indeed!

Then add a multiply function (or actually - there's wonderful `Expr()` already), plus a function to render filter kernels as images, and we almost have efficient convolution of arbitrarily large kernels.

And soon there will be experiments with deconvolution for deblurring video (think http://yuzhikov.com/articles/BlurredImagesRestoration1.htm or [Unshake](http://www.zen147963.zen.co.uk/code.html) or Adobe PhotoShop's [SmartSharpen](https://software.intel.com/sites/default/files/managed/c5/9a/The-Compute-Architecture-of-Intel-Processor-Graphics-Gen9-v1d0.pdf#page=18). (And then we can change our slogan to: _VapourSynth - where 0.01 FPS counts "FAAAAST!"_ :) )
