### ISSUE TITLE
Visual C++ 2017 Redistributable bug when installing the R38-test3.

### ISSUE THREAD

**Issue by fuchanghao** [vapoursynth/vapoursynth#311]
When updating the visual studio to 26403.07 the Visual C++ 2017 Redistributable also changed to 14.10.25017 not 14.10.25008 which would stop the installation.I can't install an old version unless I uninstall the new version first.

Visual C++ 2017 Redistributable 14.10.25017 link in : https://www.visualstudio.com/downloads

https://download.microsoft.com/download/c/9/3/c93555e3-472e-4493-a796-73fd6721c648/vc_redist.x86.exe

https://download.microsoft.com/download/3/f/d/3fd46d4d-c486-4c8c-a874-e97ae62f3633/vc_redist.x64.exe

**Comment by myrsloik** [comment]
Fixed now
