### ISSUE TITLE
Compile error in imwri.cpp

### ISSUE THREAD

**Issue by dbermond** [vapoursynth/vapoursynth#313]
I'm getting these two types of compile error:
```
src/filters/imwri/imwri.cpp:66:66: error: ‘Rec601LumaColorspace’ is not a member of ‘Magick’
     return colorspace == Magick::GRAYColorspace || colorspace == Magick::Rec601LumaColorspace || colorspace == Magick::Rec709LumaColorspace;
                                                                  ^~~~~~
```

```
src/filters/imwri/imwri.cpp:312:46: error: ‘pixels’ was not declared in this scope
                         Magick::PixelPacket* pixels = pixelCache.get(0, y, width, 1);
                                              ^~~~~~
```

It seems to be releated to ImageMagick 7 because it buils fine with IM6.

Used steps:
```
$ ./autogen.sh
$ ./configure --prefix=/usr --enable-imwri
$ make
```

System Information:
**OS:** Arch Linux x86_64
**VapourSynth:** git master (currently at R37-53-g948ded7)
**ImageMagick:** 7.0.5.6 Q32 HDRI
**gcc:** 6.3.1
**glibc:** 2.25

Complete output is attached.

[compile-output.txt](https://github.com/vapoursynth/vapoursynth/files/999387/compile-output.txt)

**Comment by dubhater** [comment]
Does ImageMagick 7 have some feature you need? Even Arch Linux doesn't provide it yet.

**Comment by dbermond** [comment]
Thank you for the reply.

Actually, really not. :)

But I'm already using the latest IM7 for my tasks and adopted its new syntax, including the `magick` command. It's the recommended version by the upstream developers, being IM6 stated as a legacy version.

Also, I maintain ImageMagick packages in the AUR that are at version 7.

Arch Linux cannot provide it until the packages that depends on ImageMagick don't support IM7.

**Comment by myrsloik** [comment]
http://www.vapoursynth.com/2015/02/imagemagick-illustrated/

Basically it's near impossible to produce a working compile on windows. The source does not match the official binaries and lots of other issues. Even FFMS2 is a better image source for common image formats.

**Comment by myrsloik** [comment]
And because of that I never got around to converting it to IM7. Maybe I'll try it again some day. Patches welcome.

**Comment by myrsloik** [comment]
Try it now, I've converted it to the imagemagick 7 api

**Comment by dbermond** [comment]
Sorry for the delay in answering.

It's compiling fine now with IM7. Thank you!

Unfortunately it broke support for IM6 and it will affect a considerable number of users. I don't know the internals and even if it's possible, but it would be good if both apis could be included in source and chosen accordingly by the configure script at build time.

**Comment by myrsloik** [comment]
Nope, not going to maintain two codebases. Updating is for everyone!

Btw, did you test writing and reading?

**Comment by dbermond** [comment]
> Nope, not going to maintain two codebases. Updating is for everyone!
I see.

> Btw, did you test writing and reading?
`imwrif.Read` and `imwrif.Write` worked for me with these testing code:

```
#!/usr/bin/env python

# read.vpy - simple test for imwrif.Read

import vapoursynth as vs
core = vs.get_core()

video = core.imwrif.Read(filename="/path/to/png", alpha=False)
video = core.resize.Bilinear(clip=video, format=vs.YUV420P8, matrix_s="709")
video.set_output()
```

**Comment by dbermond** [comment]
> Nope, not going to maintain two codebases. Updating is for everyone!

I see.

> Btw, did you test writing and reading?

Used this simple code to test `imwrif.Read`:
```
#!/usr/bin/env python

# read.vpy - simple test for imwrif.Read

import vapoursynth as vs
core = vs.get_core()

video = core.imwrif.Read(filename="/path/to/png", alpha=False)
video = core.resize.Bilinear(clip=video, format=vs.YUV420P8, matrix_s="709")
video.set_output()
```
Sending to ffmpeg through vspipe, then using ffmpeg again for trying to get the image gives me the result of the original image. So it worked.
```
$ vspipe --y4m read.vpy - | ffmpeg -i pipe: output-read-png.mkv
$ ffmpeg -i output-read-png.mkv output-read.png
```

Used this simple code to test `imwrif.Write`:
```
#!/usr/bin/env python

# write.vpy - simple test for imwrif.Write

import vapoursynth as vs
core = vs.get_core()

video = core.imwrif.Read(filename="/path/to/png", alpha=False)
image = core.imwrif.Write(clip=video, imgformat="PNG", filename="output-write-%06d.png")
image.set_output()
```
I get the png image on disk with:
`$ vspipe write.vpy - >/dev/null`

Also tested with jpeg image and worked the same way.

**Comment by 4re** [comment]
But this is not working for me, Am I doing anything wrong? GCC is 6.3.0 [build log](https://gist.github.com/4re/38776e4b5b0e6cd3b479a41a75c39e7b)

**Comment by 4re** [comment]
And ImageMagick is 7.0.5.4, Q16, no hdri

**Comment by myrsloik** [comment]
I didn't actually try building it without hdri, will try that too.

**Comment by dubhater** [comment]
How do you make it print ``checking for Magick++ > 7... yes``? I always get ``checking for IMAGEMAGICK... yes``.

**Comment by 4re** [comment]
No idea, I don't force anything special for this to build, I see is the same for dbermond. Maybe it has something to do with the version of some package. [mine](https://gist.github.com/4re/1390520d569a621254848b761d970a86)

**Comment by dbermond** [comment]
@dubhater 
> How do you make it print checking for `Magick++ > 7... yes`? I always get `checking for IMAGEMAGICK... yes`.

After the IM7 changings commited on git master (abcc451d267462538e99dbe6b7a47646b570c5e7 and 74e610f595832a284bbf0f6509208907ff8bb6e3) I'm also getting `checking for Magick++ > 7... yes`.

Complete compile output after IM7 commits is attached (building fine).

[vs-im7-build-ok.txt](https://github.com/vapoursynth/vapoursynth/files/1012887/vs-im7-build-ok.txt)

**Comment by myrsloik** [comment]
It was hdri off that caused it. And the fact that imagemagick developers are too stupid to use c++ properly. Should be fixed now.
