### ISSUE TITLE
Improve the performance of std.Levels() filter

### ISSUE THREAD

**Issue by WolframRhodium** [vapoursynth/vapoursynth#318]
Current (VapourSynth r38) std.Levels() filter runs much slower than [std.Lut()-based](https://github.com/HomeOfVapourSynthEvolution/havsfunc/blob/master/havsfunc.py#L202) counterpart. Considering that many scripts (like BluBb-mADe's [Hysteria](https://github.com/BluBb-mADe/vapoursynth-Hysteria/blob/master/hysteria.py)) are using this filter, it would be great to improve its performance.

**Comment by WolframRhodium** [comment]
Hysteria is just an example which uses levels. In my daily scripts, levels with gamma not equal to 1 appears frequently. I hope that levels can be at least as fast as using Lut or Expr in most cases.

**Comment by myrsloik** [comment]
Implemented it as a lut for integer and made it the gamma=1.0 case faster for float, I think this should be enough optimization

**Comment by WolframRhodium** [comment]
Thanks
