### ISSUE TITLE
Add more stack operations to the Expr RPN.

### ISSUE THREAD

**Issue by stuxcrystal** [vapoursynth/vapoursynth#319]
When experimenting something about creating a SymPy-like wrapper around the Expr-RPN I noticed that some stack operations are missing from the language:

1. `rot` - This operation takes the topmost three stack items and rotates the by one: `A B C` becomes `C A B`
2. `rot4` - It does the same as `rot` but with the topmost four stack operations: `A B C D` becomes `D A B C`.

Using both operations, it will be possible to duplicate the topmost three stack items which would allow more complex operations to be implemented.

**Comment by myrsloik** [comment]
I've actually thought about adding a few extra operations but didn't get around to it. Like swap2, swap3 , swapX to swap the top value with a value X step higher in the stack. The existing swap would be equal to swap1. And something euquivalent like dupX to duplicate a value X steps up in the stack.

It has the advantage of allowing any value on the stack to be grabbed unlike your rotate suggestion. Does  this sound like an acceptable solution or do you have other ideas?

**Comment by stuxcrystal** [comment]
I do not see any problems with your solution. So yes, it is acceptable.

**Comment by myrsloik** [comment]
Implemented but not very tested (yet)
