### ISSUE TITLE
Introduce wait-state for filters

### ISSUE THREAD

**Issue by stuxcrystal** [vapoursynth/vapoursynth#324]
This is just an idea. I will not take it personally if it is rejected. Discussion on this proposal is encouraged.

# Explanation
In essence, we allow the filter to signal that it is waiting for an external event and that the core can nowuse the worker to process other frames.

# Proposed API

A simple way to implement this is via a similar method to `requestFrameFilter`. It can be called from the getFrame-function of the filter to signal that the frame will enter a wait-state after exiting the function. The core will return a pointer to a handle-object that can be used to identify which filter to wake up again. I will call this function "setFrameWaiting()". On failure, this function should return `NULL`.

Waking up a filter will require another new API-function. I will call this function `notifyFrame`. It takes a single argument; the pointer to the handle that has been returned. It will return nonzero value on failure.

After notify frame is called, the core will schedule the getFrame-call with a new ActivationReason `arNotified`.

Note that the filter may still receive frames commisioned by calls to `requestFrameFilter()`. However my proposal would forbid calling `setFrameWaiting()` while the filter is in the state "sleeping".

Should the frame be notified while a getFrame-call to the same instance is currently being executed, the core will wait for the previous getFrame call to finish before invoking it again with arFilterNotified.

## Thread Safety
`notifyFrame` need to be thread safe.

## API Additions
* `void *setFrameWaiting(VSFrameContext *frameCtx)`
* `int notifyFrame(void *handle)`
* `arNotified`

## Overview:

    core                          frame      
     |
     | = getFrame(arInitial) =======> | 
     | <===== setFrameWaiting() ===== | 
     | -------------- void *handle- > |
     |                                |
     .                                .
     .                                .
     .                                .                  external Thread
     |                                |                         |
     | <=== notifyFrame(handle) =============================== |
     | -------------------------------------------------------> |
     |                                |                         |
     | = getFrame(arFrameNotified) => |                         |
     | <- frame --------------------- |                         |
     |                                |                         |

# Use-Cases

1. Implementation of I/O-operations. I/O-operations usuall don't require CPU. Therefore the core may use the resources more efficiently if it could schedule another frame while I/O-operations are in process.
   An example implementation would look like this: The `getFrame`-method may call `setFrameWaiting` and passing the returned handle to another thread. When the operation completes this thread will call `notifyFrame` with the handle passed to the thread.
2. This model can be easily used to interoperate with other concurrency models.

**Comment by BluBb-mADe** [comment]
Are there existing filters that could profit from this feature or idea-stage filter drafts that need this to not degrade performance?
This could get easily abused to spawn additional worker threads that cause load above the specified thread count.
And how would you handle erroneous threads that never return or crash without ever calling notifyFrame?
This could potentially block everything am I wrong?
Is there any way we could do something like this but directly wrapping it around async kernel apis?
There should be no other use case anyway.

**Comment by myrsloik** [comment]
My first thought is that it seems a bit convoluted and specific. The core already implements a secret system where threads are reserved/released in the thread pool to make getFrame() calls work from everywhere. Simply exposing that would probably be a better idea. At least when something fails you'd see that there are either 0 or one gazillion worker threads available...

And on the subject of having to wait for things, may as well throw gpu filters into the design ideas since they effectively are a lot of waiting too. That's something I'd actually like to do one day.

**Comment by BluBb-mADe** [comment]
Wouldn't that still cause an potentially huge bottleneck if a bunch of worker thread from the pool are just busy waiting for io or gpu? Or do I misunderstand the purpose of this pool?

**Comment by stuxcrystal** [comment]
This is exactly the reason why I wanted to allow filters to signal this since io-operations can be impemented non-blocking or can be polled. My io-example was misleading. Of course a thread can be responsible for more than one io-operation and therefore handle more than one "sleeping" filter.

Additionally sleeping 'filters' do not the resources a blocking filter requires, namely a worker thread that could be doing other things.

About letting the core spawn additional threads. From what I've seen from other worker-based applications, this will turn out to be a mess. Also, most vapoursynth users I interact with do not know a dime about programming in general and vapoursynth-internals in particular. (Sad, I know.)

How do you expect them to react when the system crashes because VS decided it needed a gazillion workers?

**Comment by BluBb-mADe** [comment]
But that could happen regardless of how a filter might spawn/use pool io threads.
What do you think about an api that instead could handle just kernel async io calls and notify like already as proposed without filter-side thread spawning? I really have no Idea how much hassle it would be to build something like that cross-platform tho.

**Comment by stuxcrystal** [comment]
This would bind the API to io. My design would allow any use-case to be implemented. Even another worker could wake-up a filter.

My proposal is be the most general solution I could find. You are waiting for the gpu? Tell the core when you're done working. Need to interoperate with some single-threaded library? Let the filter handle this by spawing a thread dedicated to that library annd wait for it to finish processing, etc.

**Comment by HuBandiT** [comment]
> Should the frame be notified while a getFrame-call to the same instance is currently being executed, the core will wait for the previous getFrame call to finish before invoking it again with arFilterNotified.

Think about filters that able to dispatch work that can be parallelized per `arFrameReady`, as well as dispatch/wait when all frames are ready `arAllFramesReady`. Example: each frame needs to be dispatched to GPU for preprocessing individually, and when all frames completed preprocessing, the computation of the final result from the preprocessed frames needs to be dispatched to the GPU, which will need one final round of GPU/waiting as well).
