### ISSUE TITLE
Add GRAY9,10,12 and 14 as formats

### ISSUE THREAD

**Issue by blaze077** [vapoursynth/vapoursynth#327]
I was working on a plugin and came across this. It would be useful to have these as formats. 
If I'm not wrong, only adding pfGrayX to `VSPresetFormat` (in `Vapoursynth.pxd/.h`) and then calling `registerFormat` should be needed, where X is the bitdepth.

**Comment by myrsloik** [comment]
There's no real need to add individual constants for them. You can call registerformat yourself

**Comment by blaze077** [comment]
That worked. Thanks.
