### ISSUE TITLE
vspipe input error

### ISSUE THREAD

**Issue by tuanden0** [vapoursynth/vapoursynth#330]
Hi Sir,
I'm using vspipe with x264/x265 to encode my video. But there're a problem:

1. I tried to encode x265 to x264 and I got this:
http://i.imgur.com/shEr97D.png

2. I tried to encode x264 video (my test video is 3 minutes) and I got this:
http://i.imgur.com/xGYAIZ4.png

I tried using vsedit with same settings x264/x265 and they are OK??!!??
I'm using Vapoursynth r38 and here's my CLI:
x264:
"C:\Program Files (x86)\VapourSynth\core64\vspipe.exe" "%~dpn1.vpy" - | "%~dp0Tools\x264_64.exe" --level 4.1 --preset veryslow --tune animation --crf %crf% --fps %fps% --input-res %width%x%height% -o "%~dpn1.h264" -

x265:
"C:\Program Files (x86)\VapourSynth\core64\vspipe.exe" "%~dpn1.vpy" - | "%~dp0Tools\x265.exe" --level-idc 4.1 --profile main10 --preset veryslow --crf %crf% --fps %fps% --input-res %width%x%height% -o "%~dpn1.hevc" -

**Comment by myrsloik** [comment]
Exactly what's the encoded output? Why aren't you using y4m headers instead of passing everything manually?

**Comment by tuanden0** [comment]
@myrsloik:
Thanks for your reply.
The output is filename.hevc for x265 and filename.h264 for x264. But, both of them are 0 byte.
Actually, I don't know how to using y4m T.T

**Comment by myrsloik** [comment]
First try it with the simplest possible example like (with y4m):
vspipe script.vpy - --y4m | x264 --demuxer y4m -o script.mkv -

**Comment by tuanden0** [comment]
Problems still there, Sir.

**Comment by myrsloik** [comment]
What's your script?
And windows version
This is an odd problem

**Comment by tuanden0** [comment]
I'm using Windows 7 Ultimate.
Here's my script:
"test.mkv" is HEVC format.
> import vapoursynth as vs 
> import havsfunc as haf 
> core = vs.get_core() 
> clip = core.lsmas.LWLibavSource(r"E:\Download\test.mkv") 
> clip = haf.FastLineDarkenMOD(clip) 
> clip.set_output()

**Comment by myrsloik** [comment]
does "vspipe script.vpy test.raw -e 5" write a file that's not 0 bytes?

**Comment by tuanden0** [comment]
The output file is filename.raw and 0 byte, the CMD showed same error [ http://i.imgur.com/shEr97D.png ] that I posted.

Just error for input x265 and x264 less than 3 minutes [ http://i.imgur.com/xGYAIZ4.png ].

**Comment by tuanden0** [comment]
I upload a sample clip with 500 frames. Hope you can find out and errors.
Here's a sample: https://mega.nz/#!HlRy3RgA!9F_tNtFTFvH-HLYGBB4lIpU4w4MJXKRPi2QhuQ3y71c

**Comment by 4re** [comment]
I can't see any problem with that sample clip using vspipe here. The warnings you see on the console output should be harmless.

**Comment by tuanden0** [comment]
@4re :
I think you're right. I will close this issue. Maybe I'm too focus on the warning.
Thank for your help @4re @myrsloik .
