### ISSUE TITLE
Linker Tools Error LNK1181 when build r2174.

### ISSUE THREAD

**Issue by fuchanghao** [vapoursynth/vapoursynth#331]
build tools:
vaoursynth srouce r2174
zimg v2.6a
yasm r2142
visual studio 2017 v15.3
Python v3.6.2

it says "LINK : fatal error LNK1181: 无法打开输入文件“x64\Release\check.obj”" in both win32 & x64 builds when build avscompat.dll and vapoursynth.dll.

**Comment by myrsloik** [comment]
I think it's a new issues with 15.3 and how it handles custom build stuff. I haven't found a good solution yet. disabling and then enabling the vsyasm build customization seems to make it build it again. Until it stop. Again.

**Comment by myrsloik** [comment]
This has been "fixed" by switching to nasm instead. See the updated build instructions.
