### ISSUE TITLE
configure script fails with GCC 6

### ISSUE THREAD

**Issue by rnhmjoj** [vapoursynth/vapoursynth#333]
The configure script fails with this error when building vapoursynth with GCC 6:
```
configure: error: C++ compiler does not understand std::mutex (a C++11 feature).
```
Here is the complete output https://hydra.nixos.org/build/60421052/nixlog/2

**Comment by dubhater** [comment]
I never had this problem with GCC 6 in Linux. config.log may have some useful information.

**Comment by rnhmjoj** [comment]
Here we go: [config.log](https://hastebin.com/raw/xaqikiqatu)

**Comment by dubhater** [comment]
```
In file included from /nix/store/hlm2kkh1f1zbcssza8pzhsk2imd7c0h6-gcc-6.4.0/include/c++/6.4.0/ext/string_conversions.h:41:0,
                 from /nix/store/hlm2kkh1f1zbcssza8pzhsk2imd7c0h6-gcc-6.4.0/include/c++/6.4.0/bits/basic_string.h:5417,
                 from /nix/store/hlm2kkh1f1zbcssza8pzhsk2imd7c0h6-gcc-6.4.0/include/c++/6.4.0/string:52,
                 from /nix/store/hlm2kkh1f1zbcssza8pzhsk2imd7c0h6-gcc-6.4.0/include/c++/6.4.0/stdexcept:39,
                 from /nix/store/hlm2kkh1f1zbcssza8pzhsk2imd7c0h6-gcc-6.4.0/include/c++/6.4.0/array:39,
                 from /nix/store/hlm2kkh1f1zbcssza8pzhsk2imd7c0h6-gcc-6.4.0/include/c++/6.4.0/tuple:39,
                 from /nix/store/hlm2kkh1f1zbcssza8pzhsk2imd7c0h6-gcc-6.4.0/include/c++/6.4.0/mutex:38,
                 from conftest.cpp:28:
/nix/store/hlm2kkh1f1zbcssza8pzhsk2imd7c0h6-gcc-6.4.0/include/c++/6.4.0/cstdlib:75:25: fatal error: stdlib.h: No such file or directory
 #include_next <stdlib.h>
                         ^
```

That is very weird and most likely not my bug. Something is broken on your end. Have you considered using a more normal distro like Arch Linux?

**Comment by rnhmjoj** [comment]
Hahah, I used to run Arch, but I'm the maintainer of this package on NixOS and I'm supposed to sort this out before the next release.

**Comment by rnhmjoj** [comment]
I did a bit of research and found the issue has been reported [here](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=70129). I also figured that removing libc from the compile time inputs solves the error.
