### ISSUE TITLE
vspipe --arg usage?

### ISSUE THREAD

**Issue by septs** [vapoursynth/vapoursynth#337]
see http://www.vapoursynth.com/doc/vspipe.html

How to get `--arg` the information in the script.

**Comment by myrsloik** [comment]
They're set as a variable with the same name in the script (main) module.

**Comment by septs** [comment]
usage sample code

command-line:
```bash
vspipe --arg example=yes script.vpy output.raw
```
`script.vpy` file:
```python
import sys

def main():
    print(example, file=sys.stderr)

if __name__ == '__vapoursynth__':
    main()
```

see https://forum.doom9.org/showthread.php?t=173734 (solved)

**Comment by myrsloik** [comment]
clarified it slightly in the docs now
