### ISSUE TITLE
build error in Visual studio 2017.

### ISSUE THREAD

**Issue by fuchanghao** [vapoursynth/vapoursynth#340]
Visual studio 2017 15.4.2
Windows SDK 10.0.16299.0
Avisynth+ headers git:6b076d18bf58ba4f6ea943d34ab38d285db73084

error message:

> 错误	C2556	“size_t VideoFrame::GetOffset(int) const”: 重载函数与“int VideoFrame::GetOffset(int) const”只是在返回类型上不同	AvsCompat	D:\Source code\VapourSynth\vapoursynth\src\avisynth\interface.cpp	507	
> 严重性	代码	说明	项目	文件	行	禁止显示状态
> 错误	C2371	“VideoFrame::GetOffset”: 重定义；不同的基类型	AvsCompat	D:\Source code\VapourSynth\vapoursynth\src\avisynth\interface.cpp	507	
>

**Comment by myrsloik** [comment]
The problem is that you've somehow configured it so the avscompat project sees the unmodified avs+ headers. It needs to use the modified ones included in the same src dir or it will fail. Oddly enough I don't have a problem with the inclusion order with exactly the same configuration.

**Comment by fuchanghao** [comment]
I just put the files in AviSynthPlus\avs_core\include to the vapoursynth\include path.
Is that wrong?
The project files remain the same.

**Comment by myrsloik** [comment]
The modified one is included. I think the problem is that you added it to the include path for all the projects. ONLY the AVFS projects in should have them in the include path at all really.

**Comment by fuchanghao** [comment]
solved.

I make a hardlink of the AviSynthPlus in vapoursynth dic and it works fine now.
