### ISSUE TITLE
SVP Linux with mpv stopped working since 40-1~xenial update

### ISSUE THREAD

**Issue by Nekotekina** [vapoursynth/vapoursynth#342]
Hello, sorry if this is not an appropriate place for this issue.
SVP Linux says in logs "Could not initialize VapourSynth scripting". This was the update from 2017-11-20 if I'm not mistaken. Works fine with older 38-1 packages.

**Comment by patxitron** [comment]
Similar problem here. I tested it on both ubuntu 16.04 and 17.10 installing binaries from PPA, and the  `vspipe --version` command says "Failed to initialize VapourSynth environment".

**Comment by myrsloik** [comment]
That's really odd, nothing was changed in those parts between the two versions.

**Comment by patxitron** [comment]
I solved it compiling from sources and moving vapoursynth.so from /usr/lib/python3.5/dist-packages to /usr/lib/python3.5/site-packages. It seems that python3 in debian based distributions use "site-packages" directory instead of "dist-packages".

**Comment by YaLTeR** [comment]
Same issue.

**Comment by myrsloik** [comment]
@YaLTeR I'm fairly certain that problem is caused by an old cython version and unrelated to the other things

**Comment by chriskretler** [comment]
Other package updates may have come down with the vapoursynth ppa update.  Once that update happened, I can't run vsynth, either from the ppas or installing from source.

What cython version is expected/needed by vsynth?

**Comment by darealshinji** [comment]
> I solved it compiling from sources and moving vapoursynth.so from /usr/lib/python3.5/dist-packages to /usr/lib/python3.5/site-packages. It seems that python3 in debian based distributions use "site-packages" directory instead of "dist-packages".

Good catch @patxitron! I'll try to incorporate that into the packages and update the PPA.

**Comment by darealshinji** [comment]
I think I've fixed it. The problem was that I passed `-fvisibility=hidden` to the Python module's cflags. It's now build separately with `-fvisibility=default` and `vspipe --version` now doesn't show an error about environment initialization.

**Comment by dubhater** [comment]
Are you not using the provided build system? It already uses ``-fvisibility=hidden`` where possible.

**Comment by Nekotekina** [comment]
Thanks, works fine in 40-3.
