### ISSUE TITLE
Enhancement: FrameProps human understandable

### ISSUE THREAD

**Issue by Selur** [vapoursynth/vapoursynth#344]
Would be nice if either FrameProps by default or using a parameter would output more human understandable values for ChromaLocation, ColorRange, Matrix, Primaries and Transfer.

Also would be nice if the documentation would include the align-chart from avisynth:
http://avisynth.nl/index.php/File:Subtitle-align-chart.png

**Comment by myrsloik** [comment]
I already exists and is called ClipInfo.

**Comment by Selur** [comment]
Thanks. Didn't known that function. :)
