### ISSUE TITLE
enhancement: vspipe --info additional information

### ISSUE THREAD

**Issue by Selur** [vapoursynth/vapoursynth#345]
Atm. ` vspipe --info script.vpy -` outputs something like:
```
Width: 1280
Height: 480
Frames: 835
FPS: 25/1 (25.000 fps)
Format Name: YUV420P8
Color Family: YUV
Sample Type: Integer
Bits: 8
SubSampling W: 1
SubSampling H: 1
```
would be nice if there was a  way to also see color matrix etc. like shown when calling ClipInfo().

Thanks for considering.

**Comment by myrsloik** [comment]
It's a per frame property, not per clip. So no way to do it without processing the whole thing.

**Comment by Selur** [comment]
Ah, okay. Thanks for clearing that up.
