### ISSUE TITLE
LoadLibraryEx doesn't work

### ISSUE THREAD

**Issue by kice** [vapoursynth/vapoursynth#348]
https://github.com/vapoursynth/vapoursynth/blob/master/src/core/vscore.cpp#L1341

LOAD_LIBRARY_SEARCH_DEFAULT_DIRS flag require all dependency dll needs to be inside the same folder as the plguin in. However, I need to make copy for the DLLs which there are many other application share, may locating in the PATH variable. 

I wrote a plugin that require many dlls that share with other programs (total DLLs size around 1GB), but I need to copy all of them to plugin64 folder because VS ask the system not to look for PATH variable.

I don't know why choose not to search PATH. But I think we can retry using LoadLibrary (or LoadLibraryEx with PATH variable) after first attempt failed.

**Comment by myrsloik** [comment]
It's to avoid conflicts because stupid avisynth users dump everything in path. I guess LoadLibraryEx with the default search strategy as a second attempt is one way to get around it. Or simply making it possible to add extra directories to search with AddDllDirectory. I'll think about the best solution, you're the first one to even notice...
Your plugin is secret and custom, right?

**Comment by kice** [comment]
Noop, please check it if you want to.
https://github.com/kice/vs_mxDnCNN

**Comment by myrsloik** [comment]
Now you should be able to load it with LoadPlugin('your.dll', altsearchpath=True)

No autoloading but it will at least save you from copying all the things while I think about whether or not I should do more. Probably not...

**Comment by GithubZhitao** [comment]
Many thanks for the good opensource project .
I compiled the sdk/invert_example.c with dll vs2013 project. But when I try to load the dll to test , loading dll failed.  By the way I have checked the string path grammer as the doc. said and i think it won't be the problem .  Just a short code as follows : 
>from vapoursynth import core 
core.avs.LoadPlugin("d:/cppPro/vapoursynth-dpid/Debug/vapoursynth-dpid.dll")

Did the invert example depend on other dlls ? Or if you don't mind , can you show a simple example of how to use the examples in sdk folder ?

**Comment by kice** [comment]
@GithubZhitao Use this tool to check all the dependency
http://www.dependencywalker.com/

If you dont want to use altsearchpath, please make sure all the dependency locate in 
+ %windows%\system32 [**strongly ***NOT*** recommended**]
+ The directory that contains the DLL [**Recommended**]
+ The application directory

---

BTW, @myrsloik 
You may consider to add function for [AddDllDirectory](https://msdn.microsoft.com/en-us/library/windows/desktop/hh310513(v=vs.85).aspx) or read some value from register (soming like HKEY_LOCAL_MACHINE\SOFTWARE\VapourSynth\DllSearchPath) and add them to the search path.

**Comment by myrsloik** [comment]
I'd rather not manipulate the whole process dll search path. I kinda think it's ugly and a bad practice for a library to do that. You're the first person to write a plugin with "weird" dependency search.

**Comment by myrsloik** [comment]
@GithubZhitao It's core.**std**.LoadPlugin(...) The "not an avisynth plugin" error message should've been a hint.
Also create separate issues

**Comment by kice** [comment]
In fact I also think the way I propose is ugly. So I will close the issue since we have solved it.

**Comment by GithubZhitao** [comment]
Yeah @myrsloik  @kice   , it works . Thank you very much .

**Comment by kice** [comment]
@myrsloik I found that we can use import to load the dll.

But it looks like that vspipe load vapoursynth core first, then the python; it is possiable to chagne it? In that way, we might can use ctypes to load all the library we need. On the other hand, import can work as I intend to under vsedit.

You might want to check this out? 
https://github.com/kice/vs_mxnet

**Comment by myrsloik** [comment]
Use import? what does that mean?

If you mean normal dll imports you may be able to use delayed imports instead to get around your problem. It's an ugly trick but I use it in vsscript to get around a similar problem. Or at least I think it's a problem.
