### ISSUE TITLE
vspipe error

### ISSUE THREAD

**Issue by JasinChen** [vapoursynth/vapoursynth#349]
video source : TFF video
vs version : R40 x64

`import sys` 
`import vapoursynth as vs`
`import havsfunc as haf`
`import mvsfunc as mvf`
`import adjust`
`import vsTAAmbk as taa`
`import math`
`core = vs.get_core(accept_lowercase=True,threads=16)`
`core.max_cache_size = 2000`
`video = core.ffms2.source("00005.m2ts")`
`a = core.std.Trim(video, 0, 2399)`
`a = haf.QTGMC(a, Preset='very slow', TFF=True, FPSDivisor =2,opencl=True) `
`a = core.std.AssumeFPS(a, fpsnum=24000, fpsden=1001)`
`b = core.std.Trim(video, 2400, 38359)`
`b = core.vivtc.VFM(b, order=1)`
`b = core.std.SelectEvery(b, 5, [0,1,3,4])#manual IVTC`
`b = haf.daa(b,opencl=True)`
`b = core.warp.AWarpSharp2(b,thresh=128,blur=15,type=1)`
`b = haf.santiag(b,opencl=True)`
`b = haf.daa(b,opencl=True)`
`b = haf.DeHalo_alpha(b)`
`b = haf.HQDeringmod(b)`
`c = core.std.Trim(video, 38360, 40459)`
`c = haf.QTGMC(c, Preset='very slow', TFF=True, FPSDivisor =2,opencl=True) `
`c = core.std.AssumeFPS(c, fpsnum=24000, fpsden=1001)`
`d = core.std.Trim(video, 40460, 40939)`
`d = core.vivtc.VFM(d, order=1)`
`d = core.std.SelectEvery(d, 5, [0,1,3,4])`
`d = haf.daa(d,opencl=True)`
`d = core.warp.AWarpSharp2(d,thresh=128,blur=15,type=1)`
`d = haf.santiag(d,opencl=True)`
`d = haf.daa(d,opencl=True)`
`d = haf.DeHalo_alpha(d)`
`d = haf.HQDeringmod(d)`
`video = core.std.Splice([a,b,c,d])`
`video.set_output()`

Vspipe.exe usually make an error and then quit at the frame 2400 ,38360 or 40939 .The frame is random.
PS. I'm not good at English ,sorry!

This is system event log.It's Chinese...
错误应用程序名称: vspipe.exe，版本: 0.0.0.0，时间戳: 0x59d94336
错误模块名称: ucrtbase.dll，版本: 10.0.16299.125，时间戳: 0x70f70cc4
异常代码: 0xc0000409
错误偏移量: 0x000000000006b70e
错误进程 ID: 0x12fc
错误应用程序启动时间: 0x01d3795c3dc6322c
错误应用程序路径: D:\1\vspipe.exe
错误模块路径: C:\WINDOWS\System32\ucrtbase.dll
报告 ID: bd00b96b-894c-4382-886c-d890b678c2d1
错误程序包全名: ?
错误程序包相对应用程序 ID: ?

http://m.qpic.cn/psb?/748faaea-067c-4598-aee9-52c3798e2c57/IKo95pE6EXLOcHOzVTk8ZPnJBp0zq1JcRZnfdUOaEUk!/b/dPIAAAAAAAAA&bo=YAGqAAAAAAARF.s!&rf=viewer_4&t=5

**Comment by myrsloik** [comment]
What kind of error? what's the error message?

**Comment by JasinChen** [comment]
This is system event log.It's Chinese...
错误应用程序名称: vspipe.exe，版本: 0.0.0.0，时间戳: 0x59d94336
错误模块名称: ucrtbase.dll，版本: 10.0.16299.125，时间戳: 0x70f70cc4
异常代码: 0xc0000409
错误偏移量: 0x000000000006b70e
错误进程 ID: 0x12fc
错误应用程序启动时间: 0x01d3795c3dc6322c
错误应用程序路径: D:\1\vspipe.exe
错误模块路径: C:\WINDOWS\System32\ucrtbase.dll
报告 ID: bd00b96b-894c-4382-886c-d890b678c2d1
错误程序包全名: ?
错误程序包相对应用程序 ID: ?

**Comment by JasinChen** [comment]
Solved,thanks.
