### ISSUE TITLE
Can't build libfftw3f-3_x64.lib for ff3tdfilter.

### ISSUE THREAD

**Issue by fuchanghao** [vapoursynth/vapoursynth#355]
I download the 3.3.7 source code.

http://www.fftw.org/download.html

And build the sln with cmake

uncheck the BUILD_SHARED_LIBS and check the ENABLE_FLOAT.

But the output lib doesn't work for the project.

Could you tell the the right way to build the lib?

**Comment by myrsloik** [comment]
No, because I don't build it myself. I just use the pre-compiled binaries and so should probably you.

**Comment by fuchanghao** [comment]
Where to find the fftw3 libs.

the official only provides 3.3.5 windows and there are no libs in in package.

**Comment by myrsloik** [comment]
You get dlls. Use those. Static is just pointless effort...

**Comment by myrsloik** [comment]
The fftw page tells you how to create them yourself using lib.exe (I think it's called)

**Comment by fuchanghao** [comment]
thanks, problem solved.
