### ISSUE TITLE
R41 does not support display_fps anymore?

### ISSUE THREAD

**Issue by EoD** [vapoursynth/vapoursynth#356]
Has the support for ``display_fps`` been dropped? The changelog does not mention it.

When I upgrade from R40 to R41, my vapoursynth script fails with
```
[vapoursynth] Script evaluation failed:
[vapoursynth] Python exception: name 'display_fps' is not defined
[vapoursynth] 
[vapoursynth] Traceback (most recent call last):
[vapoursynth]   File "src/cython/vapoursynth.pyx", line 1841, in vapoursynth.vpy_evaluateScript (src/cython/vapoursynth.c:37135)
[vapoursynth]   File "/tmp/test.vpy", line 2, in <module>
[vapoursynth]     test = display_fps
[vapoursynth] NameError: name 'display_fps' is not defined
[vapoursynth] 
```

The variable is used also in a few primary google hits:
* https://gist.github.com/phiresky/4bfcfbbd05b3c2ed8645
* https://github.com/Argon-/mpv-config/blob/master/vs-scripts/motion-interpolation.py

**Comment by myrsloik** [comment]
Fixed in R42
