### ISSUE TITLE
help with setting up build dependencies (eg python)

### ISSUE THREAD

**Issue by hydra3333** [vapoursynth/vapoursynth#357]
In need of assistance building vapoursynth using visual studio community 2017 under win8.1, specifically in the area of knowing which build dependencies exist and how to set them up.

So far, have done per the list of things at bottom,  putting AVISYNTHPLUS and ZIMG and NASM in the right places
then downloaded and installed the latest Python 3.6.

Building the solution results in an error in VSSCRIPT like this:

```
3>vsscript.cpp
3>C:\Users\u\Desktop\Vapoursynth\vapoursynth-master\include\cython/vapoursynth_api.h(5): fatal error C1083: Cannot open include file: 'Python.h': No such file or directory
3>Done building project "VSScript.vcxproj" -- FAILED.
========== Rebuild All: 2 succeeded, 1 failed, 0 skipped ==========
```

I notice that the VSSCRIPT project properties reference 2 "include" directories which look like a composite 32/64 bit, like this:

> vsscript Properties, VC++Directories, Include Directories
> ../../include;C:\Program Files %28x86%29\Python36-32\include;$(IncludePath)
> vsscript Properties, VC++Directories, Library Directories
> C:\Program Files %28x86%29\Python36-32\libs;$(LibraryPath)
> 

What do I have to down/load/install or manually do, to have the same folder structure that the solution expects per that error message ?  I'm not sure what to download from where.

Thanks

-------------------------

> 2018.01.18
> To  integrate VSNASM with Visual Studio 2017 Community, 
> for use with Visual Studio 2017 Community,
> in building parts of Vapoursynth.
> 
> Tested in a VM under Windows 8.1
> 
> 1. Install VS2017 and every c++ bit that comes with it. Install everything.
> 2. Don't bother installing python just for this, it only gets in the way, but you'll need it later.
> 3. Download the latest VSNASM .zip from git at https://github.com/ShiftMediaProject/VSNASM and unpack it.
> 4. change properties on the top folder .\VSNASM-master to not be read-only any more
> 5. change security permissions on the top folder .\vsnasm-master so "everyone" has full control
> 6. Follow the instructions:
> 
> 6.1 The project provides a basic installer script that can automatically detect
> any installed Visual Studio 2013, 2015 or 2017 installation and then install
> the required components.
> In the newly created folder VSNASM-master to use this script simply run 'install_script.bat' from a VS2017 elevated command prompt.
> Note this didn't work for me, I did 6.2 ...
> In Windows 10
>   Open the Start menu, by pressing the Windows logo key Windows logo on your keyboard for example.
>   On the Start menu, enter dev. 
>   This will bring a list of installed apps that match your search pattern. 
>   If you're looking for a different command prompt, try entering a different search term such as prompt.
>   Choose the Developer Command Prompt (or the command prompt you want to use).
> In Windows 8.1
>   Go to the Start screen, by pressing the Windows logo key Windows logo on your keyboard for example.
>   On the Start screen, press CTRL + TAB to open the Apps list and then enter V. 
>   This will bring a list that includes all installed Visual Studio command prompts.
>   Choose the x64 vs2017 Developer Command Prompt (or the command prompt you want to use) and right click and run as admin.
> 6.2 OR ... (I did this)
> if the 'install_script.bat' does not work (it didn't for me)
> To manually install the extension you will FIRST need to download and unpack
> the required win32 or win64 NASM binary (depending on your system) 
> from the official NASM website www.nasm.us http://www.nasm.us/pub/nasm/releasebuilds 
> I did and unpacked the x64 one into an easily accessible folder.
> 
> 6.2.1 From the download archive you will need to extract nasm.exe into a location that Visual Studio can see. 
> To tell Visual Studio where to find nasm.exe you have several options:
> a) (I didn't do this)
>    Find the directory where the Visual Studio C++ compiler is installed. 
>    This can be determined from within Visual Studio by checking the contents of the VCInstallDir macro. 
>    For example the location for Visual Studio 2015 would be:
>    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC -- For a 64 bit system
>    C:\Program Files\Microsoft Visual Studio 14.0\VC -- For a 32 bit system
> OR
> b) (I did this)
>    You can install nasm to any directory 
>    and then set environment variable NASMPATH to point to the absolute directory of the installed nasm.exe 
>    (this path should include the final backslash).
>    I did this by placing the .exe in folder C:\Users\u\Desktop\Vapoursynth\VSNASM\nasm-2.13.02\ (note the trailing slash)
>    You may have to logout and login or even reboot for the new/changed variable to take effect.
> 
> 6.2.2 To use the build customisation in Visual Studio you need to 
> copy the 3 provided files (nasm.props, nasm.xml, nasm.targets) 
> into a location where they can be found by the Visual Studio build customisation processes. 
> There are several ways to do this:
> 
> a) Copy these 3 files to the MSBuild customisations directory. 
>    This can be determined from within Visual Studio by checking the contents of the VCTargetsPath macro. 
>    For example the location for various Visual Studio versions on a 64 bit system would be:
>       Visual Studio 2013: C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\BuildCustomizations
>       Visual Studio 2015: C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\BuildCustomizations
>       I copied the 3 files here: Visual Studio 2017: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\BuildCustomizations
> b) Copy these files to a convenient location and set that path in the 'Build Customisations Search Path' 
>    in the Visual Studio 'Projects and Solutions|VC++ Project Settings' item in the 'Tools|Options' menu.
> c) Copy these files to a convenient location and set this path in the 'Build Customisation dialogue (discussed later).
> 
> 
> To use NASM in a project you must enable the customisation by right clicking 
> on the project in the Solution Explorer and select 'Build Customisations..'. 
> This will give you a dialog box that allows you to select NASM as an assembler 
> (note that your assembly files need to have the extension '.asm'). 
> If you have used option 3 above, you will need to let the dialogue 
> find them using the 'Find Existing' button below the dialogue.
> 
> To assemble a file with NASM, select the Property Page for the file and 
> ensure that 'Nasm Assembler' is selected in the Tool dialog entry. 
> The additional NASM property page can then be used to change various options supported by NASM.
> 
> Now we've enabled NASM for use in compiling Vapoursynth. Hopefully.
> 
> 
> Re this
> Quote:
> Visual Studio 2015 Update 3 is also (unfortunately) required to compile the python module
> Does that mean I need to find and install vs2015 as well ? Who knows.
> 
> 
> edit 1:
> Quote:
> for other uninitiated newbies like me coming across this, for other dependencies like cython, sphinx and sphinx-intl this seemed to not crash:
> 1. install 64 bit python (3.6 in this case) as I only need 64bit stuff
> 2. start an Admin CMD dos box (or it can't copy files into protected folders) then use the pip command to install the packages, which apparently gets installed with python:
>    pip uninstall cython
>    pip --no-cache-dir install cython
>    pip uninstall sphinx-intl
>    pip --no-cache-dir install sphinx-intl
> # uninstall and thenm install, to get the latest versions
> 
> edit 2: I got this error building avscompat
> Quote:
> LINK : fatal error LNK1181: cannot open input file 'gdi32.lib'
> which is apparently a known error per http://stackoverflow.com/questions/3...file-gdi32-lib
> Quote:
> If anyone has this problem on Visual Studio 2017, it is an issue with the Windows 10 Creators Update.
> A workaround is to select the 
> "Windows 10 SDK (10.0.15063.0) for Desktop C++ x86 and x64" 
> under the "Desktop development with C++" workload in the Visual Studio Installer.
> 
> edit 3: Last comment, for newbies like me. 
> 1. For vapoursynth to build, the avs+ mt branch placed in the root of vapoursynth folder tree must be called "AviSynthPlus" 
> 2. and the zimg v2.7.1 branch placed in the root of vapoursynth folder tree must be called "zimg".

**Comment by myrsloik** [comment]
You have to install python 3.6 for both 32 and 64 bit. And it's important to select "for all users" in the installer for both or it won't be found.

**Comment by hydra3333** [comment]
Ah.  Thank you.  

Now I notice the directories in the properties change depending on which dropdown option to build x64 or win32 is chosen.  

Been 20 years ways from serious programming, young bright sparks have done my work for me in the meantime ...  ;)

**Comment by hydra3333** [comment]
It builds now, 
Kind Rregards,
