### ISSUE TITLE
Crash in Vapoursynth Editor when previewing RGB clips

### ISSUE THREAD

**Issue by RaienryuuNoNatsu** [vapoursynth/vapoursynth#364]
I'm encountering this issue with any kind of RGB clip. For starters, I'm using Vapoursynth R42.1 x64 under Windows 10 Pro x64, and Vapoursynth Editor R18 x64.

I tested a simple Blankclip, which returns a 640x480@24fps clip in RGB24, and it crashes when opening the preview. I tried the simplest thing in the world:

```
import vapoursynth as vs
from vapoursynth import core

core.std.Blankclip().set_output()
```

Before trying this, I was trying to index an UTVideo lossless recording in RGB with ffms2 at first, then tried LWLibavSource (AVISource was never an option, it always crashed for me). Both crash with any RGB clip, but if I try to open an H264 video in the YUV420P8 format, it previews it no problem. Same is true for higher bit-depth. I've started encountering this issue since, I believe, Vapoursynth R40.

**Comment by myrsloik** [comment]
Can't reproduce it

**Comment by RaienryuuNoNatsu** [comment]
I'm using a workaround at the moment, or rather, I'm simply doing the
conversion to YV12 and preview it directly instead. I'll give it another
try once this encoding is done. Any chance that this may be related to
UTVideo RGB VCM Codec (fourCC ULRG)? Or even an Editor side bug?

2018-01-29 20:41 GMT+01:00 Fredrik Mellbin <notifications@github.com>:
