### ISSUE TITLE
Build Error - vapoursynth

### ISSUE THREAD

**Issue by Verifirs** [vapoursynth/vapoursynth#365]
I installed latest zimg, no error. To verify I used it to compress an image. Next I ./autogen.sh in vapoursynth, it goes fine. After that I do ./configure --prefix=/usr gives following error:

checking for ZIMG... no
configure: error: Package requirements (zimg) were not met:

Package 'zimg', required by 'virtual:world', not found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables ZIMG_CFLAGS
and ZIMG_LIBS to avoid the need to call pkg-config.

However, zimg is installed correctly. Thoughts?

**Comment by dubhater** [comment]
I think you might have this zimg: https://github.com/buaazp/zimg
You need this one: https://github.com/sekrit-twc/zimg

They're completely unrelated projects, with unrelated functionality.

**Comment by Verifirs** [comment]
You are 100% correct. This solved my problem, thanks.

**Comment by Verifirs** [comment]
Unfortunately, I am experiencing another error when attempting to make.
>/bin/sed: can't read Vapour/vapoursynth/libvapoursynth.la: No such file or directory
>libtool:   error: 'Vapour/vapoursynth/libvapoursynth.la' is not a valid libtool archive

Already tried cloning to home directory as specified [here
](https://github.com/vapoursynth/vapoursynth/issues/269) - error still occurs. Have tried to reconfigure by doing make disclean, autoreconf, automake, and then ./configure but the error still occurs.

**Comment by dubhater** [comment]
You're supposed to run autogen.sh then configure.

**Comment by Verifirs** [comment]
Yes, I did that as well I just forgot to add it in the list of commands I used. The problem still persists.

**Comment by Verifirs** [comment]
Great news, I just solved it. I am 95% sure the problem arose from the working directory path having a space in it. I am going to verify this now.
