### ISSUE TITLE
Is it possible to know which VSAPI version is returned by vsscript_getVSApi()?

### ISSUE THREAD

**Issue by YaLTeR** [vapoursynth/vapoursynth#366]
Maybe I'm missing something? `vsscript_getApiVersion()` returns the VSScript API version, not the VS API version.

**Comment by myrsloik** [comment]
I think the answer to your question is no... that's a bit of an oversight. I'll add vsscript_getVSApi2(int version) that takes the required api version as an argument too.

**Comment by myrsloik** [comment]
Will be fixed in R43
