### ISSUE TITLE
Threading issue in VSScript

### ISSUE THREAD

**Issue by YaLTeR** [vapoursynth/vapoursynth#367]
Example program:
```cpp
#include <iostream>
#include <thread>
#include <vector>

#include <vapoursynth/VSScript.h>

using namespace std;

int main() {
	vsscript_init();

	vector<thread> threads;

	for (int i = 0; i < 16; ++i) {
		threads.emplace_back([]() {
			VSScript* handle = nullptr;
			vsscript_evaluateScript(&handle,
			                        "from vapoursynth import core\n"
			                        "core.std.BlankClip().set_output()",
			                        nullptr,
			                        0);

			vsscript_freeScript(handle);
		});
	}

	for (auto&& thread : threads)
		thread.join();

	vsscript_finalize();
}
```
Compile with `g++ -lvapoursynth-script -lpthread main.cpp`.

Sometimes it prints out `Core freed but 1 filter instance(s) still exist` suggesting that multiple `VSScript*` handles got the same core, which shouldn't be happening AFAICT.

EDIT: vapoursynth R42.1

**Comment by myrsloik** [comment]
Hmm... technically I never made sure vsscript* function are threadsafe but this definitely shouldn't happen. Odd.

**Comment by YaLTeR** [comment]
Which functions in the API (both VapourSynth and VSScript) are threadsafe by design, as in you are _supposed_ to be able to call them from multiple threads at the same time without issues?

**Comment by myrsloik** [comment]
All the ones in vapoursynth.h are safe. Most in vsscript.h aren't. Or more exactly were never tested properly...

**Comment by myrsloik** [comment]
Can you try running your example under valgrind and see if it really leaks vapoursynth allocations? It may be a result of something like python freeing things in a slightly different order and not necessarily a real issue.

**Comment by YaLTeR** [comment]
Not sure what I'm supposed to be looking at, but valgrind shows 0 bytes were definitely and indirectly lost.

**Comment by YaLTeR** [comment]
Also it is a real issue when creating different `VSScript*`s from separate threads because in other program I was getting failures, presumably due to one thread continuing working with its output node while another thread has already freed its own `VSScript*` (which incorrectly also freed the first thread's `VSScript*`'s core). Those failures were fixed when I changed calls to `vsscript_createScript()`, `vsscript_evaluateScript()` to be behind a mutex.

**Comment by myrsloik** [comment]
I've added a mutex around all vsscript functions just to make it less confusing. Now your test program is happy. But I'll save it and try to figure out why it happens, the python GIL should've prevented some of it...
