### ISSUE TITLE
Vapoursynth Editor crashes after fresh Windows installation

### ISSUE THREAD

**Issue by RaienryuuNoNatsu** [vapoursynth/vapoursynth#369]
So, I went ahead and reinstalled Windows 10 (Pro 64bit, Fall Creators Update). Installed Python 3.6.4 and Vapoursynth, both 64bit. It returns no errors in the code because of missing filters/scripts so that's fine. Problem is when I need to open the preview. It's a similar case to my previous issue, but now even YUV colorspaces don't work, meaning there's something deeper I need to check. Unfortunately, I'm not an expert, so even going through the Visual Studio debugger, I can't figure it out on my own.

So, by checking the Event Viewer, the faulting module is vapoursynth.dll. Running VSEdit through Visual Studio, I found the following:

`00007FF84DFD417B  div         eax,dword ptr [map+64h (07FF84E0AC324h)]`

Its faulting offset is 0x00000000000a417b, and the exception code is 0xc0000094 (Integer division by zero). Now, with my capabilities, this is all I can find out. I hope this holds enough infos to figure out the issue, because I have no idea what to do next.

**Comment by myrsloik** [comment]
Post a screenshot of the stack, that's a lot more helpful. Note that you have the vapoursynth pdb file available in the vapoursynth install dir so you can load that to get proper symbols and better results.

**Comment by RaienryuuNoNatsu** [comment]
Here they come. Sorry if it took me a while, but I downloaded it in
Italian, stupidly. So I wa sdownloading the English pack.



​

2018-02-06 20:52 GMT+01:00 Fredrik Mellbin <notifications@github.com>:

**Comment by RaienryuuNoNatsu** [comment]
Ah, I have this too if it can help:





​

2018-02-06 21:16 GMT+01:00 Lilith Elessar <re.giorgio.corona@gmail.com>:

**Comment by myrsloik** [comment]
Nothing is attached. You probably need to use the github website to reply....

**Comment by RaienryuuNoNatsu** [comment]
[screens.zip](https://github.com/vapoursynth/vapoursynth/files/1700797/screens.zip)
Here they are, sorry about that.

**Comment by myrsloik** [comment]
What's your CPU model?

**Comment by RaienryuuNoNatsu** [comment]
It's an Intel Core 2 Quad Q9550.

2018-02-06 22:19 GMT+01:00 Fredrik Mellbin <notifications@github.com>:

**Comment by sekrit-twc** [comment]
@RaienryuuNoNatsu You can compile the [linked ](https://pastebin.com/yeKW4yN4) program in Visual Studio and post the output in a reply. It seems the cache size detection logic is not working correctly on your older processor.

**Comment by RaienryuuNoNatsu** [comment]
It returns me this error:

Microsoft (R) C/C++ Optimizing Compiler versione 19.12.25835 per x86
> Copyright (C) Microsoft Corporation. Tutti i diritti  sono riservati.
>
> yeKW4yN4.c
> yeKW4yN4.c(1): fatal error C1083: Impossible to open the file inclusion
> (this was in Italian, I translated it myself): 'stdio.h': No such file or
> directory
>

2018-02-07 17:32 GMT+01:00 sekrit-twc <notifications@github.com>:

**Comment by sekrit-twc** [comment]
Did you use the Visual Studio Developer Command Prompt (in start menu)?

**Comment by RaienryuuNoNatsu** [comment]
I'm probably missing a few components. I'm totally new to Visual Studio,
and I installed it without add-ons, I didn't select anything. Even because
I was planning to just send the report. I'm now installing "Desktop
development with C++", this should have all I need. When it's done, I'll
compile it for you and send the output.

2018-02-07 18:42 GMT+01:00 sekrit-twc <notifications@github.com>:

**Comment by RaienryuuNoNatsu** [comment]
So, I got new error codes, but that's beyond what I can handle. So the
error codes are:

yeKW4yN4.c
yeKW4yN4.c(164): error C2065: 'cahce': 'identifier' : undeclared identifier
(that 'cahce' is suspicious, but I'm not gonna touch anything)
yeKW4yN4.c(164): error C2224: the element to left of '->identifier' (in
this case '.l3' ) must point to struct/union
yeKW4yN4.c(163): warning C4473: 'printf': not enough arguments passed for
format string
yeKW4yN4.c(163): note: with the assignments and related parameters are
expected 6 variadic arguments, but only 5 have been specified
yeKW4yN4.c(163): note: the mssing variadic argument 6 is required by the
format string '%lu'

I had to translate the last 2 lines by myself. Should I change the OS
language for this to come out in English, even though I installed the
English language pack for Visual Studio?

2018-02-07 18:47 GMT+01:00 Lilith Elessar <re.giorgio.corona@gmail.com>:

**Comment by sekrit-twc** [comment]
See my previous post. There is a typo in the paste.

> EDIT: Also, there is a typo in the pastebin. Change "cahce" to "cache" on line 164.

**Comment by RaienryuuNoNatsu** [comment]
All right, here's the result. An exe and an obj.
[yeKW4yN4.zip](https://github.com/vapoursynth/vapoursynth/files/1704368/yeKW4yN4.zip)

**Comment by sekrit-twc** [comment]
Err, the objective was for you to run the program on your machine. I can of course run it on my machine, which has a different CPU.

**Comment by RaienryuuNoNatsu** [comment]
>
> You can compile the linked <https://pastebin.com/yeKW4yN4> program in
> Visual Studio and post the output in a reply.
>

​I assumed you wanted to see the result. :o And where's that supposed to go
though? 'Cause I'm not exactly an expert here. >.>​


2018-02-07 20:59 GMT+01:00 sekrit-twc <notifications@github.com>:

**Comment by sekrit-twc** [comment]
Yes, you need to post the output of the *program*. So that we can determine what needs to be changed to make VapourSynth not crash on your computer.

1. Compile program.
2. Run program from command prompt.
3. Copy program output from command prompt.
4. Paste output into this issue.

**Comment by RaienryuuNoNatsu** [comment]
>
> max feature #: 13
> GENUINEINTEL
> L1 cache, type 1
> 1 threads, 32768 bytes, non-inclusive
> L1 cache, type 2
> L2 cache, type 3
> 2 threads, 6291456 bytes, non-inclusive
> L0 cache, type 0
> APIC level 0
> final hierarchy: L1 32768 / 1, L2: 6291456 / 2, L3: 0 / 0
> effective cache size: 3145728
>

​This is what I get by launching the exe.​


2018-02-07 22:09 GMT+01:00 sekrit-twc <notifications@github.com>:

**Comment by sekrit-twc** [comment]
The issue has been identified and will be fixed in a future release.

**Comment by RaienryuuNoNatsu** [comment]
Thank you very much, I'll be waiting for the update. And sorry for the
hiccups along the way.

2018-02-07 23:27 GMT+01:00 sekrit-twc <notifications@github.com>:

**Comment by myrsloik** [comment]
https://forum.doom9.org/showthread.php?p=1833196#post1833196 <- have a build

**Comment by RaienryuuNoNatsu** [comment]
Thank you very much. I've just installed it and tried. The crash is now
fixed, and on top of that, it fixed the crash with RGB clips I mentioned in
the previous issue.

2018-02-08 11:48 GMT+01:00 Fredrik Mellbin <notifications@github.com>:
