### ISSUE TITLE
Data race in VSCore-related functions

### ISSUE THREAD

**Issue by YaLTeR** [vapoursynth/vapoursynth#370]
It seems to me that `api->setMaxCacheSize()` and `api->setThreadCount()` can race with `api->getCoreInfo()` as no lock is acquired for these operations.

**Comment by myrsloik** [comment]
It can but it should be harmless. Those numbers can't really be used for anything useful anyway. See the api defects issue...

**Comment by myrsloik** [comment]
Fixed by adding getCoreInfo2 and adding some extra locks
