### ISSUE TITLE
A way to clean up message handlers

### ISSUE THREAD

**Issue by YaLTeR** [vapoursynth/vapoursynth#371]
I'm allocating some data for `api->setMessageHandler()` and passing the pointer as `userData` so my handler can access it, however if something else subsequently sets another message handler this `userData` will be lost. Perhaps it's possible to add an alternative `setMessageHandler()` which additionally accepts a deleter function? The deleter function would get called with `userData` once a message handler is overriden to clean up `userData`.

**Comment by myrsloik** [comment]
I know, it's a bit iffy. It's kinda on the todo list as well.

**Comment by myrsloik** [comment]
Fixed for R47
