### ISSUE TITLE
Errors of vspipe

### ISSUE THREAD

**Issue by toyokrw** [vapoursynth/vapoursynth#373]
I install vapoursynth from https://forum.doom9.org/showthread.php?t=173453.
And Errors of vspipe happens in using KNLMeansCL
Source is from https://xiph-media.net/video/derf/y4m/bridge_far_cif.y4m
OS: Mac 10.12.6
GPU: Intel HD Graphics 630 and Radeon Pro 555

I posted this issues in the git of KNLMeansCL because I dont know a cause.
 ```
import vapoursynth as vs
core = vs.get_core()
clip=core.ffms2.Source(source='bridge_far_cif.y4m')
clip=core.knlm.KNLMeansCL(clip,channels="YUV",device_type="gpu",device_id=0)
clip.set_output()

vspipe "Untitled.vpy" /dev/null --y4m 
vspipe(4441,0x70000f97d000) malloc: *** error for object 0x7fc52d8ad200: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```

 ```
import vapoursynth as vs
core = vs.get_core()
clip=core.ffms2.Source(source='bridge_far_cif.y4m')
clip=core.knlm.KNLMeansCL(clip,channels="YUV",device_type="gpu",device_id=1)
clip.set_output()

vspipe "Untitled.vpy" /dev/null --y4m 
Segmentation fault: 11
```

 ```
import vapoursynth as vs
core = vs.get_core()
clip=core.ffms2.Source(source='bridge_far_cif.y4m')
clip=core.knlm.KNLMeansCL(clip,channels="UV",device_type="gpu",device_id=1)
clip.set_output()

vspipe "Untitled.vpy" /dev/null --y4m 
Segmentation fault: 11
```

**Comment by myrsloik** [comment]
*** set a breakpoint in malloc_error_break to debug <- try following that advice in gdb and you should get a dump, can't help you much more since it's extremely likely it's a knlmeanscl issue and not the core.

**Comment by toyokrw** [comment]
I don't have binaries before stripped.
But, thank you.
I'll send your comment to knlmeanscl.
