### ISSUE TITLE
Adding Wine support on *nix platforms

### ISSUE THREAD

**Issue by swordfeng** [vapoursynth/vapoursynth#378]
Hi, there! I am currently working on a fork which allows VapourSynth to load Windows .DLL plugins with the aid of Wine.
Here is my repo: https://github.com/swordfeng/vapoursynth
Now it seems to work well with AvsCompat (with TIVTC loaded) and VSFilterMod. I think it is a promising solution for those hard-to-port plugins. (I have not tested it thoroughly, though...)
Only the core and the vspipe (and some headers) are modified and compiled with winegcc/wineg++. Other parts are untouched.
However, I get a small problem... I am not able to handle makefiles well. Currently I use a seperated CMake file to compile the two binaries and replace the original ones. I hope to set up an option "_build with Wine"_, and when it is selected, the core and vspipe are built with winegcc/wineg++.
Any suggestions? Is it possible to get merged into the main branch? Thanks!

**Comment by dubhater** [comment]
Wow, interesting. Did you already know how to use Wine like this, or did you learn just for this project?

How does all this work? Why do you need to compile the core and vspipe with a special compiler?

There may be a (partial?) solution in [this answer](https://stackoverflow.com/a/25977757), if you must compile everything with the existing build system.

**Comment by swordfeng** [comment]
@dubhater 
This is my first time to create wined libraries, so I am not completely sure if I have done it right.

Wine needs to load the DLLs into the process's memory and resolve DLLs' dynamic linking. As a result, the real executable is going to be the Wine loader. It loads vspipe as a shared library, and goes to its main function later. That's why I have to compile vspipe with winegcc.

And winegcc also handles Windows functions, such as LoadLibraryEx, in the compiling and linking stage. As the core loads the DLLs with LoadLibraryEx, it has to be compiled using winegcc.

I made some check in the core to prevent it from loading DLLs when Wine is not loaded. So it can work in a python interpreter without DLL support.

The largest problem when loading DLL plugins is the difference between Windows and *nix calling conventions. It is hard to make MSVC support SysV ABI so I decide to handle the difference in the VapourSynth's side.
Fortunately almost all the functions for plugins are inside the VSAPI struct. Therefore I copied a VSAPIWINE struct containing MS ABI functions, and pass it to DLL plugins.

And there are callback functions. Since it is not easy to wrap these callback functions in corresponding SysV ABI functions, I did a little trick. As functions are normally aligned, the least significant bit is 0. I mark the bit to 1 if the function is MS ABI, and check the bit before calling these functions.

**Comment by myrsloik** [comment]
I don't understand why you modified so much in the core. This definitely feels like it should be a separate plugin much like the avisynth compatibility.

**Comment by swordfeng** [comment]
@myrsloik 
I haven't thinked of it. It seems that a plugin can only have one namespace, which means all the DLL plugins will have their functions in the same namespace with the loader plugin, and make it incompatible with existing scripts.
I'll try to make it a separate plugin if this is solved.

**Comment by swordfeng** [comment]
I have some ideas but I am not going to start it in the near future. Close the issue for now.
