### ISSUE TITLE
VapourSynth cannot be installed in non-admin environments

### ISSUE THREAD

**Issue by stuxcrystal** [vapoursynth/vapoursynth#379]
While I understand the requirements of VapourSynth to be installed with admin-rights, Python itself does not require administrative rights to be installed.

In my case, I have a separate Administrative Account and have installed Python on a per-user basis.

This has the following result:
1. The installer asks for an admin account via UAC.
2. The installer is now running under said admin account.
3. The code for detecting python installations then tries to find an installation under the admin-context ultimately failing to find one.
4. Refusing installation citing a missing Python installation.

Please remove the Python requirement of the installer as you can install VapourSynth after the fact using pip.

**Comment by myrsloik** [comment]
Are you sure about this? I'm fairly certain a per user installation of python will be found. Guess I'll have to try it...

**Comment by stuxcrystal** [comment]
Per-User installations _are_ found. Just not per-user installations running unter different accounts, However running the installer on a non-privileged user will cause the UAC to ask for an admin-user and after typing in its credential will run the installer with under the admin-user.

**Comment by stuxcrystal** [comment]
Well, is there actually a reason why you don't try to load the VapourSynth settings from HKCU first on windows and try HKLM as a fallback at https://github.com/vapoursynth/vapoursynth/tree/master/src/vsscript/vsscript.cpp#L73 and https://github.com/vapoursynth/vapoursynth/blob/master/src/core/vscore.cpp#L76

This would make Vapoursynth installable on a per-user basis.

**Comment by myrsloik** [comment]
It's now implemented (but not yet fully tested) using inno setup 6.
