### ISSUE TITLE
createFunc documentation is wrong

### ISSUE THREAD

**Issue by YaLTeR** [vapoursynth/vapoursynth#381]
In the docs `createFunc()` has only three arguments but it actually has five (with `core` and `vsapi` being additionally required)?

Reading the source, apparently these are the arguments passed to the function _instead_ of the ones provided at `callFunc()`?

**Comment by myrsloik** [comment]
I've updated it now. It's a leftover to preserve the ABI.

**Comment by YaLTeR** [comment]
It seems to me that it'd be better to pass them from `callFunc()`, am I mistaken or should I add a comment into the defect list issue?

**Comment by myrsloik** [comment]
No, a function always belongs to a core for various reasons. Anything else becomes very iffy and complicated. Passing the vsapi pointer several time a potential source of bugs since there's no way to tell which major api version is required when calling a function object.
