### ISSUE TITLE
Make vsscript dlopen() vapoursynth and the python code

### ISSUE THREAD

**Issue by wm4** [vapoursynth/vapoursynth#386]
Currently, using vsscript exports a bunch of API functions. If you link to them, you'll also have a hard dependency on Python. This becomes hard to distribute (for example you can't just tell users to download vapoursynth DLLs separately, and your build setup has to handle both). You could dlopen() it, but it's kind of a bother.

I propose that vsscript should be a thin wrapper that transparently dlopen()s the actual vs/python libs.

Alternatively, vsscript could use the same concept as VSAPI, and expose only 1 API function, that returns a struct with the actual API as function pointers.

In both cases, the user binary's dependencies would be minimal.

If this requires API changes or a new API, this change could also do the following things on top of it:
- hide vsscript_init/finalize from the user (is there any reason not to?)
- include a mechanism to support other scripting backends

**Comment by dubhater** [comment]
Doesn't seem like a hard dependency on Python?
```
 0x0000000000000001 (NEEDED)             Shared library: [libQt5Widgets.so.5]
 0x0000000000000001 (NEEDED)             Shared library: [libQt5Gui.so.5]
 0x0000000000000001 (NEEDED)             Shared library: [libQt5Core.so.5]
 0x0000000000000001 (NEEDED)             Shared library: [libvapoursynth-script.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libvapoursynth.so]
 0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
```
And I cross-compile the Windows version without having any part of Python for Windows installed.

**Comment by dubhater** [comment]
Is it a legal thing? Because I have been distributing certain Windows executables without Python and no one complained about any malfunctions.

**Comment by wm4** [comment]
No, just build effort and package size. I'm mostly thinking about mpv windows packages, which don't have VS I think. Also mpv has a really dumb Lua VS backend for this reason.

**Comment by wm4** [comment]
Also I wonder if it'd maybe be better to write a separate loader of some sort that builds upon vsscript. Any opinions?

**Comment by myrsloik** [comment]
I'll make the change some day. Maybe soon if it's very rainy.

**Comment by myrsloik** [comment]
Do the current changes in the doodle1 branch fix the python dependency bit?

**Comment by wm4** [comment]
From what I can tell, the VSScript4.h API would. Looking at this, it's not immediately clear which DLL to load from where.

**Comment by myrsloik** [comment]
VSScript.dll
The path can be gotten from HKCU/HKLM\SOFTWARE\VapourSynth\VSScriptDLL

**Comment by myrsloik** [comment]
Fixed in vsscript4 I think
