### ISSUE TITLE
COMPATBGR32 returns packed XRGB instead of BGRX

### ISSUE THREAD

**Issue by stuxcrystal** [vapoursynth/vapoursynth#394]
# What happens
I got an error report for my Yuuno IPython-extension that on Mac OSX the image has incorrect colors.
After some debugging I noticed that the frame is packed in the wrong order.

# Environment
Python 3.6
Mac OS X (10.13.4)
VapourSynth R34 installed via Homebrew

# How to reproduce
```py
b = core.std.BlankClip(color=[0,1,2], format=vs.RGB24, width=1, height=1)
r = b.resize.Point(format=vs.COMPATBGR32)
f = r.get_frame(0)
bytes(f.get_read_array(0))
```
Output on Windows: `b'\x02\x01\x00\xff'`
Output on Mac OS X (10.13.4): `b'\xff\x00\x01\x02'`

**Comment by kageru** [comment]
For the sake of completeness, output on Arch Linux with R43:
`b'\x02\x01\x00\xff'`

**Comment by dubhater** [comment]
This was fixed recently. You can apply https://github.com/vapoursynth/vapoursynth/commit/222e15261b5bfd1f06d0289a9412b7d65398df93 if you don't want to wait until R44.

(R34? Did you mean R43?)

**Comment by stuxcrystal** [comment]
My mistake: R43
