### ISSUE TITLE
Getting "Failed to load vapoursynth script library! Please set up the library search paths in settings." in VSEdit

### ISSUE THREAD

**Issue by Ota-Coder** [vapoursynth/vapoursynth#398]
I'm getting error every time I open VSEdit:

```
Failed to load vapoursynth script library!
Please set up the library search paths in settings.
```

![screenshot_2018-06-22_07-45-07](https://user-images.githubusercontent.com/10753056/41750762-349cb650-75f0-11e8-9965-d93fe5ca73b6.png)

I installed using the PPA - https://launchpad.net/~djcj/+archive/ubuntu/vapoursynth. I'm on Linux Mint 18.3 64bit Xfce.

Any way to solve this issue?

Edit: Just found out the PPA's inofficial. Will either find support elsewhere or compile from source. Thank you.

**Comment by theChaosCoder** [comment]
> Please set up the library search paths in settings.
Did you set the lib path?

**Comment by Ota-Coder** [comment]
I tried to set it as "/usr/lib/x86_64-linux-gnu/vapoursynth" but the error still shows even after I restarted the application.

**Comment by chriskretler** [comment]
I had to create the following symbolic link to get the editor to load on ubuntu:
$ sudo ln -s /usr/lib/x86_64-linux-gnu/libvapoursynth-script.so.0.0.0 /usr/lib/x86_64-linux-gnu/libvapoursynth-script.so

**Comment by Ota-Coder** [comment]
@chriskretler - thanks! I think that worked! Will now study encoding using VapourSynth. Thanks again! :D

**Comment by Youka** [comment]
> I had to create the following symbolic link to get the editor to load on ubuntu:
> $ sudo ln -s /usr/lib/x86_64-linux-gnu/libvapoursynth-script.so.0.0.0 /usr/lib/x86_64-linux-gnu/libvapoursynth-script.so

This issue was closed but the problem not solved. Still have to create the symbolic link on Ubuntu. Is a fix planned for next release?

**Comment by dubhater** [comment]
If that symlink doesn't exist in the package you installed, I would say it's a bug in the packaging process. I have that symlink here in Arch Linux, and no one had to create it. ``make install`` did it without prompting.
