### ISSUE TITLE
vapoursynth it only works from the linux terminal

### ISSUE THREAD

**Issue by linuxdakota** [vapoursynth/vapoursynth#410]
I have installed SVP to play my videos at 60 fps, and I have compiled mpv with vapoursynth support,
vapoursynth and vapoursynth plugins from the source code,
my OS is Debian 9 stretch

Why when I open a video from the file browser with mpv, do you show me this error ?:

[vapoursynth] Could not initialize VapourSynth scripting.
[user_filter_wrapper] Creating filter 'vapoursynth' failed.

and when I open a video from the linux terminal
with the command: mpv test.mp4
everything works fine without any error

I've added the environment variables to my bashrc file
![captura de pantalla de 2018-08-01 14-38-23](https://user-images.githubusercontent.com/7764641/43548696-34dee718-95a4-11e8-8993-17cb3ef359b1.png)

I do not know what the error is

**Comment by dubhater** [comment]
I'm guessing your graphical environment isn't started through bash, so your bashrc isn't used until you open a terminal. You're probably using some login manager like gdm/kdm/sddm/etc.

If you use KDE, this page tells you how to set environment variables: https://userbase.kde.org/Session_Environment_Variables

**Comment by linuxdakota** [comment]
My login manager is gdm, my desktop environment is gnome shell...
