### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [vapoursynth/vapoursynth#411]
I would like to point out that an identifier like “[`_PickVictim`](https://github.com/vapoursynth/vapoursynth/blob/f65402b242b1eac05de1e485306ea1466d54541e/src/filters/avisource/FastReadStream.h#L45 "Update candidate")” [does not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by myrsloik** [comment]
I'd rather not diverge from the source vdub codebase unless compiler errors happen. So in this case no. Only needs to compile in visual studio.

**Comment by myrsloik** [comment]
[Like this](https://www.allposters.ca/-sp/Ostrich-with-Head-in-Sand-posters_i12466535_.htm)
