### ISSUE TITLE
why cant installer support both python 3.6 and 3.7?

### ISSUE THREAD

**Issue by NewUserHa** [vapoursynth/vapoursynth#414]
I have python3.6-32 and python3.7-64 for some reasons.
can't just vapoursynth use whatever version python3.x.dll it found?

**Comment by myrsloik** [comment]
You simply unpack both portable python and portable vapoursynth to the same directory. Done. Just run the vs and python binaries from there and everything works.
No pip install required.

**Comment by NewUserHa** [comment]
is there a way to use python in a different location?
can the way be documented?
thanks

**Comment by stuxcrystal** [comment]
You can just do `pip install vapoursynth` for now. I maintain and compile the python package for both python 3.6 and python 3.7

**Comment by NewUserHa** [comment]
what about the files in core32/64 folders?
how do they link to the files installed by `pip`?

**Comment by stuxcrystal** [comment]
The `vapoursynth`-PyPI Package uses the system vapoursynth installation. In this regard, it behaves like a normal VapourSynth installation using the installer.
