### ISSUE TITLE
AVFS: Can not get the right path

### ISSUE THREAD

**Issue by emako** [vapoursynth/vapoursynth#415]
CLI: avfs -d "F:\file!{0}.vpy"

The generated file is "C:\Volumes\file0.vpy\file!{0}.avi" instead of "C:\Volumes\file!{0}.vpy\file!{0}.avi".
In this way, I can not get the right path.
Why did the generated path lack some symbols, such as exclamation marks or braces?
Thank you!

**Comment by myrsloik** [comment]
I never thought about this. Doesn't look like the AVFS code does the stripping either. I'll see if I can at least find an explanation for you...

**Comment by emako** [comment]
Thanks for you help. @myrsloik 
I am writting a program that can play vs script auto mounted by AVFS,
so I eager to know all the rules of AVFS's generated path.

**Comment by myrsloik** [comment]
This is how it is: the pismo mount stuff always strips these characters because reasons. It can't be disabled. I'm going to make AVFS return the mount point on success instead so you know what to open that way.

**Comment by myrsloik** [comment]
Will be resolved in the next release by AVFS printing the chosen mount path (and then you just have to parse it to figure out where to look)
