### ISSUE TITLE
[Feature] What about Julia for scripting in VapourSynth

### ISSUE THREAD

**Issue by mantielero** [vapoursynth/vapoursynth#416]
Probably this is a very stupid idea, because I am not a developer and for sure I'm missing plenty of details here. Even more when I am a happy Python user.

Anyway, here I go: what about the possibility of including Julia as an scripting language for VapourSynth.

I have been playing just one week with Julia, which makes this suggestion even more crazy.

The reasons that make me thing this could be interesting are:
1. The language is quite expressive. Probably closer to avs than to python.
2. It is very fast. Not in micro-benchmark wars. In task that last hours or days.
3. It support parallelism both in terms of multicore or cluster sense.

I think this language could cover the gap between those who implement filters as DLL in c/c++/asm and those who deal with scripting (avs/python). Julia probably could serve them both. (And yes, I know that the argument of using another language in order to cope with the problem of having several languages is pretty bad).

I recommend reading [this](http://www.stochasticlifestyle.com/modular-algorithms-scientific-computing-julia/).

And congratulations for your effort.

**Comment by stuxcrystal** [comment]
You can imaging VapourSynth as having two parts (that in this case matter):
1. VapourSynth core: It is the actual frame server plugins attach themselves to.
2. The vapoursynth module which is essentially a wrapper around the VapourSynth Core API.

You actually just need to write a wrapper in julia to do this.

I dont recommend actually doing this as this would fragment the vapoursynth community making it harder to share code between users.

**Comment by mantielero** [comment]
Thanks for your quick response. I'd love to try it anyway, even just for the sake of learning.

I am looking at *vapoursynth.pyx* and *vapoursynth.pyd*. They look like chinesse to me :( I am also having a look at [luasynth](https://github.com/tgoyne/luasynth). A bit less cryptic, but also cryptic.

I'd like to start easy. Any suggestion about what could I do?

The first issue that I am finding is that I am not sure if I am calling to the right library. would it be *VapourSynth.dll* in windows and *libvapoursynth.so* in Linux?

I would like to call an easy function. I was thinking on *getVapourSynthAPI*. Do you think this is appropriate?

I was thinking  on something like:
```julia
julia> ccall((":getVapourSynthAPI","./VapourSynth.dll"),Ptr{Any},(Int,),3)
ERROR: ccall: could not find function :getVapourSynthAPI in library ./VapourSynth.dll
Stacktrace:
 [1] top-level scope at .\none:0
```

Any guidance is more than welcome.

**Comment by dubhater** [comment]
Is this a 32 bit VapourSynth DLL? If it is, you need to specify the calling convention, which is stdcall for all VapourSynth API functions.

**Comment by mantielero** [comment]
It is 64bit. Now on Linux:
```julia
julia> m = ccall((:getVapourSynthAPI,"vapoursynth/.libs/libvapoursynth.so"), stdcall,Ptr{Any}, (Int,),3)
Ptr{Any} @0x00007f4fe81a7780
```
Is for 64bit *stdcall* also?

**Comment by mantielero** [comment]
In the process of playing with julia and vapoursynth, I am in the process of calling plugin functions from julia. I have the followging question: 

There are optional parameters for functions within plugins. What are the default parameters for those functions? In julia optional parameters need to be given beforehand, so I cannot automatically create all the functions defined in plugins. What is being done in python in that regard?

**Comment by myrsloik** [comment]
There's no way to query the defaults. If julia allows more complex types introduce an "empty argument" type and use as the default or something to get around it. That way you always have a default.

Python allows everything everywhere, you simply get a list and a dict of unnamed and named arguments respectively and then you can solve things yourself.

**Comment by mantielero** [comment]
Sounds like an interesting approach. I'll give it a try. Thanks

**Comment by mantielero** [comment]
I have made some progress. The latest problem that I am facing is using some functions, for example, I want to try [Turn180](http://www.vapoursynth.com/doc/functions/turn180.html?highlight=std#std.Turn180).
What I am doing is:
1. First I create a *VSMap* with *createMap*. This works.
2. Then I try to assign a *VSNodeRef*. I do this with *propSetNode*. But I get a return value of 1, which means "trying to append to a property with the wrong type". Does this refer to the node value?

Regards,
Jose Maria

**Comment by myrsloik** [comment]
Paste the exact code. It means that you already have a different type assigned to that key. You can simply set it with paReplace and it'll work.

**Comment by mantielero** [comment]
I have all the code [here](https://github.com/mantielero/VapourSynth.jl). But it is really ugly.
The code in Julia could be:
```julia
julia> using VapourSynth
julia> using VapourSynth.Ffms2
julia> using VapourSynth.Std
julia> clip = source("video.mkv")
julia> println(clip.ptr)
Ptr{VapourSynth.VSNodeRef} @0x000056416f617610
julia> vsmap = VapourSynth.createMap()
julia> ccall( VapourSynth.vsapi.propSetNode, Cint, (Ptr{VapourSynth.VSMap}, String, Ptr{VapourSynth.VSNodeRef}, Cint), 
       vsmap, "clip", clip.ptr, Int64(1) )
1
```

**Comment by mantielero** [comment]
I answered myself. I had to use *Cstring* instead of *String*.

**Comment by mantielero** [comment]
I am showing my progress [here](https://github.com/mantielero/VapourSynth.jl). Right now, thanks to functions chaining, the scripting looks like this:
```julia
using VapourSynth
using VapourSynth.Ffms2
using VapourSynth.Std: turn180, flipHorizontal
using Lazy
@> source( "test.mkv" ) turn180 flipHorizontal pipey4m
```
so it can be executed like:
```
$ julia example.jl | mplayer -
```
Thanks for your help.

Now I will try to make a filter directly in Julia.

**Comment by mantielero** [comment]
I am trying to use the *splice* function. How should I put the array of *VSNodeRef* into a *VSMap*?

**Comment by myrsloik** [comment]
Add each node in the array with paAppend

**Comment by mantielero** [comment]
It worked. Thanks.
