### ISSUE TITLE
AVFS for AviSynth: Doesn't support non-ASCII filename

### ISSUE THREAD

**Issue by mrhso** [vapoursynth/vapoursynth#418]
Environment: AVFS (for AviSynth 32-bit) in VapourSynth R44
If filename of AviSynth Script contains non-ASCII character, AVFS doesn't work correctly.
AVFS (or VSFS, for VapourSynth 64-bit) has no problem.

**Comment by myrsloik** [comment]
I'll fix it for Avs+. It's unfixable for plain avs.

**Comment by mrhso** [comment]
It does not work correctly.
Import: unable to locate "我谔谔.avs" (try specifying a path), error=0x2

**Comment by myrsloik** [comment]
Fixed in R45 (confirmed)
