### ISSUE TITLE
[R45] You forgot to update your setup.py again.

### ISSUE THREAD

**Issue by stuxcrystal** [vapoursynth/vapoursynth#420]
PS: You can find fixed versions of the setup.py here

* `vapoursynth/setup.py`
  https://files.pythonhosted.org/packages/13/6a/990c6544e6fca02a917a045f8387bda500937dc7cdf2582b580499db3a4f/VapourSynth-45.tar.gz

* `vapoursynth/installer/setup.py`
  https://files.pythonhosted.org/packages/f7/70/0f863e6612b2e7ee9ebce54d95a66ac1f3d558c8c281a3071f90a8336e21/VapourSynth-portable-45.tar.gz

**Comment by myrsloik** [comment]
Fixed it and make a R45.1 release
