### ISSUE TITLE
vspipe don't change CWD

### ISSUE THREAD

**Issue by q3cpma** [vapoursynth/vapoursynth#421]
Hello,

I have the habitude of using vspipe with `--arg INFILE=myfile.mkv` to avoid hardcoding the source file, but I've noticed that vspipe changes the CWD to the dirname of the script, preventing me from using relative paths when the script isn't in the same directory as `myfile.mkv`. If my rant is too long, here's a script(1) showing what the "problem" is:
```
> cat script.vpy
from sys import stderr
from os import getcwd

print(getcwd(), file=stderr)
> vspipe script.vpy - >/dev/null
/home/q3cpma
Failed to retrieve output node. Invalid index specified?
> cd Data
> vspipe ../script.vpy - >/dev/null
/home/q3cpma
Failed to retrieve output node. Invalid index specified?
>
```

**Comment by myrsloik** [comment]
This is well documented behavior. Simply use full paths. The shell may be able to help you with the expansion.

**Comment by stuxcrystal** [comment]
Let's put aside the fact that this is documented behaviour.
Why is it that way actually?

**Comment by myrsloik** [comment]
So relative paths inside scripts will work as expected. Ironically that breaks your other relative paths.

**Comment by myrsloik** [comment]
I've added a --preserve-cwd option to vspipe now. That should keep everyone happy.
