### ISSUE TITLE
VFM micmatching behavior is confusing

### ISSUE THREAD

**Issue by mgroshans** [vapoursynth/vapoursynth#425]
The documentation for VFM `mode=3` outlines its behavior as:

>2-way match + 3rd match on combed + 4th/5th matches if still combed (p/c + n + u/b)

and there are of course several thresholds one can configure to determine what VFM considers combed. Helpfully VFM also adds the `_Combed` frame property, which also has clear documentation.

>1 if VFM thinks the frame is combed, 0 if not.

So I was very confused when I saw `mode=3` change matches where the typical 2-way had yielded frames marked with `_Combed: 0`.

It seems as though there are actually some separate (and non-configurable) heuristics which can result in matching changes.
https://github.com/vapoursynth/vapoursynth/blob/0cc450efc4767145feed5bb2f8c507b16d71d8f0/src/filters/vivtc/vivtc.c#L595-L597

In my case I have several frames with mics like, `VFMMics: 31 216 256 217 0`. Because `0 * 3 < 31 && abs(31 - 0) > 30` the match is changed from 0 to 4 (regardless of `MI` configuration).

Personally I'd rather not have the extra heuristic for micmatching at all. But if the extra heuristic is desirable for some reason (maybe TFM compatibility) I think the mode documentation should probably be a little more clear that there are metrics beyond what appears in `_Combed` that determine which matches could be used.

**Comment by theChaosCoder** [comment]
Is this why on some problematic sources there are still combed frames left even with cthresh=0 and mi=0?

**Comment by mgroshans** [comment]
For what it's worth I worked around this with something like this...
```python
def mic_match_combed_only(n, f, mic_match, no_mic_match):
    return mic_match if f.props['_Combed'] == 1 else no_mic_match

no_mic_match = clip.vivtc.VFM(order=0, micmatch=0)
mic_match = clip.vivtc.VFM(order=0, micmatch=2, mode=3)
output = no_mic_match.std.FrameEval(functools.partial(mic_match_combed_only, mic_match=mic_match, no_mic_match=no_mic_match), prop_src=no_mic_match)
```
basically only using the micmatch'd output if the standard match was `_Combed`. It's not exactly the behavior from the documentation (would need a `mode=1` step in-between) but for my particular source it's all I need. Perhaps an option to get this kind of behavior less verbosely is another path forward. `strict_mic_matching=True` or `use_tfm_mic_heuristics=False` something along those lines?

**Comment by myrsloik** [comment]
Clarified in the docs now at least
