### ISSUE TITLE
Make fails with "recipe for target 'src/core/asm/x86/check.lo' failed"

### ISSUE THREAD

**Issue by VasyaTheWizard** [vapoursynth/vapoursynth#429]
Trying to compile Vapoursynth on Debian, getting the following error:
```
nasm: error: invalid warning `Worphan-labels'
nasm: error: invalid warning `unrecognized-char'
type `nasm -h' for help
Makefile:2016: recipe for target 'src/core/asm/x86/check.lo' failed
```

**Comment by dubhater** [comment]
Your nasm could be too old. What version is it?

**Comment by VasyaTheWizard** [comment]
```
# nasm -v
NASM version 2.12.01
```

**Comment by dubhater** [comment]
Yes, that's too old. You need 2.13.

But what happens if you just remove those parameters from the Makefile?

**Comment by VasyaTheWizard** [comment]
How do I update it? Apt tells me I already have the newest version.

**Comment by DJATOM** [comment]
You can build it from source. Probably that's the easiest solution on the stable systems. You can also use development versions of Debian, there must be never nasm version.

**Comment by VasyaTheWizard** [comment]
Got past that error, but I'm getting a new one now:
```
  CYTHON   src/cython/vapoursynth.c

Error compiling Cython file:
------------------------------------------------------------
...
        # If we are not using VSScript, do nothing.
        if self.single:
            return
        _environment_state.current = _env_current_stack().pop()

    def __eq__(self, other):
   ^
------------------------------------------------------------

src/cython/vapoursynth.pyx:133:4: Special method __eq__ must be implemented via __richcmp__
Makefile:2019: recipe for target 'src/cython/vapoursynth.c' failed
make: *** [src/cython/vapoursynth.c] Error 1

```

```
# cython3 -V
Cython version 0.25.2
```

**Comment by DJATOM** [comment]
https://github.com/vapoursynth/vapoursynth/issues/407#issuecomment-406808459

You also need a newer cython version.

**Comment by VasyaTheWizard** [comment]
I installed it with `pip install Cython`, the issue you referenced mentions something about updating a symlink that was pointing to the old version - where is this symlink, and how do I update it?
