### ISSUE TITLE
Better detailed error messages?

### ISSUE THREAD

**Issue by gundamftw** [vapoursynth/vapoursynth#430]
It would be better to have the error message displaying the detail of the options in the filter arguments instead of just showing the option number. For example, when I do this `clip = core.vivtc.VFM(clip, order=5)`, instead of it giving me an error saying that `only 0-1 was allowed` for the `order` argument, I would also like it to display what 0 and 1 means so I don't have to dig up the documentation every time for everything.

**Comment by theChaosCoder** [comment]
So you mean instead of `VFM: Invalid order specified; only 0-1 allowed` something like `VFM: Invalid order specified; only 0 (bottom field first) -  1 (top field first) allowed`

**Comment by myrsloik** [comment]
Error messages are not a substitute for the documentation. It could work for arguments with only 2 options, sure, but look at the number of options (and interactions) other arguments have.

**Comment by gundamftw** [comment]
> So you mean instead of `VFM: Invalid order specified; only 0-1 allowed` something like `VFM: Invalid order specified; only 0 (bottom field first) - 1 (top field first) allowed`

Yes

> Error messages are not a substitute for the documentation. It could work for arguments with only 2 options, sure, but look at the number of options (and interactions) other arguments have.

There weren't out there beside removegrain.
