### ISSUE TITLE
osx Python exception: No attribute with the name sub exists.

### ISSUE THREAD

**Issue by 786259135** [vapoursynth/vapoursynth#432]
> ```import vapoursynth as vs
> core = vs.get_core()
> core.max_cache_size = 4000
> 
> video = core.lsmas.LWLibavSource(source=r'/Users/passer/Documents/SHJS_20190321_172516_008.ts')
> video = core.sub.TextFile(video, file=r'/Users/passer/Documents/11111.ass')
> 
> video.set_output()
> ```

> ```
> 2019-03-22 14:16:58.546
> Failed to evaluate the script:
> Python exception: No attribute with the name sub exists. Did you mistype a plugin namespace?
> 
> Traceback (most recent call last):
> File "src/cython/vapoursynth.pyx", line 1927, in vapoursynth.vpy_evaluateScript
> File "src/cython/vapoursynth.pyx", line 1928, in vapoursynth.vpy_evaluateScript
> File "/Users/passer/Documents/testvpy.vpy", line 6, in 
> #src = core.vsfm.TextSubMod(src, file=r"C:/Users/Administrator/Desktop/110.ass")
> File "src/cython/vapoursynth.pyx", line 1522, in vapoursynth.Core.__getattr__
> AttributeError: No attribute with the name sub exists. Did you mistype a plugin namespace?
> ```

> mac version 10.14.3 (18D109)

> brew install vapoursynth l-smash ffmpeg libass

**Comment by dubhater** [comment]
The [VapourSynth formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/vapoursynth.rb) needs to depend on ffmpeg too, otherwise the Subtext plugin won't be built.

It's a good idea to explicitly enable all the plugins you want, because then configure will fail with an error message if a required library isn't found, instead of silently skipping that plugin.

**Comment by 786259135** [comment]
> The [VapourSynth formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/vapoursynth.rb) needs to depend on ffmpeg too, otherwise the Subtext plugin won't be built.
> 
> It's a good idea to explicitly enable all the plugins you want, because then configure will fail with an error message if a required library isn't found, instead of silently skipping that plugin.

I installed ffmprg via brew

brew install ffmpeg

**Comment by dubhater** [comment]
I think what you need to do is install ffmpeg (already done) and then reinstall VapourSynth and make sure Homebrew compiles it from source instead of downloading a binary package. A search suggests that ``brew install --build-from-source vapoursynth`` will do this.

**Comment by 786259135** [comment]
> I think what you need to do is install ffmpeg (already done) and then reinstall VapourSynth and make sure Homebrew compiles it from source instead of downloading a binary package. A search suggests that `brew install --build-from-source vapoursynth` will do this.

Strangely enough, it still doesn't work properly.

![image](https://user-images.githubusercontent.com/16495257/54860603-8166c400-4d57-11e9-85f9-5cef60ad5c49.png)

**Comment by dubhater** [comment]
In that case, you need to find the config.log created by configure and attach it here. It should contain clues about why the Subtext plugin wasn't compiled.

**Comment by 786259135** [comment]
> In that case, you need to find the config.log created by configure and attach it here. It should contain clues about why the Subtext plugin wasn't compiled.

I tried to manually compile the source code, prompting the lack of cython. After executing: pip3 install --upgrade cython, the compilation passed successfully.

After manually compiling the source code, I tried to execute: brew install --build-from-source vapoursynth, and found that the sub plugin is still not compiled. The following is the log:
[config.log](https://github.com/vapoursynth/vapoursynth/files/2999968/config.log)

**Comment by 786259135** [comment]
![image](https://user-images.githubusercontent.com/16495257/54873985-59419880-4e1d-11e9-8073-53d1bba8fad6.png)

**Comment by dubhater** [comment]
It's not finding the ffmpeg libraries (lines 773-805). But since you can compile it manually, I assume Homebrew is modifying the pkg-config search path.

I guess you could make your own copy of the VapourSynth formula and add ffmpeg to the dependencies.
