### ISSUE TITLE
SDK in portable edition

### ISSUE THREAD

**Issue by Youka** [vapoursynth/vapoursynth#434]
For plugin development i need to link with Vapoursynth SDK.
I can't run the installer of Vapoursynth in a **Windows CI environment**, so i'm forced to use the portable edition of (Python and) Vapoursynth but there's no SDK provided.
It would be nice to get the **MSVC-based libraries** in other ways too.

**Comment by myrsloik** [comment]
Sure, I'll include those files too. I didn't think anyone would actually need them for portable stuff.

**Comment by YaLTeR** [comment]
FWIW I was able to get the installer working in a CI: https://github.com/YaLTeR/vapoursynth-rs/blob/master/appveyor.yml#L62-L63

**Comment by myrsloik** [comment]
Implemented
