### ISSUE TITLE
Featurerequest: sys.exit(code) does not work as intended in VSPipe

### ISSUE THREAD

**Issue by stuxcrystal** [vapoursynth/vapoursynth#437]
`sys.exit(code)` does not work as intended as it is essentially an alias for `raise SystemExit(code)`-Exception. All exceptions are being caught in vspipe and cause the exitcode 1 to be returned by vspipe instead of the exitcode provided by `sys.exit`.

While in other vsscript-applications catching SystemExit might be intended behaviour, vspipe only executes a single script and should therefore not replace an exitcode provided by the user.

Suggested change:
- Catch SystemExit in VSPipe and return the exitcode provided by its `code`-Attribute.

See: https://docs.python.org/3/library/exceptions.html#SystemExit

**Comment by myrsloik** [comment]
I guess it makes sense. Patches welcome and so on. Or wait a long time for me to get around to it.

**Comment by myrsloik** [comment]
Could you spend some time implementing this? It'd be a big help since there are a lot of other issues for me to deal with as well.

**Comment by myrsloik** [comment]
Implemented in doodle1 branch
