### ISSUE TITLE
How to build with clang in windows?

### ISSUE THREAD

**Issue by fuchanghao** [vapoursynth/vapoursynth#439]
Tools:
LLVM/Clang 8.0.0
Visual Studio 2019 16.0.1 / Visual studio 2017 15.9.11
Python 3.7.2
NASM 2.14.02

Install Clang Power Tools & LLVM Compiler Toolchain

https://marketplace.visualstudio.com/items?itemName=caphyon.ClangPowerTools
https://marketplace.visualstudio.com/items?itemName=LLVMExtensions.llvm-toolchain

It can't build anything, Full of errors.

for example zimg.

> 1>..\..\src\zimg\depth\x86\f16c_ivb.cpp(24): error : use of undeclared identifier '_mm256_cvtph_ps'; did you mean '_mm256_cvtpd_ps'?
> 1>C:\Program Files\LLVM\lib\clang\8.0.0\include\avxintrin.h(2170): note: '_mm256_cvtpd_ps' declared here
> 1>..\..\src\zimg\depth\x86\f16c_ivb.cpp(24): error : cannot initialize a parameter of type '__m256d' (vector of 4 'double' values) with an rvalue of type '__m128i' (vector of 2 'long long' values)
> 1>C:\Program Files\LLVM\lib\clang\8.0.0\include\avxintrin.h(2170): note: passing argument to parameter '__a' here
> 1>..\..\src\zimg\depth\x86\f16c_ivb.cpp(29): error : use of undeclared identifier '_mm256_cvtph_ps'; did you mean '_mm256_cvtpd_ps'?
> 1>C:\Program Files\LLVM\lib\clang\8.0.0\include\avxintrin.h(2170): note: '_mm256_cvtpd_ps' declared here
> 1>..\..\src\zimg\depth\x86\f16c_ivb.cpp(29): error : cannot initialize a parameter of type '__m256d' (vector of 4 'double' values) with an rvalue of type '__m128i' (vector of 2 'long long' values)
> 1>C:\Program Files\LLVM\lib\clang\8.0.0\include\avxintrin.h(2170): note: passing argument to parameter '__a' here
> 1>..\..\src\zimg\depth\x86\f16c_ivb.cpp(34): error : use of undeclared identifier '_mm256_cvtph_ps'; did you mean '_mm256_cvtpd_ps'?
> 1>C:\Program Files\LLVM\lib\clang\8.0.0\include\avxintrin.h(2170): note: '_mm256_cvtpd_ps' declared here
> 1>..\..\src\zimg\depth\x86\f16c_ivb.cpp(34): error : cannot initialize a parameter of type '__m256d' (vector of 4 'double' values) with an rvalue of type '__m128i' (vector of 2 'long long' values)
> 1>C:\Program Files\LLVM\lib\clang\8.0.0\include\avxintrin.h(2170): note: passing argument to parameter '__a' here
> 1>..\..\src\zimg\depth\x86\f16c_ivb.cpp(48): error : use of undeclared identifier '_mm256_cvtps_ph'
> 1>..\..\src\zimg\depth\x86\f16c_ivb.cpp(53): error : use of undeclared identifier '_mm256_cvtps_ph'
> 1>..\..\src\zimg\depth\x86\f16c_ivb.cpp(58): error : use of undeclared identifier '_mm256_cvtps_ph'
>

**Comment by pinterf** [comment]
Is it the first time trying to compile zimg with LLVM toolset? (me never have tried)

**Comment by fuchanghao** [comment]
> 
> 
> Is it the first time trying to compile zimg with LLVM toolset? (me never have tried)

Yes, it's the first time.

PS: LLVM does not support using Windows SDK 10.0 for latest Windows 10 SDK. Must write as 10.0.17763.0.

**Comment by myrsloik** [comment]
Some simple things: don't use that stuff. Just use the official llvm installer from llvm.org. It will add the appropriate options to visual studio (at least 2017, didn't try 2019 yet).
Zimg has never worked with clang-cl inside visual studio due to some instruction extension quirk. I have no reason to doubt it's changed. The rest of vapoursynth can be compiled with clang-cl apart from avfs. I did experiment with clang-cl compiles but they always seemed to miscompile something. Things could have improved the past few years though so have fun experimenting.

**Comment by fuchanghao** [comment]
> 
> 
> Some simple things: don't use that stuff. Just use the official llvm installer from llvm.org. It will add the appropriate options to visual studio (at least 2017, didn't try 2019 yet).
> Zimg has never worked with clang-cl inside visual studio due to some instruction extension quirk. I have no reason to doubt it's changed. The rest of vapoursynth can be compiled with clang-cl apart from avfs. I did experiment with clang-cl compiles but they always seemed to miscompile something. Things could have improved the past few years though so have fun experimenting.

For me only VS 2019 add the appropriate options. VS 2017 can't add LLVM without LLVM Compiler Toolchain.
