### ISSUE TITLE
Integrate the windows install with the existing python package management.

### ISSUE THREAD

**Issue by stuxcrystal** [vapoursynth/vapoursynth#440]
The way vapoursynth is installed currently makes it hard to detect as it tells nobody that it's there.
A usecase would be support in IDEs (as shown in the image attached, [it's in an early development phase]).

And I would really hate to find some special way to detect if that damn vapoursynth-module is actually installed and which version is installed.

There are two ways:
1. Create a dist-info directory as described in [PEP376](https://www.python.org/dev/peps/pep-0376/) Please omit the preceding "R" from your version number as afaik, it is not supported by python.
2. Do `python setup.py bdist_wheel` for both 64bit and 32bit versions and install them using `[python-binary] -m pip install [path-to-.whl]` Uninstall using `[path-to-python-binary] -m pip uninstall VapourSynth` (note that pip would automatically uninstall the old version for you)

![image](https://user-images.githubusercontent.com/2260352/56015652-0e1ef500-5cfa-11e9-95ba-2550ca421f2a.png)

**Comment by myrsloik** [comment]
I actually tried #2 but couldn't get it to succeed. For some reason this happens (after I've made sure the buildp32 and buildp64) are still around. Any hints?

`c:\VapourSynth\installer>setup.py bdist_wheel
No local packages or working download links found for vapoursynth==46
Traceback (most recent call last):
  File "C:\VapourSynth\installer\setup.py", line 89, in <module>
    for p in os.listdir(os.path.join(plugin_dir, 'plugins'))
  File "C:\Program Files\Python37\lib\site-packages\setuptools\__init__.py", line 144, in setup
    _install_setup_requires(attrs)
  File "C:\Program Files\Python37\lib\site-packages\setuptools\__init__.py", line 139, in _install_setup_requires
    dist.fetch_build_eggs(dist.setup_requires)
  File "C:\Program Files\Python37\lib\site-packages\setuptools\dist.py", line 717, in fetch_build_eggs
    replace_conflicting=True,
  File "C:\Program Files\Python37\lib\site-packages\pkg_resources\__init__.py", line 782, in resolve
    replace_conflicting=replace_conflicting
  File "C:\Program Files\Python37\lib\site-packages\pkg_resources\__init__.py", line 1065, in best_match
    return self.obtain(req, installer)
  File "C:\Program Files\Python37\lib\site-packages\pkg_resources\__init__.py", line 1077, in obtain
    return installer(requirement)
  File "C:\Program Files\Python37\lib\site-packages\setuptools\dist.py", line 784, in fetch_build_egg
    return cmd.easy_install(req)
  File "C:\Program Files\Python37\lib\site-packages\setuptools\command\easy_install.py", line 673, in easy_install
    raise DistutilsError(msg)
distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('vapoursynth==46')

c:\VapourSynth\installer>`

**Comment by stuxcrystal** [comment]
Use the setup.py of the root directory instead. It will _only_ include the vapoursynth module.
The other setup.py will include the portable version.

**Comment by myrsloik** [comment]
One final question. What would the sane thing to do on uninstall? Uninstall the VapourSynth package as well?

**Comment by stuxcrystal** [comment]
My personal opionion would be to just uninstall the package

**However**, I did a poll in an [non-existent](https://github.com/vapoursynth/vapoursynth/pull/392#issuecomment-388190461) discord and got the following result:

1. If possible, ask the user if he wants to uninstall the package. If it is not possible, just uninstall it.
2. Default to uninstalling the package.
3. Explain to the user what a python-package is.

**Comment by myrsloik** [comment]
It is indeed a python package now
