### ISSUE TITLE
Ubuntu PPA removed

### ISSUE THREAD

**Issue by http403** [vapoursynth/vapoursynth#443]
The PPA listed in [official webpage](http://www.vapoursynth.com/doc/installation.html#linux-installation-from-packages) is gone. Any alternative PPA to use?

**Comment by dubhater** [comment]
I don't know of any others.

**Comment by Jukiro** [comment]
Yeah, I've been installing it directly from source and I have encountered many errors..

**Comment by GillesJ** [comment]
+1

**Comment by Ota-Coder** [comment]
There's [this PPA](https://launchpad.net/~djcj/+archive/ubuntu/hybrid) from the same maintainer... though I'm now facing [the same problem I had back in Linux Mint 18.3](https://github.com/vapoursynth/vapoursynth/issues/398) now that I'm Linux Mint 19. Hmm...

**Comment by myrsloik** [comment]
Updated the link

**Comment by chriskretler** [comment]
Myrosloik: The website (http://www.vapoursynth.com/doc/installation.html#linux-installation-from-packages)

still points here: https://launchpad.net/~djcj/+archive/ubuntu/vapoursynth
instead of here: https://launchpad.net/~djcj/+archive/ubuntu/hybrid

Was this the link you were updating?

**Comment by myrsloik** [comment]
I only update the documentation when there's a new release so you'll have to wait

**Comment by aaronfranke** [comment]
The link on this page is still broken: http://www.vapoursynth.com/doc/installation.html

**Comment by myrsloik** [comment]
READ! kthxbye

**Comment by Youka** [comment]
* [`djcj/hybrid`](https://launchpad.net/~djcj/+archive/ubuntu/hybrid) is empty with message **PPA DISCONTINUED!**.
* [Homepage](http://www.vapoursynth.com/doc/installation.html#linux-installation-from-packages) points to djcj [related packages](https://launchpad.net/~djcj/+ppa-packages) with deleted PPAs in list.
* PPA [`vapoursynth/git-ppa`](https://launchpad.net/~vapoursynth/+archive/ubuntu/git-ppa) seems not to support **xenial/ubuntu16** which is required for [Travis-CI](https://docs.travis-ci.com/user/reference/overview/#linux).

**Comment by denismn** [comment]
Why did you remove old versions from PPA Ubuntu 16.04? In 2018, I installed Vapoursynth 44 from there. Everything was there: vapoursynth, ffms2, d2v, vsedit. Everything worked. Now there is nothing. It is not builded from source code - an error appears. The new PPA doesn't have packages for Ubuntu 16.04. Packages for 18.04 are broken: there is a dependency on ffms2, but it is not built. Why didn't you save in the web archive at least?

The developer is hateful. Examples:
http://www.vapoursynth.com/2018/01/imwri-making-it-suck-less/
http://www.vapoursynth.com/2016/10/ffms-2-23-trigger-warning/
