### ISSUE TITLE
Allow for actual sequential filters

### ISSUE THREAD

**Issue by Bellaktris** [vapoursynth/vapoursynth#445]
Recently, I am using VapourSynth for my video processing pipelines a lot. Quite often I do not care about random frame access (so it is basically video in -> video out) while on the other hand I often need sequential processing (usually at the end of the graph and lightweight) to ensure temporal coherency. 

Currently to get this behavior I am using get_frame_async from python, but it feels a bit hacky, and, anyway, it only works as long as I need sequential processing at the very end of the graph. 

Thus, I would like to be able to write real sequential plugins (one thread at a time, but also frames guaranteed to be processed sequentially with an exception otherwise). 

I am pretty sure this will be useful for other people doing complex video to video processing too. Would you be interested in accepting such a change if I write pull request?

**Comment by DJATOM** [comment]
nfMakeLinear flag?

**Comment by Bellaktris** [comment]
Not sure if it will guarantee sequential processing. I will do some experiments.

**Comment by theChaosCoder** [comment]
Would get_frame(n) not guarantee a sequential processing?

**Comment by Bellaktris** [comment]
This is about how I do it right now, except that I use get_frame_async and some simple prefetching. But I just think it would be nice to have my sequential logic as an actual VapourSynth filter, so that I can have proper multithreading and ability to add other filters after.

**Comment by myrsloik** [comment]
There's no guarantee things will be sequential. There also can be no guarantee with the API design of VS or Avisynth for that matter either. Everything else is a lie. The nfMakeLinear flag simply makes a minimal effort to reduce the required seeking for source filters that benefit from this.
I still don't quite understand what your script looks like and why. Give me a proper and useful example and maybe I'll have some ideas.

**Comment by Bellaktris** [comment]
I know that there is no guarantee right now, this is why I asked if you will be interested to support it. 

I have the following use case. I have a video that I want to convert to different aspect ratio with dynamically moving crop window. I start by choosing the best crop position framewise. Than for every scene I need to ensure that cropping window moves without unpleasant jumps and jittering, and here I need to process video sequentially (and I do not care about random frame access). At the end I do framewise cropping and optionally stacking and annotating with subtitles (for visualization purposes). I attached some pseudocode below (the original script is large):

    def async_frames(clip, buf_sz=48):
        """Multithreaded generator analogous to vapoursynth's .frames()"""
        N = clip.num_frames
        buf = [None] * min(buf_sz, N)

        for i in range(0, len(buf)):
            buf[i] = clip.get_frame_async(i)

        for i in range(len(buf), N):
            yield buf[i % len(buf)].result()
            j = i % len(buf)

            buf[j] = clip.get_frame_async(i)

        for i in range(N, N + len(buf)):
            yield buf[i % len(buf)].result()

    video_yuv = core.ffms2.Source(INPUT_VIDEO_NAME)
    super_clip = core.mv.Super(video_yuv, **SUPER_KWARGS)
    mv_vecs = core.mv.Analyse(super_clip, **ANALYSE_KWARGS)
    video_yuv = core.mv.SCDetection(video_yuv, vecs, **SCDETECTION_KWARGS)
    video_yuv = core.custom_plugins.RawCropPositions(video_yuv, **RAW_CROP_POSITIONS_KWARGS)
    video_rgb = core.resize.Bilinear(video_yuv, matrix_in_s='709', format=vs.RGB24)   

    def smooth_crop_windows(clip):
          for frame in async_frames(clip):
              ....
              yield frame, (left_crop_position, right_crop_position)
              ....

    for i, (frame, (p1, p2)) in enumerate(smooth_crop_windows(video_rgb)):
         R = np.asarray(frame.get_read_array(0))[:, p1:p2]
         G = np.asarray(frame.get_read_array(0))[:, p1:p2]
         B = np.asarray(frame.get_read_array(0))[:, p1:p2]
         RGB = cv2.merge([R, G, B])
         cv2.imwrite(OUTPUT_PATH + "%d.png" % i, RGB)

**Comment by myrsloik** [comment]
This is the kind of use case where I'd simply turn it into a 2-pass operation. You want to split the whole clip into scenes and then based on a metric calculated form every contained frame determine the best value, right?
For some reason I think you may be better served by writing a proper filter since it should at least be able to do this awkward exercise a bit faster.

**Comment by Bellaktris** [comment]
The proper filter should process video sequentially (or have a huge memory cache), this is why I asked if there is interest in actual sequential filters in API. I think that use-cases like mine are quite common.

**Comment by Bellaktris** [comment]
smooth_crop_windows in the example above aggregates information from frames in chronological order, so I either need sequential access, or I need to query huge and only-known-at-runtime number of frames for every getframe call or I need a huge shared map. I think last two options aren't a good way to do it.

**Comment by sekrit-twc** [comment]
Often times "sequential" problems are not such.

> I have the following use case. I have a video that I want to convert to different aspect ratio with dynamically moving crop window. I start by choosing the best crop position framewise. Than for every scene I need to ensure that cropping window moves without unpleasant jumps and jittering.

It sounds like you really have this graph (AVS notation):

    m0 = IsSceneCut(clip) # add to separate metadata clip
    m1 = ChooseFrameCrop(clip) # add to separate metadata clip
    m2 = CropWindowSmoothing(m0, m1) # filters on metadata
    clip = ApplyCrop(clip, m2)

This graph can be buffered for the maximum reasonable window over which to smooth (O(100s of frames)), which is only gigabytes in size.

**Comment by Bellaktris** [comment]
This is surely an option, and it is probably even better than what I have right now, but my whole point is that I want to have an official way within VapourSynth to do it (and I am willing to spend some time implementing it). In terms of your suggestion it means: 
* Having native support for metadata clips (without 1x1 frames with useless data). Well, I can actually store metadata in the frame pixels (like mvtools does), but still why not to support it properly?
* Having native support for buffering and sequential processing. Yes, current caching mechanism might be a base for writing this. But the main problem will be the same we don't have any guarantees right now which frames will be cached (though, in practice I guess they are kind of sequential).

and I honestly think that my use-case is quite often once you do relatively complex video processing and do not care about random frame access. 

Anyway thank you for the idea I probably will use it next time working with VapourSynth.

**Comment by sekrit-twc** [comment]
The graph decomposition I provided is stateless, so it does have a guarantee of correctness. What is not guaranteed is cache residency and performance, but this is already the case for other graphs.

**Comment by Bellaktris** [comment]
Sure, your solution is correct, but performance also matters. I think in reality performance will be good too, so it is a good solution. But it is hacky. There are a lot of hacky ways to do what I need with VapourSynth. Some are better and some are worse (this one is better). I am just asking if we can have a native support for this use-case in VapourSynth? @myrsloik 

P.S. and I would also consider any two-pass solution as a hacky one (even though, I don't see how to implement it with VapourSynth + custom C++ filters alone). At the very least it is clearly inferior in terms of performance and storage requirements.

**Comment by myrsloik** [comment]
Definitely outside the scope of this project
