### ISSUE TITLE
Use CPU affinity as fallback instead of hardware_concurrency()

### ISSUE THREAD

**Issue by Endilll** [vapoursynth/vapoursynth#446]
Which is used by `VSThreadPool::setThreadCount()`. [sched_getaffinity()](https://linux.die.net/man/2/sched_getaffinity) and [GetProcessAffinityMask()](https://docs.microsoft.com/en-us/windows/desktop/api/winbase/nf-winbase-getprocessaffinitymask) should do the work. `std::thread::hardware_concurrency()` ignores process's affinity, and I don't see this changing in current C++20 draft or papers related to `std::thread`. Probably because all efforts are put into [Executors](https://github.com/executors/executors), which could help with this, but they didn't make it into C++20, so I don't expect any help from STL for years to come.

There are also [hwloc](https://www.open-mpi.org/projects/hwloc/) library with cross-platform API for this, but it seems [a bit complicated](https://github.com/eliben/code-for-blog/blob/master/2016/threads-affinity/hwloc-example.cpp).

**Comment by myrsloik** [comment]
Sounds reasonable. The only reason it's the default is that it's the closest thing to a cross platform value that exists without using libraries. It's also not a good default since hyperthreading rarely helps in practice.

**Comment by myrsloik** [comment]
Implemented on windows now

**Comment by myrsloik** [comment]
Implemented everywhere I guess
