### ISSUE TITLE
`dlopen()`ed files should not be installed to `/usr/lib`

### ISSUE THREAD

**Issue by ahkok** [vapoursynth/vapoursynth#447]
The file `libvapoursynth.so` is opened afaics with `dlopen`. It does not belong directly under `/usr/lib64` (in clearlinux's case). Instead, it should be installed into a private folder probably under e.g. `/usr/lib64/vapoursynth`.

Our distro tooling breaks on this as it thinks that the .so file is a `devel` object. Needless to say, `ldconfig` should not be indexing it either.

I didn't see a configure option to set e.g. a `--module-path` option to tell it where to find external DSOs.

**Comment by dubhater** [comment]
You can load libvapoursynth.so with dlopen, but you don't have to. It works like any other library and it definitely belongs in libdir. ldconfig should index it.

Your tools are probably confused because it doesn't have an soversion. The reason for that is that it handles versioning internally, so there is no need for soversion.

**Comment by darealshinji** [comment]
> The file libvapoursynth.so is opened afaics with dlopen.

The python module `vapoursynth.so` is linked against it, when I build it.

> Your tools are probably confused because it doesn't have an soversion. The reason for that is that it handles versioning internally, so there is no need for soversion.

Good to know. Though you could also just version it to `libvapoursynth.so.0` and simply never change that. However, it's not the only non-development library that ends on `.so` and gets installed directly into `/usr/lib`.

**Comment by OpenSourceAnarchist** [comment]
@ahkok This is basically the one package I need to work in Clear Linux in order for me to switch over completely (though the 3rdparty repos will be wonderful so ffmpeg doesn't have to be compiled by the user). Could Clear Linux add an soversion patch to make it compatible, or something similar so it can be introduced as a package and mpv can be built with support for it?
