### ISSUE TITLE
Sync _ColorRange frame prop values with Resize

### ISSUE THREAD

**Issue by Endilll** [vapoursynth/vapoursynth#449]
After all those nice references to ITU-T H.265 for matrix, transfer function, primaries and even color range itself (only in Resize docs) implementing _ColorRange in terms of 'isLimited' instead of 'video_full_range_flag' seems really odd. It looks like legacy for me, but maybe there are some background.

I acknowledge that this is a breaking change, so probably API v4.

**Comment by sekrit-twc** [comment]
I agree that `_ColorRange2` would be helpful. However, it should not be a boolean. `video_full_range_flag` aside, there are other range conventions used in industry (e.g. SDI coding) that may be supported in the future.

**Comment by myrsloik** [comment]
Sure, just write a sane suggestion and I'll add it officially.
