### ISSUE TITLE
sub.Subtitle top/bottom margins are not working correctly

### ISSUE THREAD

**Issue by cyaoeu** [vapoursynth/vapoursynth#452]
When using sub.Subtitle top or bottom margins the text moves correctly but gets smaller for some reason.

```

import vapoursynth as vs
core = vs.get_core()

clip = core.std.BlankClip(length=1)
clips = []
for i in range(10):
	new_clip = core.sub.Subtitle(clip, "Test", margins=[i*50, 0, 0, 0])
	clips.append(new_clip)
clips = core.std.Splice(clips)
clips.set_output()
```

**Comment by dubhater** [comment]
I think that's just how libass works. Or maybe it's because of the ASS format itself.

Try adjusting the vertical margin in the style parameter:
style="sans-serif,20,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,0,7,10,10,**10**,1"

**Comment by cyaoeu** [comment]
> I think that's just how libass works. Or maybe it's because of the ASS format itself.
> 
> Try adjusting the vertical margin in the style parameter:
> style="sans-serif,20,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,0,7,10,10,**10**,1"

I see. Thanks for the workaround!
