### ISSUE TITLE
VapourSynth R46 Installer Laundry list

### ISSUE THREAD

**Issue by stuxcrystal** [vapoursynth/vapoursynth#454]
https://f.nemur.in/file/stux-sharex/ShareX/2019/06/2019-06-27_23-25-16.mp4

Or is the first section not supposed to be clickable?

**Comment by stuxcrystal** [comment]
I instantly got this error after installing.

https://f.nemur.in/file/stux-sharex/ShareX/2019/06/vs_installershell_2019-06-27_23-32-05.png
Python 3.7 installed via Windows Store.

**Comment by myrsloik** [comment]
The first item is simply a header. For some reason the whole scaling looks off now.

**Comment by stuxcrystal** [comment]
Well I got around to updating the pip packages.

**Comment by myrsloik** [comment]
This is fun. If you install the ms store version of Python you get virtual registry entries (not seen in regedit) that are roughly equivalent to a normal python installation in HKCU. Unfortunately they seem to be completely unusable. Like the 'ExecutablePath' that even finishes with a [               ] in your screenshot so trying to execute it obviously fails.
It's obvious the ExecutablePath should be something like %LOCALAPPDATA%\Microsoft\WindowsApps\Python.exe in order to not break things. Maybe it's a packaging oversight?

**Comment by myrsloik** [comment]
And if that's corrected there still has to be a reliable way to locate the python dll or vsscript won't be able to load properly.

**Comment by stuxcrystal** [comment]
I suggest
* opening an issue at the python gh repo
* dont fix it, just keep it as a known issue, abd refer to this text in the app-description:
  > We are still evaluating the Microsoft Store release of Python, and not all features are guaranteed stable.

**Comment by myrsloik** [comment]
Does vspipe really work correctly using vapoursynth-portable and ms store python? In my imagination it seems like it'd break but I didn't actually test it.

**Comment by stuxcrystal** [comment]
Well. It's apparently not just your imagination. Man that sucks.

**Comment by stuxcrystal** [comment]
VapourSynth fails to load on `C:\\Users\\stuxc\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python37\\site-packages\\vapoursynth.cp37-win_amd64.pyd`

After manually installing `vapoursynth` via pip on the ms-store version, it works there too. Before doing that, it errored with a dll-load error.

**Comment by FichteFoll** [comment]
For the record, Python issues are to be filed at pbo. The github repo [for CPython] only accepts pull requests.

**Comment by Lypheo** [comment]
The 64-bit installer doesn’t give the user an option to choose an installation mode prior to this message. Executing the installer prompts UAC and immediately throws this error after accepting.
![grafik](https://user-images.githubusercontent.com/45497420/60439318-e8c3c800-9c12-11e9-8f56-8130e0fa2f75.png)

**Comment by myrsloik** [comment]
If it's already installed it will automatically select the previouslt selected install type.

**Comment by myrsloik** [comment]
The relevant Python bug I created: https://bugs.python.org/issue37452
Seems like they're at least taking another look at it.

**Comment by myrsloik** [comment]
The MS store python has now been updated and installations to it at least won't fail anymore. Will do more testing and see how functional it actually is later.

**Comment by myrsloik** [comment]
Here's the next quirk. You can only install the package using pip install --user blah.whl. However vapoursynth.dll and vapoursynth.cp37-win_amd64.pyd won't end up in the same directory then and will as a result fail to load properly. Any ideas on how to solve it?

**Comment by stuxcrystal** [comment]
Im gonna take at it today




Holen Sie sichOutlook für Android







On Fri, Jul 5, 2019 at 7:59 PM +0200, "Fredrik Mellbin" <notifications@github.com> wrote:












Here's the next quirk. You can only install the package using pip install --user blah.whl. However vapoursynth.dll and vapoursynth.cp37-win_amd64.pyd won't end up in the same directory then and will as a result fail to load properly. Any ideas on how to solve it?

**Comment by myrsloik** [comment]
@stuxcrystal do you have an update on the --user option? It'd be nice to get in for R47.

**Comment by myrsloik** [comment]
@stuxcrystal you are hereby poked

**Comment by myrsloik** [comment]
Everything except the broken windows store python fixed and nobody cares about that one.
