### ISSUE TITLE
Modularize vapoursynth project

### ISSUE THREAD

**Issue by Youka** [vapoursynth/vapoursynth#456]
Vapoursynth has an organization but puts so much code into one project with a mix of different technologies and purposes. This could get optimized for better management and overview by splitting it up into multiple projects with references:

- One project for Vapoursynth **core** (frameserving with C API).
- One project for Vapoursynth **scripting** (python wrapper).
- One project for Vapoursynth **Avisynth compatibility** (additional Avisynth support).
- One project for Vapoursynth **documentation** (doc generation and examples).
- One project for each Vapoursynth **distribution** (scripts for windows installer or linux packages or homebrew).
- One project for each Vapoursynth **tool** (vspipe, vsedit, Yuuno, ...).
- One project for each Vapoursynth **plugin family** (core filters, by vendor, ...).

You could even put your homepage in here with [Github pages](https://pages.github.com/). A simplified online sandbox would be a nice promotional project too.

I think it's important to centralize all Vapoursynth resources into this organization and make developers to team members with restricted permissions to their work areas.

Vapoursynth needs a home! Currently it's cumbersome to setup and discover the potential of this great frameserver which stagnates its spreading.

**Comment by stuxcrystal** [comment]
I'd like to note that VSEdit and Yuuno are (beyond depending on VS) separate projects.

**Comment by Youka** [comment]
Though it would be great to have them in this organization because they're important tools which should be near the core, not just some nice-to-have extras.
