### ISSUE TITLE
Improve software quality by automation

### ISSUE THREAD

**Issue by Youka** [vapoursynth/vapoursynth#457]
Auto-invoked builds, tests and monitoring could improve **productivity**, **safety** and **up-to-dateness** of Vapoursynth.

Building with **online CI services** ([Travis](https://travis-ci.org), [Appveyor](https://www.appveyor.com/), [Circle-CI](https://circleci.com/)), including **unit tests** ([C++](https://www.boost.org/doc/libs/1_70_0/libs/test), [Python](https://docs.python.org/dev/library/unittest.html), [JS](https://mochajs.org/#getting-started)) and **deploy** ([pypi](https://docs.travis-ci.com/user/deployment/pypi/), [Launchpad](https://docs.travis-ci.com/user/deployment/launchpad/)) a successful outcome directly.

The project **README** can already tell a lot at first sight (with help of [Shield.io](https://shields.io/)):

---

[![Travis (.org)](https://img.shields.io/travis/substation-beta/ssb_implementation.svg?logo=travis)](https://travis-ci.org/substation-beta/ssb_implementation) `[![Travis (.org)](https://img.shields.io/travis/substation-beta/ssb_implementation.svg?logo=travis)](https://travis-ci.org/substation-beta/ssb_implementation)`

[![Codecov](https://img.shields.io/codecov/c/github/SimonKagstrom/kcov.svg?logo=codecov)](https://codecov.io/gh/SimonKagstrom/kcov) `[![Codecov](https://img.shields.io/codecov/c/github/SimonKagstrom/kcov.svg?logo=codecov)](https://codecov.io/gh/SimonKagstrom/kcov)`

[![Discord](https://img.shields.io/discord/102860784329052160.svg?logo=Discord)](https://discordapp.gg/102860784329052160) `[![Discord](https://img.shields.io/discord/102860784329052160.svg?logo=Discord)](https://discordapp.gg/102860784329052160)`

[![Libraries.io dependency status for latest release](https://img.shields.io/librariesio/release/pypi/vapoursynth.svg?logo=pypi)](https://libraries.io/pypi/VapourSynth) `[![Libraries.io dependency status for latest release](https://img.shields.io/librariesio/release/pypi/vapoursynth.svg?logo=pypi)](https://libraries.io/pypi/VapourSynth)`

[![Beerpay](https://img.shields.io/beerpay/albertogeniola/MerossIot.svg)](https://beerpay.io/albertogeniola/MerossIot) `[![Beerpay](https://img.shields.io/beerpay/albertogeniola/MerossIot.svg)](https://beerpay.io/albertogeniola/MerossIot)`

[![GitHub](https://img.shields.io/github/license/vapoursynth/vapoursynth.svg?logo=github)](https://github.com/vapoursynth/vapoursynth/blob/master/ofl.txt) `[![GitHub](https://img.shields.io/github/license/vapoursynth/vapoursynth.svg?logo=github)](https://github.com/vapoursynth/vapoursynth/blob/master/ofl.txt)`

[![GitHub release](https://img.shields.io/github/release/vapoursynth/vapoursynth.svg?logo=github)](https://github.com/vapoursynth/vapoursynth/releases) `[![GitHub release](https://img.shields.io/github/release/vapoursynth/vapoursynth.svg?logo=github)](https://github.com/vapoursynth/vapoursynth/releases)`

[![PyPI - Python Version](https://img.shields.io/pypi/pyversions/Django.svg?logo=pypi)](https://pypi.org/project/Django/) `[![PyPI - Python Version](https://img.shields.io/pypi/pyversions/Django.svg?logo=pypi)](https://pypi.org/project/Django/)`

[![GitHub commit activity](https://img.shields.io/github/commit-activity/y/vapoursynth/vapoursynth.svg?logo=github)](https://github.com/vapoursynth/vapoursynth/commits/master) `[![GitHub commit activity](https://img.shields.io/github/commit-activity/y/vapoursynth/vapoursynth.svg?logo=github)](https://github.com/vapoursynth/vapoursynth/commits/master)`

---

Furthermore filling the [github community checklist](https://github.com/vapoursynth/vapoursynth/community) helps for ranking, using [project boards](https://github.com/vapoursynth/vapoursynth/projects) makes development more transparent + main goals clear and a [modern homepage](https://angular.io) (instead of this [empty blog design](http://www.vapoursynth.com/)) would convince people that "the future" really is meant.

**Comment by CoffeeFlux** [comment]
i would hope no one actually judges the quality of software projects on how many shiny badges their readme includes

**Comment by Youka** [comment]
It's not about appearance but the services behind the badges and getting easily information without clicking around or searching through text walls. Manual updates by maintainers aren't required and compressing data by using multiple recognition patterns (text + colors + symbols) is convenient too.

All about saving time!

@CoffeeFlux These badges aren't even shiny (i saw real crimes) and getting to the point to catch peoples attention and not bore them away or inform them about changes quickly i always prefer over your childish prejudice.

**Comment by stuxcrystal** [comment]
My main problem is actually not that we could add badges but rather, *is the project ready to use the services behind those badges.*

Let's start with the ideal CI/CD Pipeline usually require more than one historical branch (to avoid new releases being put out constantly with every merged PR and so on.) And if you look ag zimg, you'll see that yes, this project has branches, no, they are misused as tags.

Also you only get advantages of CI if you have enough tests to make them useful.

Both are not given.

-------

Also: I'd love to have a vapoursynth with a modern homepage. I'd offer myself to make one. And if there's someone who wants to make a design (with Myrsloiks blessing) of course, I think, this will make a great difference.
