### ISSUE TITLE
Move Auto-Load Discovery to Library-Consumers

### ISSUE THREAD

**Issue by stuxcrystal** [vapoursynth/vapoursynth#462]
On windows there is a portable mode that is being activated by a `portable.vs`-file beside the DLL-File.

To implement something similar, the so-file must be able to discover its own path. I do not know of a way to achieve something like this.

This is why I propose that we allow library-consumers (everyone who includes the frameserver directly) to disable plugin-autoloading in the core.

If the python wrapper could discover the plug-in-directories by itself, it may be possible to implement a "portable" version for Linux and Mac too. There are ways for a python module to discover its own path. 

Instead I propose we add
* a new Function `std.LoadAllPlugins(path: str)`
* a new C-Function `createCore2(int threads, int flags)`
* a flag along the line of `DISABLE_AUTOLOADING`
* and increment the API Minor Version by one.

The old createCore function will be deprecated and will be functionally the same as `createCore2(threads, 0)`

This might be a way for me to allow installing vapoursynth purely through PyPI as a binary-wheel.

**Comment by myrsloik** [comment]
Sounds reasonable

**Comment by myrsloik** [comment]
Just another though. How would it interact with vsscript? That would have a flag as well to create a core with different flags?

**Comment by stuxcrystal** [comment]
Generally, I was thinking something along the lines of:
If there's a `portable.vs`-file alongside the `vapoursynth.pyd`-file, we just switch over to discovering the file ourselves.

Otherwise, yes, I'd expose the flag to vsscript and the module. In both cases, it should default to passing `0` (meaning use the system-autoload directories)

**Comment by myrsloik** [comment]
Everything in the first post is implemented in the doodle1 branch. The python/vsscript bit will be revisited.

**Comment by stuxcrystal** [comment]
Since this issue is a little bit older and things changed since then:

I think we have a place where we can introduce non-autoloading Core-instances in Python-land as follows:
I suggest changing `EnvironmentPolicyAPI.create_environment()` into `EnvironmentPolicyAPI.create_environment(flags: int = 0)`.
The core-instance created by this function then will use the flags passed to the `create_environment`-function.
That way, editors can manually implement autoloading-logic if they so wish.

**Comment by myrsloik** [comment]
Sounds kinda reasonable. Will try it and see what happens.

**Comment by myrsloik** [comment]
Done
