### ISSUE TITLE
Cython: "Failed to obtain VapourSynth API pointer." (R47; Linux)

### ISSUE THREAD

**Issue by Youka** [vapoursynth/vapoursynth#468]
**R47** [works on windows](https://ci.appveyor.com/project/Youka/ssb-implementation/build/job/cv63tcibj6ogt5f1#L119), but [doesn't build](https://travis-ci.org/substation-beta/ssb_implementation/jobs/567654540#L801-L807) on Linux.

For some reason it's [not possible to get](https://github.com/vapoursynth/vapoursynth/blob/master/src/cython/vapoursynth.pyx#L1628-L1630) the [VS api instance](https://github.com/vapoursynth/vapoursynth/blob/master/src/core/vsapi.cpp#L662-L679) by [version constant](https://github.com/vapoursynth/vapoursynth/blob/master/include/VapourSynth.h#L26-L28).

_(Installation script changes: [download url to R47 + remove nasm installation](https://github.com/substation-beta/ssb_implementation/commit/439f78596235adb6028c8f65b50c2cac5c66d2b2#diff-2fb877560a0f635a60ab4958633f3d01))_

**Comment by myrsloik** [comment]
Can you try to debug it?

It's most likely getCPUFeatures() (in cpufeatures.c) that returns bad values. You can try to see why it doesn't work.

**Comment by rathsky** [comment]
Same issue on Arch (kernel 5.2.6, glibc 2.29).

**Comment by Youka** [comment]
Added some debug output (rough blueprint):
```
src/core/vsapi.cpp @670

#include <iostream>

    std::cout << "API MAJOR: " << apiMajor << '\n'
                        << "API MINOR: " << apiMinor << '\n'
                        << "VAPOURSYNTH_API_MAJOR: " << VAPOURSYNTH_API_MAJOR << '\n'
                        << "VAPOURSYNTH_API_MINOR: " << VAPOURSYNTH_API_MINOR << '\n'
                        << "CPUFeatures.can_run_vs: " << static_cast<int>(f.can_run_vs) << std::endl;


src/core/cpufeatures.c @48

#error Unknown compiler, cannot get cpuid


src/core/cpufeatures.c @73

#include <stdio.h>

printf("CPU edx: %d\n", edx);
```

Got:
```
CPU edx: 0
CPU edx: 0
API MAJOR: 3
API MINOR: 6
VAPOURSYNTH_API_MAJOR: 3
VAPOURSYNTH_API_MINOR: 6
CPUFeatures.can_run_vs: 0
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "src/cython/vapoursynth.pyx", line 1679, in vapoursynth._CoreProxy.__getattr__
  File "src/cython/vapoursynth.pyx", line 1669, in vapoursynth._CoreProxy.core.__get__
  File "src/cython/vapoursynth.pyx", line 1647, in vapoursynth.get_core
  File "src/cython/vapoursynth.pyx", line 1630, in vapoursynth.createCore
vapoursynth.Error: Failed to obtain VapourSynth API pointer. System does not support SSE2 or is the Python module and loaded core library mismatched?
```

**SSE2** doesn't [get detected](https://github.com/vapoursynth/vapoursynth/blob/master/src/core/cpufeatures.c#L72-L73) (but is definitely available, checked by [lshw](https://wiki.ubuntuusers.de/lshw/) and listed in _capabilities_ as _sse2_)!

**Comment by dubhater** [comment]
The problem is that __cpuid_count takes integers, not pointers to integers for the last four parameters.

**Comment by myrsloik** [comment]
Doh, the wonders of C where anything goes

**Comment by myrsloik** [comment]
Try the fixes_R47_1 branch and see if it works

**Comment by Youka** [comment]
Commands:
```

# apt-get install -y build-essential autoconf libtool pkg-config python3-pip && pip3 install cython
# wget -qO- https://github.com/sekrit-twc/zimg/archive/release-2.9.2.tar.gz | tar -zxf- && pushd ./zimg-release-2.9.2
# ./autogen.sh && ./configure && make install
# popd
# apt-get install git
# git clone -b fixes_R47_1 https://github.com/vapoursynth/vapoursynth.git && cd vapoursynth/
# ./autogen.sh && ./configure && make install
# ldconfig /usr/local/lib
# ln -s /usr/local/lib/python3.5/site-packages/vapoursynth.so /usr/local/lib/python3.5/dist-packages/vapoursynth.so
# python3 -c "from vapoursynth import core;print(core.version())"
```
Final output:
```
VapourSynth Video Processing Library
Copyright (c) 2012-2019 Fredrik Mellbin
Core R47
API R3.6
Options: -
```

Looks good.
