### ISSUE TITLE
Doesn't build for arches others thans X86

### ISSUE THREAD

**Issue by marillat** [vapoursynth/vapoursynth#469]
Fail to build for powerpc, armel, armh and arm64 with 
````
../src/core/mergefilters.c:25:10: fatal error: emmintrin.h: No such file or directory
 #include <emmintrin.h>
          ^~~~~~~~~~~~~
compilation terminated.
````

**Comment by sekrit-twc** [comment]
Try again. That file was rewritten recently.

**Comment by marillat** [comment]
I'm talking about files in vapoursynth 47 tarball

**Comment by myrsloik** [comment]
I'll make a R47.1 release in a day or two with only that fix

**Comment by marillat** [comment]
@myrsloik OK, thanks

**Comment by myrsloik** [comment]
Try the fixes_R47_1 branch and see if it works

**Comment by marillat** [comment]
Build fine for all my ARM arches.
Thanks again.
