### ISSUE TITLE
Prewitt filter is actually Sobel (for masktools compatibility)

### ISSUE THREAD

**Issue by myrsloik** [vapoursynth/vapoursynth#470]
This makes no sense and should be changed at some point

**Comment by dubhater** [comment]
It is? I remember implementing both according to their Wikipedia pages, not by imitating Masktools.

**Comment by myrsloik** [comment]
Maybe I've been tricked again. Will have to check it.

**Comment by sekrit-twc** [comment]
Only Prewitt SSE2 asm is Sobel. The others were fixed at some point in time, as can be seen from the '* 2' in the kernels.
