### ISSUE TITLE
Add a registry entry for the VSPipe path

### ISSUE THREAD

**Issue by myrsloik** [vapoursynth/vapoursynth#472]

**Comment by myrsloik** [comment]
Call it VSPipeExe

**Comment by myrsloik** [comment]
Maybe have one for vsrepo too

**Comment by theChaosCoder** [comment]
Maybe also add vspipe  to PATH via the installer? I found it very handy on my system.

**Comment by myrsloik** [comment]
Added in R48 including the PATH option
