### ISSUE TITLE
release 47.1 has no binaries

### ISSUE THREAD

**Issue by hydra3333** [vapoursynth/vapoursynth#473]
Thank you for your great work.
Wondering, would it be possible to attach binaries to release 47.1 ?

It looks like there's good things to be had in .1 including a bugfix or two
https://github.com/vapoursynth/vapoursynth/compare/R47...master

Regards

**Comment by myrsloik** [comment]
You didn't read the release message and you didn't look at the correct branch.

**Comment by hydra3333** [comment]
OK.   I re-grabbed the portable r47.7z and it was bit identical to the prior downloaded r47.7z so I guess r47.1 has no newer binaries.

However not sure about the branch thing you mentioned. I went by the git releases text 
"R47 @myrsloik myrsloik released this 3 days ago · 11 commits to master since this release"
and clicked on "11 commits" to see what they were, which included what looked to be fixes
- Fix SSE float prewitt filter
- Supply variables instead of pointers to __cpuid_count

Thank you.
