### ISSUE TITLE
std.Merge broken?

### ISSUE THREAD

**Issue by 4re** [vapoursynth/vapoursynth#479]
Linux, maybe it's OK on Windows, maybe it's just me. I only tested it with `47.1` and `Master` (46 is OK).

If `std.Merge` is used with `weight` different from `0` or `1` output appears glitched.

Example:
```
import vapoursynth as vs
import finesharp as fs
core = vs.get_core()
v = core.lsmas.LWLibavSource('video.mkv')
v = fs.sharpen(v, xstr=.5)
v.set_output()
```
https://imgur.com/RkXPYP8

**Comment by kageru** [comment]
I tried to reproduce this, but `std.Merge` seems to work fine on my system (current master on Arch Linux). I tested both RGB and YUV, as well as int and float.
`core.std.Merge(core.std.BlankClip(), core.std.BlankClip(color=[255, 255, 255]), 0.6).imwri.Write('PNG', 'whatever%d.png').get_frame(0)` (and equivalent calls for YUV) returns the expected monochrome image.

**Comment by myrsloik** [comment]
Note that master is more or less rewritten from the latest release when it comes to filter intrinsics so this tells us nothing (except that master is working).

**Comment by 4re** [comment]
The problem can't be seen with that line. You need an image with more texture to see it. The blending actually occurs, but vertical strips are just displaced fragments of the image.

**Comment by 4re** [comment]
Easy example:
```
import vapoursynth as vs
core = vs.get_core()
v = core.lsmas.LWLibavSource('Natural_image_you_can_recognice_so_not_a_plain_color.mkv')
m = core.std.Merge(v, v, 0.6)
m.set_output()
```

**Comment by Infiziert90** [comment]
Tested it with Master on Arch and same problem, with an image from a normal episode

**Comment by 4re** [comment]
Welp, this happens to me in both my ryzen and i5 machines. This fixes itself if I pass at compile time `--disable-x86-asm`, and this bug is present in `47.1` and `Master`, `46` is fine.
I have not tested it on Windwos but I will probably test it later today or tomorrow.

**Comment by pinterf** [comment]
Perhaps in this line
https://github.com/vapoursynth/vapoursynth/blob/master/src/core/kernel/x86/merge_sse2.c#L53
`v1w_hi`  should be used instead of `v1w_lo`?

**Comment by myrsloik** [comment]
It most definitely should be.

**Comment by myrsloik** [comment]
I'll prepare R47.2 in a day or two when I have time.

**Comment by myrsloik** [comment]
Fixed in latest release
