### ISSUE TITLE
Dont error out to warn the user

### ISSUE THREAD

**Issue by stuxcrystal** [vapoursynth/vapoursynth#486]
https://github.com/vapoursynth/vapoursynth/blob/17cf12d807ad9226d1e879f291182bf704070661/src/filters/imwri/imwri.cpp#L498

Use the logging-system of vapoursynth instead and carry on overwriting the same file.

A script in python might format the name itself and only call `get_frame` once on that particular filter-instance. No digit substitution needed in this case as the user already substituted it for himself.

Maybe add a flag to disable the error or something like it.

Also, we have this. We could make use of it.
https://github.com/vapoursynth/vapoursynth/blob/17cf12d807ad9226d1e879f291182bf704070661/include/VapourSynth.h#L338

**Comment by myrsloik** [comment]
Why would you ever want to overwrite the same file? Seems like a definite user error to me.

**Comment by Lypheo** [comment]
Because a user may only want to write a single image, in which case no digit substitution should be required.

**Comment by myrsloik** [comment]
Settings overwrite=True will now satisfy all your overwrite needs
