### ISSUE TITLE
std.Convolution output differs in Windows and Linux

### ISSUE THREAD

**Issue by b6b** [vapoursynth/vapoursynth#502]
I noticed `std.Convolution` seems to give incorrect output when used on a Linux machine (Arch to be specific).

Here's a comparison of a source clip, Windows, and Linux output running this convolution `core.std.Convolution(clip, [-3, 5, 5, 5, 0, -3, -3, -3, -3], saturate=False)`: https://slowpics.org/comparison/be7effcd-5370-4180-aeeb-a79e25b45e80

Setting `core.std.SetMaxCPU('none')` seems to break it even more and returns an all-white frame.

Observed this issue on both 47.2 and the latest master. Happy to give more details if needed.

**Comment by DeadNews** [comment]
R46 vs R48 (git):
https://slowpics.org/comparison/72922629-1003-4292-ae20-f758d7afcd51 (R46 works as expected)
It's [retinex_edgemask](https://github.com/Irrational-Encoding-Wizardry/kagefunc/blob/master/kagefunc.py#L223), std.Convolution is also used there.
OS: Linux

**Comment by myrsloik** [comment]
Try with latest master now

**Comment by b6b** [comment]
Appears to be working now. Thanks!

**Comment by myrsloik** [comment]
Probably a small issue still lurking in there so be aware. Will update when it's less broken.

**Comment by myrsloik** [comment]
Everything should be fixed now including saturate=True. Report your findings.

**Comment by 4re** [comment]
Commit ad3c7fc3547ddaaf9648ad004abba7e79f69b6a2 fixes this problem but now `saturate=True` produces solid green images, so the example in the documentation `Convolution(matrix=[1, 2, 1, 2, 4, 2, 1, 2, 1])` returns: https://i.imgur.com/2UgwDAM.jpg

**Comment by DeadNews** [comment]
> fixes this problem

 [Yes](https://slowpics.org/comparison/cf8c5930-e0bc-41a3-9f5f-1857a5ad2f57).
> but now [...]

Plus [visual artifacts](https://slowpics.org/comparison/de3dd2b8-c116-4806-9745-f01a7a9a972e) appeared.

**Comment by DeadNews** [comment]
> fixes this problem

 [Yes](https://slowpics.org/comparison/cf8c5930-e0bc-41a3-9f5f-1857a5ad2f57).
> but now [...]

Plus, for example, [visual artifacts](https://slowpics.org/comparison/de3dd2b8-c116-4806-9745-f01a7a9a972e) appeared.

**Comment by myrsloik** [comment]
Updated again.

**Comment by DeadNews** [comment]
At first glance, the problems are solved. Thanks.

**Comment by 4re** [comment]
Everything looks good here, thank you.

**Comment by b6b** [comment]
LGTM too. Thanks again.
