### ISSUE TITLE
Error reading DXT1 compressed DDS files with IMWRI

### ISSUE THREAD

**Issue by AlphaAtlas** [vapoursynth/vapoursynth#505]
IMRWI.read() seems to output a blank/corrupt image when reading dds files compressed with DXT1, but works fine with DXT5.

This is the script I tested with:

```
import vapoursynth as vs
core = vs.get_core()
clip, alpha = core.imwri.Read(r"""C:/(path to the image)/1.dds""", mismatch=False, alpha=True)
clip = core.imwri.Write(clip, "jpg", "output%d.jpg")
clip.set_output()
```

Command I used: `vspipe.exe "C:\(path to image)\test.vpy" "NUL"`

Here are 2 sample images. "1" is a DXT1 dds file, "2" is a dxt5 dds file, which you can verify with something like [WTV](https://developer.nvidia.com/legacy-texture-tools). 

[Samples.zip](https://github.com/vapoursynth/vapoursynth/files/3736762/Samples.zip)

This is the written image from feeding it the DXT1 file:

![dxt1](https://user-images.githubusercontent.com/46462706/66966841-a05ad980-f04c-11e9-9a2c-214ed1f73ef8.jpg)

This is DXT5:

![dxt5](https://user-images.githubusercontent.com/46462706/66966851-aa7cd800-f04c-11e9-8f1c-828bcff21920.jpg)

Previewing the outputted DXT1 frame is VSEdit is particularly strange, as the artifacts change every time I open the file:

![test vpy - 0](https://user-images.githubusercontent.com/46462706/66967005-51617400-f04d-11e9-8b26-0a7aa88719fa.png)

Note this was tested with VapourSynth 47.2, as I just noticed R48 as I was typing this out. Running that exact command in R48 spits out this error:

`AttributeError: No attribute with the name imwri exists. Did you mistype a plugin namespace?`

I probably screwed up my VS installation somehow, so I'll see if I can replicate the issue in R48.

**Comment by dubhater** [comment]
Looks like a bug in ImageMagick which was probably fixed already, because I can't reproduce it with ImageMagick 7.0.8.67 in Linux. The Imwri DLLs contain ImageMagick 7.0.7.25.

**Comment by dubhater** [comment]
Try again with these:
[imwri-r48-win32.zip](https://github.com/vapoursynth/vapoursynth/files/3738596/imwri-r48-win32.zip)
[imwri-r48-win64.zip](https://github.com/vapoursynth/vapoursynth/files/3738597/imwri-r48-win64.zip)

They contain ImageMagick 7.0.8.68.

**Comment by dubhater** [comment]
I found the problem. It's in Imwri after all, not in ImageMagick.

**Comment by myrsloik** [comment]
Committed an untested fix for it.

**Comment by myrsloik** [comment]
Try this build:
https://www.dropbox.com/s/zopcwxqj4hk8192/imwri-r48-win64.7z?dl=1
https://www.dropbox.com/s/dcuwvqd8qbv5hug/imwri-r48-win32.7z?dl=1

**Comment by AlphaAtlas** [comment]
Yep, issue is gone with R48-RC2, thanks!
