### ISSUE TITLE
Slightly different results with Convolution and BoxBlur

### ISSUE THREAD

**Issue by blaze077** [vapoursynth/vapoursynth#506]
I get a slightly different result with BoxBlur (default settings) compared to its convolution equivalent (a one-off difference in most places where it happens). Here's an example for a 10-bit video.

https://i.imgur.com/a1BFPdA.png

Here's my script:
```py
import vapoursynth as vs
core = vs.core
src = core.ffms2.Source(r"C:\Users\Naval Wing\Downloads\source.mkv")
src = core.std.ShufflePlanes(src, 0, vs.GRAY)
box = core.std.BoxBlur(src)
conv = core.std.Convolution(src, matrix=[1]*9)
diff = core.std.MakeDiff(box, conv)
binarized = core.std.Expr([conv, box], "x y - abs 0 > 1023 0 ?").text.Text("Binarized")
diff = diff.text.Text('Difference')
src = src.text.Text('Source')
stacked = core.std.StackHorizontal([src, diff, binarized])
stacked.set_output()
```

Using R48-RC1 but this also happened with R46.

**Comment by myrsloik** [comment]
BoxBlur rounds after each pass so a small difference is expected. The difference should be at most 2 or maybe 3 in the absolute worst case scenario.

**Comment by blaze077** [comment]
Gotcha, thanks.
