### ISSUE TITLE
Calling setMessageHandler twice deadlocks

### ISSUE THREAD

**Issue by YaLTeR** [vapoursynth/vapoursynth#507]
Pretty sure this is because `vsSetMessageHandler` acquires a lock:
https://github.com/vapoursynth/vapoursynth/blob/a22fe2578fb81bb3bb735239dd5c135ee02b7664/src/core/vslog.cpp#L42
then calls `vsRemoveMessageHandler`:
https://github.com/vapoursynth/vapoursynth/blob/a22fe2578fb81bb3bb735239dd5c135ee02b7664/src/core/vslog.cpp#L44
which also tries to acquire the same lock:
https://github.com/vapoursynth/vapoursynth/blob/a22fe2578fb81bb3bb735239dd5c135ee02b7664/src/core/vslog.cpp#L61

**Comment by myrsloik** [comment]
Doh, fixed.
