### ISSUE TITLE
Add NEON optimizations on ARM

### ISSUE THREAD

**Issue by SuNNjek** [vapoursynth/vapoursynth#516]
Hi,
since VS has SSE and AVX2 optimized code on x86, would it be possible to do the same for ARM with NEON?

**Comment by myrsloik** [comment]
Sure, if someone writes it.

**Comment by Stefan-Olt** [comment]
Simple idea: There is [sse2neon](Intel SSE intrinsics): It implements all the Intel SSE intrinsics defined in *mmintrin.h in NEON, so no need to write NEON assembly, just include sse2neon.h instead of the Intel-specific header. I have not tried it yet, but it should cover everything up to SSE4.2 (no AVX).
Not all SSE instructions have an exact counterpart in NEON, so sse2neon often has to use multiple instructions for one SSE instructions, but I assume it's still a lot faster.
If it really works that simple, all what needs to be adjusted are the options to include and build the "SSE code" in ARM builds

**Comment by Stefan-Olt** [comment]
Just for fun I added sse2neon and (maybe) it worked: The SSE2 code compiles on ARM. I modified the select functions that the SSE2 code is used.
I cannot measure any performance difference in my simple test script, I'm not sure these functions are used at all. Can somebody provide an example that makes extensive use of the assembly in the Vapoursynth kernel?

**Comment by myrsloik** [comment]
It's also possible the code is good enough already. Things get memory bw limited fast for many filters that don't do very complicated things. For example on ivy bridge I only wrote asm for 8 bit paths since 16 bit formats gained nothing.

**Comment by Stefan-Olt** [comment]
Possible, there could be another bottleneck so the instructions used don't matter. I'll test on Apple Silicon as soon as I have access to such a system again, as it's probably the most important ARM platform for Vapoursynth right now (I doubt somebody really wants to use VS on a Raspberry Pi or similar devices) and check if there any differences there.
I did not change the expr function as it uses a jit compiler (not sure the sse2neon approach works), and resize seems to be done by zimg, that already has NEON code.

**Comment by Stefan-Olt** [comment]
I did another test on my Raspberry Pi 3 Model B+, this time with a generated blank clip of 512x512 (1000 frames) and output directly as Y4M to /dev/null, here are the frames per seconds:
```
                   C   NEON    Diff
AverageFrames:   425    852   +100%
Convolution:     233    486   +109%
Merge:           908    920   +  1%
Transpose:      1059   1125   +  6%
```
I made 5 runs each time and took the highest fps (they are usually very close, but sometimes one is significantly lower, probably as a result of some other process). For AverageFrames and Convolution you can see a massive improvement, for Merge and Transpose the improvement is minimal. Are there any other functions I should test? I hope next weekend I can test on Apple Silicon.
I also compared the outputs (with real video input, not a blank clip): Bit identical for C and NEON code.

BTW, I tried the same trick with mvtools: Massive improvement from what I can tell (Raspberry Pi hasn't got the power/memory for a proper test). I did not only use sse2neon, I also took the aarch64 functions from x264 of the SSE2 ones they had already copied from x264.

@myrsloik Do you want me to prepare a Pull request or is it simpler for you to do the changes yourself? All that has to be done is replace `#include <emmintrin.h>` by
```
#ifdef VS_TARGET_CPU_ARM
#include "sse2neon.h"
#else
#include <emmintrin.h>
#endif
```
Additionally the SSE2 source files needs to be added in the build system form ARM and the function selector at runtime has to choose the "SSE2" functions for ARM. Unfortunately there doesn't seem to be any proper runtime detection for NEON: There is no cpuid-equivalent on ARM I could find, NNEDI3 has some OS-function (which states it was taken from VS), but that doesn't compile at all on macOS (is not a standard posix function) and on my Raspberry Pi it doesn't work correctly, as it doesn't detect NEON, so it's rather useless. But on aarch64 NEON is mandatory and I don't think anyone would like to use VapourSynth on an ARM32 CPU without NEON (the first generation Raspberry Pi doesn't have NEON from what I read), so making NEON mandatory for VapourSynth on ARM doesn't seem to an issue.

**Comment by Stefan-Olt** [comment]
I tested with a few different color formats other YUV420P8, for the 10 Bit formats the results are a bit more mixed: The NEON transpose is slightly slower. I hope next weekend I can do a test on a Apple Silicon machine.
```
RGB24
                   C   NEON    Diff
AverageFrames:   218    433   + 99%
Convolution:     117    242   +107%
Merge            466    467
Transpose:       525    576   + 13%


YUV420P8
                   C   NEON    Diff
AverageFrames:   425    852   +100%
Convolution:     233    486   +109%
Merge            908    920   +  1%
Transpose:      1059   1125   +  6%


YUV422P10
                   C   NEON    Diff
AverageFrames:   268    362   + 35%
Convolution:     167    378   +126%
Merge            362    362
Transpose:       494    434   - 12%


YUV444P10
                   C   NEON    Diff
AverageFrames:   168    233   + 39%
Convolution:     111    248   +123%
Merge            231    232
Transpose:       324    294   -  9%
```

**Comment by Stefan-Olt** [comment]
Finally had the possibility to test on an Apple Silicon. No build issues at all. Speed improvements everywhere, NEON seems to be more efficient on Apple Silicon. I changed the resolution from 512x512 to 3840x3840, otherwise these are the same tests as on the Raspberry Pi 3 (the much higher resolution results in the lower speeds compared to the Raspberry).
```
RGB24
                   C   NEON    Diff
AverageFrames:   110    254   +131%
Convolution:      60    131   +118%
Merge            204    286   + 40%
Transpose:       200    401   +101%


YUV420P8
                   C   NEON    Diff
AverageFrames:   217    452   +108%
Convolution:     122    258   +111%
Merge            365    508   + 39%
Transpose:       408    731   + 79%


YUV422P10
                   C   NEON    Diff
AverageFrames:   100    146   + 46%
Convolution:      78    134   + 72%
Merge            139    152   +  9%
Transpose:       160    256   + 60%
```
I think it's definitely worth to use sse2neon

**Comment by Stefan-Olt** [comment]
I could create a pull request if you like.

For those interested: See [here](https://github.com/Stefan-Olt/vapoursynth-mvtools) for my mvtools-version with NEON support. 8-Bit is about 4 times faster on Apple Silicon and 10-Bit still about 2 times faster. I used sse2neon and also took the NEON versions of those functions from x264, where the x86 versions had already been copied. At least for my test clips (real footage, not blank clips), the output was bit-identical. Would be happy if others would test it as well.

**Comment by myrsloik** [comment]
Only interested in proper arm intrinsics. I had a look at the sse2neon header and many shuffles and other instructions expand to 4+ intrinsics on arm. Do it properly or not at all is what I say.

**Comment by Stefan-Olt** [comment]
Sorry to hear that. Sure, well designed implementations of the functions with proper arm intrinsics would perform a lot better, but still the performance is more than doubled in many cases using sse2neon. sse2neon is also not somekind of experimental stuff, it's used in Blender, Intel & NVIDIA projects. If you look at the copyrights, developers from Amazon, Apple and NVIDIA made contributions.
Counting the number of intrinsics is also not the best measurement: Not all intrinsics perform equally (in the past when AMD Athlon started to support SSE, it was rather slow executing it). So 4 ARM intrinsics are not necessarily slower than one SSE intrinsic at the same clock speed (also I assume in this shuffle-case they are).  

And there may even be one advantage in using sse2neon: No additional assembly code to maintain. If you modify something in the SSE code, no worries about the NEON implementation now being incompatible.

**Comment by jan-wassenberg** [comment]
Hi @myrsloik , have you come across github.com/google/highway? This provides portable intrinsics. x86 can be fairly mechanically ported with zero runtime cost, and then it also works on NEON/WASM etc.
Disclosure: I am the main author of this library. Happy to discuss.

**Comment by myrsloik** [comment]
> Hi @myrsloik , have you come across github.com/google/highway? This provides portable intrinsics. x86 can be fairly mechanically ported with zero runtime cost, and then it also works on NEON/WASM etc.
> 
> Disclosure: I am the main author of this library. Happy to discuss.

No, never heard of it and I'm not even going to look at it.

Disclosure: I despise google employees and their mostly automated suggestions which mainly involve me adding a useless document/policy to my projects. Dealing with corporate BS costs extra.

**Comment by jan-wassenberg** [comment]
Thanks for your response, though I do not understand how "automated suggestions", "useless document/policy" and "corporate BS" relate to a suggestion to use an open-source library.

**Comment by myrsloik** [comment]
Probably obsolete. The future for most simple internal functions is probably auto vectorization.
