### ISSUE TITLE
[BUG] imwri.Write produces dark images

### ISSUE THREAD

**Issue by jkotra** [vapoursynth/vapoursynth#519]
Image with `imwri.Write`

![imwri](https://user-images.githubusercontent.com/29590316/70250867-9465db00-17a4-11ea-8131-2aad8cf91bfc.png)

Script:

```python

import vapoursynth as vs

core = vs.core

clip = core.ffms2.Source(source="E:\Encoding WS\Movie/main.mkv",threads=6)

clip = core.resize.Spline36(clip, format=vs.RGB24, matrix_in_s='709',transfer_in_s='709',primaries_in_s='709',
                            prefer_props=True)

print(core.text.CoreInfo(clip))

frames = [0, 68477]


for f in frames:
    print(f)
    clip.get_frame(f)
    clip = core.imwri.Write(clip, "PNG64", "source_compare_%d.png",overwrite=True)

```
This is the image taken from `VapourSynth Editor` with default settings:

![709-editor](https://user-images.githubusercontent.com/29590316/70251059-e0188480-17a4-11ea-8630-7f4ed3558cfd.png)

default settings in VS editor:
![Capture](https://user-images.githubusercontent.com/29590316/70251097-edce0a00-17a4-11ea-8267-82f197977968.PNG)

why is this difference?

I want them to be same, essential reproduce VS editor image with script.

**Comment by myrsloik** [comment]
What do you mean by default setting? you convert the image to rgb in the vs edit script, right?

**Comment by jkotra** [comment]
> 
> 
> What do you mean by default setting? you convert the image to rgb in the vs edit script, right?

no, i did not convert anything.

my vsedit script:
```py
import vapoursynth as vs
core = vs.get_core()


clip = core.ffms2.Source(source="E:\Encoding WS\Movie/main.mkv",threads=6)
clip.set_output()
```


In VSedit preview window, settings can be accessed by clicking cogwheel button.

![tempsnip](https://user-images.githubusercontent.com/29590316/70263144-b028ab80-17bb-11ea-8a54-cd67fbbe0eb6.png)

**Comment by myrsloik** [comment]
VSEdit will always invoke resize at the end to do a conversion to rgb with the default settings. 

`import vapoursynth as vs
core = vs.get_core()

clip = core.ffms2.Source(source="E:\Encoding WS\Movie/main.mkv",threads=6)
clip = core.resize.Spline36(clip, format=vs.RGB24, matrix_in_s='709',transfer_in_s='709',primaries_in_s='709',
                            prefer_props=True)
clip.set_output()
`

Try that script in VSEdit and see what happens.

**Comment by jkotra** [comment]
Okay.. I got the same result as the pic above(VSedit). The exact thing i want.

![compare vpy - 68477](https://user-images.githubusercontent.com/29590316/70270871-41ebe500-17cb-11ea-8fbc-ccf25e024991.png)

as you can see, i tried to replicate this very same script in my python code for automatic screenshot and i get worse screenshot comparing.

is it not a bug?

**Comment by age1988** [comment]
Why png64? Is that 16 bpc + alpha?
I think you should try png or png24 because you're converting to rgb24

**Comment by jkotra** [comment]
> 
> 
> Why png64? Is that 16 bpc + alpha?
> I think you should try png or png24 because you're converting to rgb24

I tried everything `PNG`, `png`, `PNG24` etc..

same result.

**Comment by motbob** [comment]
I looked into this issue myself and determined that it was a product of bad metadata.

Currently, I run a script on all imwri-exported images to strip metadata. Please try imagemagick with -strip and see if that fixes your problem. I believe the command is `magick infile -strip outfile`.

**Comment by jkotra** [comment]
@motbob , ah, finally someone see's it. i will try it out.

**Comment by dubhater** [comment]
Funny, the two images in the first post look identical in Firefox. In Chromium I can see that the first one is darker.
