### ISSUE TITLE
Correct _ChromaLocation value for PAL DV?

### ISSUE THREAD

**Issue by tvasenin** [vapoursynth/vapoursynth#520]
In PAL DV, Cr and Cb have different positions, so it's not clear what **_ChromaLocation** value should be used.

Also, it should probably be different for even/all frames after **SeparateFields()** (that should probably also be applied to DVD Video?).

Nice reference: http://www.mir.com/DMG/chroma.html

**Comment by sekrit-twc** [comment]
It is not supported. You have to separate the planes into three clips and process them separately using the subpixel scaling paramteters.

**Comment by sekrit-twc** [comment]
@tvasenin 

Do you have an example of PAL DV? If you also have an example of correct resampling for PAL DV, that would help.

**Comment by tvasenin** [comment]
PAL DV example (download link is valid for 14 days):
https://www.mediafire.com/file/ue5o7mp7bn2bhdj/PAL-DV-sample.avi/file

I don't know what the correct resampling result should be.
Maybe look at the Cedocida DV Codec source?
http://www.cithraidt.de/cedocida/index.html

**Comment by sekrit-twc** [comment]
Finally had time to look at this. _ChromaLocation is BOTTOM for Cb and TOP for Cr. Have to scale the image twice with current code:

    c = mypaldv
    a = core.std.Bicubic(c, chroma_loc_in="bottom", ...)
    b = core.std.Bicubic(c, chroma_loc_in="top", ...)
    c = core.std.ShufflePlanes([a,b], [0,0,1], vs.YUV)
