### ISSUE TITLE
Memory leak when using std.Expr

### ISSUE THREAD

**Issue by MonoS** [vapoursynth/vapoursynth#522]
Vapoursynth R48 start leaking memory and pegging a core when executing this simple script

```
import vapoursynth as vs

core = vs.get_core()

clip1 = core.std.BlankClip(length=24, format=vs.YUV444P16)
clip2 = core.std.BlankClip(length=24, format=vs.YUV444P16)

leak = core.std.Expr(clips=[clip1,clip2], expr="x y / y x / min")

leak.set_output()
```

**Comment by sekrit-twc** [comment]
Can you try again with the latest master?

**Comment by MonoS** [comment]
Hi, i'm having some problem compiling VS from master (due to my environment), could you, if it's not a burden of course, compile it and share the updated dll for me?

**Comment by myrsloik** [comment]
Don't forget to replace the copy in the python dir as well.

[VapourSynth.zip](https://github.com/vapoursynth/vapoursynth/files/4093788/VapourSynth.zip)

**Comment by MonoS** [comment]
Thanks @myrsloik, i've tested it and it's working fine now, just i did not found any dll in the python dir.
