### ISSUE TITLE
Missing file for installation since R46

### ISSUE THREAD

**Issue by MonoS** [vapoursynth/vapoursynth#523]
When installing since R46, but debugged on R48, a missing file in folder Python37\Lib\site-packages makes VS fails to load with the message
`Failed to initialize VapourSynth environment`
Downloading the portable package and moving the file `vapoursynth.cp37-win_amd64.pyd` to the site-packages folder fixes the problem.

This problem was found on a Win10 64bit system with python installed inside the Program Files folder (full path `C:\Program Files\Python37` ).

More information may be found [here](https://forum.doom9.org/showthread.php?p=1891153#post1891153).

**Comment by myrsloik** [comment]
For some reason the package install fails. Does "pip install vapoursynth" work as expected? (uses the same package)

**Comment by fuchanghao** [comment]
why not install the python form the Microsoft store?

https://www.microsoft.com/en-us/p/python-37/9nj46sx7x90p

**Comment by MonoS** [comment]
@myrsloik: i don't install pip alongside python, just the runtime as i don't use anything else, i could try to reinstall python, but i'm doing some long encode and it will take me some days to test it.

@fuchanghao: because i uninstall and block such a malware on my pc.

**Comment by myrsloik** [comment]
> why not install the python form the Microsoft store?
> 
> https://www.microsoft.com/en-us/p/python-37/9nj46sx7x90p

MS Store python is broken for embedded use.

**Comment by myrsloik** [comment]
> @myrsloik: i don't install pip alongside python, just the runtime as i don't use anything else, i could try to reinstall python, but i'm doing some long encode and it will take me some days to test it.
> 
> @fuchanghao: because i uninstall and block such a malware on my pc.

It's no problem if it takes a bit of time. You did install python for all users, right?

**Comment by MonoS** [comment]
@myrsloik: yes, or else it would have been installed in the appdata directory, i'll reinstall it making sure to select the "for all users" option.

**Comment by myrsloik** [comment]
You need pip to or the VS installer won't work. The python module is installed as a proper package with:
`python.exe -m pip install "{app}\python\<packagename>"`

**Comment by myrsloik** [comment]
Probably user error due to an exotic configuration
