### ISSUE TITLE
R48 RegCreateKeyEx failed code 5

### ISSUE THREAD

**Issue by metr0jw** [vapoursynth/vapoursynth#524]
An error occurs when trying to install for me only on R48(Windows).

Select action

Error creating registry key:
HKEY_CLASSES_ROOT\Environment
RegCreateKeyEx failed; code 5.
Access denied.

The problem can be solved by running the installer as admin.

Install for all users requires admin, but install for me does not require admin when trying to install.
So, it seems to be appropriate to change it to require admin privileges.

**Comment by myrsloik** [comment]
Is it the 32 bit or 64 bit installer?

**Comment by metr0jw** [comment]
> Is it the 32 bit or 64 bit installer?

64bit installer.
And I also installed python 3.7.6 for me only.

**Comment by myrsloik** [comment]
Sigh, appears the "add X to path" options are simply broken for single user installs. Will be fixed/disabled in the next version.

**Comment by myrsloik** [comment]
Fixed in R49
