### ISSUE TITLE
Wondering if it's possible to attach some user defined information to VideoNode or VideoFrame?

### ISSUE THREAD

**Issue by RedmondLee** [vapoursynth/vapoursynth#525]
Hi,
I would like to let my video carry some extra information from the original source , such as the overall bitrate of source ,etc. (for whom I can get via python) ,so that I can access those information during processing if needed.
It's not important those information is attached to a VideoNode object or to the VideoFrame objects.
Is there any possible method?

Big thanks!

**Comment by myrsloik** [comment]
If that's the kind of stuff you want to know I'd suggest using ffprobe which can output a lot of file metadata in different formats that are easy to parse in python. You can run it directly by using the subprocess module.

**Comment by RedmondLee** [comment]
Thanks for reply , 
since to do some interprocess comunicating / synchronizing stuff it's pretty annoying ,between using subprocess ,I'd rather lean towards generating those metadata into a disk file ,then attach them to vs object, thus they can affact my video processing. I can't figure out a practical solution ,need help.

**Comment by RedmondLee** [comment]
Thanks , this problem has been resolved. I've found out std.ModifyFrame could implement my requirement ,which allows me to modify vs.VideoFrame.props object.
By the way ,if there's any method let me modify vs.VideoNode object ? such as vs.videonode.format?

**Comment by myrsloik** [comment]
No, there's no way to attach values to a VideoNode. Format is obviously only changable by video filters. You can however cheat and simply stuff properties into frame 0 or attach them to every frame (it's fairly cheap to do).
