### ISSUE TITLE
windows installer finally no response in R45 and Installation failed in R48

### ISSUE THREAD

**Issue by rainchery** [vapoursynth/vapoursynth#527]
windows10 1909

-  setup- Vapoursyth R45

 installing please wait while Setup installs Vapoursynth R45 on your computer
Finishing installation...

window no response  long time....

`vsrepo.py install havsfunc`

'NoneType' object is not iterable

Python 3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 00:42:30) [MSC v.1916 64 bit (AMD64)] on win32
```
from vapoursynth import core
print(core.version())
```
VapourSynth Video Processing Library
Copyright (c) 2012-2018 Fredrik Mellbin
Core R45
API R3.5
Options: -

**Comment by rainchery** [comment]
setup- Vapoursyth R45

installing please wait while Setup installs Vapoursynth R45 on your computer
Finishing installation...

window no response long time...
Installation failed

```
from vapoursynth import core
print(core.version())
```invalid

**Comment by rainchery** [comment]
setup Vapoursyth R44 success

**Comment by myrsloik** [comment]
Does R49-RC1 work for you? There are some installer fixes in it.
