### ISSUE TITLE
Banding when upscaling chroma for 444 with resize

### ISSUE THREAD

**Issue by LightArrowsEXE** [vapoursynth/vapoursynth#528]
Sometimes when scaling the chroma planes using `resize` heavy banding will be produced where there was previously none or very little. ~~`fmtc.resample` does not produce this issue.~~ I am running VapourSynth R48.

Code:
```py
planes = vsutil.split(src)
planes[0] = core.descale.Debicubic(planes[0], get_w(h), h, b, c)
planes[1], planes[2] = [core.resize.Bicubic(p, planes[0].width, planes[0].height, src_left=.25) for p in planes[1:]]
scaled = vsutil.join(planes)
```
This issue can also be reproduced by simply using `vs.YUV444P16` in `resize`, so it does not appear to be a dithering issues with `fvf.Depth` either. The issue persists regardless of scaler used.

420 descaled clip
![](https://files.catbox.moe/xn1wex.png)
![](https://files.catbox.moe/zst13r.png)

444
![](https://files.catbox.moe/iibbav.png)
![](https://files.catbox.moe/80nwwp.png)

What makes this even more confusing is that there's very little chroma information at all, since this clip is mostly greyscaled, with very few colors.

![](https://files.catbox.moe/5mh6ep.png)

The luma itself has nowhere close to the amount of banding we can see on the 444 clips (which makes sense, because else we'd see it on the 420 frames too).

~~As previously mentioned, this issue does not appear when using `fmtc.resample`.~~ My bad, forgot to remove `/2`'s. This also happens when using fmtc.resample.

[Here](https://drive.google.com/open?id=18Z4lvT4KHBobyY91k_qfTzoD0TLNe6ei) is a link to the clip in question

**Comment by LightArrowsEXE** [comment]
After additional testing, it appears the issue was created through something other than `resize`. Simply setting the output node to `scaled` seems to somehow work this time around. Closing for now. Will reopen if I notice the issue still being something `resize` plays a part in, otherwise it should be alright.

**Comment by dubhater** [comment]
So where does the banding come from?

**Comment by LightArrowsEXE** [comment]
During the conversion process in `lvf.compare`, which I've since fixed [here](https://github.com/Irrational-Encoding-Wizardry/lvsfunc/commit/e3ed24e0aa5fba3e5be190121ea04326f66dbe1b). The clips given to it get resampled to RGB24, and the banding was introduced during that specific action. Probably just rounding errors due to it being dithered down to 8bit and changed to RGB at the same time or something.
