### ISSUE TITLE
Need force flush stdout/stderr in python script

### ISSUE THREAD

**Issue by elxy** [vapoursynth/vapoursynth#530]
Hello there. In python script, if flush=False in print(), the shell could not catch stdout/stderr output.

Sample code:

```python
import os
import sys

from vapoursynth import core

clip = core.ffms2.Source(source=os.path.expanduser("input.mp4"))

print('flushed stdout', file=sys.stdout, flush=True)
print('flushed stderr', file=sys.stderr, flush=True)
print('no flush stdout', file=sys.stdout)
print('no flush stderr', file=sys.stderr)

clip.set_output()
```

Shell command:

```bash
vspipe test.py /dev/null 1>stdout 2>stderr
```

The content of stdout:

```
flushed stdout
```

And the content of stderr:

```
flushed stderr
Output 152 frames in 0.50 seconds (305.17 fps)
```

The expected output `no flush stdout` & `no flush stderr` is lost.

**Comment by myrsloik** [comment]
Sounds more like a python quirk to me. The functions you use aren't implemented/modified by vapoursynth at all.

**Comment by elxy** [comment]
> 
> 
> Sounds more like a python quirk to me. The functions you use aren't implemented/modified by vapoursynth at all.

But the code bellowing works properly:

```python
import sys

print('flushed stdout', file=sys.stdout, flush=True)
print('flushed stderr', file=sys.stderr, flush=True)
print('no flush stdout', file=sys.stdout)
print('no flush stderr', file=sys.stderr)
```

**Comment by HolyWu** [comment]
> vspipe test.py /dev/null 1>stdout 2>stderr
> 
> The expected output `no flush stdout` & `no flush stderr` is lost.

The strange thing is that if you don't use output redirection, i.e. simply `vspipe test.py /dev/null`, then the `no flush` lines do appear in the console.

**Comment by elxy** [comment]
> 
> The strange thing is that if you don't use output redirection, i.e. simply `vspipe test.py /dev/null`, then the `no flush` lines do appear in the console.

And the caller couldn't catch the output of subprocess. Really strange.
