### ISSUE TITLE
Add support for importing image with icc profile?

### ISSUE THREAD

**Issue by gundamftw** [vapoursynth/vapoursynth#533]
I have tiff images that have the "Adobe RGB 1998" color profile embedded, when importing to vs, the program discarded the profile, resulting in wrong color. So I'm requesting a feature in the imwri filter to be able to read the profile and convert it to RGBS to display them correctly.

**Comment by YomikoR** [comment]
I'm trying to import some elementary features of Little CMS to VS, see [this repo](https://github.com/YomikoR/VapourSynth-ICCConvert). I wish to add support for reading embedded profiles in the future. Anyway, you are very welcomed to have a try.

**Comment by YomikoR** [comment]
Some thoughts about your case:
1) I don't think there's a default behavior for color profile conversion, unless automatically towards the profile of the current monitor, which iccc is now trying to present. However, detection of the monitor is platform specific with unwelcome third-party dependencies, which suggests it might never be a part of VS.

2) ImageMagick uses Little CMS too, which is known to be slow for float types.

3) Currently the best option for your case might be getting an Adobe RGB profile (e.g. by downloading from an official source or by manual extraction using ImageMagick), loading images using imwri in a bit-exact manner (except JPEG, which may be converted to RGBS), converting to RGB48, and calling iccc for color profile conversion.

4) Let's see what we can do to use ImageMagick as a profile loader.

**Comment by pdr0github** [comment]
A workaround is to use fmtc to convert between adobeRGB <=> sRGB (or others like ProPhoto/romm). 

(But there is an issue with fmtc r24, it worked ok in r22)
https://forum.doom9.org/showthread.php?p=1951340#post1951340

**Comment by myrsloik** [comment]
Both BestSource and imwri attaches icc profiles that can be applied. BestSource also turns the icc profile into normal matrix/transfer/primaries properties when possible.
