### ISSUE TITLE
[Question] Manipulating frames without creating plugin/registering functions

### ISSUE THREAD

**Issue by mantielero** [vapoursynth/vapoursynth#534]
If I understand properly, a plugin is a mean to register functions so that they can be invoked by means of `invoke`.

I would like to have a function acting as a filter so that it receives a VSMap pointer and returns a new one, performing the frame manipulation inside. Is that posible?

How could I do that?

**Comment by mantielero** [comment]
# A bit more clarification
## My understanding about how a function is made available
Just to clarify a bit more my doubt. Looking to how a function is implemented. The function [Crop](https://github.com/vapoursynth/vapoursynth/blob/master/src/core/simplefilters.c#L134), is [registered](https://github.com/vapoursynth/vapoursynth/blob/master/src/core/simplefilters.c#L2524). In the registration, it is referred the [creation function](https://github.com/vapoursynth/vapoursynth/blob/master/src/core/simplefilters.c#L260), which creates the filter (refering to [init](https://github.com/vapoursynth/vapoursynth/blob/master/src/core/simplefilters.c#L145), [getFrame](https://github.com/vapoursynth/vapoursynth/blob/master/src/core/simplefilters.c#L183) and singleClipFree). This way the functions are available in the "std" plugin so that we are able to invoke those functions available in the plugin.

## My use case
What I am doing is creating a function where:
- inputs: a VSMap which contains the input node. All the parameteres required by the function that I am calling.
- output: a VSMap with the output node.
Within that function I am invoking the function from the plugin. So I am converting the function parameters into a VSMap which I use with [invoke](http://www.vapoursynth.com/doc/api/vapoursynth.h.html#invoke).
Then I can use the function to perform my processing.

I would like to do the same, but without using a registered function. How can I do that? The bit that I think I am missing is how I can I create the output node. In the [creation phase](https://github.com/vapoursynth/vapoursynth/blob/master/src/core/simplefilters.c#L260), the output node comes as an input, but I don't know how it is created.

**Comment by stuxcrystal** [comment]
Ok.

As far as I see there are two possible ways to do this:

1. The canonical answer, as far as I can see from the VapourSynth-API: Use `createFunc`, then `callFunc` and `freeFunc` to free your private function. Inside the callback of `createFunc` you can easily use `createFilter`.
2. [Use with caution] Create two maps (in and out) using `createMap`, pass them to `createFilter` directly. Your new node will be attached to the `out`-map under the key `"clip"`.

**Comment by mantielero** [comment]
Is there an example somewhere?

Looking at `createFunc` signature, the first parameter is a function with the signature:
```c
typedef void (VS_CC *VSPublicFunction)(const VSMap *in, VSMap *out, void *userData, VSCore *core, const VSAPI *vsapi)
                                                        ^^^^^^^^^^
```
Regarding `out`, I know how to create a VSmap and I know how to add a node with the key "clip". But how do I create the node itself. I don't see a `createNode` or something like that.

**Comment by sekrit-twc** [comment]
This actually happens when invoking `createFilter`.

    void (VS_CC *createFilter)(const VSMap *in, VSMap *out, const char *name, VSFilterInit init, VSFilterGetFrame getFrame, VSFilterFree free, int filterMode, int flags, void *instanceData, VSCore *core) VS_NOEXCEPT;

`createFilter` creates a new `VSNodeRef` object backed by the provided function pointers, then invokes the `init` function, which is responsible for setting the `VSVideoInfo` for the new node.

**Comment by mantielero** [comment]
Thanks.
Another question that I have (this is a C question) is with the following lines in the `createFilter`:
```c
// I usually keep the filter data struct on the stack and don't allocate it
// until all the input validation is done.
data = malloc(sizeof(d));
*data = d;
```
Why it is copying the `d` content into `data`, instead of using a pointer to `d` in the `createFilter` function?

**Comment by myrsloik** [comment]
Pay attention and you see that d is allocated on the stack. It goes out of scope and disappears so you need to pass something with a suitable lifetime.

**Comment by mantielero** [comment]
Understood. 
Now I am facing another problem. I have a function named `cropAbsCreate1` which calls the `createFilter` function. During execution, it is complaining with the message:
```bash
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```
I have checked that the initialization `cropInit1` is done successfully. 

Where should I look at? GetFrame?

> Note: I am trying to work in a different programming language.

**Comment by myrsloik** [comment]
Which language? And post all your code.

**Comment by mantielero** [comment]
I am doing a wrapper in Nim [here](https://github.com/mantielero/VapourSynth.nim).

 I will update it with the part that is failing in a few minutes.

**Comment by mantielero** [comment]
What I am trying to do is in [function.nim](https://github.com/mantielero/VapourSynth.nim/blob/master/test/function.nim). 

In Nim comments start with `#` or are contained between `#[` and `]#`. I added `c` code just for reference.

So far it compiles. In order to explain it a bit:
1. The [executable part](https://github.com/mantielero/VapourSynth.nim/blob/master/test/function.nim#L354-L365), aims to create a private function. Uses the `Source` function from the plugin `ffms2`. Then calls the private function in order to store the video as `.y4m` file.
2. [cropAbsCreate1](https://github.com/mantielero/VapourSynth.nim/blob/master/test/function.nim#L278-L335): for the filter creation.
3. [cropInit](https://github.com/mantielero/VapourSynth.nim/blob/master/test/function.nim#L69-L107): this function prints `[INFO] Initialization done` (the last line), so I think is working fine. Besides, I am able to see `userData` content.

Then, I am a bit lost.

**Comment by mantielero** [comment]
Something that would simplify a lot my problem is, if somehow I could edit the incoming clip.

I have checked that if a have a VSMap with a clip as an input and I return a new VSMap as an output with the same node in the output VSMap I get a passthrough filter.

Can I modify the original? Or could I copy the old node into a new node and modify? Or copy the frames and modify them (I don't know how to relate them to the new node)?

The following Nim code shows  what I am aiming for. It compiles and it works. Well, it works but not as expected (right now it is simply a pass-through):
```nim
import ../src/vapoursynth
import options

proc Simple*(vsmap:ptr VSMap; planes=none(seq[int])):ptr VSMap =
    let tmpSeq = vsmap.toSeq    # Convert the VSMap into a sequence
    if tmpSeq.len == 0:
      raise newException(ValueError, "the vsmap should contain at least one item")
    if tmpSeq[0].nodes.len != 1:
      raise newException(ValueError, "the vsmap should contain one node")
    var clip = tmpSeq[0].nodes[0] # This is a node
    #var newclip = API.cloneNodeRef(clip)
    #API.freeNode(clip)

    #------------------
    let vinfo = getVideoInfo(clip)
    for i in 0..<vinfo.numFrames:
        #strm.writeLine("FRAME")
        let frame = clip.getFrame(i)
        let format = frame.getFrameFormat.toFormat
        for i in 0..<format.numPlanes:
          let plane = frame.getPlane(i)
          let address = frame.getWritePtr(i)
          let width = plane.width
          let height = plane.height
          #let size = width * height  
          for row in 0..<height:
            let newaddress = cast[pointer](cast[int](address) + row*plane.stride)
            for j in 0..10:
               let tmp = cast[int](newaddress) + j
               let address:ptr uint8 = cast[ptr uint8](tmp)
               address[] = 255.uint8
               echo repr address, " ", address[]
            #strm.writeData(address, plane.width)          
    # Convert the function parameters into a VSMap (taking into account that some of them might be optional)
    #if planes.isSome: args.set("planes", planes.get)
    var outclip = createMap()
    outclip.append("clip", clip)
    return outclip

#-------------------------------------------------
# Reads the file, applies the Simple filter and saves the result in a file
Source("2sec.mkv").Simple.Savey4m("deleteme.y4m")
``` 
Why the output clip does not get modified if I am modifying the frame?

**Comment by mantielero** [comment]
I have been checking, and the problem is that, when I call `callFunc`, the parameter `out` remains empty, so the later `Savey4m` fails.
```nim
API.callFunc(myfunc, `in`, `out`, CORE, API)
`out`.Savey4m("borrame.y4m")
```
> Above is Nim code. The words `in` and `out` are keywords in nim, that's why they are backquoted.

Why `callFunc` returns an empty pointer in `out`?

The way in which I am using `callFunc` is as follows:
```nim
# Read the video file
let `in` = Source("2sec.mkv")  
# Create the function; and store the pointer in `myfunc`
let myfunc:ptr VSFuncRef = API.createFunc( cropAbsCreate1, 
                                           cast[pointer](nil), 
                                           cropFree, 
                                           CORE, 
                                           API) 
# IMPORTANT:
# I define here `out` as a VSMap pointer. If not, `callFunc` will failed because `out` is undefined
var `out`:ptr VSMap 
API.callFunc(myfunc, `in`, `out`, CORE, API)

# Save the result in a file
`out`.Savey4m("deleteme.y4m")
```

**Comment by mantielero** [comment]
Once `callFunc` is called, `cropAbsCreate1` is called. Once inside, it reaches `createFilter`. It is strange because it manages to successfully call `cropInit1` and finishes. Then it fails (still in `createFilter` call). So it is something deep inside vapoursynth. I think it might have to do with `out` being `nil`, but from the documentation it is `createFilter` the one that creates the `out` pointer.

Looking at [vapoursynth's code](https://github.com/vapoursynth/vapoursynth/blob/master/src/core/vscore.cpp#L1468-L1480):
```cc
void VSCore::createFilter(const VSMap *in, VSMap *out, const std::string &name, VSFilterInit init, VSFilterGetFrame getFrame, VSFilterFree free, VSFilterMode filterMode, int flags, void *instanceData, int apiMajor) {
    try {
        PVideoNode node(std::make_shared<VSNode>(in, out, name, init, getFrame, free, filterMode, flags, instanceData, apiMajor, this));
        for (size_t i = 0; i < node->getNumOutputs(); i++) {
            // fixme, not that elegant but saves more variant poking code
            VSNodeRef *ref = new VSNodeRef(node, static_cast<int>(i));
            vs_internal_vsapi.propSetNode(out, "clip", ref, paAppend);
            delete ref;
        }
    } catch (VSException &e) {
        vs_internal_vsapi.setError(out, e.what());
    }
}
```
I don't really understand what the first line after `try` does. C++ is quite cryptic to me. I guess a node is created there. Then for each output, a new VSNodeRef is created an appended to the "clip" key.

I am lost.

**Comment by DJATOM** [comment]
PVideoNode node() is the another way (btw, that's C++ way) of declaring variable. Code inside () is just value, assigned to variable. Or that's how I read it.

**Comment by mantielero** [comment]
Is that function expecting `out` to be initialized somehow?

When I run the executable this is all that I am [echoing to stdout](https://github.com/mantielero/VapourSynth.nim/blob/master/test/function.nim#L239-L254) where you can see the content of the parameters used with `createFilter`:
```
[jose@mountain test]$ ./function 
[INFO] Function created by calling 'createFunc'
[INFO] `in` created
[INFO] Calling 'callFunc'
[INFO] Starting 'cropAbsCreate1'
===== WHICH ONE IS nil =====
IN:
ptr 0x55ef25035f40 --> []

OUT:
nil

cropInit1:
0x55ef23605c80

cropGetFrame1:
0x55ef23605f1e

cropFree1:
0x55ef23605db1

data1
ptr 0x7f9ec8415048 --> [node = ptr 0x55ef250ab3a0 --> [],
vi = ptr 0x55ef25037a10 --> [format = ptr 0x55ef24fa8240 --> [name = ['Y', 'U', 'V', '4', '2', '0', 'P', '8', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0'],
id = 3000010,
colorFamily = 3000000,
sampleType = 0,
bitsPerSample = 8,
bytesPerSample = 1,
subSamplingW = 1,
subSamplingH = 1,
numPlanes = 3],
fpsNum = 24,
fpsDen = 1,
width = 854,
height = 480,
numFrames = 100,
flags = 4],
x = 10,
y = 20,
width = 300,
height = 200]

core
ptr 0x55ef24fa7ca0 --> []

===========================
[INFO] 'cropAbsCreate1' > calling 'createFilter' (fails after calling 'cropInit1')
[INFO] 'cropAbsCreate1'>'createFilter':'cropInit1': starting
[INFO] 'cropAbsCreate1'>'createFilter'>'cropInit1': DONE
Traceback (most recent call last)
/home/jose/src/VapourSynth.nim/test/function.nim(297) function
/home/jose/src/VapourSynth.nim/test/function.nim(261) cropAbsCreate1
SIGSEGV: Illegal storage access. (Attempt to read from nil?)

```

**Comment by Kamekameha** [comment]
Yes, the `out` parameter of both `createFilter()` and `callFunc()` may not be null.  No instance of `VSMap` should be null at all, for that matter.

**Comment by mantielero** [comment]
I have uncommented [this line](https://github.com/mantielero/VapourSynth.nim/blob/master/test/function.nim#L237), in order to have an empty VSMap. But despite, now it is not empty:
```
[jose@mountain test]$ ./function 
[INFO] Function created by calling 'createFunc'
[INFO] `in` created
[INFO] Calling 'callFunc'
[INFO] Starting 'cropAbsCreate1'
===== WHICH ONE IS nil =====
IN:
ptr 0x5610a198df40 --> []

OUT:
ptr 0x5610a1999360 --> []
...
```
it fails exactly the same.

On the other hand, if I look to [simplefilters.c](https://github.com/vapoursynth/vapoursynth/blob/aa075b009fd4bdbf6aad7b4784092e79eb2f680c/src/core/simplefilters.c#L230-L258), it doesn't creates `out` inside that function. So it must be created beforehand, but where/when?

**Comment by Kamekameha** [comment]
Because those on `simplefilters.c` are called through the plugin api, that is, with `invoke()`, which creates the output `VSMap` beforehand.  As far as I can see, you're not consuming such api and if anything, you mentioned you wanted to bypass it to begin with.

In any case, like I said, no function expects a null `VSMap` in the api.

**Comment by mantielero** [comment]
Is there anywhere a minimal working example in C using `callfunc`?

**Comment by Kamekameha** [comment]
Not entirely C, but here nonetheless,  https://github.com/vapoursynth/vapoursynth/blob/83c63ad716112ddc4977de8be91100b6fd13f375/src/cython/vapoursynth.pyx#L306-L335

The definition of `Func.__call__()` in particular.

**Comment by mantielero** [comment]
First, thanks all of you for your support.

I think I am doing pretty much the same:
```nim
let myfunc:ptr VSFuncRef = API.createFunc( cropAbsCreate1, 
                                           cast[pointer](nil), #cast[pointer](unsafeAddr(a)), #
                                           cropFree, 
                                           CORE, 
                                           API) 
      
echo "[INFO] Function created by calling 'createFunc'"
# Apply "myfunc" to `in`
let `in` = Source("2sec.mkv")
echo "[INFO] `in` created"
var `out`:ptr VSMap  # `out` is declared, but contains 

echo "[INFO] Calling 'callFunc'"
`out` =createMap() 
API.callFunc(myfunc, `in`, `out`, CORE, API)

echo repr `out`
# Save the result in a file
`out`.Savey4m("deleteme.y4m")
```
I know that `Source` and `Savey4m` work.  And I am creating an empty map before I call `callFunc`.

Still I am getting that nasty error.

**Comment by mantielero** [comment]
I have changed the following line (the documentation and the .pyx example say that they should be NULL):
```nim
API.callFunc(myfunc, `in`, `out`, nil, nil)
```
Still not working.

> Why is the API asking for two parameters that need to be NULL?

**Comment by Kamekameha** [comment]
I don't know how exactly your application works but if you're the client of that crop function you don't need the `VSFuncRef` api at all, just call your function directly.  The point of that api is pretty much for *vapoursynth* to consume or pass around the function, not the client code.

I did notice, though, that your [cropFree()](https://github.com/mantielero/VapourSynth.nim/blob/02d6c5cd102d90dcf904d6bc948bae76241f9dc9/test/function.nim#L268-L273) is expecting and trying to free a `CropData` pointer when in reality it's a nil [`userData`](https://github.com/mantielero/VapourSynth.nim/blob/02d6c5cd102d90dcf904d6bc948bae76241f9dc9/test/function.nim#L279-L283), so maybe that's where you might be getting those segfaults.  If no `userData` is provided in `createFunc()` then there's likely no need to provide for a `free` function.

> Why is the API asking for two parameters that need to be NULL?

Deprecated, I guess.  They're stored in `VSFuncRef` by `createFunc()`.

**Comment by mantielero** [comment]
In fact, I would like to avoid the whole API. My desire would be to do what I explained in [this comment above](https://github.com/vapoursynth/vapoursynth/issues/534#issuecomment-600336510). But I don't know how to create node from scratch. There is no `createNode` in the same way there is a `createMap`.

I will try to look the free functions tomorrow. 

Thanks a lot for your help.

**Comment by Kamekameha** [comment]
Well, for that you only need `createFilter()`, as mentioned in https://github.com/vapoursynth/vapoursynth/issues/534#issuecomment-599735780.

**Comment by mantielero** [comment]
I have created a new [simple.nim](https://github.com/mantielero/VapourSynth.nim/blob/c56c8185037221bdc0cd7eccb2a38107a472e564/test/simple.nim) file. I have the same problem as before. It fails in the same [createFilter](https://github.com/mantielero/VapourSynth.nim/blob/c56c8185037221bdc0cd7eccb2a38107a472e564/test/simple.nim#L135-L143) call.

[These lines](https://github.com/mantielero/VapourSynth.nim/blob/c56c8185037221bdc0cd7eccb2a38107a472e564/test/simple.nim#L118-L132) print the following:
```
===== WHICH ONE IS nil =====
IN:
ptr 0x561706bb1cb0 --> []

OUT:
ptr 0x561706c3af80 --> []

cropInit1:
0x56170620587e

cropGetFrame1:
0x561706205ad5

cropFree1:
0x561706206342

data1
ptr 0x7fdaa9aeb048 --> [node = ptr 0x561706c3db20 --> [],
vi = ptr 0x561706bb9390 --> [format = ptr 0x561706baa240 --> [name = ['Y', 'U', 'V', '4', '2', '0', 'P', '8', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0'],
id = 3000010,
colorFamily = 3000000,
sampleType = 0,
bitsPerSample = 8,
bytesPerSample = 1,
subSamplingW = 1,
subSamplingH = 1,
numPlanes = 3],
fpsNum = 24,
fpsDen = 1,
width = 854,
height = 480,
numFrames = 100,
flags = 4],
x = 10,
y = 20,
width = 300,
height = 200]

core
ptr 0x561706ba9ca0 --> []
```
What could I do in order to find out which one is creating the problem?

**Comment by Kamekameha** [comment]
Parameters `init` and `getFrame` may not be null for [`createFilter()`](https://github.com/mantielero/VapourSynth.nim/blob/c56c8185037221bdc0cd7eccb2a38107a472e564/test/simple.nim#L135-L143).  `free` can but in your case `instanceData` needs to be dealt with.

Whatever the code's doing after the `createFilter()` call isn't affecting the filter chain in any way.

Also, `outnode` is declared but never defined so I assume appending it to [`outclip`](https://github.com/mantielero/VapourSynth.nim/blob/c56c8185037221bdc0cd7eccb2a38107a472e564/test/simple.nim#L173) is bound to fail;  in any case, your output clip actually resides in the `tmpout` map, it's set in by `createFilter()`, so that's what the function should be returning, not `outclip`.

**Comment by mantielero** [comment]
I removed the nils in [createFilter](https://github.com/mantielero/VapourSynth.nim/blob/8da28735e9606003c4dd10b6b1cb99898b49d870/test/simple.nim#L137-L139).

Yeah, I haven't looked into whatever happens after `createFilter`. I just want to see [this line](https://github.com/mantielero/VapourSynth.nim/blob/8da28735e9606003c4dd10b6b1cb99898b49d870/test/simple.nim#L144) printed in the console.
I commented the [outnode](https://github.com/mantielero/VapourSynth.nim/blob/8da28735e9606003c4dd10b6b1cb99898b49d870/test/simple.nim#L94). And I am returning [tmpout](https://github.com/mantielero/VapourSynth.nim/blob/8da28735e9606003c4dd10b6b1cb99898b49d870/test/simple.nim#L174).

Still no luck after all this:
```
[INFO] 'createFilter': starting
[INFO] 'createFilter':'cropInit1': starting
[INFO] 'createFilter'>'cropInit1': DONE
Traceback (most recent call last)
/home/jose/src/VapourSynth.nim/test/simple.nim(178) simple
/home/jose/src/VapourSynth.nim/test/simple.nim(135) Simple
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

**Comment by Kamekameha** [comment]
I have no clue then.  All parameters seem valid at a glance, although I have exactly zero knowledge of Nim.

**Comment by mantielero** [comment]
I managed to fixed the issue. It looks like I had not some functions signatures wrong. 

I don't have a working filter yet, but at least it looks like I managed to fulfill the objective set in the title. 

I can only thank you all for your patience.
