### ISSUE TITLE
conflict with powershall commands on Windows

### ISSUE THREAD

**Issue by legends-killer** [vapoursynth/vapoursynth#536]
I use the vspipe and x256 encoder to rip a moive in windows powershall, but it consumes a great number of memorys(almost 16 gigs) on my computer, though I restrict the memory cost at 4gigs. At the same time, there's no any output files at my rip folder.
And when I siwtch to windows cmd, the problem has gone and it works normally.
I guess it output all files into powershall instead the directory I assigned.
Is it a bug?
![image](https://user-images.githubusercontent.com/47050572/76772706-51bc9180-67dc-11ea-950d-6918f989e093.png)
![image](https://user-images.githubusercontent.com/47050572/76772758-6567f800-67dc-11ea-9e93-b19363a05577.png)

**Comment by sekrit-twc** [comment]
PowerShell use an "object-based" pipe system. This means that it fully buffers the output, converts it to unicode, and attempts to parse .NET objects from it. vspipe is a binary output program, so it is not compatible with PowerShell. You can invoke cmd.exe from powershell.exe if you need to use VapourSynth in a PowerShell script.

**Comment by legends-killer** [comment]
thx a lot, I got it.
