### ISSUE TITLE
VSPipe.exe randomly fails fwrite() calls when outputting video frames to stdout

### ISSUE THREAD

**Issue by tnatiuk17piano** [vapoursynth/vapoursynth#542]
Hello,

I use VapourSynth in combination with StaxRip to encode videos in H.265 format. I recently started using VSPipe instead of AVSPipe because it appears to be much faster.

However, as I've been encoding, I've randomly seen the program output the following error message: "Error: fwrite() call failed when writing frame: 6965, plane: 0, errno: 32". It has happened at anytime in the process of outputting frames, from something as low as 300 to something as high as 11000. I presume it is not because of any software I have installed, as I have Python 3.7.7 installed and VapourSynth R48 installed. These have worked before with no problems. This has led me to believe there is something physically wrong with my system. I'll post my computer specs below. Also, an important note, VSPipe will use roughly 5GB of my memory when running, since my script has a max cache size set to 8192 MB. The .vpy script is attached (renamed to .txt so it can be uploaded). My command line script is as follows:
`"C:\Program Files\VapourSynth\core\vspipe.exe" "F:\Video Script.vpy" --y4m -`
which is then piped to StaxRip for encoding.
[Video Script.txt](https://github.com/vapoursynth/vapoursynth/files/4366700/Video.Script.txt)

- AMD Ryzen 9 3900X 3.8GHz (not OCed) 12/Core 70MB Cache 105W Processor
- GeForce RTX 2070 SUPER 8GB GDDR6
- 16 GB (2x8GB) DDR4/3000MHz Dual-Channel Memory (ADATA XPG 71)
- ASUS PRIME X570-P ATX Motherboard
- 1200W Power Supply

Any insight or help would be appreciated.

**Comment by sekrit-twc** [comment]
errno 32 is SIGPIPE. It means that the other end of the connection closed the pipe.

**Comment by tnatiuk17piano** [comment]
So you're saying it's not the program's fault, but the source input (in this case LWLibavSource)? I've tried both that one and ffms2 on multiple files, and they all have the same problem.

**Comment by sekrit-twc** [comment]
No, it is whatever is on the other side of the pipe...

**Comment by tnatiuk17piano** [comment]
So VSPipe is application A, but what is B? LWLibavSource? As I understand it, you have reader B (LWLibavSource) --> Application A (VSPipe) --> pipe (stdout).

**Comment by sekrit-twc** [comment]
No, those are all the same application. An application is a process. vspipe.exe is the pipe writer. There must be a pipe reader...

**Comment by tnatiuk17piano** [comment]
Oh, so would that be the program I send the pipe to? x265?

**Comment by sekrit-twc** [comment]
Yes. Check the logs on the other side. It may have crashed, or it may have simply exited early (because of incorrect frame count).

**Comment by tnatiuk17piano** [comment]
Here's a copy of the log. x265 crashes with error code 0xC0000005, which I presume is the access violation from VSPipe, correct?
[S01E01. Pilot_new_staxrip.log](https://github.com/vapoursynth/vapoursynth/files/4367311/S01E01.Pilot_new_staxrip.log)

**Comment by sekrit-twc** [comment]
There is no access violation in VSPipe. The downstream application crashed, which caused the pipe to automatically close. You should follow-up with x265 or STAX developers.

**Comment by tnatiuk17piano** [comment]
Thank you so much for your help. I ended up updating my BIOS, which reset it to default settings. I then re-enabled only SVM so I can run a VM for local dev, and now things are working again.
