### ISSUE TITLE
error on build

### ISSUE THREAD

**Issue by polearnik** [vapoursynth/vapoursynth#543]
Using Linux Mint 19.3 
http://vapoursynth.com/doc/installation.html#compilation 
after `./configure` it show me error 

> checking for a Python interpreter with version >= 3... python3
checking for python3... /usr/bin/python3
checking for python3 version... 3.6
checking for python3 platform... linux
checking for python3 script directory... ${prefix}/lib/python3.6/site-packages
checking for python3 extension module directory... ${exec_prefix}/lib/python3.6/site-packages
checking for PYTHON3... no
checking for PYTHON3... no
configure: error: Package requirements (python-3.6) were not met:
No package 'python-3.6' found

Please help to fix

**Comment by dubhater** [comment]
Perhaps you haven't installed the dev package? python3-dev or something like that.

**Comment by myrsloik** [comment]
No feedback from user
