### ISSUE TITLE
Adding VapourSynth.nim to "Applications and Libraries"

### ISSUE THREAD

**Issue by mantielero** [vapoursynth/vapoursynth#544]
Thanks to your help I have manage to wrap VapourSynth in the Nim programming language. I think that despite it is in an early stage it could be added to the proper [documentation section](https://github.com/vapoursynth/vapoursynth/blob/master/doc/applications.rst#libraries).

I have created a post [here](https://forum.doom9.org/showthread.php?p=1905351#post1905351) talking about it, but basically, with Nim you get easy development (as in python) and performance (as in C). This avoids needing one language for scripting and another language for developping filters.

**Comment by myrsloik** [comment]
Done
