### ISSUE TITLE
Make colorfamily setting optional in ShufflePlanes when possible

### ISSUE THREAD

**Issue by myrsloik** [vapoursynth/vapoursynth#545]

**Comment by myrsloik** [comment]
Also default planes to [0, 1, 2] or 0 depending on colorfamily?

**Comment by DJATOM** [comment]
It usually depends on input, so
1 or 2 clips = [0,1,2]
3 clips = [0,0,0] ?

**Comment by myrsloik** [comment]
Depends on if you want to merge planes from multiple clips:
clips = [a, b], planes = [0, 1, 2]
is a reasonable use case as well.
I guess planes should depend on the input clips to so if they're gray then 0 otherwise the index number.

**Comment by myrsloik** [comment]
SplitPlanes() implemented instead which solves the case of splitting. Can't assume anything else without making a mess.
