### ISSUE TITLE
libvapoursynth.so: undefined symbol: pthread_create

### ISSUE THREAD

**Issue by mantielero** [vapoursynth/vapoursynth#546]
Tonight I updated my archlinux installation. It updated vapoursynth from R48 to R49 and now it is failing with the message in the title.
The files that I compiled before the update keep working fine with R48, but that is not the case when I compile them now.

Any clue about what might be happening?

**Comment by mantielero** [comment]
I have checked that it works if I activate threads and deactivate the garbage collector in Nim, but that wasn't needed with R48:
```
nim c -f --threads:on --gc:none modifyframe
```
Has something changed from R48 to R49? Might that be the Archlinux packaging?

**Comment by myrsloik** [comment]
Probably the Archlinux packaging. R49 was just small bugfixes and nothing thread related at all.

**Comment by mantielero** [comment]
It was Archlinux packaging. Solved in R49-2.

**Comment by orbea** [comment]
This is a GNU libtool and vapoursynth bug, fixed in https://github.com/vapoursynth/vapoursynth/pull/650.
