### ISSUE TITLE
Floats at chroma planes has unexpected range

### ISSUE THREAD

**Issue by Endilll** [vapoursynth/vapoursynth#547]
Given the following set of clips 
```
clip0 = core.std.BlankClip(format=vs.YUV444PS, color=(1, 0, -1.5))
clip1 = core.std.BlankClip(format=vs.YUV444PS, color=(1, 0, -1))
clip2 = core.std.BlankClip(format=vs.YUV444PS, color=(1, 0, -0.5))
clip3 = core.std.BlankClip(format=vs.YUV444PS, color=(1, 0, 0))
clip4 = core.std.BlankClip(format=vs.YUV444PS, color=(1, 0, 0.5))
clip5 = core.std.BlankClip(format=vs.YUV444PS, color=(1, 0, 1))
clip6 = core.std.BlankClip(format=vs.YUV444PS, color=(1, 0, 1.5))
```
and a note from `Expr` documentation that _floating point clips are even more difficult, as most channels are stored in the 0-1 range with the exception of U, V, Co and Cg planes, which are in the -0.5-0.5 range_, one can expect that clips 0-2 are filled with exact the same color, as well as clips 4-6, because Y values are properly clipped. But rendered on screen (converted to `COMPATBGR32` by means of `resize`), only clips 0 and 1 are the same. Both `YUV444PH` format and `U` plane affected, too.

Actual range for chroma values appears to be about -0.6-2.3 (experimental data).

**Comment by sekrit-twc** [comment]
>rendered on screen (converted to COMPATBGR32 by means of resize), only clips 0 and 1 are the same

This is because the conversion to RGB happens without clipping the imaginary YUV colors.

Example:

    P0 = Y=1 Cb=0 Cr=-1.0
    P1 = Y=1 Cb=0 Cr=-0.5

In Rec.709:

    R = Y + 1.28033*Cr
    G = Y - 0.21482*Cb - 0.38059*Cr
    B = Y + 2.12798*Cb

    R0 = 1.0 + (-1.0)*1.28033 = -0.28033 = 0
    G0 = 1.0 - 0 - (-1.0)*0.38059 = 1.38059 = 1.0
    B0 = 1.0 + 0 = 1.0

    R0 = 1.0 + (-0.5)*1.28033 = 0.359835
    G0 = 1.0 - 0 - (-0.5)*0.38059 = 1.190295 = 1.0
    B0 = 1.0 + 0 = 1.0

Your original YUV values were illegal (not all combinations of YUV produce valid RGB, so you are merely seeing the projection of the imaginary color into the physical colorspace. See this ancient Doom9 thread for more information about legal YUV values: http://forum.doom9.org/showthread.php?t=154731

**Comment by Endilll** [comment]
Thank you for details.
Now it clear that Y appeared clipped to me because it was tested with `Cb=0 Cr=0`, which wasn't pretty wise of me.
So, what got clipped are RGB values after conversion, but shouldn't it be YUV values before conversion?

**Comment by sekrit-twc** [comment]
Input can't be clipped, because sometimes invalid inputs become valid again after conversion (e.g. BT709->BT2020 expanding the gamut).
