### ISSUE TITLE
SIMD options have no effect

### ISSUE THREAD

**Issue by 4re** [vapoursynth/vapoursynth#548]
This is more a call for help in trying to know why, because looks like I'm the only one with this problem.
I tested R48 and R49, all the same.
This is the test script used:
```python
import vapoursynth as vs
core = vs.get_core()
# core.std.SetMaxCPU('none')
clip = core.std.BlankClip(format=vs.GRAYS, length=50000, fpsnum=24000, fpsden=1001, keep=True)
clip = core.std.Convolution(clip, matrix=[1,2,1,2,4,2,1,2,1])
clip.set_output()
```

`core.std.SetMaxCPU('none')` in scripts has no effect.
`--disable-x86-asm` | `--enable-x86-asm` in configure has no effect.
Compiler used to build vapoursynth has no effect (`GCC` | `Clang`).

Build configure line looks something like:
`./configure --prefix=/usr --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu --mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share --sysconfdir=/etc --localstatedir=/var/lib --disable-dependency-tracking --disable-silent-rules --docdir=/usr/share/doc/vapoursynth-9999 --htmldir=/usr/share/doc/vapoursynth-9999/html --with-sysroot=/ --libdir=/usr/lib64 --enable-core --enable-python-module --enable-vsscript --enable-x86-asm --enable-eedi3 --enable-imwri --enable-miscfilters --enable-morpho --enable-ocr --enable-removegrain --enable-subtext --enable-vinverse --enable-vivtc --enable-shared --disable-static --disable-debug --disable-guard-pattern --enable-vspipe`

`Linux 5.5.13-gentoo-x86_64 #1 SMP PREEMPT Thu Mar 26 18:20:17 CET 2020 x86_64 AMD Ryzen 7 3700X 8-Core Processor AuthenticAMD GNU/Linux`

**Comment by sekrit-twc** [comment]
Do you mean that it is always using SIMD?

**Comment by 4re** [comment]
fps seems high enough to assume that.

**Comment by 4re** [comment]
Let me change my mind about that last statement. I manually edited the build script to not use any sse avx source file and I'm getting the same fps (~10500 for that script). I was under the impression that with crappy ram that was to much for no-simd.

**Comment by sekrit-twc** [comment]
It could be autovectorized. GenericFillters has a data access pattern that is easy for the autovec.
