### ISSUE TITLE
Error when make -j4

### ISSUE THREAD

**Issue by ckgio99** [vapoursynth/vapoursynth#550]
After `make -j4` I get the Error. Please help me. This is the first time I'm using Linux Mint

  CXXLD    libvapoursynth.la
  CXXLD    libvapoursynth-script.la
  CCLD     libeedi3.la
  CXXLD    libmiscfilters.la
/usr/bin/ld: cannot open output file .libs/libeedi3.so: Permission denied
collect2: error: ld returned 1 exit status
Makefile:963: recipe for target 'libeedi3.la' failed
make: *** [libeedi3.la] Error 1
make: *** Waiting for unfinished jobs....
/usr/bin/ld: cannot open output file .libs/libvapoursynth-script.so.0.0.0: Permission denied
collect2: error: ld returned 1 exit status
Makefile:1087: recipe for target 'libvapoursynth-script.la' failed
make: *** [libvapoursynth-script.la] Error 1
/usr/bin/ld: cannot open output file .libs/libmiscfilters.so: Permission denied
collect2: error: ld returned 1 exit status
Makefile:998: recipe for target 'libmiscfilters.la' failed
make: *** [libmiscfilters.la] Error 1
rm: cannot remove '.libs/libvapoursynth.a': Permission denied
rm: cannot remove '.libs/libvapoursynth.la': Permission denied
rm: cannot remove '.libs/libvapoursynth.lai': Permission denied
rm: cannot remove '.libs/libvapoursynth.so': Permission denied
/usr/bin/ld: cannot open output file .libs/libvapoursynth.so: Permission denied
collect2: error: ld returned 1 exit status
Makefile:1159: recipe for target 'libvapoursynth.la' failed
make: *** [libvapoursynth.la] Error 1

**Comment by myrsloik** [comment]
Probably a directory permission error.
