### ISSUE TITLE
[Question] VapourSynth.nim - plugin performance issue

### ISSUE THREAD

**Issue by mantielero** [vapoursynth/vapoursynth#551]
I am comparing the performance between Python and Nim. It is better in Python while they should be similar.

I am testing:
```python
import vapoursynth as vs
core = vs.get_core()
core.std.SetMaxCPU('none')
clip = core.std.BlankClip(format=vs.GRAYS, length=100000, fpsnum=24000, fpsden=1001, keep=True)
clip = core.std.Convolution(clip, matrix=[1,2,1,2,4,2,1,2,1])
clip.set_output()
```
that in my computer produces:
```
$ vspipe convolution.vpy /dev/null
Output 100000 frames in 26.71 seconds (3743.75 fps)
```
On the other hand the Nim's version is written like:
```nim
import ../vapoursynth
import options
import times

let time = epochTime()

let nframes = BlankClip( 
      format=pfGrayS.int.some, 
      width=640.some,
      height=480.some,
      length=100000.some,
      fpsnum=24000.some, 
      fpsden=1001.some, 
      keep=1.some).Convolution(@[1.0,2.0,1.0,2.0,4.0,2.0,1.0,2.0,1.0]).Null

let dif = epochTime() - time
echo "Time       : ", dif
echo "Num. frames: ", nframes
echo "FPS        : ", (nframes.float / dif.float)
```
and then compiled and executed:
```
$ nim c -d:release -d:danger convolution.nim
$ ./convolution
Time       : 38.33977603912354
Num. frames: 100000
FPS        : 2608.257280844723
```
This is more than 1000fps slower.

Regarding calling a filter I don't do things differently. Internally I just call invoke:
- [BlankClip](https://github.com/mantielero/VapourSynth.nim/blob/master/src/plugins/std.nim#L89)
- [Convolution](https://github.com/mantielero/VapourSynth.nim/blob/master/src/plugins/std.nim#L173)

I think that the difference might be in how I request frames in the custom made `Null` filter:
```nim
proc Null*(vsmap:ptr VSMap):int =
  let node = getFirstNode(vsmap)
  let vinfo = API.getVideoInfo(node) # video info pointer
  let nframes = vinfo.numFrames 
  for i in 0..<nframes:  
    let frame = node.getFrame(i)
    API.freeFrame( frame )

  API.freeMap(vsmap)
  API.freeNode(node)
  return nframes
```
So I request all the frames using `node.getFrame(i)`.

Looking into [vspipe.cpp](https://github.com/vapoursynth/vapoursynth/blob/66d7d04399bfaa5b2054ec0aa198f99c4bfc330a/src/vspipe/vspipe.cpp), I see that it uses [getFrameAsync](https://github.com/vapoursynth/vapoursynth/blob/66d7d04399bfaa5b2054ec0aa198f99c4bfc330a/src/vspipe/vspipe.cpp#L191). 

Can that account for so much difference?

Any other idea about what can I be doing wrong?

**Comment by myrsloik** [comment]
Yes, multiple requests (usually equal to the number of core threads) with getFrameAsync is key to performance. Your code is effectively single-threaded.

**Comment by mantielero** [comment]
I know that this is Nim language but does it look like it makes sense? 
```nim
proc callback( userData: pointer, 
               f: ptr VSFrameRef, 
               n: cint, 
               a4: ptr VSNodeRef, 
               errorMsg: cstring) {.cdecl.} = 
  API.freeFrame( f )  # Just free the frame.

proc NullAsync*(vsmap:ptr VSMap):int =
  let node = getFirstNode(vsmap)   # Extracts the first node in the first item of vsmap 
  let vinfo = API.getVideoInfo(node) # Gets video info pointer from the node
  let nframes = vinfo.numFrames     # Get the number of frames from the video info.
  for i in 0..<nframes:    # Iterates between 0 and nframes-1
    API.getFrameAsync( i, node, callback, nil)  # Request frame i, from node and uses callback when ready.
    
  API.freeMap(vsmap)  # Free the VSMap
  API.freeNode(node)   # Free the node
  return nframes
```
The filter would be `NullAsync`.

> Right now is not working, but I think this is due to something I am doing wrong in Nim's. For me is difficult because I am both learning Nim and how to use VapourSynth as a library. Here I try to focus on how to use VapourSynth properly.

**Comment by myrsloik** [comment]
Don't request all frames at once. Queue more in the completion callback or you'll clog the request queue in no time.

**Comment by mantielero** [comment]
I am a bit inexperienced with threads (I am not a pro). Reading [getFrameAsync](http://www.vapoursynth.com/doc/api/vapoursynth.h.html#getframeasync), I am curious about `void *userData` purpose. When I look into `vspipe.cpp <https://github.com/vapoursynth/vapoursynth/blob/master/src/vspipe/vspipe.cpp>`_, it looks like it modifies the global state. Could the state be handled with that user data  pointer or is it meant for something different?

**Comment by myrsloik** [comment]
Yes, use the userData pointer instead of global state. That's the purpose.

**Comment by mantielero** [comment]
Thanks for the info. Huge improvement.
