### ISSUE TITLE
[Question] VSScript

### ISSUE THREAD

**Issue by mantielero** [vapoursynth/vapoursynth#553]
I am trying to wrap VSScript, and `vsscript_init()` is returning `0`. Is there something that I should do before I call that function?

**Comment by myrsloik** [comment]
No, there's nothing you need to do before calling it. Usually failures are because it can't locate the python installation (python38.dll) due to it either not being in the path or being discoverable through the registry.
Your VapourSynth installation works properly with vspipe and such?

**Comment by mantielero** [comment]
I have just realize this is a problem related with RTLD_GLOBAL. In Nim I have to do [this](https://forum.nim-lang.org/t/3996). Now hitting a different issue.

> Just to say THANKS SO MUCH for your helpful attitude (not only now, but for all the others questions that I have raised so far). I am learning A LOT. It encourage me a lot.
