### ISSUE TITLE
R49 still doesn’t support greyscale colorspace conversions

### ISSUE THREAD

**Issue by Lypheo** [vapoursynth/vapoursynth#554]
The issue I described in #537 is not fully fixed in R49. The same code now throws:
```py
Resize error -1: cannot apply colorspace conversion to greyscale image
```
zimg master doesn’t seem to throw that error since sekrit-twc/zimg@bfc973933421ab78873029ded2f5fc22121104d4, so maybe the windows binaries for R49 were linked against an old version?

**Comment by myrsloik** [comment]
It's linked against the v2.9 branch.

**Comment by Lypheo** [comment]
... which [doesn't support](https://github.com/sekrit-twc/zimg/blob/v2.9/src/zimg/graph/graphbuilder.cpp#L332) grey scale csp conversions 😞

**Comment by myrsloik** [comment]
Will be in the next release

**Comment by myrsloik** [comment]
Please verify that R50-RC1 fixes this

**Comment by Lypheo** [comment]
It does, though zimg still requires an input matrix to be set, which doesn’t make sense a lot of sense for greyscale clips, @sekrit-twc. (So 
```py
out =  core.std.BlankClip(format=vs.GRAYS, color=0.5).resize.Spline16(transfer_in_s="709", transfer_s="linear")
``` 
doesn’t work, but
```py
out =  core.std.BlankClip(format=vs.GRAYS, color=0.5).resize.Spline16(transfer_in_s="709", transfer_s="linear", matrix_in_s="709")
``` 
does.)
