### ISSUE TITLE
[Question] How to integrate .vpy declared functions

### ISSUE THREAD

**Issue by mantielero** [vapoursynth/vapoursynth#555]
I have managed to execute a **.vpy** file from Nim. For instance, I have **script.vpy**:
```python
from vapoursynth import core
video = core.ffms2.Source(source='2sec.mkv')
video = core.std.Transpose(video)
video.set_output()
```
I do `vsscript_init`, `vsscript_evaluateFile`, `vsscript_getOutput`, and export the node into a file.

Now I would like to be able to reuse functions, like those defined in `havsfunc.py <https://github.com/HomeOfVapourSynthEvolution/havsfunc/blob/master/havsfunc.py>`_. 

Is there a way to do that?

**Comment by stuxcrystal** [comment]
Yes. It is technically possible to make vpy-files importable. For more information look at the module "importlib". Using the same module you can hack your way into allowing python to import .vpy-files as if they were normal .py-files.

That you can do it, doesn't mean you should. vpy-files exist for a reason. This reason being: They explicitly declare to the user that they construct a finished filter-chain and export them for the script-runner (ie. vspipe, vsedit, ...). **So if you want to reuse a function from a vpy-file, polish your function up and pack them in your own .py-file.**

Another possible case is creating a "builtin"-module that your application exposes to the python-interpreter. In this case, refer to [this documentation](https://docs.python.org/3/extending/embedding.html#extending-embedded-python).

**Comment by mantielero** [comment]
Sorry I wasn't clear enough. I was not talking about importing vpy-files in python. I was thinking about exposing a particular Python function though a Nim function. For example, the following python function:
```python
# Anti-aliasing with contra-sharpening by Didée
def daa(c, nsize=None, nns=None, qual=None, pscrn=None, int16_prescreener=None, int16_predictor=None, exp=None, opencl=False, device=None):
    if not isinstance(c, vs.VideoNode):
        raise TypeError('daa: This is not a clip')

    if opencl:
        nnedi3 = partial(core.nnedi3cl.NNEDI3CL, nsize=nsize, nns=nns, qual=qual, pscrn=pscrn, device=device)
    else:
        nnedi3 = partial(core.znedi3.nnedi3 if hasattr(core, 'znedi3') else core.nnedi3.nnedi3,
                         nsize=nsize, nns=nns, qual=qual, pscrn=pscrn, int16_prescreener=int16_prescreener, int16_predictor=int16_predictor, exp=exp)

    nn = nnedi3(c, field=3)
    dbl = core.std.Merge(nn[::2], nn[1::2])
    dblD = core.std.MakeDiff(c, dbl)
    shrpD = core.std.MakeDiff(dbl, core.std.Convolution(dbl, matrix=[1, 1, 1, 1, 1, 1, 1, 1, 1] if c.width > 1100 else [1, 2, 1, 2, 4, 2, 1, 2, 1]))
    DD = core.rgvs.Repair(shrpD, dblD, mode=[13])
    return core.std.MergeDiff(dbl, DD)
```
I was wondering if there is a way to call that particular function passing the required parameters.

After reading further documentation, I was wondering if `vsscript_setVariable` is meant to do that. And in the other hand, how I could call that function.

> You are right that .vpy are more a **finished filter-chain**, and it that regard probably it is not worth it to wrap those functions.

**Comment by stuxcrystal** [comment]
The easy way:
1. Dynamically create a script that runs your function and use `set_output` to store the result.
2. Use `createMap`. The key is the variable name of your choice, the value is your input clip.
3. Use `vpy_evaluateScript` to run your script.
4. Use `vpy_getOutput2` with your desired output to get a reference to the output node.

**Comment by mantielero** [comment]
Thanks for the information
