### ISSUE TITLE
[Question] FrameEval

### ISSUE THREAD

**Issue by mantielero** [vapoursynth/vapoursynth#557]
I would like to understand better FrameEval. I see that it applies a defined function [here](https://github.com/vapoursynth/vapoursynth/blob/master/src/core/simplefilters.c#L1480). It is not very clear for me the function declaration. It seems to go [here](https://github.com/vapoursynth/vapoursynth/blob/master/src/core/simplefilters.c#L1454). 

I am bit lost with FrameEval.

**Comment by myrsloik** [comment]
A VS function object is any wrapped function that takes a VSMap for input and a VSMap for output. The function called there usually comes from Python and you can see how it's defined there.

**Comment by mantielero** [comment]
I think it is that last element what I don't get. How the python function gets "converted" into a `ptr VSFunc` that serves as an input for FrameEval. Where is that defined?

**Comment by myrsloik** [comment]
That's in the cython bits. Look in vapoursynth.pyx for the class Func and the createFuncRef function.
