### ISSUE TITLE
make error during compilation

### ISSUE THREAD

**Issue by boredness** [vapoursynth/vapoursynth#563]
OS: Ubuntu 19.10
Python 3.6

Here are the output logs of all the commands being ran:
./autogen.sh: https://0bin.net/paste/uECpKIRh0BAVUbOD#yZbqk-qVquBGhoMfaakBrH6AlUk4G1zeoamKkbVQJ8k
./configure: https://0bin.net/paste/vh2L-9UxvqZEGmU3#GtONwldra6e79JVLsY2PY545I7wutJ9T2kwpPkOgp3j

make:
$ make
  CXX      src/vspipe/vspipe.o
  CXX      src/vsscript/libvapoursynth_script_la-vsscript.lo
  CXXLD    libvapoursynth-script.la
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(dictobject.o): relocation R_X86_64_32S against `.text' can not be use d when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(object.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be  used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(obmalloc.o): relocation R_X86_64_32S against `.data' can not be used  when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(capsule.o): relocation R_X86_64_32 against `.rodata.str1.1' can not b e used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(rangeobject.o): relocation R_X86_64_32 against symbol `_Py_NoneStruct ' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(setobject.o): relocation R_X86_64_32S against `.data' can not be used  when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(sliceobject.o): relocation R_X86_64_32 against `.rodata.str1.1' can n ot be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(tupleobject.o): relocation R_X86_64_32 against symbol `_PyEval_SliceI ndexNotNone' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(typeobject.o): relocation R_X86_64_32 against symbol `PyBaseObject_Ty pe' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(unicodeobject.o): relocation R_X86_64_32 against `.rodata.str1.1' can  not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(unicodectype.o): relocation R_X86_64_32S against `.rodata' can not be  used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(weakrefobject.o): relocation R_X86_64_32S against symbol `_Py_NoneStr uct' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(_warnings.o): relocation R_X86_64_32 against symbol `_Py_NoneStruct'  can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(bltinmodule.o): relocation R_X86_64_32S against symbol `PyFilter_Type ' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(ceval.o): relocation R_X86_64_32 against `.bss' can not be used when  making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(compile.o): relocation R_X86_64_32S against `.rodata' can not be used  when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(codecs.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be  used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(errors.o): relocation R_X86_64_32S against symbol `PyTraceBack_Type'  can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(future.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be  used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(getargs.o): relocation R_X86_64_32S against `.rodata' can not be used  when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(import.o): relocation R_X86_64_32 against `.data' can not be used whe n making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(importdl.o): relocation R_X86_64_32 against `.rodata.str1.1' can not  be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(marshal.o): relocation R_X86_64_32 against `.rodata.str1.1' can not b e used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(modsupport.o): relocation R_X86_64_32S against `.rodata' can not be u sed when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(peephole.o): relocation R_X86_64_32S against symbol `PyFrozenSet_Type ' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(pyhash.o): relocation R_X86_64_32S against `.rodata' can not be used  when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(pylifecycle.o): relocation R_X86_64_32 against `.rodata.str1.1' can n ot be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(pystate.o): relocation R_X86_64_32 against `.rodata.str1.8' can not b e used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(pythonrun.o): relocation R_X86_64_32 against `.data' can not be used  when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(pytime.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be  used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(random.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be  used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(symtable.o): relocation R_X86_64_32 against `.rodata.str1.8' can not  be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(sysmodule.o): relocation R_X86_64_32 against symbol `_Py_NoneStruct'  can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(traceback.o): relocation R_X86_64_32 against `.rodata.str1.1' can not  be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(pystrtod.o): relocation R_X86_64_32S against symbol `_Py_ctype_tolowe r' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(dtoa.o): relocation R_X86_64_32S against `.bss' can not be used when  making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(formatter_unicode.o): relocation R_X86_64_32S against symbol `_Py_cty pe_table' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(fileutils.o): relocation R_X86_64_32S against `.rodata.str1.1' can no t be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(dynload_shlib.o): relocation R_X86_64_32 against `.rodata.str1.1' can  not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(thread.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be  used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(getpath.o): relocation R_X86_64_32 against `.rodata.str1.8' can not b e used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(gcmodule.o): relocation R_X86_64_32 against symbol `_Py_NoneStruct' c an not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(_threadmodule.o): relocation R_X86_64_32 against symbol `_Py_NoneStru ct' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(posixmodule.o): relocation R_X86_64_32S against symbol `_Py_NoneStruc t' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(errnomodule.o): relocation R_X86_64_32 against `.data' can not be use d when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(pwdmodule.o): relocation R_X86_64_32 against `.bss' can not be used w hen making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(_sre.o): relocation R_X86_64_32S against symbol `_Py_ctype_tolower' c an not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(_codecsmodule.o): relocation R_X86_64_32 against `.rodata.str1.1' can  not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(_weakref.o): relocation R_X86_64_32 against `.rodata.str1.1' can not  be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(_functoolsmodule.o): relocation R_X86_64_32 against `.data' can not b e used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(_operator.o): relocation R_X86_64_32 against `.data' can not be used  when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(_collectionsmodule.o): relocation R_X86_64_32 against symbol `_Py_Non eStruct' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(itertoolsmodule.o): relocation R_X86_64_32S against `.data' can not b e used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(atexitmodule.o): relocation R_X86_64_32 against `.rodata.str1.8' can  not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(signalmodule.o): relocation R_X86_64_32 against `.rodata.str1.8' can  not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(_stat.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be  used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(timemodule.o): relocation R_X86_64_32 against `.rodata.str1.1' can no t be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(_localemodule.o): relocation R_X86_64_32 against `.rodata.str1.1' can  not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(_iomodule.o): relocation R_X86_64_32 against `.data' can not be used  when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(iobase.o): relocation R_X86_64_32 against symbol `_Py_FalseStruct' ca n not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(fileio.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be  used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(bytesio.o): relocation R_X86_64_32 against `.rodata.str1.1' can not b e used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(bufferedio.o): relocation R_X86_64_32 against `.rodata.str1.1' can no t be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(textio.o): relocation R_X86_64_32 against symbol `_Py_NoneStruct' can  not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(stringio.o): relocation R_X86_64_32 against `.rodata.str1.1' can not  be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(zipimport.o): relocation R_X86_64_32 against `.rodata.str1.1' can not  be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(faulthandler.o): relocation R_X86_64_32 against `.rodata.str1.1' can  not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(_tracemalloc.o): relocation R_X86_64_32 against `.rodata.str1.1' can  not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(hashtable.o): relocation R_X86_64_32 against symbol `PyMem_RawFree' c an not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(symtablemodule.o): relocation R_X86_64_32 against symbol `PyUnicode_F SDecoder' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(xxsubtype.o): relocation R_X86_64_32 against `.data' can not be used  when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(getbuildinfo.o): relocation R_X86_64_32 against `.rodata.str1.1' can  not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(acceler.o): relocation R_X86_64_32 against `.rodata.str1.1' can not b e used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(grammar1.o): relocation R_X86_64_32 against `.rodata.str1.1' can not  be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(myreadline.o): relocation R_X86_64_32 against `.rodata.str1.1' can no t be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(parsetok.o): relocation R_X86_64_32 against `.rodata.str1.1' can not  be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(tokenizer.o): relocation R_X86_64_32 against `.rodata.str1.8' can not  be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(abstract.o): relocation R_X86_64_32S against symbol `_Py_NotImplement edStruct' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(accu.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be u sed when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(boolobject.o): relocation R_X86_64_32 against `.data' can not be used  when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(bytes_methods.o): relocation R_X86_64_32S against symbol `_Py_NoneStr uct' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(bytearrayobject.o): relocation R_X86_64_32 against symbol `_Py_NoneSt ruct' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(bytesobject.o): relocation R_X86_64_32 against symbol `_Py_NoneStruct ' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(cellobject.o): relocation R_X86_64_32 against `.rodata.str1.1' can no t be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(classobject.o): relocation R_X86_64_32 against `.rodata.str1.1' can n ot be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(codeobject.o): relocation R_X86_64_32S against symbol `PyUnicode_Type ' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(complexobject.o): relocation R_X86_64_32 against `.data' can not be u sed when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(descrobject.o): relocation R_X86_64_32 against `.rodata.str1.1' can n ot be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(enumobject.o): relocation R_X86_64_32 against `.data' can not be used  when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(exceptions.o): relocation R_X86_64_32S against symbol `_Py_NoneStruct ' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(genobject.o): relocation R_X86_64_32 against symbol `_Py_NoneStruct'  can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(fileobject.o): relocation R_X86_64_32 against symbol `_Py_NoneStruct'  can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(floatobject.o): relocation R_X86_64_32 against `.rodata.str1.1' can n ot be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(frameobject.o): relocation R_X86_64_32 against symbol `_Py_NoneStruct ' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(funcobject.o): relocation R_X86_64_32S against symbol `PyCode_Type' c an not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(iterobject.o): relocation R_X86_64_32 against symbol `_Py_NoneStruct'  can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(listobject.o): relocation R_X86_64_32 against symbol `_Py_NoneStruct'  can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(longobject.o): relocation R_X86_64_32 against `.rodata.str1.1' can no t be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(odictobject.o): relocation R_X86_64_32 against `.rodata.str1.8' can n ot be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(memoryobject.o): relocation R_X86_64_32 against `.rodata.str1.8' can  not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(methodobject.o): relocation R_X86_64_32 against symbol `_Py_NoneStruc t' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(moduleobject.o): relocation R_X86_64_32 against `.rodata.str1.8' can  not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(namespaceobject.o): relocation R_X86_64_32S against `.rodata.str1.1'  can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(structseq.o): relocation R_X86_64_32 against `.data' can not be used  when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(Python-ast.o): relocation R_X86_64_32S against symbol `_Py_NoneStruct ' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(ast.o): relocation R_X86_64_32S against symbol `_Py_NoneStruct' can n ot be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(getcopyright.o): relocation R_X86_64_32 against `.rodata' can not be  used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(getplatform.o): relocation R_X86_64_32 against `.rodata.str1.1' can n ot be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(getversion.o): relocation R_X86_64_32 against `.rodata.str1.1' can no t be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(mystrtoul.o): relocation R_X86_64_32S against symbol `_Py_ctype_table ' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(structmember.o): relocation R_X86_64_32S against `.rodata' can not be  used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(parser.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be  used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libpython3.6m.a(getcompiler.o): relocation R_X86_64_32 against `.rodata.str1.1' can n ot be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: nonrepresentable section on output
collect2: error: ld returned 1 exit status
make: *** [Makefile:1187: libvapoursynth-script.la] Error 1

**Comment by sekrit-twc** [comment]
You need to compile Python as a shared library.
