### ISSUE TITLE
misc.AverageFrames broken?

### ISSUE THREAD

**Issue by theChaosCoder** [vapoursynth/vapoursynth#565]
VS R50-rc1, win10 x64 ryzen 2600 cpu

Maybe I used it wrong but

`clip.misc.AverageFrames(weights=30)` # or any other weights value -> seems to do nothing at all. setting setcpu to none does not help
`clip.misc.AverageFrames(weights=3, scale=1)` -> pink image even with a blank YUV420P8 clip, rgb seems fine with a blank clip. But is looks like a rainbow with a rgb video

Maybe someone will post here https://forum.doom9.org/showthread.php?t=166582&page=29 additional infos.

**Comment by sekrit-twc** [comment]
>clip.misc.AverageFrames(weights=30) # or any other weights value -> seems to do nothing at all.

This is because scale is by default the sum of weights.

>setting setcpu to none does not help

MiscFilters is not part of the core, so it's not affected by SetMaxCPU.

>clip.misc.AverageFrames(weights=3, scale=1) -> pink image even with a blank YUV420P8 clip, rgb seems fine with a blank clip. But is looks like a rainbow with a rgb video

This is because a blank YUV clip has U=V=128 which is multiplied by 3 and saturates to 255, i.e. no longer blank.

**Comment by myrsloik** [comment]
Maybe making UV-planes zero centered before calculations makes more sense and wouldn't harm sane existing usage. I guess.

**Comment by sekrit-twc** [comment]
Implemented in e680805
