### ISSUE TITLE
Additional Enums

### ISSUE THREAD

**Issue by Frechdachs** [vapoursynth/vapoursynth#570]
It would be nice to have additional enums in VapourSynth.h and the python bindings. Namely for Range, Matrix, Transfer, Primaries, ChromaLocation and FieldBased.
The values for all of those are actually defined in the [C API Reference](http://www.vapoursynth.com/doc/apireference.html#reserved-frame-properties).

There are some things to consider, though. Currently matrix names (for `matrix_s`) are exactly as specified in ITU-T H.265 like it is written in the [docs](http://www.vapoursynth.com/doc/functions/resize.html), but variables in python can't start with a digit. Zimg already changed its enum names to e.g.`ZIMG_MATRIX_BT709` instead of `ZIMG_MATRIX_709` and deprecated the latter, so to be consistent with zimg, "BT709" could be used.
Secondly, it might be preferable to put the enum in a namespace (class which inherits from IntEnum) like `Range` and `Matrix` to not clutter the main vs namespace in python, but I have no strong opinion on this.

**Comment by Frechdachs** [comment]
Oh, `vs.SampleType` is actually a thing. I thought it is only accessable directly like vs.INTEGER. Then my second point is already implented anyway.

**Comment by myrsloik** [comment]
Basically implemented in the doodle1 branch. The constants are in vsconstants4.h but I'm too lazy to transcribe all of them into vsconstants.pxd. Patches welcome.

**Comment by myrsloik** [comment]
Done, unless the naming is derpy
