### ISSUE TITLE
Build error with GCC 9: relocation R_X86_64_PC32 against symbol ff_pw_9

### ISSUE THREAD

**Issue by sylvainhalle** [vapoursynth/vapoursynth#573]
Steps to reproduce:

Download sources for R50, then:

```
./autogen.sh
./configure
make
```

After some time, the process halts with this message:

```
/usr/bin/ld: /usr/local/lib/libavcodec.a(vc1dsp_mmx.o): relocation R_X86_64_PC32
against symbol `ff_pw_9' can not be used when making a shared object; recompile
with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
Makefile:1075: recipe for target 'libsubtext.la' failed
make: *** [libsubtext.la] Error 1
```

Environment:

- Ubuntu 18.04 LTS 64-bit
- g++ version 9.3.0
- Python 3.6.9

FWIW, seems to be related to the use of GCC 9: https://stackoverflow.com/a/47201755

**Comment by sylvainhalle** [comment]
If I replace the second command by  `./configure CXXFLAGS='-fPIC'`, the build process succeeds.

**Comment by myrsloik** [comment]
Nothing to see here. It's simply a mismatch between ffmpeg and vapoursynth compilation options.

**Comment by sylvainhalle** [comment]
I am not sure to understand. I am not trying to compile ffmpeg.

**Comment by HolyWu** [comment]
[Subtext is a subtitle renderer that uses libass and ffmpeg.](http://www.vapoursynth.com/doc/plugins/subtext.html)

**Comment by dubhater** [comment]
The message "recompile with -fPIC" is about vc1dsp_mmx.o, which is located in the static library libavcodec.a, which you did compile earlier (I assume). That's what you need to recompile with -fPIC, not the Subtext plugin.
