### ISSUE TITLE
Halos

### ISSUE THREAD

**Issue by nobananasforyou** [vapoursynth/vapoursynth#574]
Hi,

I'm running the latest vs r50 along with the recent havsfunc's commit. There is a discrepancy between avs' and vs' finedehalo. 

Here's the source image:
![src](https://i.imgur.com/e3oGsjI.png)

avs' output:
![avs](https://i.imgur.com/VCsoqoy.png)

vs' output:
![vs](https://i.imgur.com/bteGGyK.png)

The prominent halos are around the eyes and nose.

Test script:
import vapoursynth as vs
import havsfunc as haf
import fvsfunc as fvf
core = vs.get_core()
core.std.SetMaxCPU("none") # adding this somehow reduces halos

src = core.d2v.Source(r'sad', rff=False)
src = core.std.ShufflePlanes(src, planes=0, colorfamily=vs.GRAY)
src = fvf.Depth(src, 16)
src = haf.FineDehalo(src, darkstr=0)
src = fvf.Depth(src, 10)
src.set_output()

**Comment by myrsloik** [comment]
Please report it to the FineDehalo author or reduce it to a testcase showing a problem in the VapourSynth core function.

**Comment by nobananasforyou** [comment]
I've already created an issue there.

**Comment by theChaosCoder** [comment]
```
clip = this img
clip = mvf.Depth(clip, 16)
clipx = clip.std.Sobel().text.Text("16bit")
core.std.SetMaxCPU("none")
clip = clip.std.Sobel().text.Text("16bit CPU none")
clip= core.std.StackHorizontal([clip, clipx])

```
bit depth 8-12 seems ok, but not 16
![image](https://user-images.githubusercontent.com/3579830/82680997-66d6f600-9c4d-11ea-9d92-3e8895980501.png)

**Comment by sekrit-twc** [comment]
This fix in generic.cpp should resolve the 16-bit problem

        -float tmp = std::sqrt(static_cast<float>(gx * gx + gy * gy)) * scale;
        +float tmp = std::sqrt(static_cast<float>(gx) * gx + static_cast<float>(gy) * gy) * scale;

**Comment by theChaosCoder** [comment]
Prewitt has the same issue btw

**Comment by sekrit-twc** [comment]
What is wrong with 14-bit? There was an integer overflow in the C code that affect bit depths > 13.

**Comment by theChaosCoder** [comment]
I just realized that mvf.Depth() uses fmtc.bitdepth and it seems it has some problems with 14 bit:
`vapoursynth.Error: bitdepth: output pixel bitdepth not supported.`

this `clip.resize.Bicubic(format=vs.YUV420P14, matrix_s="709")` does work!

**Comment by nobananasforyou** [comment]
@theChaosCoder you could open up an issue there: https://github.com/EleonoreMizo/fmtconv/issues
