### ISSUE TITLE
Can't build avfs with avisynth+ v3.6.0

### ISSUE THREAD

**Issue by fuchanghao** [vapoursynth/vapoursynth#576]
I tried Avisynth+ v3.6.0 or lastest git commit. both reports the same error.

Build tools
VS2019 16.6.0
Windows 10 SDK 10.0.19401.0
Python 3.8.3
Vapoursynth 830e07e7da3f4159223d28ba868eac8aec3383c4

error log:
> 13>E:\Source_Code\VapourSynth\vapoursynth\AviSynthPlus\avs_core\include\avisynth.h(1146,3): error C2365: “ptUnset”: 重定义；以前的定义是“枚举数”
> 13>E:\Source_Code\VapourSynth\vapoursynth\include\VapourSynth.h(171): message : 参见“ptUnset”的声明
> 13>E:\Source_Code\VapourSynth\vapoursynth\AviSynthPlus\avs_core\include\avisynth.h(1147,3): error C2365: “ptInt”: 重定义；以前的定义是“枚举数”
> 13>E:\Source_Code\VapourSynth\vapoursynth\include\VapourSynth.h(172): message : 参见“ptInt”的声明
> 13>E:\Source_Code\VapourSynth\vapoursynth\AviSynthPlus\avs_core\include\avisynth.h(1148,3): error C2365: “ptFloat”: 重定义；以前的定义是“枚举数”
> 13>E:\Source_Code\VapourSynth\vapoursynth\include\VapourSynth.h(173): message : 参见“ptFloat”的声明
> 13>E:\Source_Code\VapourSynth\vapoursynth\AviSynthPlus\avs_core\include\avisynth.h(1149,3): error C2365: “ptData”: 重定义；以前的定义是“枚举数”
> 13>E:\Source_Code\VapourSynth\vapoursynth\include\VapourSynth.h(174): message : 参见“ptData”的声明
> 13>E:\Source_Code\VapourSynth\vapoursynth\AviSynthPlus\avs_core\include\avisynth.h(1151,3): error C2365: “ptFrame”: 重定义；以前的定义是“枚举数”
> 13>E:\Source_Code\VapourSynth\vapoursynth\include\VapourSynth.h(176): message : 参见“ptFrame”的声明
> 13>E:\Source_Code\VapourSynth\vapoursynth\AviSynthPlus\avs_core\include\avisynth.h(1156,3): error C2365: “peUnset”: 重定义；以前的定义是“枚举数”
> 13>E:\Source_Code\VapourSynth\vapoursynth\include\VapourSynth.h(181): message : 参见“peUnset”的声明
> 13>E:\Source_Code\VapourSynth\vapoursynth\AviSynthPlus\avs_core\include\avisynth.h(1157,3): error C2365: “peType”: 重定义；以前的定义是“枚举数”
> 13>E:\Source_Code\VapourSynth\vapoursynth\include\VapourSynth.h(182): message : 参见“peType”的声明
> 13>E:\Source_Code\VapourSynth\vapoursynth\AviSynthPlus\avs_core\include\avisynth.h(1158,3): error C2365: “peIndex”: 重定义；以前的定义是“枚举数”
> 13>E:\Source_Code\VapourSynth\vapoursynth\include\VapourSynth.h(183): message : 参见“peIndex”的声明
> 13>E:\Source_Code\VapourSynth\vapoursynth\AviSynthPlus\avs_core\include\avisynth.h(1162,3): error C2365: “paReplace”: 重定义；以前的定义是“枚举数”
> 13>E:\Source_Code\VapourSynth\vapoursynth\include\VapourSynth.h(187): message : 参见“paReplace”的声明
> 13>E:\Source_Code\VapourSynth\vapoursynth\AviSynthPlus\avs_core\include\avisynth.h(1163,3): error C2365: “paAppend”: 重定义；以前的定义是“枚举数”
> 13>E:\Source_Code\VapourSynth\vapoursynth\include\VapourSynth.h(188): message : 参见“paAppend”的声明
> 13>E:\Source_Code\VapourSynth\vapoursynth\AviSynthPlus\avs_core\include\avisynth.h(1164,3): error C2365: “paTouch”: 重定义；以前的定义是“枚举数”
> 13>E:\Source_Code\VapourSynth\vapoursynth\include\VapourSynth.h(189): message : 参见“paTouch”的声明
> 13>files.cpp
> 13>ss.cpp
> 13>vsfs.cpp
> 13>E:\Source_Code\VapourSynth\vapoursynth\AviSynthPlus\avs_core\include\avisynth.h(1146,3): error C2365: “ptUnset”: 重定义；以前的定义是“枚举数”
> 13>E:\Source_Code\VapourSynth\vapoursynth\include\VapourSynth.h(171): message : 参见“ptUnset”的声明
> 13>E:\Source_Code\VapourSynth\vapoursynth\AviSynthPlus\avs_core\include\avisynth.h(1147,3): error C2365: “ptInt”: 重定义；以前的定义是“枚举数”
> 13>E:\Source_Code\VapourSynth\vapoursynth\include\VapourSynth.h(172): message : 参见“ptInt”的声明
> 13>E:\Source_Code\VapourSynth\vapoursynth\AviSynthPlus\avs_core\include\avisynth.h(1148,3): error C2365: “ptFloat”: 重定义；以前的定义是“枚举数”
> 13>E:\Source_Code\VapourSynth\vapoursynth\include\VapourSynth.h(173): message : 参见“ptFloat”的声明
> 13>E:\Source_Code\VapourSynth\vapoursynth\AviSynthPlus\avs_core\include\avisynth.h(1149,3): error C2365: “ptData”: 重定义；以前的定义是“枚举数”
> 13>E:\Source_Code\VapourSynth\vapoursynth\include\VapourSynth.h(174): message : 参见“ptData”的声明
> 13>E:\Source_Code\VapourSynth\vapoursynth\AviSynthPlus\avs_core\include\avisynth.h(1151,3): error C2365: “ptFrame”: 重定义；以前的定义是“枚举数”
> 13>E:\Source_Code\VapourSynth\vapoursynth\include\VapourSynth.h(176): message : 参见“ptFrame”的声明
> 13>E:\Source_Code\VapourSynth\vapoursynth\AviSynthPlus\avs_core\include\avisynth.h(1156,3): error C2365: “peUnset”: 重定义；以前的定义是“枚举数”
> 13>E:\Source_Code\VapourSynth\vapoursynth\include\VapourSynth.h(181): message : 参见“peUnset”的声明
> 13>E:\Source_Code\VapourSynth\vapoursynth\AviSynthPlus\avs_core\include\avisynth.h(1157,3): error C2365: “peType”: 重定义；以前的定义是“枚举数”
> 13>E:\Source_Code\VapourSynth\vapoursynth\include\VapourSynth.h(182): message : 参见“peType”的声明
> 13>E:\Source_Code\VapourSynth\vapoursynth\AviSynthPlus\avs_core\include\avisynth.h(1158,3): error C2365: “peIndex”: 重定义；以前的定义是“枚举数”
> 13>E:\Source_Code\VapourSynth\vapoursynth\include\VapourSynth.h(183): message : 参见“peIndex”的声明
> 13>E:\Source_Code\VapourSynth\vapoursynth\AviSynthPlus\avs_core\include\avisynth.h(1162,3): error C2365: “paReplace”: 重定义；以前的定义是“枚举数”
> 13>E:\Source_Code\VapourSynth\vapoursynth\include\VapourSynth.h(187): message : 参见“paReplace”的声明
> 13>E:\Source_Code\VapourSynth\vapoursynth\AviSynthPlus\avs_core\include\avisynth.h(1163,3): error C2365: “paAppend”: 重定义；以前的定义是“枚举数”
> 13>E:\Source_Code\VapourSynth\vapoursynth\include\VapourSynth.h(188): message : 参见“paAppend”的声明
> 13>E:\Source_Code\VapourSynth\vapoursynth\AviSynthPlus\avs_core\include\avisynth.h(1164,3): error C2365: “paTouch”: 重定义；以前的定义是“枚举数”
> 13>E:\Source_Code\VapourSynth\vapoursynth\include\VapourSynth.h(189): message : 参见“paTouch”的声明

**Comment by myrsloik** [comment]
Use an older version like 3.5.1 then. I won't add support for the new API until it's stable.

**Comment by myrsloik** [comment]
Fixed in master
