### ISSUE TITLE
Missing VideoNode.frames() in docs

### ISSUE THREAD

**Issue by OrangeChannel** [vapoursynth/vapoursynth#584]
https://github.com/vapoursynth/vapoursynth/blob/95015d36f23d0f4d5a4436557f5779fd615e90d2/src/cython/vapoursynth.pyx#L1639 the function (added [3.5 yrs ago](https://github.com/vapoursynth/vapoursynth/commit/786598d62c640357d23800d23684a7f29e627a9f)) is missing in the "Python Reference -> class VideoNode" section of the docs. It is only briefly mentioned in a code block under "Raw Access to Frame Data".

**Comment by myrsloik** [comment]
Patches welcome?
