### ISSUE TITLE
Python test failures

### ISSUE THREAD

**Issue by myrsloik** [vapoursynth/vapoursynth#590]
weakref.py and prop_dict_test.py have failures.

At least half of the ones in prop_dict_test.py appear to be simply due to comparing sets and lists incorrectly but I'm no python expert.

**Comment by myrsloik** [comment]
weakref.py: Should the core proxy object even allow weak references? What's the point when it's a thin wrapper that weakrefs the real core in turn?

**Comment by stuxcrystal** [comment]
I think it would be better if it weren't weak-referenciable.

If one wants to cache something core-specific one should use `vapoursynth.core.core` (which returns the currently active core).

So weakly referencing `_CoreProxy` is a bad idea. Disallowing would immediately answer the incorrect usage with an error.

**Comment by myrsloik** [comment]
Only one error in prop_dict_test.py left to fix now and I'm not sure what the problem is:
=========================
ERROR: test_get_pop (__main__.PropDictTest)
-------------------------------------
Traceback (most recent call last):
  File "C:\libraries\vapoursynth\test\prop_dict_test.py", line 69, in test_get_pop
    self.assertEqual(self.props_rw.popitem(), ("_DurationNum", 1))
  File "src\cython\vapoursynth.pyx", line 1125, in vapoursynth.VideoProps.popitem
TypeError: set object is not an iterator
