### ISSUE TITLE
SVP4 broken with 'master' but works with R50

### ISSUE THREAD

**Issue by zhangboyang** [vapoursynth/vapoursynth#594]
I'm new to vapoursynth & mpv & SVP. I compiled R50 and SVP won't work. Then, I used R49 and SVP works correctly. Log is [coder.log](https://github.com/vapoursynth/vapoursynth/files/4805882/coder.log).

**Comment by myrsloik** [comment]
I'd need to know exactly what it's doing to comment more. Chances are however that SVP did misuse the API but it wasn't detected until now as the log says.

**Comment by zhangboyang** [comment]
I misrecognized `master` as R50, R50 also works, sorry for any inconvenience.
I found SVP broken at 6f5a0fe69fc02cc459d173dd678c08c28bce5f78, but worked at cfd2c0def45b0dda3a1c5c47666bcf6115578a07.
Here is the script & log: [script.zip](https://github.com/vapoursynth/vapoursynth/files/4807451/script.zip)

**Comment by zhangboyang** [comment]
I'm not sure whether this is a vapoursynth bug. If it's not, please tell me and I'll report to SVP.

**Comment by chainikdn** [comment]
It doesn't related to SVP at all.

The minimal script that throws the error:
```
import vapoursynth as vs
core = vs.get_core(threads=5)
clip = video_in
smooth = clip.resize.Point(format=vs.YUV420P8,dither_type="random")
smooth.set_output()
```

When running inside mpv:
```
[vapoursynth] Traceback (most recent call last):
[vapoursynth]   File "src/cython/vapoursynth.pyx", line 2241, in vapoursynth.vpy_evaluateScript
[vapoursynth]   File "src/cython/vapoursynth.pyx", line 2242, in vapoursynth.vpy_evaluateScript
[vapoursynth]   File "/home/chainik/.local/share/SVP4/scripts/22e66dc5.py", line 9, in <module>
[vapoursynth]     smooth = clip.resize.Point(format=vs.YUV420P8,dither_type="random")
[vapoursynth]   File "src/cython/vapoursynth.pyx", line 2071, in vapoursynth.Function.__call__
[vapoursynth]   File "src/cython/vapoursynth.pyx", line 763, in vapoursynth.mapToDict
[vapoursynth]   File "src/cython/vapoursynth.pyx", line 2069, in vapoursynth.Function.__call__
[vapoursynth] vapoursynth.Error: Cache: nodes foreign to this core passed as input, improper api usage detected
```

BUT if I replace "video_in" with BlankClip and run through vspipe - it works.
So it could be "improper API usage" **in mpv**, but it still works with R50 and earlier.

**Comment by zhangboyang** [comment]
OK, Thank you, sorry for any inconvenience.

**Comment by chainikdn** [comment]
Hey, it's still an issue in either vapoursynth or mpv or both that prevents SVP from working. Please reopen.

**Comment by chainikdn** [comment]
looks like this one breaks things - https://github.com/vapoursynth/vapoursynth/commit/6f5a0fe69fc02cc459d173dd678c08c28bce5f78

**Comment by myrsloik** [comment]
Interesting. That commit fixes some other nasty crashes. Let's summon @stuxcrystal to see if he has any idea why it happens.

**Comment by stuxcrystal** [comment]
I submitted a PR. I'd like to write some additional tests specifically testing the vpy-part of the vapoursynth module.

**Comment by chainikdn** [comment]
yeah, it works

**Comment by myrsloik** [comment]
Closed since it's fixed in master... I guess
