### ISSUE TITLE
Random filtered result

### ISSUE THREAD

**Issue by Ilya87** [vapoursynth/vapoursynth#599]
My OS Arch Linux x86_64, latest git version of vapoursynth.
command line 
vspipe -y script.vpy -s 109400 -e 109400  - | ffmpeg -y -i pipe: -frames:v 1 1_screen.png
The problem is random result of filtered frame taken (different images) every time I execute command above (script not changed).

script:
```
import vapoursynth as vs
from havsfunc import QTGMC
from havsfunc import MCTemporalDenoise
from havsfunc import SMDegrain
from havsfunc import LSFmod
file = r'VideoFile.mkv'
load = vs.core.ffms2.Source
clip = load(file)
clip = QTGMC(clip, Preset='Slower', SourceMatch=3, Lossless=2, TFF=True)
clip = MCTemporalDenoise(clip, settings="low", edgeclean=True, ECrad=6, MVsharp=False, deblock=True, useQED=True)
clip = SMDegrain(clip,  tr=3, interlaced=False, thSAD=180, pel=2, subpixel=2, search=5, prefilter=-1, blksize=8, overlap=4, contrasharp=False, RefineMotion=False, chroma=True, plane=4)
clip = LSFmod(clip, defaults='slow', Smode=3, strength=200)
clip.set_output()
```

**Comment by myrsloik** [comment]
Try setting `vs.core.num_threads = 1` at the start of the script and see if the output becomes consistent.

You should also try to reduce the script to a few filters if possible so the actual reason can be determined.

**Comment by Ilya87** [comment]
Option `vs.core.num_threads = 1 ` doesn't help.

**Comment by Ilya87** [comment]
The problem was in vspipe - it just give 1 frame to filters. 
With `vspipe -y script.vpy -s 109400 - | ffmpeg -y -i pipe: -ss 0.5 -frames:v 1 1_screen.png` the output is quite the same even with above filter list. But it's only about `vs.core.num_threads = 1` option. Multithreading still provide **noticeable** difference.

**Comment by dubhater** [comment]
With your original vspipe and ffmpeg commands, does the problem go away if you add ``vs.core.std.SetMaxCPU("none")`` before the QTGMC line?

**Comment by Ilya87** [comment]
vs.core.std.SetMaxCPU("none") even with vs.core.num_threads = 1 doesn't help.

**Comment by dubhater** [comment]
Please run this then:
```
valgrind --log-file=valgrind.txt vspipe -y script.vpy -s 109400 -e 109400 .
```
and attach valgrind.txt.

**Comment by Ilya87** [comment]
@dubhater 
vapoursynth was recompiled with `CFLAGS and CXXFLAGS "-march=native -mtune=native -O -g2 -pipe -fno-plt"`, `CPPFLAGS="-D_FORTIFY_SOURCE=2"`
One log for vs.core.num_threads = 1 and vs.core.std.SetMaxCPU("none"), second - without. 
[valgrind_default_threads.txt](https://github.com/vapoursynth/vapoursynth/files/4831225/valgrind_default_threads.txt)
[valgrind_one_thread.txt](https://github.com/vapoursynth/vapoursynth/files/4831226/valgrind_one_thread.txt)

**Comment by dubhater** [comment]
Are you running the latest MVTools? If you're not, update that and try piping to ffmpeg again. If you are running the latest MVTools, or if you updated it and the problem is still happening, recompile MVTools the way you did VapourSynth and run it in valgrind again to see where the problem is.

**Comment by Ilya87** [comment]
[valgrind_default_threads.txt](https://github.com/vapoursynth/vapoursynth/files/4832807/valgrind_default_threads.txt)
[valgrind_one_thread.txt](https://github.com/vapoursynth/vapoursynth/files/4832808/valgrind_one_thread.txt)

**Comment by Ilya87** [comment]
Now (with the rebuild of mvtools) single-threaded script with many filters results look the same. It could be gcc bug.

**Comment by myrsloik** [comment]
Possible miscompile. No updates for a long time.
