### ISSUE TITLE
[Discussion] Arguments in VapourSynth APIv4

### ISSUE THREAD

**Issue by stuxcrystal** [vapoursynth/vapoursynth#602]
I split up this discussion from #59 so other issues that could be addressed in APIv4 could be discussed over there.

This Post only holds the latest comment from myrsloik.

----

> While you're implementing APIv4:
> Perhaps it would be a good idea to somehow let plugins specify what they return in each function. This would solve problems with function-signature generation in Python.
> 
> For example, vsgenstubs currently just assumes every plugin-function just returns clips which is not the case.

Since we're on the subject of arguments. My plan at the moment is to have a way to enumerate all functions in a plugin (that vsmap string dump is horrible) and getting the plugin part of the info as well. Is returning the in and out arguments as a string good enough? Should that be improved too?

_Originally posted by @myrsloik in https://github.com/vapoursynth/vapoursynth/issues/59#issuecomment-656052783_

**Comment by stuxcrystal** [comment]
I think this is good enough with strings.

I think we should provide the parameters in some form of a datastructure. That way, we could also add default values to the function signature.

**Comment by myrsloik** [comment]
Not all things have static defaults. Actually about half the things have defaults that vary depending on other arguments and input clips. Not a fan of the added complexity with relatively limited benefits.

**Comment by myrsloik** [comment]
See the last few commits in doodle1 for the somewhat improved api.

**Comment by myrsloik** [comment]
How should V3 filters be handled (the case of no hint available)? Should I lie and say it's a single video node, report it as unknown or report it and "anything is possible"?

**Comment by stuxcrystal** [comment]
I would say, anything is possible. Those who actually care about types will probably file appropriate issues to the plugin author, if issues can be filed against the project.

**Comment by myrsloik** [comment]
Can you take a look at the argument bits in the doodle1 branch? It's nearing completion but I suspect I did mess up the return type hints since I have no idea what I'm doing. There are also some environment policy bits I'll create another issue for later...
