### ISSUE TITLE
get_core() is deprecated but is still used in docs

### ISSUE THREAD

**Issue by theChaosCoder** [vapoursynth/vapoursynth#604]
Now that get_core() is actually deprecated https://github.com/vapoursynth/vapoursynth/pull/571 
The docs should be updated too. Every example code still uses **core = vs.get_core()**
http://www.vapoursynth.com/doc/functions/frameeval.html

**Comment by myrsloik** [comment]
There will be a huge revision in the V4 api update once it gets closer to being stable.

**Comment by myrsloik** [comment]
Done in doodle1 branch

**Comment by theChaosCoder** [comment]
Wouldn't it be better to change `core = vs.get_core()` simply to `core = vs.core` ?

**Comment by myrsloik** [comment]
Maybe... maybe not. There's a huge documentation revision coming soon anyway...
