### ISSUE TITLE
High core count workstations and "more than 64 cpu detected, thread affinity may not work properly :("

### ISSUE THREAD

**Issue by gcs8** [vapoursynth/vapoursynth#606]
Is there anything I can do to help rectify this? I would assume the solution would be to just using NUMA detection and or something like `core.numa = ` or being able to set certain tasks to use the appropriate NUMA node(s). Let me know if I am just holding it wrong. 

```vspipe -v
more than 64 cpu detected, thread affinity may not work properly :(
VapourSynth Video Processing Library
Copyright (c) 2012-2020 Fredrik Mellbin
Core R50
API R3.6
Options: -```

```OS: Microsoft Windows 10 Pro
64Bit OS: Yes
GPU0: NVIDIA Quadro P4000
GPU1: NVIDIA Quadro P4000
CPU0: Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz
CPU1: Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz
Total CPU Cores: 40
Total Logical Processors: 80
RAM: 512 GB```

**Comment by HolyWu** [comment]
`start /NODE xxx /AFFINITY xxx vspipe ...`?

**Comment by myrsloik** [comment]
Alternatively turn off hyperthreading if you have so many threads. It'll probably give you the highest single script speed. Otherwise what @HolyWu said, run one instance/NUMA node. I may take another look at NUMA support in the coming weeks.

**Comment by gcs8** [comment]
ok, let me work with the encoder/script writer and see if we can make that work. Otherwise, please feel free to reach out for anything involving this and I will do what I can to help. 

side note (you can ignore this part if you want): I have been looking for something that would give me some insight into thread scaling and other performance tuning for VS.

**Comment by myrsloik** [comment]
Things that are already done in the doodle1 development branch that may be of interest to you (won't be ready to test for another week or two so check back then):
Measurements of time spent in each individual filter
Filter graph visualization in dot file format
Uses mimalloc as the memory allocator which is NUMA aware

**Comment by gcs8** [comment]
It breaks task manager a bit also. 

![image](https://user-images.githubusercontent.com/64696803/88973830-b5c08d80-d285-11ea-974a-97f2faddf150.png)

**Comment by gcs8** [comment]
Looks like it has issues over 100G of ram also? probably a new thread but I don't know where it writes logs.

![image](https://user-images.githubusercontent.com/64696803/88974495-b3aafe80-d286-11ea-9956-fdf2ced9b231.png)

**Comment by myrsloik** [comment]
That's probably a failed allocation due to address space fragmentation. Or at least that's my guess...

**Comment by gcs8** [comment]
The scriptwriter thinks it might be bm3d, we gave it lots to work with. Anyway, will stop cluttering up the issue.

**Comment by myrsloik** [comment]
Updated test builds can be found here:
https://forum.doom9.org/showthread.php?t=177623

**Comment by gcs8** [comment]
Well, off to a "great" start.

**Comment by gcs8** [comment]
ok, I am gonna have to dick with this for a bit or rollback to R50.

![image](https://user-images.githubusercontent.com/64696803/90851002-5fed7b80-e341-11ea-8957-864eb95d3d7c.png)
