### ISSUE TITLE
Environment policy changes

### ISSUE THREAD

**Issue by myrsloik** [vapoursynth/vapoursynth#609]
Mostly for @stuxcrystal 

The VS/VSScript API has been changed a lot which affects the core creation a bit. The function vpy4_evaluateBuffer() now takes a VSScriptOptions struct argument (or NULL for defaults) where the core creation flags and a per core message handler can be supplied and should be applied immediately when a core is created with addLogHandler. The function vpy4_clearLogHandler simply removes it if it's set.

Feel free to implement this in a reasonable way and expose the core creation flags to the policy stuff as well.

Note that all old entry points still have to exist and work the same for older API compatibility.

**Comment by stuxcrystal** [comment]
I noticed that createScript for vpy4 does not accept `const VSScriptOptions*`. It however should, since that one actually creates the environment and thus should accept the script options.

**Comment by myrsloik** [comment]
Sounds reasonable I guess. Go ahead and do it. Note that there is no separate function call to create a script environment in the new api. It all starts in vpy4_evaluateBuffer().

**Comment by stuxcrystal** [comment]
I will open a PR once R51 is out.

**Comment by myrsloik** [comment]
I got all the typos out but there's still something that makes it crash inside vpy4_freeScript(). Let's see if you can spot it before I have to print() debug it...

**Comment by stuxcrystal** [comment]
ok

**Comment by stuxcrystal** [comment]
Can you push your changes somewhere?

**Comment by myrsloik** [comment]
Pushed to doodle1

**Comment by stuxcrystal** [comment]
So I did some print debugging for you. It happens here: `env.core.funcs.removeLogHandler(env.log, env.core.core)` at `_unsetLogger`

**Comment by myrsloik** [comment]
Fixed it. Tried to unset the logger after the core was unreferenced.

**Comment by myrsloik** [comment]
Does core.log_message() work properly when you add a logger through the environment policy for you? I'm not sure how to test that bit and for some random reason core.add_log_handler() likes to return cryptic errors too.
