### ISSUE TITLE
How to find out color space using VFW interface?

### ISSUE THREAD

**Issue by stax76** [vapoursynth/vapoursynth#615]
Is there a way to find out the color space using the VFW interface?

If not, I would like to suggest the expansion of IAvisynthClipInfo to IAvisynthClipInfo2 and return the AviSynth color space there.

**Comment by myrsloik** [comment]
What's wrong with using the FOURCC like intended? That's how it's already exposed.

**Comment by stax76** [comment]
Maybe I should create a thread at doom9 or do you know how I map from FOURCC DWORD to avisynth color?

**Comment by myrsloik** [comment]
Here's the list I've compiled over the years. It's more or less the fourccs with the simplest way to represent every format that actually has some kind of application support.
https://github.com/vapoursynth/vapoursynth/blob/master/src/common/fourcc.h

**Comment by stax76** [comment]
Thanks
