### ISSUE TITLE
Maximum breaks with certain coordinates in 16 bit

### ISSUE THREAD

**Issue by kgrabs** [vapoursynth/vapoursynth#621]
Maximum sometimes sets the whole right half of the frame to 0. It seems to happen whenever diagonal-only coordinates are used (i.e. [1,0,1,0,0,1,0,1]) with 16 bit. It looks like 8 bit and 32 bit are unaffected by this, at least

[Test with coordinates=[1,0,0,0,0,0,0,1]](https://slow.pics/c/1jUnnJmu)

**Comment by myrsloik** [comment]
SetMaxCPU("none") fixes it, right?

**Comment by kgrabs** [comment]
Yeah that fixed it for me

**Comment by sekrit-twc** [comment]
7cbe60f
