### ISSUE TITLE
Vertical Videos Frying

### ISSUE THREAD

**Issue by juuuli** [vapoursynth/vapoursynth#622]
![20200814_173400](https://user-images.githubusercontent.com/69698342/90294664-f955f280-de54-11ea-9e83-3701e5265a4e.jpg)
Recently whenever I try to encode a vertical video no matter what my sharpening settings are it always turns out like this. Is there anything I can do?

**Comment by theChaosCoder** [comment]
No script, no sample, blurry image. We can't mind read.
