### ISSUE TITLE
VS stops processing?

### ISSUE THREAD

**Issue by nobananasforyou** [vapoursynth/vapoursynth#623]
import vapoursynth as vs
import ASTDR as astdr
core = vs.core

src = core.d2v.Source(r'ed.d2v')
src = core.vivtc.VFM(src, order=1, cthresh=8, chroma=False, mchroma=False, micmatch=2)
src = core.vivtc.VDecimate(src, chroma=False)
src = astdr.ASTDRmc(src)
src.set_output()

script: https://github.com/dubhater/vapoursynth-astdr

vdub error:
Dub: I/O thread has not cycled for thirty seconds -- possible livelock.  (Thread action: reading video data from disk) (Current address: 00007FFDE945F9A4).

Both vs editor and virtualdub2 hang/freeze/stop processing once the script is loaded.

**Comment by dubhater** [comment]
Broken by the latest commit: https://github.com/dubhater/vapoursynth-astdr/commit/29c34acbf65404473e5b061d92a83d425539ce68

(It shows two places where Hqdn3d is called, but the second one doesn't run when ASTDR(mc) is called with the default parameters.)

Is there a problem with using two instances of a fmSerial filter?

**Comment by myrsloik** [comment]
First observation:
Hqdn3d is marked as fmSerial which it wrong. Should be fmParallelRequests which will speed it up a bit more so that should be changed anyway. Let's see what else is wrong...

**Comment by myrsloik** [comment]
Should be fixed in both branches now

**Comment by dubhater** [comment]
I picked fmSerial two years ago, but of course I didn't leave a note explaining why.

**Comment by myrsloik** [comment]
I don't see anything that requires it. The fmSerial mode only means a single frame is started and finished and does nothing for the request order in any other way so it won't help the serial processing needs of this filter. It'd probably be safer to make it fully parallel and use the past 3 frames or something...

**Comment by theChaosCoder** [comment]
What about **fmParallelRequests**?
I just compiled it with fmParallel and fmParallelRequests. fmParallel crashes after some frames, but fmParallelRequests seems to be stable. I could not find any quirks (not much tested)

Speed went from 385fps to 450 fps

**Comment by theChaosCoder** [comment]
Update:
I tested Hqdn3d with the latest astdr commit with fmParallelRequests and fmSerial mode. I also installed https://github.com/vapoursynth/vapoursynth/issues/625#issuecomment-675475856 R52-test1

ASTDR with Hqdn3d fmParallelRequests crashes after ~5000 frames
ASTDR with Hqdn3d fmSerial had no problems

**Comment by myrsloik** [comment]
Oh, never mind. It does need to be fmSerial due to the horrible logic to try to pretend access is linear. What you can do is try to determine how many frames are actually relevant and produce more than +-1 pixel value difference.
