### ISSUE TITLE
Vapoursynth R51 now produces video aliasing output compared to R50

### ISSUE THREAD

**Issue by mikaljan** [vapoursynth/vapoursynth#625]
Hi,

I discovered that with the R51 release, it now produces video aliasing output compared to R50 release.
The following zip contains a short segment which shows the difference between R51 vs R50 output.

**https://drive.google.com/file/d/1NG8-dmdqdgZ2_V6e7XeW2ihjVfKTFWqG/view?usp=sharing**

Please view the video in full screen to see the details better, and pay attention to the horizontal rail in the background, and also the guy in the blue on the left, about 5 seconds into the video, you can see a lot of aliasing that exist in R51 but not in R50.  

The exact same code was used on both R51 and R50:
clip = core.ffms2.Source(r"D:\Original_Video.mkv", cachefile=r"D:\Original_Video_temp\Original_Video.ffindex")
clip = core.std.Levels(clip, min_in=16, max_in=235, min_out=6, max_out=250, planes=[0], gamma=0.9)
clip = core.std.SetFieldBased(clip, 2) # 1 = BFF, 2 = TFF
clip = havsfunc.QTGMC(clip, TFF = True, Preset = "Placebo", InputType=0, SourceMatch=3, Sharpness=0.2, Lossless=2)
clip = core.cnr2.Cnr2(clip)
clip = fvsfunc.AutoDeblock(clip)
clip = muvsfunc.GradFun3(src=clip, mode=6, smode=1)
clip = havsfunc.FineDehalo(clip)
clip = muvsfunc.nnedi3aa(clip)
clip = core.std.Crop(clip, 10, 2, 2, 2)
clip = resamplehq.resamplehq(clip, 960, 720, kernel="Gauss")
clip.set_output()

Something changed between R50 and R51

**Comment by myrsloik** [comment]
Try to narrow it down and not use every function in existence, it'll make things so much easier for me.

**Comment by mikaljan** [comment]
ok, i'll try to narrow it down tomorrow

**Comment by myrsloik** [comment]
Here's a build you can test to see if it fixes the issue:
[VapourSynth64-R52-test1.exe](https://www.dropbox.com/s/6gdt0hnz2y2e50i/VapourSynth64-R52-test1.exe?dl=1)

**Comment by mikaljan** [comment]
ok, let me try

**Comment by mikaljan** [comment]
> Here's a build you can test to see if it fixes the issue:
> [VapourSynth64-R52-test1.exe](https://www.dropbox.com/s/6gdt0hnz2y2e50i/VapourSynth64-R52-test1.exe?dl=1)

Hi myrsloik,

Yes, that fixed the video aliasing issue with the R51, thanks!!
So what was wrong with it? out of curiosity.

**Comment by myrsloik** [comment]
I think it was a bug that managed to sneak into AverageFrames

**Comment by myrsloik** [comment]
Fixed in R52-RC1
