### ISSUE TITLE
Incorrect _ChromaLocation when doing a no-op Resize with chroma location overriding

### ISSUE THREAD

**Issue by tvasenin** [vapoursynth/vapoursynth#626]
I have a clip foo with `_ChromaLocation = 2`.

I run `bar = core.resize.Bicubic(foo, chromaloc_in = 3, chromaloc = 3)`

Even though it's a no-op, this location value(s) should still override the frame props (unless user sets `prefer_props=True`).

Expected: bar should have `_ChromaLocation = 3`
Actual: bar has `_ChromaLocation = 2`

**Comment by sekrit-twc** [comment]
1646fb7aa5

**Comment by tvasenin** [comment]
Correct commit, just for future reference: e1784d080c7ce33e7040d557926d839bb1532522
