### ISSUE TITLE
Windows 10 long paths support

### ISSUE THREAD

**Issue by stax76** [vapoursynth/vapoursynth#629]
I would like to request long path support in Windows 10. Currently, long paths don't work with long path prefix `\\?\` but only using 8.3 names. I would like to request native long path support that don't need a prefix or short name.

https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#maximum-path-length-limitation

https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#short-vs-long-names

https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#enable-long-paths-in-windows-10-version-1607-and-later

This is frequently requested by staxrip users.

https://github.com/staxrip/staxrip/issues/226#issuecomment-687586840

D:\Projekte\VB\staxrip\bin\Apps\FrameServer\VapourSynth\vspipe.exe "C:\Users\frank\long path\iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii\iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii\iiiiiiiiiiiiiiiiiiiiiiiiiiiii\iiiiiiiiiiiiiiiiiiiiiiiiiiiiii\iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii\iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii\iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii\iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii\iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii\iiiiiiiiiiiiiiiiiiiiiiiiiiiiiii\aaa_temp\aaa_new.vpy" - --y4m | D:\Projekte\VB\staxrip\bin\Apps\Encoders\x265\x265.exe --crf 18 --output-depth 10 --frames 4069 --y4m --output "C:\Users\frank\LONGPA~1\IIIIII~1\IIIIII~1\IIIIII~1\IIIIII~1\IIIIII~1\IIIIII~1\IIIIII~1\IIIIII~1\IIIIII~1\IIIIII~1\aaa_T~1\aaa_new_out.hevc" -

Script evaluation failed:
File reading exception:
[Errno 2] No such file or directory: 'C:\\Users\\frank\\long path\\iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii\\iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii\\iiiiiiiiiiiiiiiiiiiiiiiiiiiii\\iiiiiiiiiiiiiiiiiiiiiiiiiiiiii\\iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii\\iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii\\iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii\\iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii\\iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii\\iiiiiiiiiiiiiiiiiiiiiiiiiiiiiii\\aaa_temp\\aaa_new.vpy'
x265 [error]: unable to open input file <->

**Comment by myrsloik** [comment]
I'll add it to the manifest. All code already supports it.

**Comment by stax76** [comment]
I would like to find out if a generic manifests is possible, as far as I know it is. I want to know it, so I can suggest it to other.

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0" xmlns:asmv3="urn:schemas-microsoft-com:asm.v3" >
  <assemblyIdentity version="0.0.0.0" name="undefined"/>
  <description>WindowsExecutable</description>
  <trustInfo xmlns="urn:schemas-microsoft-com:asm.v2">
    <security>
      <requestedPrivileges>
        <requestedExecutionLevel level="asInvoker" uiAccess="false"/>
      </requestedPrivileges>
    </security>
  </trustInfo>
  <application xmlns="urn:schemas-microsoft-com:asm.v3">
    <windowsSettings xmlns:ws2="http://schemas.microsoft.com/SMI/2016/WindowsSettings">
      <ws2:longPathAware>true</ws2:longPathAware>
    </windowsSettings>
  </application>
</assembly>
```

Here is a small link collection:

staxrip:
https://raw.githubusercontent.com/staxrip/staxrip/master/My%20Project/app.manifest

mkvtoolnix:
https://gitlab.com/mbunkus/mkvtoolnix/-/raw/main/src/extract/manifest.xml.erb

mpv:
https://raw.githubusercontent.com/mpv-player/mpv/master/osdep/mpv.exe.manifest

mpv.net:
https://raw.githubusercontent.com/stax76/mpv.net/master/mpv.net/app.manifest

**Comment by stax76** [comment]
More info:

https://github.com/staxrip/staxrip/wiki/Windows-10-long-path-support

**Comment by stax76** [comment]
Project -> Properties -> Linker -> Manifest File

```
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
    <assemblyIdentity name="none" version="0.0.0.0"/>
    <application xmlns="urn:schemas-microsoft-com:asm.v3">
        <windowsSettings>
            <longPathAware xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">true</longPathAware>
        </windowsSettings>
    </application>
</assembly>
```
