### ISSUE TITLE
[Question] How to build VapourSynth with non-installed zimg?

### ISSUE THREAD

**Issue by antimatter84** [vapoursynth/vapoursynth#632]
I have cloned the VapourSynth and zimg repositories and I have successfully built the zimg library. I ran "make" but not "make install" because I don't want to install the lib.

Now I want to compile VapourSynth and provide the paths to the compiled zimg library. The configure script finds zimg, but fails to link it. 
```
$ ZIMG_LIBS=../zimg-release-2.9.3/ ./configure
...
checking for ZIMG... yes
configure: error: failed to link zimg. See config.log for details.
```
The config.log contains lines like these:
```
configure:13248: g++ -o conftest  ../zimg-release-2.9.3/src/zimg/api  conftest.cpp ../zimg-release-2.9.3/ >&5
conftest.cpp:27:10: fatal error: zimg.h: No such file or directory
   27 | #include <zimg.h>
      |          ^~~~~~~~
compilation terminated.
```
There seems to be something missing, because the <zimg.h> is not found. I played around with ZIMG_CFLAGS parameter, but could make it work. I'm a bit lost here. Can someone help?

**Comment by sekrit-twc** [comment]
ZIMG_CFLAGS

**Comment by antimatter84** [comment]
Hello, I don't know what you would like to tell me with this very short reply.

**Comment by sekrit-twc** [comment]
ZIMG_CFLAGS=-I{path_to_zimg.h} ZIMG_LIBS="-L{path_to_zimg.a} -lzimg"
