### ISSUE TITLE
[Question] Is there a way to limit cache size?

### ISSUE THREAD

**Issue by arition** [vapoursynth/vapoursynth#634]
I am working in a container environment that has memory limitation enforced by the host. 

I find that when I run six vapoursynth instances, out of memory errors happen frequently. However, I can run six vapoursynth instances on another computer which has less memory than the container. 

I find that when I run ```top``` command in container, it displays the size of host's memory, which is much larger than the the memory allocated to the container. I think maybe vapoursynth also gets the wrong memory size and assume a lot of memory space can be used by cache. 

So, my question is, is there a way to limit cache size manually?

**Comment by therealt3nzin** [comment]
http://vapoursynth.com/doc/pythonreference.html?highlight=max_cache_size#Core.max_cache_size

**Comment by arition** [comment]
@therealt3nzin Thanks! Not noticing this :P
