### ISSUE TITLE
Does Not Work with Python 3.9

### ISSUE THREAD

**Issue by ddelella** [vapoursynth/vapoursynth#636]
![image](https://user-images.githubusercontent.com/548747/96881745-91bbb500-144c-11eb-95c1-6b0b5817f392.png)

This is the image you get when Python 3.9 is installed and you try to install R52.

**Comment by theChaosCoder** [comment]
The message clearly says that you need python 3.8. Python 3.9 will be supported in future versions.

**Comment by ddelella** [comment]
> The message clearly says that you need python 3.8. Python 3.9 will be supported in future versions.

The whole point of the issue is to add support for 3.9 since it is now the latest for python.

**Comment by DJATOM** [comment]
I've done a pyrhon version bump on master branch and proposed a PR. In case you don't know how to compile on your own, here's my build: https://mega.nz/folder/6gsEQLjK#tLJjjYzZJMGSKHj4NTyqLA

**Comment by l00tzOMG** [comment]
> I've done a python version bump on master branch and proposed a PR. In case you don't know how to compile on your own, here's my build: https://mega.nz/folder/6gsEQLjK#tLJjjYzZJMGSKHj4NTyqLA

Thank you very much. Unfortunately the portable version cannot be unpacked (tried with both 7z and winrar...). It's probably broken.

**Comment by DJATOM** [comment]
Ok, I've uploaded new build and packed portable with LZMA method. Now it should be fine.

**Comment by rlaPHOENiX** [comment]
I know this is closed, but it would be nice if VapourSynth had PATCH# versional updates just to deal with stuff like this when possible. I'm sure it wouldnt be that difficult? Why does VapourSynth use a revision based version system too instead of semver, e.g. since VapourSynth is on v3 API, wouldnt it be ideal to state the version as v3.n.n for v3 VS API, and when v4 comes out, bump to v4.n.n. Essentially go with a similar setup as Python. This way to push small releases to support other python versions you could simply do v3.52.1 (VS API 3, Revision 52, Patch 1)

**Comment by rlaPHOENiX** [comment]
> 
> 
> > I know this is closed, but it would be nice if VapourSynth had PATCH# versional updates just to deal with stuff like this when possible. I'm sure it wouldnt be that difficult? Why does VapourSynth use a revision based version system too instead of semver, e.g. since VapourSynth is on v3 API, wouldnt it be ideal to state the version as v3.n.n for v3 VS API, and when v4 comes out, bump to v4.n.n. Essentially go with a similar setup as Python. This way to push small releases to support other python versions you could simply do v3.52.1 (VS API 3, Revision 52, Patch 1)
> 
> Your versioning is weak. I don't have the time or desire to produce builds for more than one python version due to support complexity. Development truly happens on a straight line in the master branch as well. And do you know what that means?
> 
> YOU CAN LOP OFF THE v1.X.0 BITS SINCE ONLY THE X EVER REALLY CHANGES! MAGIC!

Fair enough, but it would still be ideal to produce builds for the latest python versions as they release as stable

**Comment by myrsloik** [comment]
Ideal would be if I got paid to do this. See the pattern?
