### ISSUE TITLE
Memory leak occurring and I don't know where or why.

### ISSUE THREAD

**Issue by rlaphoenix** [vapoursynth/vapoursynth#644]
On my [VSMPEG](https://github.com/rlaPHOENiX/VSMPEG/) VapourSynth Script, if I load a DVD MPEG-2 video file, and click preview in VapourSynth Editor multiple times, VapourSynth begins to use a ton of memory.

![image](https://user-images.githubusercontent.com/17136956/99980054-b8e50980-2d9f-11eb-80e9-dc800eec23ed.png)

It gets to the point where my system will entirely freeze or crash, but luckily on Linux it detects the Memory leak and instead crashes VS Edit on purpose to clear the memory before it gets to Dangerous levels.

It seems to specifically be whenever I click Preview, and not directly any action within the script. As in, playing frames or seeking e.t.c doesn't seem to make any difference, just when I click preview.

I guess it is possible that it's an issue with [VapourSynth Editor](https://bitbucket.org/mystery_keeper/vapoursynth-editor) though, but I thought it would be best to ask here first.

**Comment by theChaosCoder** [comment]
Could be this https://forum.doom9.org/showthread.php?p=1922237#post1922237

**Comment by rlaPHOENiX** [comment]
> Could be this https://forum.doom9.org/showthread.php?p=1922237#post1922237

That does seem like it could be why. I wonder if the original repository will take any of the fixes.

**Comment by gundamftw** [comment]
The problem is this:

https://forum.doom9.org/showthread.php?p=1922363#post1922363

**Comment by rlaPHOENiX** [comment]
> The problem is this:
> 
> https://forum.doom9.org/showthread.php?p=1922363#post1922363

I should note I'm on Arch Linux, so DLLs wouldn't be used unless it also refers to shared-objects.

**Comment by sekrit-twc** [comment]
You can use this program to check if the VPY itself is leaking memory:

````
#include <stdio.h>
#include "VSScript.h"

int main(int argc, char **argv)
{
	const char *path = argv[1];
	const VSAPI *vsapi;
	char tmp[256];
	int n;

	vsscript_init();
	vsapi = vsscript_getVSApi();

	for (n = 0; n < 1000; ++n) {
		VSScript *script;
		VSNodeRef *node;
		VSFrameRef *frame;
		vsscript_evaluateFile(&script, path, efSetWorkingDir);
		vsscript_getOutput(script, 0);
		frame = vsapi->getFrame(0, node, 0, 0);
		vsapi->freeFrame(frame);
		vsapi->freeNode(node);
		vsscript_freeScript(script);

		printf("iteration #%d, press 'b' to exit\n", n);
		if (gets(tmp)[0] == 'b')
			break;
	}

	vsscript_finalize();
}
````

**Comment by rlaPHOENiX** [comment]
https://bitbucket.org/mystery_keeper/vapoursynth-editor/issues/43/memory-leak-in-relation-to-the-preview

I do believe this is an issue with vapoursynth-editor and not vapoursynth, so for now I will close the issue and I have moved it to vapoursynth-editor.

**Comment by gundamftw** [comment]
The high memory usage of vseditor came from three areas:

1. vseditor's own frame caching and queue caching
2. Vapoursynth's memory pre-allocation
3. memory leak when the core was freed

Your problem here is 3.

**Comment by myrsloik** [comment]
#3 is actually a result of how windows library loading/unloading works. I plan to fix that one in the next release by simply never unloading loaded dlls.

**Comment by rlaPHOENiX** [comment]
> #3 is actually a result of how windows library loading/unloading works. I plan to fix that one in the next release by simply never unloading loaded dlls.

I should note, I'm on Linux and crashing still occurs, though it takes a fair bit longer.

**Comment by myrsloik** [comment]
You can try to comment out the dlclose() calls and see if things improve

**Comment by myrsloik** [comment]
Could also be caused by Python's memory allocator which never releases memory back to the system.
