### ISSUE TITLE
VapourSynth installer is not working if Python Version > 3.8

### ISSUE THREAD

**Issue by AlucardSama04** [vapoursynth/vapoursynth#645]
I'm trying to install VapourSynth R52 but I have Python 3.9.0, is there any way to install VapourSynth without downgrading to Python 3.8?

OS: Windows 10

**Comment by myrsloik** [comment]
No, 3.8.x is required for the official installer. Go complain to the python developers who hate binary compatibility.

**Comment by theChaosCoder** [comment]
There's always the portable version option.

**Comment by AlucardSama04** [comment]
I would never use that, sorry.
