### ISSUE TITLE
[REQ] Haiku (sup)port

### ISSUE THREAD

**Issue by forart** [vapoursynth/vapoursynth#648]
Hi there, since [MEDO](https://github.com/smallstepforman/Medo) (a modern Media Editor built exclusively for the open source [Haiku OS](https://www.haiku-os.org/) - aka the Media OS) has been recetly released, the need for a "contemporary" frameserver becomed more urgent.

Dunno if can help in any way, but @qyot27 is also working on [AviSynthPlus porting](https://github.com/AviSynth/AviSynthPlus/pull/199) with some success:
![avp_haiku](https://user-images.githubusercontent.com/171307/103272122-509bd000-49bc-11eb-98ab-e4e7e18ecaa7.png)

Thanks in advance.

**Comment by myrsloik** [comment]
Patches welcome

**Comment by forart** [comment]
Dunno if can help in any way, but @qyot27 has just officially added the "Haiku support" for AviSynth+:

>[AviSynth+ 3.7.0 has been released](https://github.com/AviSynth/AviSynthPlus/releases/tag/v3.7.0), Haiku support is now in the master branch and tarballs.
>
>When I first posted, the only source filter I had tested was FFMS2, but thanks to some other fixes that came through for MinGW-w64 and Linux support in the past few days, the ImageSeq plugin can be used as a source filter now too. The ImageSource function allows users to import still image formats through the use of the DevIL library.
>
>When I get some time I’ll try to get a set of general build instructions posted, but AviSynth+ has a very small set of dependencies - basically just CMake and GCC. If you have devil_devel installed, CMake will be able to detect it and enable ImageSeq.

Hope that inspires !

**Comment by forart** [comment]
Dunno if can help in any way, but here's the [AviSynth+](https://github.com/AviSynth/AviSynthPlus) discussion @ Haiku forums...
https://discuss.haiku-os.org/t/avisynth-scripting-nle-frameserver/10086

...and the new recipe @ [Haikuports](https://github.com/haikuports/haikuports):
https://github.com/haikuports/haikuports/pull/5614

Hope that inspires !
