### ISSUE TITLE
Import Linux AviSynth plugins into Linux VapourSynth

### ISSUE THREAD

**Issue by ghost** [vapoursynth/vapoursynth#652]
Is it possible? I get an error.
`core.avs.LoadPlugin('/usr/local/lib/avisynth/libtivtc.so')`
`No attribute with the name avs exists`

Linux AviSynth now has an exclusive TIVTC (TDecimate) plugin and I would like to import it in Linux VapourSynth.
https://github.com/pinterf/TIVTC
https://github.com/pinterf/TIVTC/issues/14

**Comment by myrsloik** [comment]
Definitely not possible since it's only implemented for windows at the moment. I suppose linux support is theoretically possible to add so I'll leave this issue open as a reminder.

**Comment by theChaosCoder** [comment]
That means avs dlls also doesn't work on VS linux? If avs.LoadPlugin() gets implemented someday, would it be possible to also load *.dlls or only *.so libs?

**Comment by myrsloik** [comment]
> That means avs dlls also doesn't work on VS linux? If avs.LoadPlugin() gets implemented someday, would it be possible to also load *.dlls or only *.so libs?

Only native so libs obviously. Use wine for all your windows compatibility needs...

**Comment by myrsloik** [comment]
Not going to happen unless someone else does it
