### ISSUE TITLE
No information display in ffmpeg

### ISSUE THREAD

**Issue by ghost** [vapoursynth/vapoursynth#653]
http://www.vapoursynth.com/2020/08/r52-titles-are-meaningless/

> why is there no information display in ffmpeg?

Since comments are closed, I'll reply here.
ffmpeg must be compiled statically with vapoursynth support. In this case, the information will be shown and vspipe is not required.
Before import, you need to specify
`ffmpeg -f vapoursynth -i input.vpy`
Apparently this is a ffmpeg bug. Linux AviSynth has a similar problem
https://github.com/AviSynth/AviSynthPlus/issues/194

**Comment by myrsloik** [comment]
Why are you reporting it here if it's an ffmpeg bug?

**Comment by artenaki** [comment]
I am planning to inform the ffmpeg team about this issue.
But I think the information will also be useful in the Issues section of VapourSynth project. It will be possible to refer to it.

**Comment by artenaki** [comment]
https://trac.ffmpeg.org/ticket/9059
