### ISSUE TITLE
Is there a way to see what plugin loaded a clip?

### ISSUE THREAD

**Issue by rlaPHOENiX** [vapoursynth/vapoursynth#654]
My current method forcefully sets a new prop called Sourcer (specifically `PVSSourcer`) and checks in various code by grabbing the first frame, and seeing if it has the prop and if so, using that's string value.

I'm wondering if there's a better way than this?

**Comment by myrsloik** [comment]
Not at the moment, no.

**Comment by rlaPHOENiX** [comment]
It would be awesome to have in the future then

**Comment by sekrit-twc** [comment]
The graph tracing feature in the audio branch might be of interest.

**Comment by myrsloik** [comment]
If we're speaking of the future then clip properties may be of even more interest... (once I imlplement them)
