### ISSUE TITLE
y4m output: wrong "XLENGTH" when vspipe trimming is used.

### ISSUE THREAD

**Issue by the-real-tokai** [vapoursynth/vapoursynth#656]
I understand that the value in the y4m header is purely a comment (`X…`), but vspipe writes out the original clip's length to the `XLENGTH` value instead the actual stored frame range, e.g.

```
$ vspipe --start 1 --end 1 --y4m foobar.vpy - > a_single_frame.y4m

$ hexdump -C -n 64 a_single_frame.y4m
00000000  59 55 56 34 4d 50 45 47  32 20 43 34 32 30 20 57  |YUV4MPEG2 C420 W|
00000010  31 32 38 30 20 48 37 32  30 20 46 32 34 30 30 30  |1280 H720 F24000|
00000020  3a 31 30 30 31 20 49 70  20 41 30 3a 30 20 58 4c  |:1001 Ip A0:0 XL|
00000030  45 4e 47 54 48 3d 33 35  32 34 35 0a 46 52 41 4d  |ENGTH=35245.FRAM|
00000040
```

Note that it is `XLENGTH=35245` (or whatever the clip's length is that the script generates) instead `XLENGTH=1`.

**Comment by DJATOM** [comment]
@the-real-tokai 
I made a PR with fix. If you need that change asap, modified VSPipe is [here](https://github.com/vapoursynth/vapoursynth/files/5883376/VSPipe.zip).

**Comment by myrsloik** [comment]
Merged so will be fixed in the next version
