### ISSUE TITLE
Installer doesn't find existing VC++ redistributable

### ISSUE THREAD

**Issue by markfilipak-windows** [vapoursynth/vapoursynth#660]
Hello Fredrik,

Trying to install VapourSynth (64-bits) R52 I encountered a "Setup" dialog:

"The following applications are required before setup can continue:
"Visual C++ 2015-2019 64-Bit Redistributable (14.3 MB)
"Download and install now?"

There are two issues:
1, 'Control Panel' > 'Programs and Features' shows:
"Microsoft Visual C++ 2015-2019 Redistributable (x64) - 14.22.27821", and
2, My Windows 10-1803 does not have access to the Internet -- this is by design.

The installation cannot proceed.

Do you have any suggestions?
Regards,
Mark.

**Comment by DJATOM** [comment]
1) download redists somewhere else and install
2) use no-redist avisynth installer

**Comment by markfilipak-windows** [comment]
Thank you.
Regarding 1: I already have the redistributables installed.
Regarding 2: I don't have avisynth.

**Comment by DJATOM** [comment]
Ah, sorry, I mixed up repos. Since there's no "non-redist" vapoursynth package, you can try portable version. Just download embedded python archive, extract somewhere and extract vapoursynth portable in that folder. Then put needed plugins into `.\vapoursynth64\plugins`. Scripts can be placed for example into `.\scripts`, just add that line into `python39._pth`.

**Comment by markfilipak-windows** [comment]
I've already installed python... was it 3.8? I think so ...So I should put the portable into the 'c:\Program Files\Python38\' folder? Is that what you mean or am I not understanding? If so, that would be rather inconvenient, and perhaps there's a way to path to 'c:\Program Files\Python38\' from within VS, perhaps a configuration file?
Or should I uninstall python? Guidance, please. :-)

**Comment by DJATOM** [comment]
No, with portable build there's need to use special [embedded version](https://www.python.org/ftp/python/3.8.7/python-3.8.7-embed-amd64.zip) (assuming you're using 64 bit version). System-wide python shouldn't hurt it.

**Comment by DJATOM** [comment]
If you patient enough, I can build fresh release from repository and pack without redists (if you have a troubles with portable), but that will take some time.

**Comment by markfilipak-windows** [comment]
Can you be more specific, DJATOM? Of course I know that '.\' is current directory, but where in my file system would '.\vapoursynth64' be? I'll put it wherever you say. And would '.\scripts' actually be '.\vapoursynth64\scripts' or '.\script' with same parent directory as '.\vapoursynth64'?

**Comment by markfilipak-windows** [comment]
Sorry about that last post. I can't edit it because the controls in github don't work.

Can you be more specific, DJATOM? Of course I know that '.\' is current directory, but where in my file system would '.\vapoursynth64' be? I'll put it wherever you say. And would '.\scripts' actually be '.\vapoursynth64\scripts' or '.\script' with same parent directory as '.\vapoursynth64'?

**Comment by markfilipak-windows** [comment]
Jeez! How to I insert dot-backslash?

**Comment by DJATOM** [comment]
`.` refers to directory where portable python3/vapoursynth placed.

**Comment by markfilipak-windows** [comment]
I meant to write: How do I insert dot-backslash. Gawd github is just awful.

**Comment by DJATOM** [comment]
Idk, `.\`  types fine from desktop.

**Comment by markfilipak-windows** [comment]
You tell me where to put it, please.

**Comment by markfilipak-windows** [comment]
I don't know what "Idk, .\ types fine from desktop" means.

**Comment by DJATOM** [comment]
[VapourSynth64-R52.1-no-redist.exe.zip](https://github.com/vapoursynth/vapoursynth/files/5936651/VapourSynth64-R52.1-no-redist.exe.zip)
So much trouble explaining howto use portable, just try that version (install python 3.9 x64 first).

**Comment by markfilipak-windows** [comment]
Okay, let's start over, shall we?
Suppose I put the VS portable & python here: 'c:\CMD & tiny apps\VapourSynth\'. Do I need to create 'c:\CMD & tiny apps\VapourSynth\vapoursynth64\plugins' and 'c:\CMD & tiny apps\VapourSynth\scripts'? Or is it 'c:\CMD & tiny apps\VapourSynth\vapoursynth64\scripts'?

**Comment by markfilipak-windows** [comment]
I use portable apps all the time.

**Comment by DJATOM** [comment]
>c:\CMD & tiny apps\VapourSynth\vapoursynth64\plugins

No, it's already in the archive. Just extract python embedded and Vapoursynth into `c:\CMD & tiny apps\VapourSynth` (python first, then vapoursynth, replacing existing files). You only need to create folder for scripts (c:\CMD & tiny apps\VapourSynth\scripts) and declare that path for portable python 
```
python38.zip
.
.\scripts
```
in the `python38._pth`

**Comment by markfilipak-windows** [comment]
You told me to download this: https://github.com/vapoursynth/vapoursynth/files/5936651/VapourSynth64-R52.1-no-redist.exe.zip, so I did. It's an installer, not a portable. Now you tell me "extract python embedded and Vapoursynth". Now I'm at the side of the road in the weeds.

**Comment by DJATOM** [comment]
xD
Since you suggested to try portable again, I followed that.
My file is system-wide installer, I just cut vsredist stuff from it. If you manage to install from that file, skip other instructions.

**Comment by markfilipak-windows** [comment]
I have not idea what you are trying to tell me. Let's start with this: What does 'xD' mean?

**Comment by markfilipak-windows** [comment]
I didn't suggest "to try portable again", you did.

**Comment by markfilipak-windows** [comment]
Just tell me what to download and what to do with it, please.

**Comment by markfilipak-windows** [comment]
In Windows, I prefer installs. In Linux, I prefer portable (in a virtual machine). I'm installing in Windows but I'll do whatever you recommend.

**Comment by DJATOM** [comment]
Sorry, but it seems language barrier is no go for us. I can't help with my current knowledge, I just can't explain things better. English is not my native language.

**Comment by markfilipak-windows** [comment]
I know. That's why I'm asking you to simply tell me what to download and what to do with it.
Let me give you some perspective. I don't know whether VS is a GUI or a CLI. If a GUI, then I would think it needs the C++ redistributables. If a CLI, then what good would redistributables be, eh?

**Comment by DJATOM** [comment]
>I don't know whether VS is a GUI or a CLI. 

CLI, dll library and python module.

>If a CLI, then what good would redistributables be, eh

It uses msvc redistributable's functions internally, so does not work without it.

**Comment by markfilipak-windows** [comment]
Hang on, please... (Don't comment until I come back, okay?)

**Comment by myrsloik** [comment]
Either use the portable version that includes all runtimes or install a RECENT VERSION of the VS2019 runtime. Your computer has a too old one.

**Comment by markfilipak-windows** [comment]
What should I download?

VapourSynth64-Portable-R52.7z  7.59 MB?
or
VapourSynth64-R52.exe  11.3 MB?
or
somthing else?

**Comment by markfilipak-windows** [comment]
Well, I guess you are not coming back here. I downloaded VapourSynth64-Portable-R52.7z and will see how it goes. But I don't know about python. Python doesn't appear to be there, so this will probably fail.

**Comment by gundamftw** [comment]
These type of questions should be ask in the [forum](https://forum.doom9.org/forumdisplay.php?f=82).

**Comment by markfilipak-windows** [comment]
Thank you, and please excuse me. I didn't know there was a VS forum.
