### ISSUE TITLE
Now what do I do?

### ISSUE THREAD

**Issue by markfilipak-windows** [vapoursynth/vapoursynth#661]
From 'C:\CMD & tiny apps\VapourSynth\doc\installation.html':

"Windows Portable Instructions
"
"First download and decompress the prerequisites:
"        Python 3.8.x – 32 or 64 bit embeddable version
"Simply decompress the portable VapourSynth archive into the Python dir and overwrite all existing files. Done.
"You can also use the VapourSynth Editor by decompressing it into the same directory."

I put the entire contents of this:
'https://www.python.org/ftp/python/3.8.7/python-3.8.7-embed-amd64.zip'
and the entire contents of this:
'https://github.com/vapoursynth/vapoursynth/releases/download/R52/VapourSynth64-Portable-R52.7z'
(together) into here:
'C:\CMD & tiny apps\VapourSynth\'.
Is that what I was supposed to do?

According to this:
'C:\CMD & tiny apps\VapourSynth\doc\gettingstarted.html'

"Getting Started
"
"So you managed to install VapourSynth. Now what?
"If you don’t know the basics of Python, you may want to check out a tutorial.
"You can “play around” in the python interpreter if you want, but that’s not how most video scripts are created."

Now what do I do? There are no clues how to launch VS.

**Comment by richardpl** [comment]
Consult fine documentation. It is perfect.

You write vpy scripts, than execute them either via vspipe or other wrappers like ffmpeg.
If you want GUI, launch vapoursynth-editor and write python scripts.

**Comment by markfilipak-windows** [comment]
May I suggest, in addition to the code fragment in the "Windows Installation Instructions" section of installation.html, that the "Windows Portable Instructions" section suggest this:
[code]
>python
Python 3.8.7 (tags/v3.8.7:6503f05, Dec 21 2020, 17:59:51) [MSC v.1928 64 bit (AMD64)] on win32
>>> from vapoursynth import core
>>> print(core.version())
VapourSynth Video Processing Library
Copyright (c) 2012-2020 Fredrik Mellbin
Core R52
API R3.6
Options: -

>>> [/code]

**Comment by markfilipak-windows** [comment]
Gawd, github is awful. Why does anyone use it?

**Comment by markfilipak-windows** [comment]
That post was supposed to look like a Windows command line, but github turned it into vertical lines. I would fix it, but clicking on the '...' just brings up a spinner that never stops spinning. Github sucks so bad!

**Comment by markfilipak-windows** [comment]
"Consult fine documentation. It is perfect."
Oh, no. Not another project that claims to be perfect. Please, not that.

**Comment by richardpl** [comment]
Only hardcore programmers use python directly.
You write just scripts in text editor and run them with vspipe.

**Comment by richardpl** [comment]
Also you need to install couple of external plugins like ffms2 or better and couple of plugins.

sample script:

import vapoursynth as vs                                                                                                                                                                                                        
core = vs.get_core() 
clip = core.ffms2.Source("x.y4m")
clip = core.std.Transpose(clip)
clip.set_output()

**Comment by markfilipak-windows** [comment]
"You write vpy scripts, than execute them either via vspipe or other wrappers like ffmpeg.
If you want GUI, launch vapoursynth-editor and write python scripts."
Excellent. Now why doesn't the documentation say that, eh? I spent half a year learning ffmpeg. The ffmpeg documentation is also "perfect". It says NOTHING about running VS.

Neither the Contents of the documentation or the Index says anything about ffmpeg. How do I use VS with ffmpeg? I want to do stuff equivalent to this:
ffmpeg -i INPUT -filter_complex "split [1][2], [1]...do some stuff modulo 5...[3]. [2]...do some other stuff...[4], [3][4]interleave" ...codec directives here... OUTPUT.

**Comment by markfilipak-windows** [comment]
No offense intended, but programmers should not write documentation. They should put comments in their code (which they rarely do) and leave the documentation to documentarians.

**Comment by richardpl** [comment]
You can not mix VS and ffmpeg filters.

To use ffmpeg build with vpy script support just run:

ffmpeg -f vapoursynth -i script.vpy

If your build does not have VS support you can not use ffmpeg directly, but only indirectly via pipes.

**Comment by markfilipak-windows** [comment]
I'm serious. It's the true path to happiness... the way with heart. I will help. I want to help. I'm a documentarian (in addition to being an electrical engineer).

**Comment by markfilipak-windows** [comment]
richardpl kindly wrote: "If your build does not have VS support you can not use ffmpeg directly, but only indirectly via pipes."
I download ffmpeg nightly builds that have every build option. I've not seen a VS build option, ever.

**Comment by Lypheo** [comment]
Clearly they dont have every build option enabled, then.

**Comment by 4re** [comment]
You don't need ffmpeg compiled with vapoursynth, just use a pipe:
```
vspipe -y myScript.vpy - | ffmpeg -y -f yuv4mpegpipe -i pipe: myNewVideo.mkv
```

**Comment by markfilipak-windows** [comment]
@4re, Thank you!

How did you discover yuv4mpegpipe? (It appears solely in 'ffmpeg -formats', 'ffprobe -demuxers', 'ffprobe -formats', and 'ffprobe -muxers' with zero detail.)

Do you know how I can incorporate svpflow1 & svpflow2? That's the reason I'm considering VS. After 1/2 year of struggling with ffmpeg (and becoming disillusioned with Handbrake), I'm getting tired of the struggle.

**Comment by 4re** [comment]
About how I knew about it, I don't know, I used this at some point in my life.
And I don't know anything about svpflow, but because is a paid solution (I think, those guys just disgust me too much to dig into it) on their homepage should be an easy-to-follow tutorial and tech support.

**Comment by richardpl** [comment]
> @4re, Thank you!
> 
> How did you discover yuv4mpegpipe? (It appears solely in 'ffmpeg -formats', 'ffprobe -demuxers', 'ffprobe -formats', and 'ffprobe -muxers' with zero detail.)
> 
> Do you know how I can incorporate svpflow1 & svpflow2? That's the reason I'm considering VS. After 1/2 year of struggling with ffmpeg (and becoming disillusioned with Handbrake), I'm getting tired of the struggle.

There is documentation for yuv4mpeg aka y4m on internet. FFmpeg is not dictionary for dummies.

**Comment by markfilipak-windows** [comment]
@4re wrote: "I think, those guys just disgust me too much to dig into it".

Oh, I get it:
https://lookup.icann.org/lookup of SVP-TEAM.COM
"Mailing Address: DATA REDACTED, DATA REDACTED, DATA REDACTED, Saint-Petersburg, DATA REDACTED, RU".

**Comment by DJATOM** [comment]
Is there something wrong with Slavic devs? I don't get the joke, if any implied.

**Comment by markfilipak-windows** [comment]
@DJATOM. I don't do business with Russians.

**Comment by DJATOM** [comment]
Well, that's your right. I'm not Russian, but I do speak that language. As for SVP, there's probably no adequate alternative available, so good luck waiting for someone else who will re-implement a wheel.
