### ISSUE TITLE
Random Glitches in output video

### ISSUE THREAD

**Issue by servese43** [vapoursynth/vapoursynth#664]
Hi,
I'm using Vapoursynth to deinterlace some video using QTGMC. In resulting video, however, there are always a few tiny little glitches, at seemingly random places. The video just jumps back for a split second, and then continues as normal. I just want to know if there is something wrong on my end, or whether this is a big in the code of vapoursynth. I am running R52 on Manjaro linux. The script I am using goes as follows:

```
from vapoursynth import core
import havsfunc as haf
clip = core.ffms2.Source(source='input.mkv')
clip = haf.QTGMC(clip, Preset='Slow', TFF=True)
clip = core.std.Crop(clip, top=26, bottom=24, left=0, right=0)
clip.set_output()
```

And to save it as a file I am running:
vspipe --y4m script.vpy - | ffmpeg -i pipe: -crf 19 -preset slow encoded.mkv

Thank you very much for your help,
servese43

**Comment by 4re** [comment]
My bet is ffms2's fault, it's known for not getting along with temporal filters. Try with l-smash-works instead.

**Comment by servese43** [comment]
I'll give that a shot now. Thanks for your help!

**Comment by servese43** [comment]
Sorry, probably me just being a noob, but I get this error why I try using lsmashsource:
```
[importer: Error]: failed to find the matched importer.
Script evaluation failed:
Python exception: lsmas: failed to open file.
```
The script I am now using is this:

```
from vapoursynth import core
import havsfunc as haf

clip = core.lsmas.LibavSMASHSource(source='Input.mkv')
clip = haf.QTGMC(clip, Preset='Slow', TFF=True)
clip = core.std.Crop(clip, top=26, bottom=24, left=0, right=0)
clip.set_output()
```

**Comment by servese43** [comment]
Cool, it works perfectly with LSMASHSource. Thanks heaps for your help!

**Comment by 4re** [comment]
LibavSMASHSource is for mp4 files, LWLibavSource is for everything.
