### ISSUE TITLE
Max memory usage increases and spikes significantly with frames processed on Linux

### ISSUE THREAD

**Issue by quietvoid** [vapoursynth/vapoursynth#665]
Hi,

My system runs Arch Linux, a 5900X and 32GB ram.

I'm having trouble with both vspipe and `output()`, the memory usage increases as more frames are processed, and eventually it gets killed because OOM.
I've noticed lowering VS threads helps mitigate the issue, but with more complex scripts the memory still increases too much.

See script here: https://pastebin.com/UXfUrci8

Now I've used the max process memory to compare, but it is only a max and not the average memory usage over the process run.
I've noticed the memory does spike very high, and with current master it stays high until completion.

So I tried adding more garbage collection calls, but it has only lowered the average memory. The spikes are still present.
The first patch I tested is here: https://github.com/quietvoid/vapoursynth/commit/c24555a5d695bee14fd0825a110af8ab972c9f6e

I'm using the `vapoursynth` package for master, and vapoursynth-git

Results between master and patched:
```
master
Frame: 1500/1500
Max memory usage: 5323076
Frame: 4500/4500
Max memory usage: 11220752
Frame: 9000/9000
Max memory usage: 26682832

patched
Frame: 1500/1500
Max memory usage: 5674212
Frame: 4500/4500
Max memory usage: 11091560
Frame: 9000/9000
Max memory usage: 26551716
```

Monitoring the last 9000 frames run, the memory fluctuates a lot between 18GB and 27GB used, which makes little sense to me.

I'm still not sure why there are such memory spikes that only happen when more frames are processed, and I think they are the reasons I get a lot of OOM killed `vspipe` processes.

**Comment by dubhater** [comment]
> the memory usage increases as more frames are processed

As more frames are processed, they become bigger because you tied the frame height (and width) to the frame number. Keeping just 100 frames in the cache can be a lot:

```python
>>> def howbig(start, end):
...  sum = 0
...  for height in range(start, end):
...   width = height * 1920 / 1080
...   size = width * height * 4
...   sum += size
...  print("{} megabytes".format(sum / 1024 / 1024))
... 
>>> howbig(1400, 1500)
1425.430976019965 megabytes
>>> howbig(4400, 4500)
13426.977199978302 megabytes
```

Even if you add ``core.add_cache=False`` at the top, you'll still have about 12 or 24 frames in memory at the same time because of your CPU's core count.

**Comment by quietvoid** [comment]
I'm not sure I understand, why would past frames affect current memory use? Is the cache never cleared?

Lowering threads to 4 is not a solution either, I have tried and it still eventually goes out of memory. Limiting the cache doesn't work well either.

**Comment by dubhater** [comment]
You should post your own script.

text.CoreInfo tells me that the cache is staying under the limit.

**Comment by quietvoid** [comment]
My own script is using many different functions,
I'm still trying to determine whether it is a plugin/function problem or Vapoursynth itself.

I've made this test script: https://pastebin.com/UXfUrci8

**Comment by quietvoid** [comment]
Now I had more things using memory, but my test with 5000 frames ended up using 10GB.
And my 10 000 frames OOM'd around 6000 frames in.

**Comment by dubhater** [comment]
There could be a leaky filter in there.

**Comment by quietvoid** [comment]
Seems to be, memory usage is normal without using `ssimdown`.

Will look into both `vs-placebo` and the SSIM GLSL.
Cheers.
