### ISSUE TITLE
VSPipe does not pass each frame at a time on Windows PowerShell

### ISSUE THREAD

**Issue by rlaPHOENiX** [vapoursynth/vapoursynth#666]
for example:
```ps
vspipe --y4m -p -r 1 --arg "Input=E:/.../file.mkv" "vsmpeg.vpy" - | ffmpeg -i - -y -c:v libx264 "out.mkv"
```

This seems to only happen with Powershell and not Command Prompt. You will see the progress information given by `-p` will render each frame and not actually pipe it to ffmpeg. It seems to wait for all the frames to finish, and THEN pass ALL of them to FFMPEG at once.

The following command on CMD Command Prompt works fine:
```bat
vspipe --y4m --arg "Input=E:/.../file.mkv" "vsmpeg.vpy" "-" | ffmpeg -i pipe: -y -c:v libx264 "out.mkv"
```

The only difference being - needing to be wrapped in quotes, and that single 's dont work.

**Comment by theChaosCoder** [comment]
https://github.com/vapoursynth/vapoursynth/issues/536
