### ISSUE TITLE
misc.Hysteresis: incorrect mask for YUV4xxPS U/V planes

### ISSUE THREAD

**Issue by AkarinVS** [vapoursynth/vapoursynth#681]
`misc.Hysteresis` is supposed to generate bi-level masks, and for YUV masks,
the range for U/V plane should still be 0.0 ~ 1.0, not -0.5 ~ 0.5. (Otherwise, the
generated masks won't be usable in our `std.MaskedMerge`.)

However, our current implementation uses -0.5 for unmarked U/V plane pixel,
and 0.5 for marked pixels.

see:
https://github.com/vapoursynth/vapoursynth/blob/cb6bb3d1cccce7501978d54be46f91a0d8cc51ba/src/filters/misc/miscfilters.cpp#L852-L860
and
https://github.com/vapoursynth/vapoursynth/blob/cb6bb3d1cccce7501978d54be46f91a0d8cc51ba/src/filters/misc/miscfilters.cpp#L744-L750

I have also checked the avisynth+ masktools2 implementation, and confirmed
that there shouldn't be any special handling of U/V planes.
see:
https://github.com/pinterf/masktools/blob/53d943f964238ea406cd890d924d222b50554cb7/masktools/filters/mask/hysteresis/hysteresis.cpp#L21

I will be happy to prepare a PR if the issue is accepted.
Thanks.

**Comment by sekrit-twc** [comment]
Agree that we should have all masks be 0...1. Additionally, should the color family be changed to cmRGB for masks (float and otherwise)?

**Comment by AkarinVS** [comment]
I think we still need to keep the input colorspace as it's perfectly valid
to have subsampling for U/V masks (and VS does not support subsampling for
the RGB colorspace).

**Comment by myrsloik** [comment]
Maybe it's better to simply define all mask planes as having a 0-1 range then. The float bits really haven't been that thought through...

**Comment by AkarinVS** [comment]
Yes, i think for masks, all planes have a range of 0-1, regardless of color
spaces.
At least this is the definition used by avs' masktools.

**Comment by sekrit-twc** [comment]
Does this issue also affect other mask-generation filters like MakeDiff?

**Comment by myrsloik** [comment]
MakeDiff is a simple a-b so it's technically not a mask filter and works in its own -1 - +1 range effectively. Binarize should maybe be looked at since I'm not sure what the defaults are.

**Comment by AkarinVS** [comment]
Indeed, Binarize also uses -0.5/0.5 for U/V planes. (I've updated my PR 682
to keep this issue open when merged.)

While fixing the issue for misc.Hysteresis is technically a bugfix as the
current behavior is not really usable and it's specially for generating
bi-level masks,
I can't say the same for Binarize: even though it is usually used as a mask
generator, its docs do say v0/v1 default to min/max value allowed by
format, which is -0.5 and 0.5 in the case of floating point YUV formats.
Therefore technically the current behavior is to be expected.

Is there any practical use for the current behavior of std.Binarize?

Also, what about std.Invert? I don't think we can change its behavior, but
perhaps we should explicitly document that it won't work as expected for
floating point YUV mask clips.

**Comment by myrsloik** [comment]
Invert is a more difficult case since mask inversion and image inversion are different things. Effectively masks aren't YUV but a separate YYY format (with subsampling). I think we'll simply need to try to think of every single filter where this could matter and then figure out a consistent solution.

**Comment by sekrit-twc** [comment]
An alternative would be to change std.MaskedMerge to add +0.5 to U/V planes for YUV masks. This would prevent std.Invert needing different semantics for clips and masks. In a sense, this is also how integer masks work, as 0 is encoded as `(2**INT_BITS)/2`.

**Comment by myrsloik** [comment]
Currently proposed solution: make filters like MaskedMerge only take Y planes for masking and make the mask argument an array

**Comment by AkarinVS** [comment]
Could we fix Binarize as well?

Its docs specify v0=0, so it's already contradicting the code.
As Binarize is primarily used to generate masks, I find it very confusing
to document that it can't be used to generate floating point YUV masks....

We can't do anything for invert, so I'm OK with documenting that. Will send
a PR for that.

**Comment by AkarinVS** [comment]
Found another filter assuming -0.5/0.5 for U/V planes: TCanny.

Given that (the old) misc.Hysteresis, std.Binarize, std.Invert and TCanny,
all make the same assumption, I'm wondering if we should just make it the
standard and change std.MaskedMerge to use [-0.5, 0.5] for U/V planes in
floating point YUV masks?

If we decide to change std.MaskedMerge, we need to figure out what does
premultiplied clip mean in this case.
Does that mean clipb is multiplied with (0.5+mask) or clipb is multiplied
with mask?

**Comment by sekrit-twc** [comment]
Premultiplication does not change the alpha channel, so it would mean that the clip is premultiplied by (0.5+mask). As for TCanny, it should just be fixed. The internal mask-producing filters do not work in -0.5...0.5:

- Expr: expression ("0 255 ?") needs to be customized per-format. [0...1] would provide consistency between YUV and RGB expressions
- Sobel/Prewitt: produces [0...Inf], or [0...1] after clamping
- Alpha channels: alpha is always the Y plane
- Conversion from integer: this one produces [-0.5...0.5], but the fix is easy (add +0.5)

**Comment by myrsloik** [comment]
Mask clip conventions implemented. Created an issue for TCanny so maybe that'll be updated soon too.
