### ISSUE TITLE
How to  build deb file for vapoursynth

### ISSUE THREAD

**Issue by kodxana** [vapoursynth/vapoursynth#683]
Hello is there any way to build an package vapoursynth into deb file for Linux?

**Comment by dubhater** [comment]
Please refer to the Ubuntu or Debian documentation about making packages. Good luck! 😈😈

**Comment by artenaki** [comment]
checkinstall --install=no ?
https://wiki.debian.org/CheckInstall

**Comment by artenaki** [comment]
You can repackage or rebuild the plugins using deb-multimedia as an example. This is still easier than compiling for Windows. http://deb-multimedia.org/dists/stable/main/binary-amd64
repack:
```
su -
cd /home/user
mkdir -p temp
dpkg-deb -R original.deb temp
#replace the files with your precompiled versions
dpkg-deb -b temp fixed.deb
```
rebuild (using vlc as an example):
```
sudo apt install devscripts build-essential dpkg-dev fakeroot patch
sudo apt build-dep vlc
apt source vlc
cd vlc
debuild -us -uc -b
sudo dpkg -i *.deb
```
