### ISSUE TITLE
Poor compatibility with UWP Python 3.9

### ISSUE THREAD

**Issue by BinToss** [vapoursynth/vapoursynth#684]
Python.exe and Python3.9.exe both lead to my Python 3.9 install.
![Clipboard01.webp](https://user-images.githubusercontent.com/7243190/116954335-973c5800-ac44-11eb-9cf8-87cbb3f9c3a4.png)

**Comment by BinToss** [comment]
I believe the issue is that the Window Store releases of Python register the applications, but not the DLLs.

**Comment by BinToss** [comment]
Adding `C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.9_3.9.1264.0_x64__qbz5n2kfra8p0\\` to the System PATH variable resolved it.

**Comment by BinToss** [comment]
Nevermind. I did not test the solution correctly.
After adding the WinStore Python 3.9 directory to PATH, the dll is now accessible as a path variable, but the Vapoursynth setup still can't find my Python 3.9 install.

**Comment by BinToss** [comment]
I believe I've found the real cause.
The VapourSynth installer checks for Python via the Windows Registry.
https://github.com/vapoursynth/vapoursynth/blob/cb6bb3d1cccce7501978d54be46f91a0d8cc51ba/installer/vsinstaller.iss#L271-L275

However, the UWP Python releases do not create the expected Registry keys.
![image](https://user-images.githubusercontent.com/7243190/116958797-990c1880-ac50-11eb-8bd7-aece900304bc.png)

The best alternative containing UWP Python 3.9's path is...
- `HKCU\Software\Microsoft\Windows\CurrentVersion\App Paths\python3.9.exe`
  <ul>
    <li> (Default) : <code>C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1264.0_x64__qbz5n2kfra8p0\python3.9.exe</code> </li>
    <li> Path : <code>C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1264.0_x64__qbz5n2kfra8p0</code></li>
  </ul>

Or simply get the parent directory of the Python39.exe path variable and append Python39.dll to the resulting path.

**Comment by myrsloik** [comment]
The MS Store version of python isn't supported. Use the desktop installer form python.org

**Comment by BinToss** [comment]
I set up the expected registry keys and the Vapoursynth is happy with the
result. I'll upload the exported .reg when I have the time.

**Comment by BinToss** [comment]
> The MS Store version of python isn't supported. Use the desktop installer form python.org

I understand.
However, I'm stubborn as hell and I got it working with the UWP version of Python 3.9.4...sorta.

Auto-generated Vapoursynth scripts were be unable to `import vapoursynth as vs`. Likewise, `from vapoursynth import core` resulted in the same error:
`ImportError: DLL load failed while importing vapoursynth: The specified module could not be found.`

Every time Python UWP 3.9.4 is started, it starts without any modules imported, including `os`.
Also, its default environment is very restrictive. DLLs can only be loaded from Python's system DLL directory or the user's DLL directory unless os.add_dll_directory() is used at runtime to add additional directories.

**Comment by BinToss** [comment]
I was finally able to `import vapoursynth`.

The issue was the location of vapoursynth.dll.
`%LocalAppData%\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Lib\site-packages\vapoursynth.dll`
works when moved to
`%LocalAppData%\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\vapoursynth.dll`

After moving it (and creating a junction link to \Python39\ named Lib as a precaution), VSPipe no longer outputs the "Failed to initialize VapourSynth environment" error. I used [this part of the VapourSynth documentation](https://vapoursynth.com/doc/installation.html#compilation) as reference.
Specifically...
![image](https://user-images.githubusercontent.com/7243190/117524817-1ba81700-af74-11eb-8f38-d53c70bc2188.png)

I had also tried creating the PYTHONPATH environment variable and adding `D:\\apps\\vapoursynth\\` and `D:\\apps\\vapoursynth\\core`, but it didn't seem to do anything.

Next, I need to figure out why SVP4 is still unable to initialize its VapourSynth script.

**Comment by myrsloik** [comment]
> Hopefully, the information I post here may be used to improve UWP Python compatibility in the future.

No, it won't. I've investigated this before and reported issues to the Python developers. They don't care and therefore neither do I. Use the proper windows installer.

**Comment by BinToss** [comment]
So...
This whole wild goose chase was started because I was hoping UWP Python would work as a replacement for the win32 Python whose installers haven't worked on my PC in years.
I tried it again just now and the win32 installer did not halt while installing pip, py launcher, tkinter, or other modular feature.

Somebody pinch me.
