### ISSUE TITLE
pip install vapoursynth fails on python 3.9 and Big Sur macOS 11.3

### ISSUE THREAD

**Issue by bryanmobrien** [vapoursynth/vapoursynth#685]
As subject says.

```
brew info vapoursynth
vapoursynth: stable 53 (bottled), HEAD
Video processing framework with simplicity in mind
http://www.vapoursynth.com
/usr/local/Cellar/vapoursynth/53 (23 files, 4.3MB) *
  Poured from bottle on 2021-04-25 at 12:29:07
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/vapoursynth.rb
License: LGPL-2.1-or-later
```

```
 vspipe --version
VapourSynth Video Processing Library
Copyright (c) 2012-2021 Fredrik Mellbin
Core R53
API R3.6
Options: -
```

```
python -V
Python 3.9.4
```

When running pip install vapoursynth, pip pulls down VapourSynth-51.zip (although vspipe shows Core 53).
I believe this may be a version mismatch between VapourSynth R51 and VapourSynth53?

Full gist of pip install error is here:  https://gist.github.com/bryanmobrien/5cc66b7a93c317f5c2f93eb02dc59da3

**Comment by 4re** [comment]
Why are you installing that?

**Comment by bryanmobrien** [comment]
I don’t understand.  Is this level of OS/Python not supported?

**Comment by myrsloik** [comment]
The python packages aren't official and not maintained by us. Please contact the maintainer directly (or use the brew version which tends to be instantly updated by its maintainer)
