### ISSUE TITLE
Installer creates invalid link to User Autoload Directory if directory didn't exist

### ISSUE THREAD

**Issue by luglio** [vapoursynth/vapoursynth#694]
If the directory does not exist when VS is installed, it will be created but the link is broken. Otherwise it's fine.
![unknown](https://user-images.githubusercontent.com/13797847/119544997-e95e2e00-bd57-11eb-8ae7-1fcc1b8628b0.png)

**Comment by myrsloik** [comment]
Installer limitation. Run vsrepo and it'll create the dirs.
