### ISSUE TITLE
Building Vapoursynth with ffmpeg master(libav rather) doesn't work anymore

### ISSUE THREAD

**Issue by BlueSwordM** [vapoursynth/vapoursynth#695]
So, with an ffmpeg version >4.4(master build of ffmpeg and the related libav stuff), building Vapoursynth doesn't seem to be possible anymore, as it looks like some functions have been depreciated:
https://pastebin.com/yJyMKfNB

Thankfully should be a simple enough fix. Most people are probably building against distro FFmpeg, which is usually from a release branch, but I am not building from a release branch.

**Comment by myrsloik** [comment]
Pull requests welcome. Should simply be to remove the *register_all() calls and change codec => codecpar.
