### ISSUE TITLE
Can VapourSynth filter add frame properties starting with "_"?

### ISSUE THREAD

**Issue by CrendKing** [vapoursynth/vapoursynth#697]
The [Reserved Frame Properties](http://www.vapoursynth.com/doc/apireference.html#reserved-frame-properties) talks about the frame properties starting with "_". But it's not clear if only these listed properties can start with underscore.

For example, `_AbsoluteTime` is a float of a frame's start time. Can a source filter also put integer property `_AbsoluteTimeInRefTime` which denotes the time in [REFERENCE_TIME unit](https://docs.microsoft.com/en-us/windows/win32/directshow/reference-time) (basically _AbsoluteTime * 10^7)? Or put properties `_DARNum` and `_DARDen` to convey display aspect ratio, etc.

If the underscore is not reserved only for these properties, what is the guideline of when to use underscore? Will VapourSynth add more Reserved Frame Properties in the future? One concern is that a popular filter uses a property starts with underscore, and later VapourSynth adds their own version of the same name (but different meaning), forcing the filter to break backward compatibility.

If the underscore is reserved for these, having `AbsoluteTimeInRefTime` though it's pretty much the same as `_AbsoluteTime` is a bit weird.

**Comment by myrsloik** [comment]
You can add properties named anything but I'd really advise you not to prefix them with underscore. And what's the point of introducing _AbsoluteTime * constant? Seems trivial to compute and it's a double so you don't lose any meaningful precision.
