### ISSUE TITLE
FFMPEG Compatibility with VS R40???

### ISSUE THREAD

**Issue by zacharyhalberd** [vapoursynth/vapoursynth#698]
Hello. I'm new to using VapourSynth and accompanying tools/plugins. I'm simply trying to export an MOV file from VSPipe via the command line and I keep getting this error below. I've run this in VSEdit and it works flawlessly. My suspicion is that the problem lies somewhere near ffmpeg. I'm using Windows 10 Professional and I'm trying to transcode, deinterlace, and conform a miniDV captured as an .AVI file into a progressive ProRes 422 HQ file (rec709).  I am at a total loss at why this export isn't working... Any advice would be helpful 

**Installed Software:**

- Python 3.6.8 - Using for Davinci Resolve 17.2 Studio compatibility reasons
- VapourSynth64-Portable-R40 - Using for compatibility reasons with Python 3.6.8

**#dll files**
ffms2-2.22-msvc
fmtconv-r20
vapoursynth-mvtools-v20-win64
vapoursynth-nnedi3-v12-win64

**#python files**
havsfunc-r31
mvsfunc-r8
vapoursynth-adjust-1
VapourSynth-script-master

**My Current VapourSynth SCRIPT:**

import vapoursynth as vs
import havsfunc as haf
core = vs.get_core()
clip = core.ffms2.Source(source='E:\CAPTURED_ARCHIVAL\thedude_DV_CAPTURE_20210120\\MTNOT002C001.avi')
#clip = vs.core.resize.Point(clip, format = vs.YUV422P10)
#clip = haf.QTGMC(clip, Preset='Slower', TFF=False)
#clip = core.resize.Spline36(clip, 720, 540)
clip.set_output()

**COMMAND LINE AND ERROR:**

C:\Users\thedude\VapourSynth-working version>vspipe --y4m test1.vpy -   | ffmpeg -i pipe: -i "ΓÇ¬E:\CAPTURED_ARCHIVAL\DV_CAPTURE_20210120\GT_T001_C001.avi" -c:v prores -profile:v 3 -c:a copy -map 0:0 -map 1:1 "ΓÇ¬E:\TESTS\thedude_TEST_03\GT_T001_C001_TESTOUTPUT1.mov"

ffmpeg version 4.3.1-2020-11-19-essentials_build-www.gyan.dev Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 10.2.0 (Rev5, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100

Input #0, yuv4mpegpipe, from 'pipe:':
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: rawvideo (Y3[10][10] / 0xA0A3359), yuv422p10le(progressive), 720x540, 59.94 fps, 59.94 tbr, 59.94 tbn, 59.94 tbc
ΓÇ¬E:\CAPTURED_ARCHIVAL\DV_CAPTURE_20210120\GT_T001_C001.avi: Invalid argument
Error: fwrite() call failed when writing frame: 1, plane: 0, errno: 32
Output 14 frames in 3.05 seconds (4.59 fps)

**Comment by dubhater** [comment]
```
ffmpeg -i pipe: -i "ΓÇ¬E:\CAPTURED_ARCHI
```
What is that before the drive letter?

**Comment by zacharyhalberd** [comment]
That's a very good question, but it's exactly what was regurgitated by the command line once I ran the script. Those characters are not in any of my scripts.

**Comment by dubhater** [comment]
So you're using a bat file? Did you check it in a hex editor?

**Comment by zacharyhalberd** [comment]
This issue has been solved. I believe it was the ffmpeg compatibility from version 2.40 in my system. I used the brute force method by installing multiple versions to see which one would stick. So, not really solved so much as stopgapped until I can figure out what was causing the issue. 

I did not check the file in a hex editor. Can you recommend one to use? I've never used one. Good tip!

**Comment by dubhater** [comment]
I don't know any for Windows. A few lines of Python will do the job.
