### ISSUE TITLE
When to use _AbsoluteTime RFP?

### ISSUE THREAD

**Issue by CrendKing** [vapoursynth/vapoursynth#702]
In the [RFP document](http://www.vapoursynth.com/doc/apireference.html#reserved-frame-properties), `_AbsoluteTime` has the description that "Should only be set by the source filter and not be modified". What categorizes as source filter? If user puts a frame interpolation filter (such as AviSynth's ChangeFPS or SVP) on top of FFMS to double the frame rate, should the filter put "_AbsoluteTime" in the interpolated frames? Otherwise, if the downstream renderer directly use "_AbsoluteTime" to determine when to present each frame, those interpolated frames will have exactly the same start time as their source frame.

If the intermediate frame-generating filters are not responsible to assign _AbsoluteTime, the consumer of the frames have to count the frame times and calculate with _DurationXXX RFPs, assuming each frames are adjacent. What if an intermediate filter wants to create "gaps" between frames?

**Comment by sekrit-twc** [comment]
The reason for this advice is that floating-point time is imprecise under addition, whereas _Duration is rational. For a node with variable frame time, the only way to know the precise timestamp of a given frame is to accumulate _Duration. The reason why a rational _AbsoluteTime is unavailable is that it would need to be recalculated with a new time-base any time a frame with an incompatible duration denominator is introduced.
