### ISSUE TITLE
Expr Pixel Addressing

### ISSUE THREAD

**Issue by mysteryx93** [vapoursynth/vapoursynth#703]
I'm trying to run this code ported from Avisynth

    EM.std.Expr("x[0,1]  0.12 * x[0,0] 0.76 * x[0,-1] 0.12 * + +")
    > Failed to convert x[0,1] to float.

Does Vapoursynth Expr support [Pixel Addressing](http://avisynth.nl/index.php/Expr#Pixel_addressing)?

**Comment by sekrit-twc** [comment]
No. Maybe you want ExprCpp.

**Comment by AkarinVS** [comment]
I'm actually working on this feature in my LLVM rewrite.

Is there a way to know the line stride before the first getframe call? i.e.
at filter creation time.

Also, do you want relative pixel addressing or absolute pixel addressing?
(avs uses relative, but would absolute addressing also be useful?)
And how should we handle out of bound coordinates? (avs uses clamping, but
our std.resize.* uses mirror, which one should be used? or perhaps,
configurable?

**Comment by sekrit-twc** [comment]
>Is there a way to know the line stride before the first getframe call?

You can round up to 64 bytes, but this is an implementation detail.

**Comment by mysteryx93** [comment]
This feature would allow for a replacement to the last 2 things I need to convert FrameRateConverter to VapourSynth:

Blur(.6)

    EM.std.Expr("x[0,1]  0.12 * x[0,0] 0.76 * x[0,-1] 0.12 * + +")

mt_expand(mode= mt_circle(zero=True, radius=1))

[ex_expand using Pixel Addressing](https://github.com/Dogway/Avisynth-Scripts/blob/master/ExTools.avsi#L553)

**Comment by sekrit-twc** [comment]
This invocation is equivalent to std.Maximum

**Comment by mysteryx93** [comment]
No, Convolution gives a stronger Blur(1.0), and Maximum gives square patches

    EM = EM.resize.Bicubic(round(C.width/blkSize/4.0)*4, round(C.height/blkSizeV/4.0)*4)
    EM = EM.std.Maximum()
    EM = EM.std.Binarize(maskThr)
    EM = EM.resize.Point(C.width, C.height)

Btw I'm getting a weird issue of vertical blurring on resize; Point should give pure black and white output.

[![Mask-Point.png](https://i.postimg.cc/Pq8JgS4F/Mask-Point.png)](https://postimg.cc/5HbfvqDw)

I need to obtain a mask like this. Maximum gives square patches, and Blur(1) is too strong.

[![MaskAvs.png](https://i.postimg.cc/d1P3wGNQ/MaskAvs.png)](https://postimg.cc/jWcthnrB)

**Comment by sekrit-twc** [comment]
"x[0,1]  0.12 * x[0,0] 0.76 * x[0,-1] 0.12 * + +" is equivalent to std.Convolution([0.12, 0.76, 0.12])

""x[-1,1] x[0,1] max x[1,1] max x[-1,0] max x[0,0] max x[1,0] max x[-1,-1] max x[0,-1] max x[1,-1] max "" is equivalent to std.Maximum

**Comment by mysteryx93** [comment]
I didn't know Convolution could take float numbers! Never seen any example nor usage of it. That could be clarified in the doc, perhaps adding an example.

**Comment by mysteryx93** [comment]
OK I'm able to get a good mask using this

    EM = EM.resize.Bicubic(round(C.width/blkSize/4.0)*4, round(C.height/blkSizeV/4.0)*4) \
        .std.Maximum(coordinates=[0, 1, 0, 1, 1, 0, 1, 0]) \
        .std.Binarize(maskThr) \
        .std.Convolution(matrix=[0, 1, 0, 1, 3, 1, 0, 1, 0]) \
        .resize.Bicubic(C.width, C.height)

Remains a weird issue with Resize

    EMskip = EM.resize.Bicubic(round(C.width//blkSize//4.0)*4, round(C.height//blkSizeV//4.0)*4) \
            .std.Maximum(coordinates=[0, 1, 0, 1, 1, 0, 1, 0]) \
            .std.Binarize(skipThr) \
            .resize.Bicubic(C.width, C.height)

Gives this (5x zoom)

[![Resize-Issue.png](https://i.postimg.cc/zvBFYkZy/Resize-Issue.png)](https://postimg.cc/qhP38y7r)

Also remains replacing mt_expand with mt_circle(radius=8). Other than that, I should be good to go.

Still, supporting Pixel Addressing would be great :)

**Comment by sekrit-twc** [comment]
This artifact is indicative of an interlaced image. You may need to set _FieldBased attribute to 0 prior to resampling.

http://www.vapoursynth.com/doc/apireference.html#reserved-frame-properties

**Comment by myrsloik** [comment]
> I'm actually working on this feature in my LLVM rewrite. Is there a way to know the line stride before the first getframe call? i.e. at filter creation time. Also, do you want relative pixel addressing or absolute pixel addressing? (avs uses relative, but would absolute addressing also be useful?) And how should we handle out of bound coordinates? (avs uses clamping, but our std.resize.* uses mirror, which one should be used? or perhaps, configurable?

The only truly safe way to get the stride is to create a new frame in the constructor with the same dimensions and get it from there and then free it.

**Comment by sekrit-twc** [comment]
Even that relies on the assumption that a given width can have only one stride. It is best to accept a stride argument in the generated code.

**Comment by myrsloik** [comment]
> Even that relies on the assumption that a given width can have only one stride. It is best to accept a stride argument in the generated code.

That assumption is guaranteed in VS that any plane with the same width and bytes per sample will be stored identically. I don't exactly market this fact though.

**Comment by AkarinVS** [comment]
Released my Expr implementation with relative pixel addressing just like
AVS+'s: https://github.com/AkarinVS/vapoursynth-plugin/releases/tag/v0.60.

**Comment by AkarinVS** [comment]
Now that we have an external plugin that implements this feature (shameless
plug: my https://github.com/AkarinVS/vapoursynth-plugin, use the lexpr
releases), do we have plan to incorporate this feature into std.Expr?

It will involve a very significant amount of work to get it working with
jitasm (e.g. the AVS+ implementation uses almost 1k lines to implement this
feature; as a comparison, mine uses 100 lines).

**Comment by myrsloik** [comment]
I don't think it's that important as a feature. Or if it's implemented simply "cheat" and offset the input clips as a separate filter for compatibility purposes. That'd probably let us implement it in ~20 lines. Anyone who wants performance will use your plugin anyway.

**Comment by Setsugennoao** [comment]
This could be closed since it was recently implemented by @AkarinVS in his plugin. [#35b7fb6](https://github.com/AkarinVS/vapoursynth-plugin/commit/35b7fb64fdfc80ee362822cfefa25e9be1b20661)
