### ISSUE TITLE
How to install bm3d and  msvfunc using anaconda env?

### ISSUE THREAD

**Issue by dzh929** [vapoursynth/vapoursynth#704]
Hello, 
   i want to install bm3d and msvfunc by using 'vsrepo.py install' . But this line of code doesn't seem to work :

```
vsrepo.py install bm3d
vsrepo.py install msvfunc
```
![image](https://user-images.githubusercontent.com/61380549/123512397-cfe33580-d6b9-11eb-941a-f989dba9c968.png)

![image](https://user-images.githubusercontent.com/61380549/123512412-ebe6d700-d6b9-11eb-83bd-d354ea432275.png)
![image](https://user-images.githubusercontent.com/61380549/123512498-66175b80-d6ba-11eb-8a84-f816ac89fadc.png)
Windows 10, Python3.8

I don't know how to install it properly, can someone kindly help me?

**Comment by myrsloik** [comment]
Doesn't seem to work means what exacty? What's the error?
Also, you probably mean MVSFUNC

**Comment by dzh929** [comment]
> `vsrepo.py install bm3d` should not print the error arguments required line
> I can not reproduce it. What OS are you using and what happens if you run `vsrepo.py paths`
> How did you install Python? for all users or only for your user?

![image](https://user-images.githubusercontent.com/61380549/125466937-df1b51a3-e9ed-4874-a6f2-3f8ab37c81cc.png)
I don't know whether it is correct to use `vsrepo.py install bm3d ` in this way
I use python in anaconda env with admin authority 
I am not very sure how to use this command `vsrepo.py paths`

**Comment by dzh929** [comment]
> In cmd
> `python vsrepo.py paths`
> or just
> `vsrepo.py paths`
> if your python.exe is in PATH
> 
> I never used anaconda, so can't comment on that.

![image](https://user-images.githubusercontent.com/61380549/125744276-85d7cde5-4d5b-4d4e-8b4b-1d4a7234febd.png)
I installed it successfully,thank you!
