### ISSUE TITLE
std.MaskedMerge bizzare behaviour at float32 (YUV4XXPS/RGBS/GRAYS)

### ISSUE THREAD

**Issue by NSQY** [vapoursynth/vapoursynth#708]
When merging clips with std.MaskedMerge, I had noticed that the output appeared to be more intense than the reference clip. Clamping the mask with std.Limiter(clip, max=1.0) results in the expected output (same/similar intensity as reference clip within masked areas) - changing line 15 in this example script demonstrates this.

This behavior seems to be unique to float formats.

Test image: https://0x0.st/-OsE.png

```
import vapoursynth as vs
core = vs.core

def unsharp(clip: vs.VideoNode) -> vs.VideoNode:
    # https://www.vapoursynth.com/doc/functions/makediff.html
    
    blur_clip = core.std.Convolution(clip, matrix=[1, 2, 1, 2, 4, 2, 1, 2, 1], planes=[0])
    diff_clip = core.std.MakeDiff(clip, blur_clip, planes=[0])
    return core.std.MergeDiff(clip, diff_clip, planes=[0])


image = core.imwri.Read('foo.png')
image = core.resize.Point(image, format=vs.GRAYS, matrix_s='709')

mask = core.std.Prewitt(image, scale=10.0).std.Limiter(max=10.0)

reference = unsharp(image)
merge = core.std.MaskedMerge(image, reference, mask)

image.set_output(1)
reference.set_output(2)
merge.set_output(3)
mask.set_output(4)
```
```
VapourSynth Video Processing Library
Copyright (c) 2012-2021 Fredrik Mellbin
Core R53
API R3.6
Options: -
```

**Comment by myrsloik** [comment]
Related to #681, basically the math is inconsistent with float masks and will be fixed.

**Comment by myrsloik** [comment]
The convention of 0-1 range for all float mask clips will be in R54 so this is fixed I guess.

**Comment by NSQY** [comment]
> The convention of 0-1 range for all float mask clips will be in R54 so this is fixed I guess.

This is still reproducible with R54
```
>>> from vapoursynth import core
>>> print(core.version())
VapourSynth Video Processing Library
Copyright (c) 2012-2021 Fredrik Mellbin
Core R54
API R3.6
Options: -```

**Comment by sekrit-twc** [comment]
The gods hath spoken. If you have scripts generating old-style (-0.5...0.5) masks, they should be updated. One nuance with floats is that expressions, convolutions, etc. can produce values outside of 0-1, which need to be clamped for use in a mask.
