### ISSUE TITLE
General ideas/enhancements

### ISSUE THREAD

**Issue by myrsloik** [vapoursynth/vapoursynth#714]
MakeWritable - unlike in Avisynth this could actually work surprisingly well in API4 since all dependencies are known
Tiled filters
A simple API for filters that can split the processing of independent planes (something like 3x createFilter and then merging the end result without being extremely annoying to implement in every filter)

**Comment by DJATOM** [comment]
Tiled filters might be interesting approach for slow spatial algos like eedi3, where single frame generation takes significant amount of time.

**Comment by myrsloik** [comment]
> Tiled filters might be interesting approach for slow spatial algos like eedi3, where single frame generation takes significant amount of time.

It's mostly intended for simple filters the way we've imagined it so far. But you're right that having some kind of system with multiple threads processing a single frame could be useful as well.

**Comment by NSQY** [comment]
I've had conceptually similar idea in the past based around edge detection but I have no idea how practical it would be.

Say we have an image that is largely flat with a few edges of which we want to apply some sort of (slow) filter, applying this filter to the entire frame is hugely inefficient when we only care about certain areas in the image and perhaps some of their surroundings.

My thought was that if we could isolate these areas and paint them on their own frame dynamically (reducing a 1920x1080 image to say 500x500 which only contains the areas detected by the mask and some optional overshoot) which could be processed and then overlaid back to their original locations.

**Comment by myrsloik** [comment]
> My thought was that if we could isolate these areas and paint them on their own frame dynamically (reducing a 1920x1080 image to say 500x500 which only contains the areas detected by the mask and perhaps some optional overshoot) which could be processed and then overlaid back to their original locations.

Not practical at all.

**Comment by AkarinVS** [comment]
how about adding a mechanism to compute a plane only as needed?

Most filters are processing each plane separately, and if a filter is only
used by a ShufflePlane that extracts only one of its planes, we don't need
to process those unneeded planes.
Right now, each individual filter has to design its own way to encode such
info as an argument (e.g. `planes`) and it's inconsistent at best (e.g.
fmtconv's `planes` has much complicated rules than the rest.)

What's worse, for some filters, not processing a plane will leave garbage
in that plane, but if that plane is actually used in a later step, it might
not be easy to debug the script to find the culprit.

If we're bringing in a complete new incompatible API version, perhaps we
can address this issue at the API level.

**Comment by myrsloik** [comment]
> how about adding a mechanism to compute a plane only as needed

Filters don't have to design it. There's the standard convention of the planes argument followed by all filters in existence. Since same format/dimension plane copies are free the only edge case that happens is when you have a filter that modifies the output format/resolution but doesn't process all planes. In those you get obvious garbage.

>Most filters are processing each plane separately, and if a filter is only
used by a ShufflePlane that extracts only one of its planes, we don't need
to process those unneeded planes.

Write scripts that extracts the used planes earlier. There's also no way to force anyone to write things that make sense in the output at an api level. Poorly chosen operation order will always yield worse performance. Most of the time not even the most trivial operation can be reordered without affecting the output. You can't protect the users from themselves and so on...

**Comment by sekrit-twc** [comment]
Lazy-processing of planes will be possible when the tiled filter API is introduced, since the tiled-style filters will need to declare their dependencies at the plane level, allowing VS to kill references to unused planes early in the chain*. For complex/frame-style filters, VS does not have the visibility to perform this optimization.

*Behavior not guaranteed.

**Comment by Kamekameha** [comment]
A file naming scheme for plugins would be nice, specially now that API v3 and v4 plugins might coexist.
