### ISSUE TITLE
core: make std.LoadPlugin return loaded plugin (and optionally ignore id/namespace conflicts)

### ISSUE THREAD

**Issue by AkarinVS** [vapoursynth/vapoursynth#721]
Right now, it's impossible to load plugins with conflicting namespaces/ids.
This makes it difficult to write a script that loads and uses its version of a plugin, regardless of the plugins already present in the VS auto-load plugins directory. (Think when you distribute your script & an experimental plugin to other encoders, you probably don't want to modify their VS environment just to be able to load your custom plugin.)

With API4 we could create a core without auto-loading any plugins, but this mechanism is pretty overkill when we just need to load one potentially-conflicting plugin.

I propose that we make `core.std.LoadPlugin` returns the plugin just loaded, and add a new parameter `bint ignore_conflict` which will ignore conflicts in plugin ids and namespaces (e.g. by appending a random string to the plugin id/namespace to make it unique). And then we can do this:

```python
import vapoursynth as vs
import os, os.path
core = vs.core

# Load my version of the plugin.
myplugin = core.std.LoadPlugin(os.path.join(os.getcwd(), "myplugin.dll"), ignore_conflict=True)

# Use my loaded plugin, regardless of any versions already preloaded.
c = myplugin.MyFilter(src)
```

This will also make plugin development easier: we can put a stable version in the autoload directory, and use this mechanism to load development version and test it without having to prepare two separate VS installations, one with and one without the stable plugin.

This of course will break plugins that looks up a plugin via its id and invoke its filters, but such cases are pretty rare (oftentimes it's used to invoke a builtin filter, not a user-defined filter). And if we really need to do this, we can always add a way to find the plugin id given `myplugin` and pass that to those plugins. (A related issue is that, in the Python API, there is no way to query a _given_ plugin's namespace, id, and path except by using `core.get_plugins()` to query all loaded plugins.)

An alternative would be to provide a way to create a core that skips auto-loading a given plugin (if exists), but I think it's not as elegant as this solution. And it also doesn't help the cases when the core is already created for your script (e.g. when used with Python based previewers.)

Yet another alternative is for a plugin to discover that there is a conflict in the chosen id/namespace and act appropriately, however, if the plugin decides to change its id, how could the script know which id to use?

What do you think? Thanks.

**Comment by myrsloik** [comment]
This is implemented already but not advertised. LoadPlugin has the secret arguments forcens and forceid if you really want to subvert the checks. Adjust identifiers in the script after doing so.

**Comment by AkarinVS** [comment]
OK so the conflict resolution part is doable now, but what about having
LoadPlugin returning the loaded plugin?

>

**Comment by myrsloik** [comment]
I probably won't do that. It's a convoluted solution to a simple problem. Note that the api4 builds have a flag to disable autoloading which can help you avoid this problem completely.

**Comment by AkarinVS** [comment]
`forceid` and `forcens` seem good enough for my purposes.
Thanks.

```
import vapoursynth as vs
import os, os.path
core = vs.core

# Load my version of the plugin.
core.std.LoadPlugin(os.path.join(os.getcwd(), "myplugin.dll"), forcens="XXX.YYY", forceid="myplugin2")
myplugin = core.myplugin2

# Use my loaded plugin, regardless of any versions already preloaded.
c = myplugin.MyFilter(src)
```
