### ISSUE TITLE
Subtext errors if _ColorRange=0

### ISSUE THREAD

**Issue by noizuy** [vapoursynth/vapoursynth#734]
Subtext errors complaining about input frames not having the same range in MaskedMerge if the input clip's _ColorRange is set to 0.

Script to reproduce:
```py
import vapoursynth as vs
core = vs.core

clip = core.std.BlankClip(format=vs.YUV444P8)

clip = clip.std.SetFrameProp("_ColorRange", intval=0)

clip = clip.sub.Subtitle("vapoursynth")

clip.set_output()
```

This results in:
```
Error: Failed to retrieve frame 0 with error: MaskedMerge: Input frames must have the same range
```

**Comment by myrsloik** [comment]
Range argument added in the doodle1 branch. You can always merge the subtitles yourself as a workaround.
