### ISSUE TITLE
api4: std.SetFrameProp no longer supports deleting frame property

### ISSUE THREAD

**Issue by AkarinVS** [vapoursynth/vapoursynth#736]
I understand that api4 have introduced `std.RemoveFrameProps` dedicated for this purpose, but I think removing `delete` support from `std.SetFrameProp` breaks backword compatibility for no good reason and makes writing portable scripts that work with both api3 and api4 VS unnecessarily harder than it should be.

What's the rationale behind this backward incompatible change?

Thanks.

**Comment by myrsloik** [comment]
Mostly that having a function that both sets and deletes gets a really convoluted argument list and isn't intuitive at all.
