### ISSUE TITLE
A new directory structure of docoument

### ISSUE THREAD

**Issue by soldivelot** [vapoursynth/vapoursynth#751]
In my humble opinion, we can sort out the directory structure of the document a bit to make it look neater, for example: 

- Introduction (former "About")
- Installation (former "Installation Instructions" and "Plugins and Scripts")
- Getting Started
- Python Reference
- Function Reference
- Output (VSPipe, AVFS and VFW)
- Applications and Libraries
- VapourSynth C API Reference

**Comment by myrsloik** [comment]
Makes sense. It could definitely use a general cleanup. Not sure when I'll have time to actually do the edit work so it could take a while.

**Comment by soldivelot** [comment]
good :smile:

by the way, i have just tried widely used `sphinx_rtd_theme` doc theme, It looks nice and highlighting is better

comparing with old one:

***
![1](https://user-images.githubusercontent.com/84898012/132991092-5b8da77c-5ea5-4290-8f1a-e1c8a8e07251.png)
***
![2](https://user-images.githubusercontent.com/84898012/132991095-53ab11b2-0967-41e3-ad34-6e21351cdc3e.png)
***
![3](https://user-images.githubusercontent.com/84898012/132991098-31ecdca2-2ab7-48e5-a56d-c2027d267ddd.png)
***
![4](https://user-images.githubusercontent.com/84898012/132991091-ae5afcaf-0724-42d3-b6ac-6797e56b1c34.png)

**Comment by myrsloik** [comment]
Sure, include it in a pull request and the python dependencies if you want. I'm not particularly attached to the current theme either.
