### ISSUE TITLE
Crash with odd-width images

### ISSUE THREAD

**Issue by viliml** [vapoursynth/vapoursynth#756]
Because GetNative.getw always rounds the width to an even number, images with odd width will cause the descaled-then-upscaled image to have different dimensions from the original image, causing a crash when trying to compare them.

**Comment by DJATOM** [comment]
Vapoursynth has nothing to do with third-party code (getnative). You should open issue there.

**Comment by viliml** [comment]
Whoops I posted in the wrong tab 😅
