### ISSUE TITLE
Compile list of insane expressions

### ISSUE THREAD

**Issue by sekrit-twc** [vapoursynth/vapoursynth#760]
[havs_exprs.txt](https://github.com/vapoursynth/vapoursynth/files/7150484/havs_exprs.txt)
[muvs_exprs.txt](https://github.com/vapoursynth/vapoursynth/files/7150485/muvs_exprs.txt)

**Comment by YomikoR** [comment]
Why is an expr for sigmoid transform insane?

**Comment by myrsloik** [comment]
Notable in muvs exprs that have direct filter equivalents:
LIMITER: x 0 < 16 x ? 255 > 235 x ?
AVERAGEFRAMES: x y + z + a + b + 4 /
AVERAGEFRAMES: x y + z + a + b + c + d + e + 8 /
