### ISSUE TITLE
not sure if this is the place to ask this, but i could really use some help!!

### ISSUE THREAD

**Issue by caylaanne** [vapoursynth/vapoursynth#772]
vs started showing this error earlier today, after i’d already made a couple of gifs. i’ve uninstalled and reinstalled the app multiple times and the error is still the same. pls pls help, i feel like i’m losing brain cells :(
<img width="1276" alt="A78D09DC-93B8-45E9-A2EE-4BC92596467E" src="https://user-images.githubusercontent.com/30377846/134105129-f488b3b9-b532-4355-b54f-01407d6b9c6c.png">

**Comment by theChaosCoder** [comment]
Is your source path writable? Is the file path correct?

**Comment by caylaanne** [comment]
i’m not sure. it seems like this only comes up when i use a .ts file. i’ve checked it with mp4’s, and it works fine, but i work with ts files frequently on vapoursynth so i’m not sure what the problem is

**Comment by tuilakhanh** [comment]
It seems your video source is .mkv format try using
`core.ffms2.Source(abs_file_path)`  instead of `core.lsmas.LWLibavSource(abs_file_path)`

**Comment by caylaanne** [comment]
omg this worked!! thank you so much!!

**Comment by vxzms** [comment]
You should try https://github.com/AkarinVS/L-SMASH-Works with `repeat=1` if you open interlaced TS files. And `LWLibavSource` can open MKV safety because it’s not `LibavSMASHSource`.
