### ISSUE TITLE
AudioNode and VideoNode share all std lib

### ISSUE THREAD

**Issue by Ichunjo** [vapoursynth/vapoursynth#775]
Running this:
```py
audio = vs.core.std.BlankAudio()
print(
    type(audio),
    '\n',
    dir(audio)
)
```
outputs this
```
<class 'vapoursynth.AudioNode'> 
 ['__add__', '__class__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__pyx_vtable__', '__radd__', '__reduce__', '__reduce_ex__', '__repr__', '__rmul__', '__setattr__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__', 'acrop', 'adg', 'akarin', 'area', 'average', 'avs', 'avsw', 'bilateral', 'bits_per_sample', 'bm3d', 'bm3dcuda', 'bytes_per_sample', 
'cas', 'ccd', 'channel_layout', 'comb', 'ctmf', 'd2v', 'dctf', 'deblock', 'delogohd', 'descale', 'descale_getnative', 'dfttest', 'dgdecodenv', 'dpid', 'dpriv', 'edgefixer', 'eedi2', 'eedi3m', 'f3kdb', 'fb', 'ffms2', 'fft3dfilter', 'flux', 'fmtc', 'focus2', 'frames', 'ftf', 'get_frame', 'get_frame_async', 'get_frame_async_raw', 'grain', 'hist', 'hqdn3d', 'jinc', 'knlm', 'lghost', 'libp2p', 'lsmas', 'median', 'mpls', 'msmoosh', 'mv', 'mvsf', 'mx', 'neo_f3kdb', 'neo_fft3d', 'neo_vd', 'nnedi3', 'nnedi3cl', 'num_channels', 'num_frames', 'num_samples', 'ocr', 'placebo', 'remap', 'resize', 'retinex', 'rgsf', 'rgvs', 'rsnv', 'sample_rate', 'sample_type', 'sangnom', 'scxvid', 'set_output', 'srmdnv', 'std', 'svp1', 'svp2', 'tcanny', 'tdm', 'tedgemask', 'text', 'tivtc', 'tla', 'tmedian', 'tonemap', 'ttmpsm', 'vcmod', 'vsf', 'vsfm', 'w2xc', 'w2xnvk', 'warp', 'wwxd', 'yadifmod', 'znedi3']
```
This is problematic because AudioNode and VideoNode share the same `std` property while not being of the same type:
This code will pass typechecks and will only raise an error during runtime
```py
clip = vs.core.std.BlankClip()
audio = clip.std.BlankAudio()
```
Likewise:
```py
audio = vs.core.std.BlankAudio()
audio = audio.grain.Add(1)
```

The ` __dir__` method of VideoNode and AudioNode should be fixed. And it would be nice to have a separate std lib for AudioNode and also not have the audio methods in VideoNode class.

I'm currently fixing the stubs in https://github.com/vapoursynth/vsrepo/pull/158 and wanted to have details on how to handle this as it may also involve cython and/or C code.

**Comment by myrsloik** [comment]
Right, either only return audio/video suitable plugins/functions in __dir__ (having the advantage that std.SetMaxCPU wouldn't turn up in the completion list for either) or do the same filtering in vsgenstubs when compiling all signatures. Have to think about which one I prefer.

The rule:
If a function signature contains a vnode it can be bound to VideoNode and similarly anode for AudioNode. Other functions can't be called that way.

**Comment by myrsloik** [comment]
Implemented in __dir__
output from dir(blankclip.std):
['AddBorders', 'AssumeFPS', 'AverageFrames', 'Binarize', 'BinarizeMask', 'BlankClip', 'BoxBlur', 'Cache', 'ClipToProp', 'Convolution', 'CopyFrameProps', 'Crop', 'CropAbs', 'CropRel', 'Deflate', 'DeleteFrames', 'DoubleWeave', 'DuplicateFrames', 'Expr', 'FlipHorizontal', 'FlipVertical', 'FrameEval', 'FreezeFrames', 'Inflate', 'Interleave', 'Invert', 'InvertMask', 'Levels', 'Limiter', 'Loop', 'Lut', 'Lut2', 'MakeDiff', 'MaskedMerge', 'Maximum', 'Median', 'Merge', 'MergeDiff', 'Minimum', 'ModifyFrame', 'PEMVerifier', 'PlaneStats', 'PreMultiply', 'Prewitt', 'PropToClip', 'RemoveFrameProps', 'Reverse', 'SelectEvery', 'SeparateFields', 'SetFieldBased', 'SetFrameProp', 'SetFrameProps', 'SetVideoCache', 'ShufflePlanes', 'Sobel', 'Splice', 'SplitPlanes', 'StackHorizontal', 'StackVertical', 'Transpose', 'Trim', 'Turn180']
output from dir(blankaudio.std):
['AssumeSampleRate', 'AudioGain', 'AudioLoop', 'AudioMix', 'AudioReverse', 'AudioSplice', 'AudioTrim', 'BlankAudio', 'SetAudioCache', 'ShuffleChannels', 'SplitChannels']
