### ISSUE TITLE
core.ffms2.Source() -> endless recursion

### ISSUE THREAD

**Issue by Memnarch** [vapoursynth/vapoursynth#791]
I started with vapoursynth and installed ffms2.
I try to open one of my files likes this:
```
from vapoursynth import core
clip = core.ffms2.Source(source="E:\\Videos\\MyVideo.mov")
```
And it results in this(and I'm not sure what to do from here):
```
Traceback (most recent call last):
  File "src\cython\vapoursynth.pyx", line 2071, in vapoursynth.Function.__call__
  File "src\cython\vapoursynth.pyx", line 763, in vapoursynth.mapToDict
  File "src\cython\vapoursynth.pyx", line 2071, in vapoursynth.Function.__call__
  File "src\cython\vapoursynth.pyx", line 763, in vapoursynth.mapToDict
  File "src\cython\vapoursynth.pyx", line 2071, in vapoursynth.Function.__call__
  File "src\cython\vapoursynth.pyx", line 763, in vapoursynth.mapToDict
...
  File "D:\ProgramData\Miniconda3\envs\riven\lib\enum.py", line 384, in __call__
    return cls.__new__(cls, value)
  File "D:\ProgramData\Miniconda3\envs\riven\lib\enum.py", line 674, in __new__
    if type(value) is cls:
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by myrsloik** [comment]
VapourSynth version and which FFMS2 compile did you use?

**Comment by Memnarch** [comment]
Oh I'm sorry, shame on me.

From the top of my Head, I'm running R55 of Vapoursynth and ffms2 installed through vsrepo.py, which should be 2.40.

Though I'll verify once I'm back home. Sorry for the inconvenience.

**Comment by Memnarch** [comment]
It seems it was my convoluted conda environment. redid it, and it's working now.

**Comment by Memnarch** [comment]
Okay I think I got it nailed down. When vapoursynth worked, I had the conda environment not activated, so it works outside of it, but not inside?

I ran the windows installer VapourSynth64-R55.exe on my machine (windows 10).
here are my reprosteps(running from cmd):
```
conda create -n foo python=3.9
conda activate foo
pip install vapoursynth
(change dir to vsrepo)
python vsrepo.py install ffms2
(change dir to the folder with my scripts)
python MyDemo.py
```

**Comment by YomikoR** [comment]
It's a known issue that VS installation on the recent conda won't work out of the box. But pip installing again probably won't help, because it's outdated and provides an incompatible dll.

**Comment by Memnarch** [comment]
if i'm not mistaken, pip installs the wrapper from the local cache where the windows installer had placed it?

Otherwhise it seems I either need to use an older conda or not work in a conda environment at all?

Are there any other workarounds?

**Comment by myrsloik** [comment]
> It's a known issue that VS installation on the recent conda won't work out of the box. But pip installing again probably won't help, because it's outdated and provides an incompatible dll.

NOBODY EVER TOLD ME THIS

It was unknown until you said it. Also I have no idea why code execution would change in conda.

**Comment by Memnarch** [comment]
Good thing I didn't know it does not work and stumbled into this :D 
(At first I thought I had missed something on the installer page or something)

**Comment by YomikoR** [comment]
If the python interface is enough for your job (while keeping vspipe broken), you can pip uninstall the downloaded VapourSynth-R51 and make sure installing the wheel from the VS installation path, by default `C:\Program Files\VapourSynth\python`.

> NOBODY EVER TOLD ME THIS

Because it's due to the env management of conda, also "why do you keep using conda for VS".

**Comment by Memnarch** [comment]
"why do you keep using conda for VS"
Currently exploring different ai upscalers and they all share some packages but in different versions and upgrading one package "to far" causes the rest to collapse. Conda seemed like a good idea to have everything isolated.

**Comment by YomikoR** [comment]
Yep, but the trade-off is that conda hijacks its python. External programs may suffer and VS is not the only victim.
https://github.com/conda/conda/issues/9648

**Comment by Memnarch** [comment]
However it seems I'm lost with VSPipe anyway, as I work with RGB output and VSpipe supports YUV headers, only?
(Though I could convert the RGB to YUV before outputting but that means I'm going YUV->RGB->YUV oO)

**Comment by myrsloik** [comment]
It's called YUV4MPEG headers. They're only defined for yuv. Would be nice if they were defined for everything but that's not the case. Pipe raw output to ffmpeg and specify all format information manually.
Raw output is either planar GBR of planar YUV.

**Comment by quietvoid** [comment]
I'm getting the same problem with regular Python 3.9 on Arch.
Installed vapoursynth R56 and ffms2-git. When running test.py, 39/47 tests fail.

And zimgtest.py also fails with this
```
python zimgtest.py
Traceback (most recent call last):
  File "/home/user/Downloads/vapoursynth/test/zimgtest.py", line 18, in <module>
    formatids.append(core.query_video_format(cfs, vs.INTEGER, bps, 0, 0).id)
  File "src\cython\vapoursynth.pyx", line 1893, in vapoursynth._CoreProxy.__getattr__
  File "src\cython\vapoursynth.pyx", line 1756, in vapoursynth.Core.__getattr__
AttributeError: No attribute with the name query_video_format exists. Did you mistype a plugin namespace?
```

**Comment by aethanol** [comment]
> I'm getting the same problem with regular Python 3.9 on Arch. Installed vapoursynth R56 and ffms2-git. When running test.py, 39/47 tests fail with the recursion error.
> 
> And zimgtest.py also fails with this
> 
> ```
> python zimgtest.py
> Traceback (most recent call last):
>   File "/home/user/Downloads/vapoursynth/test/zimgtest.py", line 18, in <module>
>     formatids.append(core.query_video_format(cfs, vs.INTEGER, bps, 0, 0).id)
>   File "src\cython\vapoursynth.pyx", line 1893, in vapoursynth._CoreProxy.__getattr__
>   File "src\cython\vapoursynth.pyx", line 1756, in vapoursynth.Core.__getattr__
> AttributeError: No attribute with the name query_video_format exists. Did you mistype a plugin namespace?
> ```
> 
> I must've read too fast, but uninstalling vapoursynth from pypi fixes it.

I also just ran into this issue, thought the docs were saying to always install from pip after compiling but I don't think this is the case.

**Comment by myrsloik** [comment]
The bit about pip is very wrong. Ignore it.

**Comment by myrsloik** [comment]
Note to self. Test R56 with R51 python module.
