### ISSUE TITLE
High CPU utilization when using VFW on R56

### ISSUE THREAD

**Issue by soldivelot** [vapoursynth/vapoursynth#799]
I preview vpy script using virtualdub, I found that scripts that used to play in real time can't now, so i run a simple script

```python
import vapoursynth as vs
core = vs.core
clip = core.std.BlankClip(width=1920,height=1080,format=vs.YUV444P8,length=30*60,fpsnum=30,fpsden=1,color=[0,128,128])
clip = core.grain.Add(clip=clip,var=8,uvar=8,hcorr=0,vcorr=0)
clip.set_output()
```

CPU: 8C16T
realtime playback results:

||cpu utilization|
|-|-|
|R54 vdub|<1%|
|R56 vdub|55%|
|R54 vspipe-mpv|<1%|
|R56 vspipe-mpv|<1%|

I have't test other VFW based program yet, just virtualdub

**Comment by soldivelot** [comment]
BTW, how about move `build instructions windows.md` `ChangeLog` `APIV4 changes.txt` to doc, the linux compilation instructions is in the doc (it's outdated)

**Comment by myrsloik** [comment]
I guess the windows build instructions can be integrated as they are and I guess APIV4 changes.txt if you want yo clean it up a bit in the process.
Changelog should be separate.

**Comment by myrsloik** [comment]
Fixed, forgot to add a cache and it also happened in avfs

**Comment by soldivelot** [comment]
:rocket:
