### ISSUE TITLE
Only black frames with AverageFrames

### ISSUE THREAD

**Issue by OldTuxedo** [vapoursynth/vapoursynth#810]
AverageFrames outputs only black frames when one of the weights is less than 0.5, with some specific combinations of weights. Examples:

Normal: clip = core.std.AverageFrames(clip, [0.5, 0.21, 0.12])

Black: clip = core.std.AverageFrames(clip, [0.4, 0.21, 0.12])

Normal: clip = core.std.AverageFrames(clip, [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.28, 0.5, 0, 0.12])

Black: clip = core.std.AverageFrames(clip, [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.28, 0.4, 0, 0.12])

OS: Linux
Version: r56

**Comment by myrsloik** [comment]
It's very clearly stated that all coefficients are rounded to the nearest integer when processing integer formats.
