### ISSUE TITLE
[ Linux ] vspipe Failed to initialize VSScript

### ISSUE THREAD

**Issue by TRPB** [vapoursynth/vapoursynth#826]
I have narrowed this down to vapoursynth itself rather than any plugins. If I run:

```
vspipe 
```

regardless of arguments, it gives me `Failed to initialize VSScript` is there any way I can determine exactly what the issues is? Even `vspipe --help` gives the same error which makes it very difficult to track down the problem.

I'm using the `vapoursynth` package from Arch Linux.

**Comment by CaffeineViking** [comment]
I'm also running into this problem, but on Windows through MinGW64. This is the package: [mingw-w64-x86_64-vapoursynth](https://packages.msys2.org/package/mingw-w64-x86_64-vapoursynth?repo=mingw64). I've also created an issue for the package itself: [msys2/MINGW64#10528](https://github.com/msys2/MINGW-packages/issues/10528).

This is the stuff I've investigated so far (a copy-paste from that issue):

```python
$ python
Python 3.9.7 (default, Nov 21 2021, 22:02:56)  [GCC 11.2.0 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import vapoursynth
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'vapoursynth'
```

i.e. it can't find the `vapoursynth` module, so maybe the path is wrong?

```python
$ python
Python 3.9.7 (default, Nov 21 2021, 22:02:56)  [GCC 11.2.0 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> print('\n'.join(sys.path))
C:/msys64/mingw64/lib/python39.zip
C:/msys64/mingw64/lib/python3.9
C:/msys64/mingw64/lib/python3.9/lib-dynload
C:/msys64/home/Erik
C:/msys64/mingw64/lib/python3.9/site-packages
```

`C:/msys64/mingw64/lib/python3.9/site-packages` seems to be correct:

```
$ ls C:/msys64/mingw64/lib/python3.9/site-packages
vapoursynth.dll
```

There are of course other files there as well, but the DLL isn't missing.

```
$ vspipe -v
Failed to initialize VSScript
```

Maybe it just can't find `libvapoursynth-script-0.dll` or something?

```
$ ldd /mingw64/bin/vspipe.exe
ntdll.dll => /c/WINDOWS/SYSTEM32/ntdll.dll (0x7ff8bbe70000)
KERNEL32.DLL => /c/WINDOWS/System32/KERNEL32.DLL (0x7ff8baa50000)
KERNELBASE.dll => /c/WINDOWS/System32/KERNELBASE.dll (0x7ff8b9b50000)
msvcrt.dll => /c/WINDOWS/System32/msvcrt.dll (0x7ff8ba150000)
libvapoursynth-script-0.dll => /mingw64/bin/libvapoursynth-script-0.dll (0x7ff8a8ca0000)
ADVAPI32.dll => /c/WINDOWS/System32/ADVAPI32.dll (0x7ff8ba470000)
libgcc_s_seh-1.dll => /mingw64/bin/libgcc_s_seh-1.dll (0x7ff8a8c60000)
libwinpthread-1.dll => /mingw64/bin/libwinpthread-1.dll (0x7ff8a8c80000)
sechost.dll => /c/WINDOWS/System32/sechost.dll (0x7ff8bb340000)
libstdc++-6.dll => /mingw64/bin/libstdc++-6.dll (0x7ff887b60000)
RPCRT4.dll => /c/WINDOWS/System32/RPCRT4.dll (0x7ff8baf90000)
libpython3.9.dll => /mingw64/bin/libpython3.9.dll (0x7ff8829f0000)
SHLWAPI.dll => /c/WINDOWS/System32/SHLWAPI.dll (0x7ff8bb0c0000)
WS2_32.dll => /c/WINDOWS/System32/WS2_32.dll (0x7ff8ba0e0000)
VERSION.dll => /c/WINDOWS/SYSTEM32/VERSION.dll (0x7ff8aeed0000)
```

Seems to be fine as well... I've run out of ideas on what to check next.

**Comment by CaffeineViking** [comment]
I'll try to dig a bit further later this week, any suggestions on what to try next are welcome!

**Comment by CaffeineViking** [comment]
Renaming `vapoursynth.dll` to `vapoursynth.pyd` seems to have been enough to get `import vapoursynth` to work at least. I'll try to figure out what's wrong with the `PKGBUILD` in MinGW64 and if it needs some additional patching for `vspipe` work correctly (that's still giving me `Failed to initialize VSScript`).

**Comment by couleurm** [comment]
Hey, I'm also experiencing this issue using the portable version from this GitHub. 

I'm currently trying to make a [scoop](http://scoop.sh) manifest for VapourSynth so I also have to use a portable version of Python

vsrepo.py works fine while VSPipe also tells me it fails to initialize VSScript, renaming vapoursynth.dll to vapoursynth.pyd did not help me import it though (issue might come from my end on this one, I'm not as experienced for setting up vs/py)

**Comment by edison23** [comment]
Just for passers-by like me:
I had the same issue:
```
$ vspipe --version
Failed to initialize VSScript
```
I fixed by adding the correct path to the library to the `PYTHONPATH` environment variable as described here - https://www.vapoursynth.com/doc/installation.html#linux-and-os-x-compilation :
```
PYTHONPATH=/usr/local/lib/python3.10/site-packages/
export PYTHONPATH=$PYTHONPATH

vspipe --version
VapourSynth Video Processing Library
Copyright (c) 2012-2023 Fredrik Mellbin
Core R66
API R4.1
API R3.6
Options: -
```

**Comment by 64kramsystem** [comment]
> Just for passers-by like me: I had the same issue:
> 
> ```
> $ vspipe --version
> Failed to initialize VSScript
> ```
> 
> I fixed by adding the correct path to the library to the `PYTHONPATH` environment variable as described here - https://www.vapoursynth.com/doc/installation.html#linux-and-os-x-compilation :
> 
> ```
> PYTHONPATH=/usr/local/lib/python3.10/site-packages/
> export PYTHONPATH=$PYTHONPATH
> 
> vspipe --version
> VapourSynth Video Processing Library
> Copyright (c) 2012-2023 Fredrik Mellbin
> Core R66
> API R4.1
> API R3.6
> Options: -
> ```

This fixed the same problem on my setup. For reference, I'm on a Ubuntu 22.04.
