### ISSUE TITLE
Passing input file to the "vpy" script through "vspipe" 

### ISSUE THREAD

**Issue by miaoqiz** [vapoursynth/vapoursynth#828]
Hi there,

Thanks so much for the software! I appreciate it.

Just a quick question, is there a way to pass the input file to "script.vpy" script for "vspipe" to process. Currently, most of the examples have the input file's path hard-coded in the "script.vpy" script.

I found a link that talks about this: https://stackoverflow.com/questions/42279927/vapoursynth-output-nodes-in-python-mainargv-function-using-vspipe

Thanks so much and have a good day!

**Comment by Ichunjo** [comment]
You did say using `clip = core.lsmas.LWLibavSource(source=globals()["source"] ... )` but you’re not using the globals dict variable in your error message.

**Comment by miaoqiz** [comment]
Hi there,

Thanks for your help on this! I appreciate it.

It is something like this - 
-----------------------------------------------------------------
src = globals()["source"]
clip = core.lsmas.LWLibavSource(source=src, format="YUV422P10", cache=0, fpsnum=30000, fpsden=1001, prefer_hw=0)
.............
-----------------------------------------------------------------

If you can kindly give an actual example here on how to pass the global variables to "vspipe", that would be more effective.

Thanks so much and have a good week!

**Comment by miaoqiz** [comment]
Hi there,

Thanks for your help on this! I appreciate it.

The code is something like this:
---
src = globals()["source"]
clip = core.lsmas.LWLibavSource(source=src, format="YUV422P10", cache=0, fpsnum=30000, fpsden=1001, prefer_hw=0)
---

If you can kindly give an actual example here on how to pass the global variables to "vspipe", that would be more effective.

Thanks so much and have a good week!

**Comment by miaoqiz** [comment]
Any updates? 

Thanks so much!

**Comment by miaoqiz** [comment]
Actually I just solved it. I placed the "--arg" in the wrong location in the pipe. I apologize for it.
