### ISSUE TITLE
Transpose displaying random garbage on playback with certain width

### ISSUE THREAD

**Issue by gundamftw** [vapoursynth/vapoursynth#829]
I was playing a script in vsedit2, with Transpose in the script, when the video width was set to somewhere between like 242-260 pixel, there would be random garbage flashing in the frame. Clip with width outside that range played without problem.

To reproduce, load a 1080p video and crop its width to 256, then play in vsedit2.
```
clip = core.std.Transpose(clip)
clip = core.std.Crop(clip, 824, 0, 0, 0)
```

**Comment by Ichunjo** [comment]
Is it a Vapoursynth issue?

**Comment by gundamftw** [comment]
I tested it thoroughly last night, it is a vsedit2 issue, not vapoursynth. Sorry.
