### ISSUE TITLE
Bicubic: Function does not take argument(s) named bob; QTGMC; R57 fresh install

### ISSUE THREAD

**Issue by Johnreidsilver** [vapoursynth/vapoursynth#830]
Fresh install on Ubuntu 20.04 machine
Using this version of havsfunc:
https://github.com/vapoursynth/vapoursynth/pull/819
(with old havsfunc, it throws a znedi3 error)

calling this script:
LD_LIBRARY_PATH=/usr/local/lib PYTHONPATH=/usr/local/lib/python3.8/site-packages vspipe -c y4m DeinterlaceVapor-newU20.py - | ffmpeg -i pipe: /dev/shm/testb.mp4 

```
import vapoursynth as vs
import havsfunc
from havsfunc import QTGMC

core= vs.core #core = vs.get_core()
core.std.LoadPlugin(path="/usr/local/lib/libfmtconv.so")
core.std.LoadPlugin(path="/usr/local/lib/libmiscfilters.so")
core.std.LoadPlugin(path="/usr/local/lib/libffms2.so.5.0.0")
core.std.LoadPlugin(path="/usr/local/lib/libnnedi3.so")
core.std.LoadPlugin(path="/usr/local/lib/libmvtools.so")
core.std.LoadPlugin(path="/usr/local/lib/libeedi3m.so")

clip = core.ffms2.Source(source='/dev/shm/moon.webm', fpsnum=60000, fpsden=1001)
clip = QTGMC(clip, Preset='Slow', TFF=True) 
clip.set_output()
```

throws this error:

```
Script evaluation failed:
Python exception: Bicubic: Function does not take argument(s) named bob

Traceback (most recent call last):
  File "src/cython/vapoursynth.pyx", line 2786, in vapoursynth._vpy_evaluate
  File "src/cython/vapoursynth.pyx", line 2787, in vapoursynth._vpy_evaluate
  File "DeinterlaceVapor-newU20.py", line 25, in <module>
    clip = QTGMC(clip, Preset='Slow', TFF=True) #, InputType=0) # TFF=True,  InputType=0) # Preset='Slower',
  File "/usr/local/lib/python3.8/site-packages/havsfunc.py", line 1167, in QTGMC
    bobbed = Bob(clip, 0, 0.5, TFF)
  File "/usr/local/lib/python3.8/site-packages/havsfunc.py", line 5359, in Bob
    clip = core.resize.Bicubic(clip, height=clip.height * 2, filter_param_a=b, filter_param_b=c, bob=True)
  File "src/cython/vapoursynth.pyx", line 2505, in vapoursynth.Function.__call__
vapoursynth.Error: Bicubic: Function does not take argument(s) named bob

```

treating the file as progressive works (clip = QTGMC(clip, Preset='Slower', InputType=1)), but the source is actually interlaced and I want to deinterlace to progressive with double frame rate

system details:
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal

VSPipe R57 usage

**Comment by Ichunjo** [comment]
R57 doesn’t have any bob argument in `resize`. Besides, you’re using a test version so I’m not sure what you was expecting.

**Comment by Johnreidsilver** [comment]
Ok, so what's the latest stable version where I can expect things to just work?

**Comment by Ichunjo** [comment]
If you want a stable version of havsfunc, just grab it in its repo.

**Comment by Ichunjo** [comment]
That will probably part of R58 when it’ll be released.

**Comment by Johnreidsilver** [comment]
Just tried with r56, working ok with old havsfunc, thanks.
