### ISSUE TITLE
"AssumeFPS" function and the framerate when reading the input

### ISSUE THREAD

**Issue by miaoqiz** [vapoursynth/vapoursynth#831]
Thanks so much for your help! I appreciate it.

I am just wondering if the "[AssumeFPS](http://www.vapoursynth.com/doc/functions/video/assumefps.html)" is the appropriate method to call if the input frame-rate differs from the output frame-rate? 

For example, reading the input clip in "25fps" and generating the output clip in "50fps".

Also, I saw some people use "30000" instead of "29.9fps" for the "fpsnum" parameter. Is there a math to convert the frame-rate back and forth? 

Thanks so much and have a good day!

**Comment by LightArrowsEXE** [comment]
Yes, it is.

24000/1001 is a relic of NTSC framerates that are (unfortunately) still in use today, so you'll often find movies/TV series having those framerates.

Also, this is not a public forum. If you have specific encoding/filtering questions, either go to doom9 (or some other relevant forum), or find a support discord server.

**Comment by miaoqiz** [comment]
Thanks so much! I appreciate it. :)
