### ISSUE TITLE
Error compiling vapoursynch

### ISSUE THREAD

**Issue by phharley17** [vapoursynth/vapoursynth#832]
I am relatively a beginner to the Linux environment, so is very likely my environment the fault of this. I am trying to find out what could be the reason. I am compiling it on Google Colab which uses Ubuntu. I've installed and meet all the requirements but I still get the following

`CXXLD    libvapoursynth.la
ar: `u' modifier ignored since `D' is the default (see `U')
  CXX      src/vsscript/libvapoursynth_script_la-vsscript.lo
  CXXLD    libvapoursynth-script.la
ar: `u' modifier ignored since `D' is the default (see `U')
  CYTHON   src/cython/vapoursynth.c

Error compiling Cython file:
------------------------------------------------------------
...
from libc.stdint cimport intptr_t, int16_t, uint16_t, int32_t, uint32_t
from cpython.buffer cimport PyBUF_SIMPLE
from cpython.buffer cimport PyBuffer_FillInfo
from cpython.buffer cimport PyBuffer_IsContiguous
from cpython.buffer cimport PyBuffer_Release
from cpython.memoryview cimport PyMemoryView_FromObject
^
------------------------------------------------------------

src/cython/vapoursynth.pyx:30:0: 'cpython/memoryview.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
from libc.stdint cimport intptr_t, int16_t, uint16_t, int32_t, uint32_t
from cpython.buffer cimport PyBUF_SIMPLE
from cpython.buffer cimport PyBuffer_FillInfo
from cpython.buffer cimport PyBuffer_IsContiguous
from cpython.buffer cimport PyBuffer_Release
from cpython.memoryview cimport PyMemoryView_FromObject
^
------------------------------------------------------------

src/cython/vapoursynth.pyx:30:0: 'cpython/memoryview/PyMemoryView_FromObject.pxd' not found`

This is the log preceding the first error, after that there are multiple errors of 'not found' .pxd files. I've tried to copy some of those files from the source code (not sure of they are the same), does not seem to make a difference. Any suggestions or ideas what could it be.

Since it appears related to it. I've uninstalled Cython and reinstalled Cython 28, and still does not seem to make any difference.

**Comment by 4re** [comment]
You need cython 0.29.

**Comment by phharley17** [comment]
> You need cython 0.29.

Thank you. I forgot to mention, Colab comes with Cython 0.29. I tried uninstalling it and installing 0.28. but I can try uninstalling and trying installing again.

**Comment by phharley17** [comment]
Update, it Colab actually had Cython 29.24, but I uninstalled it and installed again, this time it did compile with no problems. Thank you again.
