### ISSUE TITLE
VS clip freezing in resizer 

### ISSUE THREAD

**Issue by caylaanne** [vapoursynth/vapoursynth#835]
Hey guys! Recently, the clip in my resizer has stopped looping continuously. I’m not sure what exactly happened but, I’ve tried to uninstall and reinstall VS and nothing has changed. This problem makes it difficult to resize efficiently and I’m hoping some of you may have a solution! Thanks!

**Comment by RivenSkaye** [comment]
Please explain what you mean by looping, ehat resizer it is that freezes and if possible, provude example code. We need some useful information in order to help figure out what the issue even is

**Comment by LightArrowsEXE** [comment]
This is not a filtering support forum.
