### ISSUE TITLE
Why is coreplugins rolled back after R55?

### ISSUE THREAD

**Issue by emako** [vapoursynth/vapoursynth#836]
## R54

in VapourSynth64-Portable-R54\vapoursynth64\coreplugins\

```
avisource.dll
AvsCompat.dll
EEDI3.dll
libhistogram.dll
libimwri.dll
libsubtext.dll
MiscFilters.dll
Morpho.dll
RemoveGrainVS.dll
Vinverse.dll
VIVTC.dll
```
**After R55, only `AvsCompat.dll` is left.**

**What happened?**

**Comment by theChaosCoder** [comment]
They are all external plugins now. Each one has it's own repo https://github.com/vapoursynth

**Comment by emako** [comment]
Some are obsolete, such as https://github.com/vapoursynth/vs-miscfilters-obsolete ,
is there any upgrade plan?

**Comment by YomikoR** [comment]
These obsolete filters are either superseded by others (misc->std, eedi3->eedi3m, etc.) or rarely used in existing public scripts. Old builds are supposed to work on if you keep a copy.

**Comment by emako** [comment]
I'm glad it's not bad news.
