### ISSUE TITLE
Error importing misc filters within vpy scripts

### ISSUE THREAD

**Issue by aRI0U** [vapoursynth/vapoursynth#843]
Hi!
I try to run an existing `.vpy ` but I get an error when I try to use Hysteresis.
Here is the python instruction:
```python
Bright_Not=core.misc.Hysteresis(clipa=Bright_Out,clipb=Bright_Raw)
```
and the error is:
```
Bright_Not=core.misc.Hysteresis(clipa=Bright_Out,clipb=Bright_Raw)
File "src/cython/vapoursynth.pyx", line 2437, in vapoursynth._CoreProxy.__getattr__
File "src/cython/vapoursynth.pyx", line 2279, in vapoursynth.Core.__getattr__
AttributeError: No attribute with the name misc exists. Did you mistype a plugin namespace?
```
I therefore assume that the script was originally written with an older version of VapourSynth and that the `Hysteresis` filter's location might have changed (I use version R57). I tried different importing paths mixing `filters` and `misc` but none of them works.
Does anyone know the right way to import it?

Thanks!

**Comment by theChaosCoder** [comment]
You need to install the misc plugin. Download it here https://github.com/vapoursynth/vs-miscfilters-obsolete/releases or run in terminal `vsrepo install misc`

**Comment by aRI0U** [comment]
It works, thanks a lot!
Since the way to install the misc filters was not indicated in the repo and was not so obvious for me (I'm not familiar with compiling C++ libraries), here is the method I used on my Ubuntu machine, maybe it'll help anyone else:
```
sudo apt-get install ninja meson
git clone https://github.com/vapoursynth/vs-miscfilters-obsolete.git
cd vs-miscfilters-obsolete
meson setup builddir
meson compile
cd compile
ninja
ninja install
```
It might be non-optimal but at least it works
