### ISSUE TITLE
Migration: Is there any migration doc?

### ISSUE THREAD

**Issue by emako** [vapoursynth/vapoursynth#845]
such as
1. in script
import vapoursynth as vs
`core = vs.get_core()` not found.

2. in vsedit
Error forming pixmap from frame. Expected format CompatBGR32. Instead got 'YUV420P8'.

How to migrate old scripts to R57?
Is there any migration doc?

**Comment by myrsloik** [comment]
1. Has been deprecated for like 3 years now. But nobody gives a shit about warnings. Solution: vs.core

2. Update to one of the many vsedit forks with API4 support.

https://github.com/vapoursynth/vapoursynth/blob/master/APIV4%20changes.txt#L104
