### ISSUE TITLE
Subsampled single precision formats via resize function

### ISSUE THREAD

**Issue by NSQY** [vapoursynth/vapoursynth#846]
I was just wondering if we could get YUV422PS and YUV420PS exposed? These formats can be seen via vspipe, however as far as I can tell there is no way to convert directly to them, only workarounds (i.e resample chroma, shuffle, then shift).

In my script, I am converting from 4:4:4 subsampling to 4:2:0. To do this, I have to convert to YUV420P16 and apply dither. I would prefer to have a consistent bit depth all the way down until my final call. I understand this is extremely pedantic, but I prefer the syntax of the zimg filter to fmtc.

```
Width: 1920
Height: 1080
Frames: 5367
FPS: 30/1 (30.000 fps)
Format Name: YUV420PS
Color Family: YUV
Alpha: No
Sample Type: Float
Bits: 32
SubSampling W: 1
SubSampling H: 1
```

**Comment by myrsloik** [comment]
1. You're wasting your time with float if you also subsample.
2. You can get the format constants with this function: http://vapoursynth.com/doc/pythonreference.html#Core.query_video_format
