### ISSUE TITLE
[Question] vapoursynth4.nim: output

### ISSUE THREAD

**Issue by mantielero** [vapoursynth/vapoursynth#848]
Sorry to post here a question, but I am not managing to log into doom9. 

I created [vapoursynth4.nim](https://github.com/mantielero/vapoursynth4.nim) which aims to wrap the new API4 for Nim programming language. I just did a test to play a video and it worked. In order to output the video, I keep on using the same function [Pipey4m](https://github.com/mantielero/vapoursynth4.nim/blob/058882b094470f5b15b7b251e9e0b128ff94944a/src/lib/output.nim#L198), which sends to stdout as uncompressed y4m format.

I've been off for a while, and now I see that audio is supported. How should I deal with audio? I think I saw somewhere like it outputs PCM audio. Do I have to choose between outputing video or audio? Is there a way to get multiplexed audio/video.

Kind regards

**Comment by DJATOM** [comment]
Guess you can't draw 2 nodes simultaneously. But requesting  2 nodes on your will virtually possible. 
It's up to you howto manage request synchronization.

**Comment by mantielero** [comment]
I am thinking in this example:
```python
# vspipe -c y4m ex02.vpy - | ffmpeg -i pipe: encoded.mkv
import vapoursynth as vs
audio = vs.core.bas.Source("./resources/file_example_MP3_700KB.mp3", track=-1)
video = vs.core.std.BlankClip()
video.set_output(0)
audio.set_output(1)
```
where it looks like audio and video are processed at the same time. I would expect this to create both video and audio (I cannot check because is failing in my computer):
```
$ vspipe -c y4m ex02.vpy - | ffmpeg -i pipe: encoded.mkv
ffmpeg version n4.4.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11.1.0 (GCC)
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-amf --enable-avisynth --enable-cuda-llvm --enable-lto --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmfx --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librav1e --enable-librsvg --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-libzimg --enable-nvdec --enable-nvenc --enable-shared --enable-version3
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
[mp3float @ 0x5575276b9400] Could not update timestamps for skipped samples.
Error: can only apply y4m headers to YUV and Gray format clips without alpha
Output 240 frames in 153917.99 seconds (0.00 fps)
pipe:: Invalid data found when processing input
```

If so, then I'd like to do the same in Nim.

**Comment by DJATOM** [comment]
Nah, `vspipe` computes only one node at time. By default it takes node 0. 
y4m is video-only container and you can't do anything with it. But it should be possible to mux into NUT format, it supports interleaving and piping.

**Comment by mantielero** [comment]
Thanks for the info. I will see what I can do.
