### ISSUE TITLE
Consider WAVE_FORMAT_EX support for VFW in addition to existing WAVE_FORMAT_EXTENSIBLE

### ISSUE THREAD

**Issue by Mikewando** [vapoursynth/vapoursynth#852]
Currently (as of R57) audio output for VFW always uses `WAVE_FORMAT_EXTENSIBLE`. As I understand it (which is not deeply) that supports arbitrary channels and perhaps other desirable things that `WAVE_FORMAT_EX` does not. However it also does not seem to work properly with the `AVI/WAV File Source` DirectShow filter. This means, for example, that MPC-HC is not able to play audio from a Vapoursynth file (it knows the audio is there, but the DirectShow components don't want to connect I guess).

Avisynth++ supports both formats via [OPT_UseWaveExtensible](http://avisynth.nl/index.php/Internal_functions#OPT_UseWaveExtensible), and notes this deficiency in `AVI/WAV File Source` (which I wish I had read much earlier while investigating this issue).

I don't know what mechanism Vapoursynth would prefer to use to toggle the behavior. Anecdotally my use case is simple stereo audio so I would actually prefer WAVE_FORMAT_EX by default, but I don't mind adding boilerplate to my scripts.

(And also if anyone has a video player that does support `WAVE_FORMAT_EXTENSIBLE` audio that would be of personal interest).

**Comment by DJATOM** [comment]
Guess you can output raw audio and "mux" it with ffmpeg. Or even "remux" `WAVE_FORMAT_EXTENSIBLE` into desired wav container 😕

**Comment by myrsloik** [comment]
Directshow is still relevant? Now I'm curious about the work flow

**Comment by Mikewando** [comment]
Getting the audio to ffmpeg works just fine, no issue there.

The workflow is quite simple, just opening a script that has audio in MPC-HC.
