### ISSUE TITLE
Is there any possibility to support YUVA format?

### ISSUE THREAD

**Issue by BlackMickey** [vapoursynth/vapoursynth#859]
I am using VapourSynth filter and LAV decoder in MPC-BE.
When playing YUV444P10 video, the output format of LAV decoder is Y410/Y416, and the format of Y410/Y416 is YUVA444, not YUV444 which is supported by VapourSynth.

Is it possible for VapourSynth to support YUVA format?

**Comment by DJATOM** [comment]
Vapoursynth already supports alpha, but extra plane handled separately. Source filter must support it. Read the docs.

**Comment by CrendKing** [comment]
@DJATOM Are you referring to [this](http://vapoursynth.com/doc/apireference.html?highlight=alpha)? Is there any more detail about the frame? What's the color family required?

**Comment by DJATOM** [comment]
Yeah, that. I think there's no restriction, just ensure the same bit-depth and dimensions. It's just a frame attached via props.
