### ISSUE TITLE
Import video with alpha channel from ffms2

### ISSUE THREAD

**Issue by RealTehreal** [vapoursynth/vapoursynth#867]
Hey community,

I've read up quite a bit and finally came to a stall.

I'm trying to import a video with alpha channel (yuva444p12le) using ffms2. Regarding ffms2' documentation, one would have to set a parameter to get the alpha channel imported:

> Output the alpha channel as a second clip if it is present in the file. When set to True an array of two clips will be returned with alpha in the second one. If there is alpha information present.

https://github.com/FFMS/ffms2/blob/master/doc/ffms2-vapoursynth.md#bint-alpha--false

It seems to work on ffms2' side, but regarding following message, Vapoursynth does not to accept an input array:
`setVideoInfo: Video filter Source has more than one output node but only the first one will be returned`

Now, what can I do to import my video, including the alpha channel? 
And when we're already at it, what would I do to output it afterwards? It'd be fine if I had to pipe both the main and the alpha stream one after another.

Used code:
```
import vapoursynth as vs
core = vs.core

core.std.LoadPlugin('/home/realtehreal/git/ffms2/src/core/.libs/libffms2.so.5.0.0')

vclip = core.ffms2.Source('meow.mov', alpha=True)

vclip.set_output(0)
```

Thank you very much in advance!

**Comment by myrsloik** [comment]
You need a newer compile of ffms2, the latest release is too old

**Comment by RealTehreal** [comment]
Thank you for replying.

I have compiled from source (https://github.com/FFMS/ffms2). `git pull` tells me, that the code is still up-to-date. Where would I find a more recent version of ffms2?
