### ISSUE TITLE
Additional info in certain errors

### ISSUE THREAD

**Issue by LightArrowsEXE** [vapoursynth/vapoursynth#880]
More verbose errors to help with diagnosing issues would be useful.

This is already implemented with something like colour spaces, where it displays x/x/x.
I'd like that to be expanded to all errors involving incompatible formats/dimensions.

To name a few examples:

* MaskedMerge: Print clip formats or dimensions if they don't match in clip_a and clip_b's. Same with mask
* ShufflePlanes: Every clip's format if they don't match
* AverageFrames: Every clip's format if they don't match

The last two prove a fun game of figuring out what the best way to print a whole bunch of clips would be. Sequentially? On new lines? Maybe enumerated?

**Comment by myrsloik** [comment]
Done?
