### ISSUE TITLE
Make FreezeFrames no frames passed a no-op

### ISSUE THREAD

**Issue by LightArrowsEXE** [vapoursynth/vapoursynth#881]
It's not uncommon for FreezeFrames to be used purely for optimisation and automatically applied in a script (for example, in some cuts of openings/endings), but those are not always going to be there. It'd be nice if FreezeFrames simply passed the original clip untouched if there were no ranges passed at all, but still error if one of them was passed and another was missing.

Here's an example of a code snippet where having it as a no-op would be very nice.

```py
opstart = None

freeze_frames = []

if opstart is not None:
    freeze_frames += [[100], [200], [100]]

src = ...
...
fs, fe, ff = [], [], []  # Moving the individual frames into their own lists
for frames in freeze_frames:
    fs += [frames[0]]
    fe += [frames[1]]
    ff += [frames[2]]

freeze = src.std.FreezeFrames(fs, fe, ff)
```

Whereas this should still fail because the user is clearly trying to actually freezeframe something, but something just messed up.

```py
...
freeze = src.std.FreezeFrames([], [200], [100])
```

This would make it so users don't have to add special exceptions just to make sure FreezeFrames doesn't randomly kill the script unless they manually check every video.

**Comment by myrsloik** [comment]
Done
