### ISSUE TITLE
compilation fails in Arch Linux

### ISSUE THREAD

**Issue by prestidigitonium** [vapoursynth/vapoursynth#883]
All the system is updated, I installed as requested by wiki: `python3 ffmpeg libass zimg imagemagick cython` 
I did:
```
git clone https://github.com/vapoursynth/vapoursynth.git
./autogen.sh
./configure
make
```
but during the make there is this error:
![image](https://user-images.githubusercontent.com/63223659/174843956-925b2885-26f3-425c-b68f-0cba25eb8866.png)

**Comment by myrsloik** [comment]
Incomplete output unless you compiled with -Werror or something, in which case it'll never work.

**Comment by 4re** [comment]
To install you need to be root, but you will start to litter your system installing like that.
It's better to use packages and Arch has good support for Vapoursynth via [AUR](https://aur.archlinux.org/packages/vapoursynth-git).
Oh, and your `make` command didn't crash without output, it just finished its job.

**Comment by myrsloik** [comment]
Go learn the basics someplace else
