### ISSUE TITLE
Failed to initialize VapourSynth environment on Ubuntu

### ISSUE THREAD

**Issue by feckpown** [vapoursynth/vapoursynth#892]
After building VapourSynth on Ubuntu, i get the following error when i try to use mpv with VapourSynth:

```
[vapoursynth] Could not initialize VapourSynth scripting.
[user_filter_wrapper] Creating filter 'vapoursynth' failed.
```
When i type vspipe -v i also get
```
vspipe -v
Failed to initialize VapourSynth environment
```
Failed to initialize is not a very useful error message, where should begin to locate the issue?

**Comment by stuxcrystal** [comment]
Hi.

I have two questions:

A) How did you install vapoursynth and on what Ubuntu Version.
B) What happens if you do `import vapoursynth` in your Python shell? Please send us the full output, including your Python invocation.

This should get us a step further

**Comment by feckpown** [comment]
A) Ubuntu 20.04, i used the guide here https://www.svp-team.com/wiki/SVP:Linux "Building 3rd-party apps from sources" 

B) Import in python seems to work fine:

```
Python 3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
import vapoursynth
vapoursynth
<module 'vapoursynth' from '/home/user/anaconda3/lib/python3.8/site-packages/vapoursynth.cpython-38-x86_64-linux-gnu.so'>
```

The strange thing is that when using the control panel of SVP, mpv with vapoursynth seems to work perfectly fine behind the curtains, but if i copy the command from the SVP Log and manually enter it into a terminal:

`/usr/bin/mpv input.mp4 --o=input.SVP.temporary.mkv --no-audio --no-sub --no-sub-auto --input-ipc-server=/tmp/mpvencodesocket --input-media-keys=no --no-msg-color --vf=vapoursynth:/home/user/.local/share/SVP4/scripts/ffff.py:4:48 --of=matroska --ovc=libx264 --ovcopts=crf=17,preset=slow,threads=48`

 i also get the "Failed to initialize VapourSynth environment" error..

```
[vapoursynth] Could not initialize VapourSynth scripting.
[user_filter_wrapper] Creating filter 'vapoursynth' failed.
[vo/lavc] error encoding at EOF
```

**Comment by stuxcrystal** [comment]
Are you sure mpv uses the Python provided by Anaconda?
If not, then mpv (and vspipe) can't find the module and thus can't work.

**Comment by feckpown** [comment]
Not at all sure, though i figured there would be some sort of issue with my VapourSynth environment since vspipe -v gives the Failed to initialize VapourSynth environment error. If i try with the system python /usr/bin/python3.8 or /usr/bin/python , the import vapoursynth also works. 

Does the "Failed to initialize VapourSynth environment" come from a failed vapoursynth import or something else?

**Comment by feckpown** [comment]
If i do 

`LD_LIBRARY_PATH=/usr/local/lib vspipe --version`

as suggested in http://www.vapoursynth.com/doc/installation.html, i also get 

`Failed to initialize VapourSynth environment`

But if i do the other suggestion: 

`PYTHONPATH=/usr/local/lib/python3.x/site-packages vspipe --version`

I get

```
PYTHONPATH=/usr/local/lib/python3.8/site-packages vspipe --version
VapourSynth Video Processing Library
Copyright (c) 2012-2020 Fredrik Mellbin
Core R52
API R3.6
Options: -
```

Which looks correct, yet if i do 

`vspipe -v`

I still get

`Failed to initialize VapourSynth environment`

I feel like i am missing something here?

**Comment by hooke007** [comment]
> Failed to initialize VapourSynth environment

vspipe cannot found your python. Are you sure your python is in PATH?

**Comment by DJATOM** [comment]
@feckpown You can set environment variable for python path in your shell (bash/zsh or whatever you're using). That should fix your python issue, but might interfere with any other python env. More clean solution is to create some bash script with altered PYTHONPATH, like a `PYTHONPATH=/usr/local/lib/python3.x/site-packages vspipe "$@"` with similar name (`myvspipe` for example) and executable rights (0755).
