### ISSUE TITLE
Crash with vsscript freeScript

### ISSUE THREAD

**Issue by YomikoR** [vapoursynth/vapoursynth#897]
VSEditor crashes when checking the following script (by pressing F6; without acquiring any specific frame) for the second time:
```python
import vapoursynth as vs
core = vs.core
import vsdehalo
clip = core.std.BlankClip(width=1920, height=1080, format=vs.GRAY16)
clip = vsdehalo.fine_dehalo(clip)
clip.set_output()
```
This can be repeatedly reproduced on Windows 10, with Python 3.10 and VS R59.
In the above script [vsdehalo](https://github.com/Irrational-Encoding-Wizardry/vs-dehalo) only uses VS built-in functions, and no other plugins are required. A debug build of vsedit may be found [here](https://github.com/YomikoR/VapourSynth-Editor/releases/tag/debug-build-1).

In vsedit I can only see it crashes at freeScript. Some further console outputs suggest when checking for the second time, [clearing outputs](https://github.com/vapoursynth/vapoursynth/blob/master/src/cython/vapoursynth.pyx#L3072) doesn't seem to work.

**Comment by YomikoR** [comment]
A slightly different way to reproduce a similar (?) bug with minimal lines of code, requiring multiple F6 checks:

foo.py
```python
import vapoursynth as vs
scaler = vs.core.resize.Lanczos
```

script.vpy
```python
import vapoursynth as vs
import foo
clip = vs.core.std.BlankClip()
clip = foo.scaler(clip, 1920, 1080)
#clip = foo.scaler(clip)
clip.set_output()
```

The `foo.py` does what vskernel does in the filter chain of vsdehalo.

**Comment by myrsloik** [comment]
CPU and OS?
Things like these usually depend on things like that

**Comment by YomikoR** [comment]
Windows 10, same as above. Will check Linux in a few hours. Happens to AMD 4750U and Intel 9700KF.

**Comment by cid-chan** [comment]
Incorrect use:

```py
# foo.py
import vapoursynth as vs

# Is only run once and never gets the new cores of the actual .vpy-script run.
# Thus it should crash since from the second use onwards, it's gonna get a clip from a different core assigned.
scaler = vs.core.resize.Lanczos 

# script.vpy
# This file is run with a new core for every run.
import vapoursynth as vs
import foo
clip = vs.core.std.BlankClip()
clip = foo.scaler(clip, 1920, 1080)
#clip = foo.scaler(clip)
clip.set_output()
```

This is why every *func.py had to run vs.get_core() within a function back in the day and couldn't store the core on module level. `scaler = vs.core.[something]` functionally does the same.

**Comment by YomikoR** [comment]
Is there a way vsedit can detect such improper usage?

**Comment by myrsloik** [comment]
VS will print something to stderr when it terminates

**Comment by YomikoR** [comment]
Sure, but what if in stderr there's simply segfault...
