### ISSUE TITLE
[Feature Request] Expr - Support for bit-depth aware constants (like AVS+)

### ISSUE THREAD

**Issue by adworacz** [vapoursynth/vapoursynth#903]
Reference: https://avisynthplus.readthedocs.io/en/latest/avisynthdoc/corefilters/expr.html#bit-depth-aware-constants

Avisynth+'s Expr has some useful functions that make dealing with higher bit depth a bit easier. I'm thinking specifically of things like `range_half` or `range_min`/`range_max`, which make writing certain Expr statements a fair sight easier for anything over 8-bit.

Some of the `scalef`/`scaleb` functions might be useful as well, but I'm just spitballing a bit here.

What do you think? Some of these seem like low hanging fruit, especially the bit-depth aware constants.

**Comment by Setsugennoao** [comment]
You might be interested in https://github.com/Irrational-Encoding-Wizardry/vs-exprtools.

These are the available [tokens](https://github.com/Irrational-Encoding-Wizardry/vs-exprtools/blob/master/vsexprtools/exprop.py#L25-L42). The names are close to those of AVS' for ease of porting functions.

There are also plane and range dependant constants.

**Comment by myrsloik** [comment]
Probably outside the scope, there are alternatives with kitchen sink included for those who want it
