### ISSUE TITLE
Run the installer again and select "Install for me only"

### ISSUE THREAD

**Issue by hanacchi** [vapoursynth/vapoursynth#905]
How?

I'm trying to install VapourSynth R60 on Windows 10. Python 3.10 x64 is installed for the current user only:
```
C:\>where python
C:\Users\user\AppData\Local\Programs\Python\Python310\python.exe
```

When I run the installer, the first thing that shows up is this message box:
```
---------------------------
Setup
---------------------------
Python 3.10 or 3.8 (64-bit) is installed for the current user only.
Run the installer again and select "Install for me only" or install Python for all users.
---------------------------
OK   
---------------------------
```

I would prefer not to install Python for all users. How do I get the VapourSynth installer to let me select "Install for me only"?

**Comment by YomikoR** [comment]
Does it happen only when an installation exists?

**Comment by Setsugennoao** [comment]
You had already installed VapourSynth, and now you're updating.
You can only update on the same installation type.
If you want to change it, you can uninstall and change install type.
If uninstalling doesn't work, go into the registry and manually delete the entries.
