### ISSUE TITLE
Python 3.11 not found/recognized

### ISSUE THREAD

**Issue by tormento** [vapoursynth/vapoursynth#909]
I have Python 3.11 installed (last stable).

VS gives me error on installation with "no suitable python 3.10 found".

How to fix that, apart from rolling back python version?

**Comment by Setsugennoao** [comment]
You should either roll back to Python 3.10 or wait for R61/2 in which Myrsloik will bump Python version.

Of course, you can always compile it yourself, or if you must use 3.11, you can use this [build](https://github.com/Setsugennoao/vapoursynth/releases/tag/R61-RC1), but absolutely don't ask for support; I've done it just for lazy people that cba to build it themselves ![](https://cdn.discordapp.com/emojis/805663853069205544.gif?size=16&quality=lossless)
(Also please don't use my repo for anything, any issue/pr will be rejected)

**Comment by myrsloik** [comment]
Python 3.11 will be used in the next release
