### ISSUE TITLE
Version numbers in plugins are usually 0, -1 or similar

### ISSUE THREAD

**Issue by myrsloik** [vapoursynth/vapoursynth#912]
Solution: add an annoying warning whenever loading one of these plugins

**Comment by YomikoR** [comment]
Will it be possible to warn only once in a previewer when scripts getting reloaded?

**Comment by myrsloik** [comment]
> Will it be possible to warn only once in a previewer when scripts getting reloaded?

It's usually a new core with no knowledge of previous state so maybe not? I suspect people will add a proper version fairly quickly anyway.

**Comment by YomikoR** [comment]
> It's usually a new core with no knowledge of previous state so maybe not? I suspect people will add a proper version fairly quickly anyway.

If in the API error messages are further classified then we can let previewers remember them.
