### ISSUE TITLE
Missing files in vsrepo folder & ImportError

### ISSUE THREAD

**Issue by Ichunjo** [vapoursynth/vapoursynth#916]
[__main__.py](https://github.com/vapoursynth/vsrepo/blob/master/vsgenstubs4/__main__.py) and [init.py](https://github.com/vapoursynth/vsrepo/blob/master/vsgenstubs4/init.py) are missing in the `C:\Program Files\VapourSynth\vsrepo` folder resulting in the failure to generate the stubs

**Comment by Ichunjo** [comment]
Even by manually adding the file I still get the error:
```
Traceback (most recent call last):
  File "C:\Program Files\VapourSynth\vsrepo\vsgenstubs4\__init__.py", line 1, in <module>
    from .init import main  # noqa: F401
ImportError: attempted relative import with no known parent package
```

**Comment by Ichunjo** [comment]
Errors probably introduced by https://github.com/vapoursynth/vsrepo/pull/186

**Comment by dexeonify** [comment]
In that directory (`C:\Program Files\VapourSynth\vsrepo\vsgenstubs4\`), there's a ".init.py" file. I renamed it from ".init" to "init" and it seems to silence the error. Not sure if it breaks other stuffs though.

**Comment by dexeonify** [comment]
Ah, you're talking about the built-in vsrepo that came with Vapoursynth. Weirdly enough, even using the standalone vsrepo, I encountered the same error.

**Comment by Ichunjo** [comment]
#917 only half fixed the issue as I said [there](https://github.com/vapoursynth/vapoursynth/issues/916#issuecomment-1336316303). I compiled the master branch and it's still broken for me.

**Comment by Setsugennoao** [comment]
It installs fine for me
![image](https://user-images.githubusercontent.com/41454651/208782015-cf620abf-e1d8-4b3d-8ce9-0fa427c9eaf0.png)
Build can be found here https://github.com/Setsugennoao/vapoursynth/releases/tag/R61-build-test
