### ISSUE TITLE
Improve Pismo virtual FS

### ISSUE THREAD

**Issue by Artofeel** [vapoursynth/vapoursynth#92]
Right now you have to wait very long when you open virtual AVI file larger than ~ 100GB
It is also often that the cache(?) gets off when switching from one mounted script to another, and you have to wait to re-open the file
Is possible if output of video data in a sequence of images (png\tiff\RAW) will be more comfortable than their withdrawal into an one big AVI file?

**Comment by Artofeel** [comment]
So, no progress?.. it's really useful feature
just make some test with .avs vs .vpy
simple FFMS2 source and internal color conversion to RGB32
AVFS 1.0.0.5 and 1.0.0.6 (32 bit!) is ~2.5x faster (open file) that VSFS... (~3min vs ~8min)
looking at this post: http://forum.doom9.org/showthread.php?p=1387878#post1387878
the problem is that the program is trying to get frames from all over AVI file
also about "switching from one mounted script to another" issue, it's only happens in After Effects and because it's close AVI file when I'm switching to another and then open it again...
AVI file is completely not usable it this case, image sequence is best solution

ps: some useful info maybe
if I'm opened file in VirtualDub with "AVIFile compatibility mode" it's opened instantly, but without seeking ability.

**Comment by myrsloik** [comment]
No progress at all. I've worked on other stuff. I was going to add the latest AVFS changes but then it turns out that AVFS won't even compile with the latest pismo sdk stuff. So now I'm waiting for that before I go back to this.

**Comment by Artofeel** [comment]
and more experimenting..
increasing cache size gives interesting results
source is 1920x814@24 \ 1h:35m \ convert to RGB32 == 800GB virtual AVI file
`import vapoursynth as vs`
`core = vs.get_core()`
**`core.set_max_cache_size(8192)`**
`v = core.ffms2.Source(source=r"video.mkv")`
**`v = core.std.Cache(v, 2000)`**
`v = core.fmtc.resample(v, css="444", kernel="spline64")`
`v = core.fmtc.matrix(v, mat="709", col_fam=vs.RGB)`
`v = core.fmtc.bitdepth(v, bits=8)`
`v = core.resize.Bicubic(v, format=vs.COMPATBGR32)`
`v.set_output()`
will decrease second open time _TO_ 1 minute, first one is still ~8min
adding `core.std.Cache` after color conversions
`import vapoursynth as vs`
`core = vs.get_core()`
**`core.set_max_cache_size(8192)`**
`v = core.ffms2.Source(source=r"video.mkv")`
`v = core.fmtc.resample(v, css="444", kernel="spline64")`
`v = core.fmtc.matrix(v, mat="709", col_fam=vs.RGB)`
`v = core.fmtc.bitdepth(v, bits=8)`
**`v = core.std.Cache(v, 2000)`**
`v = core.resize.Bicubic(v, format=vs.COMPATBGR32)`
`v.set_output()`
will decrease open time to ~10 seconds!, but it's required more memory since video is RGB24, not YUV
anyway this workaround will not help
first: pfmhost.exe eats ~8GB RAM and I only have just 16GB :)
second: it's only helps to open, while working cache fills with different frames and frames that needed to open is no longer in cache.

the number of frames to cache `core.std.Cache(v, 2000)` depend on video, don't know why
for first video 2000 frames is enough, but with other one need 3000 frames
the second video is 1920x1080@23.976 \ 1h:57m \ convert to RGB32 == 1,27TB virtual AVI file
at first I thought it was key-frames, but their number is almost the same (1220 vs 1226)
possible just duration
also, sometimes the cache dropped to ~500mb (overload?) when hitting the limit and then fills again, but in this case second open time is still long as first, so, need to guess how many frames to cache and try to not hit the limit

anyway just make simple avs with `AviSource("MyScript.vpy")` and mount it with AVFS. I can't use v210, but it's faster.
also I completely forgot about makeAVIS, I can make dummy AVI with it! It's not so stable, but no more open delays and seeking is pretty fast.

PS: did you saw that the developer of AVFS, wants to make an output to DPX, maybe you cooperate?
http://forum.doom9.org/showthread.php?p=1714419#post1714419
PPS: an idea, separate 32bit and 64bit VSFS.dll's by renaming them to VSFS32.dll and VSFS64.dll
and register them both, just for filters 32b\64b compatibility
I have already did this for my system and VSFS64 works fine, but VSFS32 don't, pismo say "The file could not be mounted"
if I unregister VSFS64, then VSFS32 works, is there are conflict? why?

**Comment by myrsloik** [comment]
Try the new updated AVFS, no idea how it will perform now

**Comment by Artofeel** [comment]
yeah, I forgot to check this after last update
it seems faster
open 1TB .avi takes "just" ~1.5 min
BUT! IT EATS MEMORY, A LOT!
~3GB just after open file twice (VirtualDub), even with limit
core.set_max_cache_size(512)
and if I start playing\seeking, it hit 10GB easily and keeps growing (+100mb per 1 played second)
also it's not opened faster after it cached so much (even longer)
probably leak?
anyway thanks for trying to improve this
and plz keep compatibility for old VSFS.dll, it's still work well for me :)

**Comment by myrsloik** [comment]
Sigh, I found the leak so maybe the next release will be better for you...

**Comment by myrsloik** [comment]
Can you try the build I've linked here and see if it's good now?
[](http://forum.doom9.org/showthread.php?p=1781901#post1781901)

**Comment by Artofeel** [comment]
checked
memory is OK, no leaks
it's still don't opens video instantly, but it's much faster than original vsfs, thanks!

**Comment by myrsloik** [comment]
Good enough I guess. No more time will be invested into this unless there's substantial number of users requiring it.

**Comment by Artofeel** [comment]
why avisynth is so fast?
for example
I have AVI file with lossless Ut encoding
about 1.5 hour, 1080p, ~200GB in size
when I use AS AVISource and VS AVISource
the different is: ~5 sec versus ~1min 15sec
what exactly vapoursynth DO all this time?..

**Comment by myrsloik** [comment]
So I need a huge lossless test file to really notice this?

**Comment by myrsloik** [comment]
One more question, is it slow if you use the VS avfs.exe with Avisynth?

**Comment by Artofeel** [comment]
yes, I used avfs.exe (64bit)
just grab some HD movie and convert it to lossless avi (RGB)

**Comment by myrsloik** [comment]
I found a problem that probably made it slower. Does your cpu have 16 threads by any chance?

**Comment by Artofeel** [comment]
4 core, with 8 threads (Intel HT)

**Comment by Artofeel** [comment]
just tested R40
and opens time is identical for AviSource
also tested ffms2 (900GB virtual avi)
and it's identical too! about ~1:40 min
Good job!
