### ISSUE TITLE
Logging in APIv4

### ISSUE THREAD

**Issue by Setsugennoao** [vapoursynth/vapoursynth#921]
As of APIv4, the `messageHandlers` are a per-core thing.

APIv3 https://github.com/vapoursynth/vapoursynth/blob/master/src/core/vslog.h 
APIv4 https://github.com/vapoursynth/vapoursynth/blob/master/src/core/vscore.h#L1043 
^ this means you can only add a message logger after a core has been created and initialized, and possibly, all plugins loaded, throwing messages and whatnot.

These all get shadowed in APIv4 applications, and of course in the cython extension too.

Resolving this would also make possible an implementation of #912 effectively work.

My initial solution to this was to store undeliverable messages (meaning no callbacks in `VSCore::messageHandlers`) and then deliver them once `addLogHandler` gets called for the first time, but as Myrsloik pointed out, it could lead to memory leaks if the developer never attaches a log handlers, meaning the "undeliverable messages" list would just grow.

What about limiting the amount of that list then?
Another solution could be to add a global default log handler, maybe?

IMO it's a pretty annoying issue, but it'd be even worse to reverse to what APIv3 did, even if it worked.

**Comment by myrsloik** [comment]
Now caches up to 500 messages
