### ISSUE TITLE
when using VSEdit to preview - Failed to convert to RGB

### ISSUE THREAD

**Issue by liwick** [vapoursynth/vapoursynth#924]
I have installed python3.10.9 VapourSynth64-R61 ffms2 and VapourSynthEditor-r19-64bit,my os is windows 10 64bit.
And this is my code.
```
from vapoursynth import core
clip = core.ffms2.Source(source='out.mp4')
clip = core.std.FlipHorizontal(clip)
clip.set_output()

```
when I want to Preview the log shows 
```
2023-01-19 18:56:27.495
Failed to convert to RGB:
Resize error: Invalid format id.
Couldn't create preview node for output number 0.
```
What's the problem?
How can I solve this?
Thanks！

**Comment by YomikoR** [comment]
It's not a VS issue. You may use an unofficial but maintained version of VSEdit instead, as mentioned in the VS doc.

**Comment by liwick** [comment]
> It's not a VS issue. You may use an unofficial but maintained version of VSEdit instead, as mentioned in the VS doc.

Thanks!
Sorry,i should have checked my soft‘s version first.
