### ISSUE TITLE
R61 - AttributeError: There is no attribute or namespace named misc

### ISSUE THREAD

**Issue by strike94** [vapoursynth/vapoursynth#925]
![image](https://user-images.githubusercontent.com/34638547/213957007-eea1cada-c1d2-4fe7-84f3-a6cb12778a9a.png)
installed r61 and use it in potplayer,but there is a problem:There is no attribute or namespace named misc,how to fix it?

**Comment by WolframRhodium** [comment]
https://github.com/vapoursynth/vs-miscfilters-obsolete/releases/tag/R2
