### ISSUE TITLE
AVFS: Add linux support

### ISSUE THREAD

**Issue by myrsloik** [vapoursynth/vapoursynth#93]
Theoretically porting it to linux (and maybe mac) should be easy since the underlying Pismo driver works everywhere.

**Comment by muxketeer** [comment]
Any chance this will be added soon? Would be really great to have.

**Comment by myrsloik** [comment]
Unfortunately this is one of the things that requires quite a bit of work. Step one would be to port all the AVFS updates into VSFS (which is hard since I made a huge mess of it all).

I was also hoping that Joe (author of the underlying Pismo stuff) would get around to adding image sequence output support but that has been an ongoing project of his for years now...

I want to do it but the universe doesn't give me enough time.

**Comment by muxketeer** [comment]
I assume that R33's addition of AVFS support means we can (theoretically) now do this VSFS stuff in Linux (except using AVFS, instead of VSFS) .  Correct?

**Comment by myrsloik** [comment]
No, won't compile or work at all.

**Comment by myrsloik** [comment]
Won't happen unless someone funds the development/codes it themselves
