### ISSUE TITLE
VS Code autocompletion and newer versions of Vapoursynth

### ISSUE THREAD

**Issue by dixie-flatliner** [vapoursynth/vapoursynth#931]
Not sure how directly related to Vapoursynth this is, but:
With versions of Vapoursynth up to R60, editing .vpy scripts in VS Code allowed for autocompletion and type-checking like normal python scripts. With R61 and newer, this functionality seems to be broken. I've tried multiple fresh installs of valid Vapoursynth/Python combinations, making sure to clean up all the leftover files from each installation when testing a new version. Have tested with R60/3.10 (works), R61/3.10 (doesn't work), and R62/3.11 (see below).

With the R62 release candidates on Setsugennoao's repo, autocomplete worked again for functions from Python scripts, but not plugins. An earlier git build I did myself didn't, so that appears to have been restored by something committed in the past couple of days.

**Comment by LightArrowsEXE** [comment]
![image](https://user-images.githubusercontent.com/42927908/217580478-2d60ead2-0ffd-4312-a705-77e568666f89.png)
Highlighting and autocomplete works with both Python packages and plugins for me on Setsu's R62 build. You may need to install vsrepo again and run `vsgenstubs4` for it to work. This was broken in previous versions.

**Comment by YomikoR** [comment]
> It is now fixed and i also added the package to the portable version.

Do you refer to the files in #917 or are there even more?

**Comment by YomikoR** [comment]
> You may need to install vsrepo again

Do you have clear steps to reproduce from clean installation without any existing stubs?

**Comment by YomikoR** [comment]
> > > You may need to install vsrepo again
> > 
> > 
> > Do you have clear steps to reproduce from clean installation without any existing stubs?
> 
> 1. Install VS
> 2. pip install vsrepo
> 3. vsgenstubs4
> 
> You now have stubs

How did you pip install vsrepo? Does it conflict with the existing one in PATH, if the VS installer with default options were applied?

**Comment by LightArrowsEXE** [comment]
> How did you pip install vsrepo? Does it conflict with the existing one in PATH, if the VS installer with default options were applied?

Nothing special, just `pip install vsrepo`.

**Comment by theChaosCoder** [comment]
Hmm when I try `pip install vsrepo` I get this
Python 3.10.9 on Win11

ERROR: Could not find a version that satisfies the requirement vsrepo (from versions: none)
ERROR: No matching distribution found for vsrepo

**Comment by LightArrowsEXE** [comment]
```py
$ pip freeze | grep vsrepo
vsrepo==50
```
Might have done a git install then, so `pip install git+https://github.com/vapoursynth/vsrepo.git`?

**Comment by YomikoR** [comment]
>  so `pip install git+https://github.com/vapoursynth/vsrepo.git`?

Installing from git and running `vsgenstubs4` works for me with the following residual path issues:
- `vsgenstubs4` creates a folder `vapoursynth-stubs` with functioning .pyi in a subfolder of my python installation path. If python was installed in Program Files, then admin rights might be required.
- Operations with (the newly installed) `vsrepo` often ends with regenerating stubs. This creates a folder `vapoursynth-stubs` with broken .pyi in %APPDATA%\Roaming\Python\Python31x\site-packages, and unfortunately, VSCode plugins prefer this one by default.

**Comment by Setsugennoao** [comment]
Simply don't use vsrepo, since it's fucked to the core.
