### ISSUE TITLE
Instructions to use a venv for python with vapoursynth

### ISSUE THREAD

**Issue by d3xMachina** [vapoursynth/vapoursynth#933]
Hello, I'm on windows and I need to have python 3.11 as my main python version which is not compatible with vapoursynth. Is it possible to use an older python version (3.10) in a virtual environnement with vapoursynth ? I could not manage to do it.

The final setup I want is mpc be + [vapoursynth filter](https://github.com/CrendKing/avisynth_filter) + my script
I had a working setup when python 3.10 was my main version.

Thanks.

**Comment by Setsugennoao** [comment]
You could either compile latest and use python 3.11 or install vapoursynth-portable (since you're on windows) in your 3.10 venv.

**Comment by d3xMachina** [comment]
I finally managed to make it work. I could not make it work with the vapoursynth-portable in a venv.

Here is what I did : 
I followed the instructions [here](http://www.vapoursynth.com/doc/installation.html#windows-installation-portable) to install a portable version.

Vapoursynth filter needs to see VapourSynth.dll but I could not just add its path to the system-wide PATH environment variable since it has python.exe in the same folder and it would make a conflict with my other programs.

That's why before executing MPC BE I change the PATH environment variable to remove the existing python paths and add the location of VapourSynth.dll. To do that you can make a simple batch but it would open a console each time. You can avoid the console with a vbs but I'm not sure how it goes with file associations. So I made an application to edit the environment variables before starting the process [HERE](https://github.com/d3xMachina/EnvForwarder) with the rules : 
```
PATH REMOVE ;?[^;]*\\AppData\\Local\\Programs\\Python\\[^;]*
PATH ADD C:\\MyApps\\Media Player Classic BE\\filters\\VapourSynth
```

It works perfectly now. Thanks for the help.
