### ISSUE TITLE
Clarify in documentation whether vspipe accepts stdin/pipe input, and how if so

### ISSUE THREAD

**Issue by kinkinkijkin** [vapoursynth/vapoursynth#945]
Currently the documentation appears to assume all tasks would involve loading a static file for vspipe, viewing in a media player directly for more arbitrary input types, or writing your own software.

As a result, it is unclear whether vspipe can be used for a configuration which receives live video and returns live video, such as using ffmpeg and the v4l2loopback on linux to analyse capture data from a known problem feed and perform corrections as needed, then return it to a new v4l2 device for broadcast.

The documentation should make clarifications of this, as someone structuring such a setup may spend more time attempting to find the answer to this than they would've taken in finding a workaround should it not be present. (this is the case I find myself in, for context)

The documentation also significantly ambiguates information which would pertain to writing original software for involvement in input streams, as far as making unclear the usage of input streams in this API to a point where I am left uncertain whether the API uses such streams wholesale internally, or is entirely incompatible with them, or anything in between.

I should also request other clarifications in the documentation if applicable, as it appears to ambiguate other actual functions of the API significantly attempting to engage in readability, to the point of potentially being less useful than an autogenerated API reference if this assessment is correct.

**Comment by myrsloik** [comment]
1. It doesn't support stdin since the number of frames is unknown. That's bad m'kay.
2. Live streaming support does however exist if you use vapoursynth in mpv (I think) where it simply cheats and says it has INT_MAX frames or something along those lines.

**Comment by YomikoR** [comment]
What about the situation of stdin support on the python side? A simple input() line is going to make gui apps such as vspreview-rs stuck.

**Comment by myrsloik** [comment]
> What about the situation of stdin support on the python side? A simple input() line is going to make gui apps such as vspreview-rs stuck.

How do you even imagine this working? Interactive scripts will probably always work badly unless run in an interactive environment (like python cli). I'm not sure what you want. You can pass variables to scripts so I don't understand exactly what it is you want.

**Comment by YomikoR** [comment]
Just asking because now it "works" although it should not.

**Comment by couleurm** [comment]
> It doesn't support stdin since the number of frames is unknown. That's bad m'kay.
if it is known, it could be provided as a cli argument so you can e.g. pipe from ffmpeg to vspipe
