### ISSUE TITLE
R62: vspipe instant crash when -s or -e is used

### ISSUE THREAD

**Issue by Mr-Z-2697** [vapoursynth/vapoursynth#946]
Even with minimal script like
```
import vapoursynth as vs
core=vs.core
src=core.std.BlankClip()
src.set_output()
```

**Comment by YomikoR** [comment]
Let's wait for https://github.com/vapoursynth/vapoursynth/pull/942/commits/2f4e08ee1797814eaadb0424e07c1460812eb969 to happen

**Comment by Setsugennoao** [comment]
Tehe
![](https://cdn.discordapp.com/emojis/506480418959261699.webp?size=96&quality=lossless)

**Comment by LightArrowsEXE** [comment]
A temporary workaround is to download the R61 portable version and replace your current vspipe with the vspipe from that.

**Comment by Setsugennoao** [comment]
Or compile it yourself

**Comment by Setsugennoao** [comment]
> Let's wait for [2f4e08e](https://github.com/vapoursynth/vapoursynth/commit/2f4e08ee1797814eaadb0424e07c1460812eb969) to happen

It happened btw

**Comment by Mr-Z-2697** [comment]
No I'm gonna stick with R61 for now

**Comment by NSQY** [comment]
This is still broken @myrsloik 
R61 + 3.10.0 works fine.

python 3.11.0
>vspipe -p test.vpy .
Could not find platform dependent libraries <exec_prefix>
Script evaluation done in 0.22 seconds
Output 16171 frames in 13.54 seconds (1194.46 fps)

>vspipe -p test.vpy --start 0 --end 1000 .
Could not find platform dependent libraries <exec_prefix>
Script evaluation done in 0.14 seconds

python 3.11.1
>vspipe -p test.vpy .
Failed to initialize VSScript

>vspipe -p test.vpy --start 0 --end 1000 .
Failed to initialize VSScript

python 3.11.2
>vspipe -p test.vpy .
Script evaluation done in 0.14 seconds
Output 16171 frames in 13.13 seconds (1231.84 fps)

>vspipe -p test.vpy --start 0 --end 1000 .
Script evaluation done in 0.14 seconds

python 3.11.3
>vspipe -p test.vpy .
Script evaluation done in 0.21 seconds
Output 16171 frames in 13.27 seconds (1218.59 fps)

>vspipe -p test.vpy --start 0 --end 1000 .
Script evaluation done in 0.14 seconds
