### ISSUE TITLE
No C API documentation

### ISSUE THREAD

**Issue by CrendKing** [vapoursynth/vapoursynth#947]
As you can see, 50d31b6643ab31d7b8d7f7957f4828b9fc406e6e removed all VapourSynth 3 C API documentation, and no adding anything back. Currently the [Public Headers](http://www.vapoursynth.com/doc/apireference.html#public-headers) section is empty, and the only ones available is in the [R59 version](http://www.vapoursynth.com/doc/api/vapoursynth.h.html).

Can we fix that?

**Comment by CrendKing** [comment]
Thanks. Didn't know there is a TODO list. Take your time. Feel free to close this.

**Comment by myrsloik** [comment]
Done, if you build the docs in master it should be complete
