### ISSUE TITLE
Build Error - Commit #b380a58

### ISSUE THREAD

**Issue by frkli1965** [vapoursynth/vapoursynth#948]
Experiencing compilation errors on Linux which I assume is related to commit #b380a58.

Trace is as follows:-

src/cython/vapoursynth.c:3444:75: warning: ‘enum VSPresetFormat’ declared inside parameter list will not be visible outside of this definition or declaration
 3444 | static CYTHON_INLINE PyObject* __Pyx_PyInt_From_enum__VSPresetFormat(enum VSPresetFormat value);
      |                                                                           ^~~~~~~~~~~~~~
  CXXLD    vspipe
src/cython/vapoursynth.c: In function ‘__pyx_pymod_exec_vapoursynth’:
src/cython/vapoursynth.c:113119:56: error: type of formal parameter 1 is incomplete
113119 |     __pyx_t_36 = __Pyx_PyInt_From_enum__VSPresetFormat(pfNone); if (unlikely(!__pyx_t_36)) __PYX_ERR(1, 54, __pyx_L1_error)
       |                                                        ^~~~~~
src/cython/vapoursynth.c:113137:56: error: type of formal parameter 1 is incomplete
113137 |     __pyx_t_36 = __Pyx_PyInt_From_enum__VSPresetFormat(pfGray8); if (unlikely(!__pyx_t_36)) __PYX_ERR(1, 55, __pyx_L1_error)

... ... ... ... ...

src/cython/vapoursynth.c:113713:56: error: type of formal parameter 1 is incomplete
113713 |     __pyx_t_36 = __Pyx_PyInt_From_enum__VSPresetFormat(pfRGB24); if (unlikely(!__pyx_t_36)) __PYX_ERR(1, 87, __pyx_L1_error)

src/cython/vapoursynth.c:113731:56: error: type of formal parameter 1 is incomplete
113731 |     __pyx_t_36 = __Pyx_PyInt_From_enum__VSPresetFormat(pfRGB27); if (unlikely(!__pyx_t_36)) __PYX_ERR(1, 88, __pyx_L1_error)

... ... ... ... ...

FWIW, I have successfully built VS many times previously on my system.

**Comment by myrsloik** [comment]
Fixed
