### ISSUE TITLE
API MISUSE! Function 'Reference' failed to register with error: Argument 'clip' has invalid type 'clip'

### ISSUE THREAD

**Issue by sl1pkn07** [vapoursynth/vapoursynth#950]
Hi

i get this output when run any script

API MISUSE! Function 'Reference' failed to register with error: Argument 'clip' has invalid type 'clip'

my latest build is a2a59c68b27c95bf24ea877b014fc94e26be82f0 with #949 applied

i'm not sure if is a VS or python3.11 thing

greetings

**Comment by Setsugennoao** [comment]
You are trying to load an API3 plugin built with API4 on API4.
`clip:clip` should be `clip:vnode`.

**Comment by sl1pkn07** [comment]
mmmmm. ok. how i can search what is the culprit?

greetings

**Comment by Setsugennoao** [comment]
I would also like to note that this is NOT a forum or a place for help, the issue is not VapourSynth related, but rather a (very bad) config issue; issue should be closed.

**Comment by sl1pkn07** [comment]
okidoki.

**Comment by sl1pkn07** [comment]
for the record. @4re, i love you so much!

here is a script for detect the api misuse (and other fail loaling plugins)

1 step: create a  `vapoursynth.conf` with custom:

~~~conf
UserPluginDir=/tmp
SystemPluginDir=/tmp
~~~

2 step: create `api_misuse_detector_xd.vpy`

~~~python
import glob
import os
import vapoursynth as vs

core = vs.core

def get_all_plugins(directory):
    return glob.glob(os.path.join(directory, "**.so"))

plugins = get_all_plugins("/usr/lib/vapoursynth/")

for plugin in plugins:
    print(f"Cargando '{plugin}'")
    try:
        core.std.LoadPlugin(plugin)
    except Exception as Err:
        print(f"'{plugin}' ha fallado la carga: ", Err)
~~~

Note: edit the get_all_plugins with you binary plugin path (no scripts at the moment)

run:

~~~
VAPOURSYNTH_CONF_PATH=./vapoursynth.conf vspipe api_misuse_detector_xd.vpy -
~~~

see the output. example:

~~~
Cargando '/usr/lib/vapoursynth/libvsedgefixer.so'
Critical: API MISUSE! Function 'Reference' failed to register with error: Argument 'clip' has invalid type 'clip'.
~~~

tnx bro XD
