### ISSUE TITLE
Vapoursynth Resize's `matrix_in` parameter not able to override source's matrix metadata

### ISSUE THREAD

**Issue by damian101** [vapoursynth/vapoursynth#952]
Using a script like this
```
import vapoursynth as vs
core = vs.core
c = core.lsmas.LWLibavSource(source="test.mkv")
c = core.resize.Spline64(clip=c, matrix_in_s="2020ncl", matrix_s="709", dither_type="error_diffusion", format=vs.YUV444P8)`
c.set_output()
```
on a source with color matrix metadata does not (visibly) change the content, but on an untagged source it does.

Applied to a source with color matrix metadata again, this slightly altered script 
 ```
 import vapoursynth as vs
core = vs.core
c = core.lsmas.LWLibavSource(source="test.mkv")
c = core.resize.Spline64(clip=c, matrix_in_s="709", matrix_s="709", dither_type="error_diffusion", format=vs.YUV444P8)`
c.set_output()
```
produces identical output as the first script, which also should not be the case, this time regardless of the source.

I would not be surprised if this issue affected primaries and transfer curve as well, did not test.

**Comment by Setsugennoao** [comment]
Welcome to APIv4 behaviour without `prefer_props`.

Either set the prop or clear all props.

Hacky ver: `c.std.CopyFrameProps(c.std.BlankClip())`

**Comment by myrsloik** [comment]
The arguments are only used if no frame property is set. So you'll see the same behavior with everything.

**Comment by damian101** [comment]
> The arguments are only used if no frame property is set. So you'll see the same behavior with everything.

Indeed, which I consider both unintuitive and impractical. 
I'm also quite sure that behavior was different in the past, since I just noticed that a lot of my scripts using vs-placebo tonemap are broken now, because it signals the wrong transfer curve, that of the source instead of the new one, which I could simply override with Vapoursynth Resize in the past, but not anymore.

**Comment by damian101** [comment]
> Welcome to APIv4 behaviour without `prefer_props`.
> 
> Either set the prop or clear all props.
> 
> Hacky ver: `c.std.CopyFrameProps(c.std.BlankClip())`

Thanks, setting frame properties directly works, the hacky solution of removing all properties produced some weird issue though, output always had a strong yellow discoloration for some reason, but just specifying the incorrect properties like this, `c = core.std.SetFrameProps(c, _Transfer=13, _Primaries=12)`, works well.

**Comment by Setsugennoao** [comment]
For your info, this change was a decision, so the issue should be closed.
Also, the change was done 2 years ago; it's strange it took you this long to notice.

**Comment by damian101** [comment]
> For your info, this change was a decision, so the issue should be closed. Also, the change was done 2 years ago; it's strange it took you this long to notice.

Hmm, I guess the reasoning was that matrix_in parameter has higher utility if it does something else than can already be done with std.SetFrameProps? Anyway, closing this...
