### ISSUE TITLE
Critical: Core plugin autoloading failed. Installation is broken! (portable R62)

### ISSUE THREAD

**Issue by Selur** [vapoursynth/vapoursynth#957]
Using the 64bit portable R62 version (Windows 11) and:
```
import vapoursynth as vs
core = vs.core
import site
clip = core.std.BlankClip(format=vs.RGB24, color=[255, 255, 255])
clip = core.text.Text(clip, site.getsitepackages()[0])
clip.set_output()
```
together with:
```
VSPipe.exe c:\Users\Selur\Desktop\version.vpy -p -c y4m NUL
````
I get:
`Critical: Core plugin autoloading failed. Installation is broken!`
piping and opening the script in vsedit/vsviewer/.. works fine.

**Comment by Setsugennoao** [comment]
Config config config config config config config config config config config.

# Nuke your install PLEASE.

**Comment by Setsugennoao** [comment]
On a more serious note:
Either your path doesn't exist, VapourSynth can't access the folder anymore (HOW) or your OS is fucked.

In short, the error seems pretty clear and you fucked your installation.

**Comment by Selur** [comment]
Seems like Vapoursynth is stumbling over something in my Lib\site-packages folder.
...
-> got it, seems like somehow a vapoursynth.dll got copied into the folder, removing that fixed the problem.

**Comment by Setsugennoao** [comment]
The dll should in fact be copied there... when installing system wise, not portable.

**Comment by jlw4049** [comment]
Using `pip install Vapoursynth` on `R62` in a fresh `.venv` I get the same error. Dropping back to `r61` solves it, so I'm not really sure what the issue is here. Anyway this could be investigated further? 

@Setsugennoao
