### ISSUE TITLE
(Ubuntu) ./configure: line 19306: syntax error near unexpected token `ZIMG,'

### ISSUE THREAD

**Issue by ckcr4lyf** [vapoursynth/vapoursynth#959]
I am trying to compile Vapoursynth, but am getting an error in the `./configure` step.

I am doing this in an ubuntu docker container so its a clean environment, the Dockerfile is here: https://github.com/ckcr4lyf/vapoursynth-build/blob/cb8cdf20cfdb3058035638bcdd5e10242f0d5b93/Dockerfile

I am not sure why this is happening, did I miss some step? The error seems to imply it is just something with the syntax of the configuration file?

This error is reproducible in Github Actions. Here is a sample run: https://github.com/ckcr4lyf/vapoursynth-build/actions/runs/5221118544/jobs/9425003714#step:5:2688

Thanks for your help.

Error Log:
```
 > [18/18] RUN ./configure:
#22 1.845 checking for _FILE_OFFSET_BITS value needed for large files... no
#22 1.866 checking for _LARGEFILE_SOURCE value needed for large files... no
#22 1.906 checking how to run the C preprocessor... gcc -E
#22 1.950 checking whether gcc is Clang... no
#22 1.963 checking whether pthreads work with "-pthread" and "-lpthread"... yes
#22 2.006 checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
#22 2.044 checking whether more special flags are required for pthreads... no
#22 2.044 checking for PTHREAD_PRIO_INHERIT... yes
#22 2.084 ./configure: line 19306: syntax error near unexpected token `ZIMG,'
#22 2.084 ./configure: line 19306: `       PKG_CHECK_MODULES(ZIMG, zimg)'
------
```

**Comment by HolyWu** [comment]
You didn't install `pkg-config`.

**Comment by ckcr4lyf** [comment]
Pretty embarrassing, thanks for that.
