### ISSUE TITLE
How to write a frame to a file (PNG)

### ISSUE THREAD

**Issue by ckcr4lyf** [vapoursynth/vapoursynth#960]
Hi, I am trying to do some screenshot comparisons. I am only using vapoursynth on a remote system (no VSEdit).

Using ffms2 I am able to index the file and all, but after interleaving the videos, I am not sure how to write frames to a single PNG.

E.g. I want to write frame 100 from videoA & videoB to `videoA_100.png` & `videoB_100.png`, how could I do it?

I am seeing some old docs for "imwri" but they seem missing now. FYI I am on R62.

Thanks for your help.

**Comment by DJATOM** [comment]
If you're on Windows, download imwri plugin and make desired screens following to documentation. If you are on Linux - compile this plugin on your own and follow documentation to make screens.

**Comment by ckcr4lyf** [comment]
I should compile https://github.com/vapoursynth/vs-imwri/, is that correct?

**Comment by ckcr4lyf** [comment]
I figured it out, that is the correct repository to compile, but it also needs ImageMagick 7+, which needs to be compiled.

To write PNGs, libpng is also needed with ImageMagick, with the `--with-png` flag.

I've built it in a Docker container, this is the main part for the plugin - https://github.com/ckcr4lyf/vapoursynth-build/blob/b2d3e809d9eafd8d513cc8090854d4fda35cc767/Dockerfile#L47-L65

Then to write screenshots to a file, for example, the following can be used:

```py
import vapoursynth as vs
import awsmfunc as awf
core = vs.core

src = core.ffms2.Source('/Arch.Linux.REMUX.2023-LINUS.mkv')
crop = core.std.Crop(clip=src, left=0, right=0, top=132, bottom=132)
extract = awf.SelectRangeEvery(clip=crop, every=3000, length=200, offset=10000)

# Comparison
encode = core.ffms2.Source('/Arch.Linux.1080p.2023-STALLMAN.mkv')
comparison = core.std.Interleave([extract, encode])
comparison = core.resize.Bicubic(comparison, format=vs.RGB24, matrix_in_s="470bg")
comparison = core.imwri.Write(clip=comparison, imgformat="PNG", filename="PREFIX_%03d.png")

limit = len(comparison)
if limit > 50000:
    limit = 50000
skip = 5000

for x in range(2000, limit, skip):
    comparison.get_frame(x)
    comparison.get_frame(x+1)

dummy = core.std.BlankClip(length=1)
dummy.set_output()
```

And then run `vspipe scriptname.vpy .`

This should work with:

* Vapoursynth R62
* vs-imwri R2
* ImageMagick7+

**Comment by couleurm** [comment]
you could also makea script that returns a videonode which has a single frame and call it with vspipe like so:

```bash
vspipe script.vpy --container y4m - | ffmpeg -i - out.png
```

**Comment by NSQY** [comment]
There is also the ScreenGen function in awsmfunc, which you already have.

https://github.com/OpusGang/awsmfunc/blob/master/src/awsmfunc/base.py#L878-L914

**Comment by ckcr4lyf** [comment]
> There is also the ScreenGen function in awsmfunc

This does require `vs-imwri` though. Tbh the compilation was the tricky part, once that's done it's not so bad.

**Comment by damster101** [comment]
> you could also makea script that returns a videonode which has a single frame and call it with vspipe like so:
> 
> vspipe script.vpy --container y4m - | ffmpeg -i - out.png

Doesn't work for RGB output, though:
```
Error opening input files: Invalid data found when processing input
```

**Comment by myrsloik** [comment]
Y4M only works with YUV, you need to manually specify the resolution and colorspace when piping to ffmpeg. Mildly annoying but that's the way it is.

**Comment by myrsloik** [comment]
> would it be easy to make a helper cli tool / vspipe argument that returns what ffmpeg arguments to use to match color/res/fps metadata? if so lets move to a separate issue :p

I guess. Or you could simply use an FFmpeg build compiled with VapourSynth support so you can load the script directly

**Comment by damster101** [comment]
> Y4M only works with YUV, you need to manually specify the resolution and colorspace when piping to ffmpeg. Mildly annoying but that's the way it is.

Well, it should be possible to send planar RGB over Y4M, though... it's just three planes like for YUV.

**Comment by DJATOM** [comment]
> Well, it should be possible to send planar RGB over Y4M, though... it's just three planes like for YUV.

It's effectively not usable in any common software. Dumping it raw and specifying import options is what you normally want to do. Or use nut container, so it can hold an uncompressed RGB frames.
