### ISSUE TITLE
Cache Warning

### ISSUE THREAD

**Issue by nobananasforyou** [vapoursynth/vapoursynth#961]
Hello.

I'm on python 3.11.2 and installed R63 last night. Loading a simple script triggers the following warning(s):
Explicitly instantiated a Cache. This is no longer possible and the original clip has been passed through instead.
Explicitly instantiated a Cache. This is no longer possible and the original clip has been passed through instead.

Script:
import vapoursynth as vs
core = vs.core

src = core.d2v.Source(r'no_you_didnt.d2v')
src.set_output()

**Comment by Setsugennoao** [comment]
Just this needs to be removed
https://github.com/dwbuiten/d2vsource/blob/700523ca0eb4232ae624f12dd81b23ab52517534/src/vs4/d2vsource4.cpp#L253-L259

**Comment by Setsugennoao** [comment]
https://github.com/Setsugennoao/d2vsource/releases/tag/v1.3RC1

No warning on R63 + ffmpeg5 fixed too.

**Comment by myrsloik** [comment]
Harmless warning. The plugin will be updated to remove it soon.
