### ISSUE TITLE
vapoursynth 63 build issue

### ISSUE THREAD

**Issue by chenrui333** [vapoursynth/vapoursynth#962]
👋 trying to build the latest release, but run into some build issue. The error log is as below:

<details>
<summary>error build log</summary>

```
  libtool: compile:  clang++ -DPACKAGE_NAME=\"vapoursynth\" -DPACKAGE_TARNAME=\"vapoursynth\" -DPACKAGE_VERSION=\"63\" "-DPACKAGE_STRING=\"vapoursynth 63\"" -DPACKAGE_BUGREPORT=\"https://github.com/vapoursynth/vapoursynth/issues\" -DPACKAGE_URL=\"http://www.vapoursynth.com/\" -DHAVE_STDIO_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_STRINGS_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_UNISTD_H=1 -DSTDC_HEADERS=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_FSEEKO=1 -DHAVE_PTHREAD_PRIO_INHERIT=1 -DHAVE_PTHREAD=1 -DNDEBUG=1 -DVS_TARGET_OS_DARWIN=1 -DVS_TARGET_CPU_X86=1 -DVS_CORE_EXPORTS=1 -DVS_GRAPH_API=1 -I. -pthread -I/usr/local/Cellar/zimg/3.0.4/include -DVS_PATH_PLUGINDIR=\"/usr/local/lib/vapoursynth\" -std=c++17 -O3 -fvisibility=hidden -Wall -Wextra -Wno-unused-parameter -Wno-unused-function -Wno-ignored-attributes -I./include -mfpmath=sse -msse2 -c src/core/expr/jitcompiler.cpp  -fno-common -DPIC -o src/core/expr/.libs/libvapoursynth_la-jitcompiler.o
  src/core/expr/expr.cpp:206:23: error: call to deleted function 'from_chars'
          auto result = std::from_chars(token.data(), token.data() + token.size(), f);
                        ^~~~~~~~~~~~~~~
  /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/usr/include/c++/v1/charconv:116:19: note: candidate function has been explicitly deleted
  from_chars_result from_chars(const char*, const char*, bool, int = 10) = delete;
                    ^
  /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/usr/include/c++/v1/charconv:776:1: note: candidate template ignored: requirement 'is_integral<float>::value' was not satisfied [with _Tp = float]
  from_chars(const char* __first, const char* __last, _Tp& __value)
  ^
  /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/usr/include/c++/v1/charconv:783:1: note: candidate function template not viable: requires 4 arguments, but 3 were provided
  from_chars(const char* __first, const char* __last, _Tp& __value, int __base)
  ^
```

</details>

full build log, https://github.com/Homebrew/homebrew-core/actions/runs/5272841905/jobs/9535894456
relates to Homebrew/homebrew-core#133713

**Comment by HolyWu** [comment]
https://github.com/vapoursynth/vapoursynth/pull/953#issue-1708623023

**Comment by Setsugennoao** [comment]
Idk why sekrit even changed it, really.

**Comment by chenrui333** [comment]
what is the actionable item to fix the build?

**Comment by sekrit-twc** [comment]
Solution is to update to libc++ 14.0: https://libcxx.llvm.org/Status/Cxx17.html#id2

**Comment by chenrui333** [comment]
> https://developer.apple.com/xcode/cpp/
> 
> Minimum deployment target: For floating-point types, macOS 13.3, iOS 16.3, tvOS 16.3, watchOS 9.3

I have xcode 14.3 builds failed as well, see https://github.com/Homebrew/homebrew-core/actions/runs/5272841905/jobs/9535894456

**Comment by chenrui333** [comment]
this event failed in the project CI as well, https://github.com/vapoursynth/vapoursynth/actions/runs/5424277904/jobs/9863414919#step:10:94

**Comment by chenrui333** [comment]
any idea?

**Comment by HolyWu** [comment]
Plan A: keep using R62 and stay away from R63 until [a volunteer provide the implementation to libc++](https://github.com/llvm/llvm-project/issues/59374#issuecomment-1346558102).
Plan B: replace `std::from_chars` with [`fast_float::from_chars`](https://github.com/fastfloat/fast_float) for the floating point code path.

**Comment by diizzyy** [comment]
For now at least it appears to work by just reverting that change however it should be fixed in next release.

**Comment by diizzyy** [comment]
@myrsloik 
Can we revert this change for R64 release until it also compiles using LLVM/Clang?

**Comment by myrsloik** [comment]
> @myrsloik Can we revert this change for R64 release until it also compiles using LLVM/Clang?

Try it now, main library compilation is fixed and the workflow errors out on some cython stuff instead

**Comment by diizzyy** [comment]
Using master branch does indeed seem to fix the issue, thanks
