### ISSUE TITLE
Flashing artifacts in R63 when resizing video

### ISSUE THREAD

**Issue by the-database** [vapoursynth/vapoursynth#975]
Hello, I am using VapourSynth in my project and had a user report this issue: https://github.com/the-database/mpv-upscale-2x_animejanai/issues/17

We narrowed things down and found that this user was seeing green flashing artifacts in the video when resizing videos in VapourSynth R63 and Python 3.11. The only thing that fixed the issue for this user was to revert to VapourSynth R61 and Python 3.10. 

Unfortunately only this user was able to reproduce this issue on one of his PCs. I am unable to reproduce the issue, and that user couldn't reproduce on his other PC. Any ideas?

**Comment by hooke007** [comment]
To be clear, only `spline36` would show green blcok. (R62&R63)

**Comment by Mr-Z-2697** [comment]
The cause is inside zimg, I tested with an old tag and no problem on my side.
https://github.com/Mr-Z-2697/vapoursynth/releases/tag/R63

**Comment by sekrit-twc** [comment]
What are the dimensions, and what is the CPU? No repro with provided script in R63 official build.

**Comment by Mr-Z-2697** [comment]
> What are the dimensions, and what is the CPU? No repro with provided script in R63 official build.

hooke007 and I are using ryzen 9 7950x, video I use for testing is 1920x1080 but other dimemsions have problem too, the key is yuv to rgbh/s conversion based on what hooke007 told me.

**Comment by sekrit-twc** [comment]
Debugging steps:

1. Can it be repro'd in valgrind?
2. Does the 'cpu' parameter modulate the failure?
3. Does VS debug build trip an assertion (internal heap checker)?
4. Do any of the internal chicken bits modulate the failure*?

*src/zimg/graph/graphbuilder.cpp:1174: real_graph = std::make_unique<...>
--> flip chicken bits here

List of chicken bits in graphengine/include/graphengine/graph.h:L280: // Optimization toggles...

**Comment by Mr-Z-2697** [comment]
> Debugging steps:
> 
> 0. Can it be repro'd in vspipe?
> 1. Can it be repro'd in valgrind?
> 2. Does the 'cpu' parameter modulate the failure?
> 3. Does VS debug build trip an assertion (internal heap checker)?
> 4. Do any of the internal chicken bits modulate the failure*?
> 
> *src/zimg/graph/graphbuilder.cpp:1174: real_graph = std::make_unique<...> --> flip chicken bits here
> 
> List of chicken bits in graphengine/include/graphengine/graph.h:L280: // Optimization toggles...

Sorry I don't have enough skill to perform the real debug...
I have some sitrep though.

0. It can be repro'd in vspipe.
1. It happens when taps is not power of 2, vertical chroma subsampling is involved in source clip, and doing YUV(subsampled) to RGB conversion in single line of code. (so it's not specific to spline36 and floating point output, interger output have small black bars) (although I said power of 2 but from 8 above have no problem, at least I can't spot, is this some kind of regression from https://github.com/sekrit-twc/zimg/commit/479206c28b0f59fa94f78fcf253145534ee49560? I'm just guessing here, I'm a noob.)
2. Turning off AVX-512 from BIOS makes this problem disappear.

**Comment by sekrit-twc** [comment]
Can you try the attached test builds (remove .zip extension, file is a 7z) and confirm if one of them removes the artifact? Replace VapourSynth.dll in the python site-packages directory with the test DLL.

[test.7z.zip](https://github.com/vapoursynth/vapoursynth/files/11901146/test.7z.zip)

**Comment by hooke007** [comment]
a & b would remove the artifact here.

**Comment by sekrit-twc** [comment]
The example script contains two calls to z.lib:

````
clip = core.resize.Spline36(clip, format=vs.RGBH, matrix_in_s='709')
clip = core.resize.Spline36(clip, format=fmt_in, matrix_s='709')
````

If we test them independently by passing `cpu_type='none'` to one or the other call, do both test builds a and b still resolve the issue?

**Comment by Mr-Z-2697** [comment]
> The example script contains two calls to z.lib:
> 
> ```
> clip = core.resize.Spline36(clip, format=vs.RGBH, matrix_in_s='709')
> clip = core.resize.Spline36(clip, format=fmt_in, matrix_s='709')
> ```
> 
> If we test them independently by passing `cpu_type='none'` to one or the other call, do both test builds a and b still resolve the issue?

In fact, **only build b** fully resolves the problem.
passing `cpu_type='none'` to one or the other call does not affect this result.

**Comment by sekrit-twc** [comment]
Please verify that the attached test build fixes the issue.

[test2.7z.zip](https://github.com/vapoursynth/vapoursynth/files/11912310/test2.7z.zip)

**Comment by hooke007** [comment]
It works well.

**Comment by Mr-Z-2697** [comment]
It works well. (+1)

**Comment by sekrit-twc** [comment]
Fixed upstream
