### ISSUE TITLE
AVFS.exe no longer works in R62 and R63

### ISSUE THREAD

**Issue by jonpoeschek** [vapoursynth/vapoursynth#978]
I've downloaded the R62 and R63 portable packages and AVFS.exe does not work. When attempting to load and avs file, the avs file is copied to the Volumes dir and error.log is present but is blank.

Reverting to R61 package AVFS.exe works.

**Comment by myrsloik** [comment]
Can't reproduce. Used 64 bit R63 avfs.exe and a script consisting of `colorbars()` and it works. Also nothing was changed at all for many releases.
