### ISSUE TITLE
Accessing/creating individual frame data in Python for interacting with PyTorch

### ISSUE THREAD

**Issue by Stefan-Olt** [vapoursynth/vapoursynth#980]
I would like to test some AI super resolution models on video, like those provided by the super-image packet in Python. For that I need to convert the frames PyTorch tensors. Unfortunately I cannot see a way on how to make VapourSynth interact with other Python code on a per-frame basis. The documentation shows how to access the data of specific frames, but I think I need a callback that allows me to process a frame and return a new one.
Is there any way to do that directly in Python?

**Comment by DJATOM** [comment]
Simplified example howto write your video data per plane:

```python

import numpy as np

def fill_frame(n, f):
    fout = f.copy()

    for p in range(fout.format.num_planes):
        np.asarray(fout.get_write_array(p))[:] = !your plane data from pytorch goes here!

    return fout

clip = core.std.ModifyFrame(clip, clip, fill_frame)
```

**Comment by Stefan-Olt** [comment]
Thanks, I got this working:
```python
import vapoursynth as vs
import torch
import numpy as np
from super_image import CarnModel

core = vs.core
video = core.ffms2.Source(source='test.mkv')

video = core.resize.Bicubic(video,format=vs.RGB30, matrix_in_s="470bg")
videoout = core.std.BlankClip(clip=video,width=video.width*2,height=video.height*2,keep=1)

model = CarnModel.from_pretrained('eugenesiow/carn', scale=2)

def process_frame(n, f):
    fout = f[0].copy()
    in_fr = torch.ShortTensor([[np.asarray(f[1][0]), np.asarray(f[1][1]), np.asarray(f[1][2])]])
    in_fr = in_fr.float()
    in_fr[0] = in_fr[0].mul(torch.FloatTensor([1.0/1024.0]))
    out_fr = model(in_fr)
    out_fr = torch.clamp(out_fr, min=0.0, max=1.0)
    out_fr[0] = out_fr[0].mul(torch.FloatTensor([1024.0]))
    out_fr = out_fr.short()
    np.asarray(fout[0])[:] = out_fr.detach().numpy()[0][0]
    np.asarray(fout[1])[:] = out_fr.detach().numpy()[0][1]
    np.asarray(fout[2])[:] = out_fr.detach().numpy()[0][2]
    return fout

video = core.std.ModifyFrame(videoout, [videoout, video], process_frame)
video = core.resize.Bicubic(video,format=vs.YUV422P10, matrix_s="709")
video.set_output(0)
```
Unfortunately it is incredibly slow (compared to using the model with a bunch of pictures). there is also a warning shown:
```
UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at ../torch/csrc/utils/tensor_new.cpp:245.)
  in_fr = torch.ShortTensor([[np.asarray(f[1][0]), np.asarray(f[1][1]), np.asarray(f[1][2])]])
```
Is there a better way to convert the frame data into a PyTorch tensor? Also, inference could be faster with two images in parallel. There is no way to process two frames at one? Video filters can do that. Would it be possible to create a video filter in Python? Maybe as a class that inherits from a dummy filter that is just pass-through and the override the methods?

**Comment by HolyWu** [comment]
Maybe you can borrow some ideas from https://github.com/HolyWu/vs-femasr/blob/master/vsfemasr/__init__.py#L184-L213.
