### ISSUE TITLE
Portable detection from Windows PATH fails.

### ISSUE THREAD

**Issue by Samhayne** [vapoursynth/vapoursynth#983]
edit: Well... for Python 3.10 I should have invoked "pip install VapourSynth=61" anyway, as it doesn't seem happy with R62 it would automatically chose.

===

Unfortunately installation of VapourSynth via 'Pip install VapourSynth' failed for me, because setup.py failed finding my VS portable installation in the system path.

````
 OSError: Couldn't detect vapoursynth installation path
````

The culprit seems to be here:
https://github.com/vapoursynth/vapoursynth/blob/master/setup.py line 65:
````
dll_path = which("vapoursynth.dll")
````

(At least my version of) _which()_ isn't able to find non-exe files, i.e. also not .dll files.
For .dll files _which()_ would return NONE.

![image](https://github.com/vapoursynth/vapoursynth/assets/7030482/8f6ef58f-dd96-4c56-9415-6ef7fa262c8a)

![image](https://github.com/vapoursynth/vapoursynth/assets/7030482/952a8042-acbf-40f6-afdd-e200255e79f6)

**Comment by Setsugennoao** [comment]
cfg
