### ISSUE TITLE
Core plugin autoloading failed. Installation is broken! (portable R62 installed via pip)

### ISSUE THREAD

**Issue by jlw4049** [vapoursynth/vapoursynth#984]
Using `pip install Vapoursynth` on `R62` in a fresh `.venv` I get the above error. Dropping back to r61 solves it, so I'm not really sure what the issue is here. Anyway this could be investigated further?

I noticed this thread https://github.com/vapoursynth/vapoursynth/issues/957 and he marked it as solved, but I tried it on a fresh pip install and it throw the error. It still works perfectly, just throws an error in stdout.

**Comment by myrsloik** [comment]
Only windows installer is officially supported
