### ISSUE TITLE
AVFS produced avi doesn't work in av1an

### ISSUE THREAD

**Issue by Boulder08** [vapoursynth/vapoursynth#986]
When using a simple command line "av1an -i c:\Volumes\lotr_fotr.avs\lotr_fotr.avi", I get the error "The parameter is incorrect. (os error 87)". The source of the avi is an Avisynth script, and if I open the avi in MPC, it works fine.

I'm not sure if this is an av1an issue or what, but the error message seems to be from the OS itself. It would be very useful to be able to use av1an since aomenc is just not good at utilizing a multicore CPU.

**Comment by myrsloik** [comment]
The virtual avis have been tested and work with a large number of applications so that is an odd error. From what I can tell av1an probably uses ffmpeg so I don't know what causes it.
This is where you run av1an in a debugger I guess. I'll make it easy for myself and point at someone else.

**Comment by Boulder08** [comment]
Fair enough :)

In fact, this whole thing made me fire up ChatGPT and start working on my own tool for the same purpose. I don't know if it's a good or bad thing but maybe it'll keep me from doing naughty things for a while.
