### ISSUE TITLE
Distributions built by setuptools put VAPOURSYNTH_VERSION file in Python env root

### ISSUE THREAD

**Issue by JustinTArthur** [vapoursynth/vapoursynth#990]
Because `VAPOURSYNTH_VERSION` doesn't have a target directory specified, installation from a wheel or sdist created by setuptools will put the file in the prefix hosting Python env (e.g. as a peer to the bin, lib, etc, folders).

e.g. on a system where packages are installed to `/usr/local/lib/python3.11/site-packages`, the file would be copied to `/usr/local/VAPOURSYNTH_VERSION`. If the user doesn't have write permission to that path, the installation will fail.

@Setsugennoao was this the intention or is it supposed to land inside the root package?

**Comment by Setsugennoao** [comment]
Definitely was not intentional
It's only needed for compilation.

**Comment by JustinTArthur** [comment]
Thanks, @Setsugennoao, hopefully #991 does the trick.

**Comment by Setsugennoao** [comment]
Thank you!!
